cal-itp/data-infra

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- README.md
- catalogs/catalog.yml
- setup.cfg
- src/downloader.py
- src/gtfs_static_downloader.py
This PR adds a script and some structure for a static GTFS downloader. It also adds code formatting and linting as a pre-commit hook.
As of now, the deployment strategy isn't figured out. I see two routes 
1) [Kubernetes Cron](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/)
2) [Cloud Composer](https://cloud.google.com/composer) / Airflow 
Each of these have pro / cons that would be good to discuss as a team. 
TODOs
Once w have this done, we need to pipe the collected data at the GTFS-Validator. 
Commits: 
- adding src folder
- adding catalogs folder
- Adding readme
- rename file, fix paths
> WIP: GTFS-Static Downloader

- data/agencies.yml
This PR converts the existing GTFS spreadsheet from the drive and creates rows for every agency with a GTFS URL that starts with http(s). Missing agencies that have "in google" or "not in google" filled out and I haven't loaded RT feeds yet. 
I think, to load RT feeds, the best option is to join on transitland atlas via NTP ID, but curious if we've been tracking those URL(s) elsewhere.
> Create Initial GTFS "Catalog" 

- airflow/dags/dags.py
Quick fix. The gist is that in our dev environment, the dags folder lives inside AIRFLOW home. However, google cloud uses `/etc/airflow` for home, and has dags in `/home/airflow/gcs/dags`.
> fix: google cloud dag dir is not in AIRFLOW_HOME

- .github/workflows/push_to_gcloud.yml
addresses #35. Will double check in the morning. Pulled the sync command out of [this article](https://www.mickaelvieira.com/blog/2020/01/29/deploying-a-static-website-to-google-cloud-storage-with-github-actions.html
):
* the bucket the dag dir is being uploaded to also has the whole data-infra repo in it (from some point in time?)
* tested by creating a new bucket `gtfs-data-test` and syncing a folder to it, deleting file, re-syncing.
* the dag bucket currently has a task called `airflow_monitoring.py`. Looks like it is [automatically added](https://stackoverflow.com/questions/56496779/why-is-there-a-dag-named-airflow-monitoring-automatically-generated-in-cloud-c) for health checks.
* for some reason on the 19th a job used the full datetime-stamp when saving data, rather than only the …
> remove old files from dags folder on gcloud

- .github/workflows/push_to_gcloud.yml
@hunterowens I made an error with PR #36, and needed to specify we're syncing to the dags subfolder on gcloud. Going to merge, so I can make sure everything is syncing properly.
> fix: dags accidentally syncing to root

- airflow/docker-compose.yaml
- airflow/plugins/calitp.py
I have no idea why this is happening, but after..
* setting airflow to reload whenever a plugin changes
* restarting the server
I'm seeing in the logs that the scheduler [can't find the environment variable `COMPOSER_ENVIRONMENT`](https://console.cloud.google.com/logs/query;pinnedLogId=2021-04-05T18:53:33.973701836Z%2F19sc6eog8rzlfaq;query=resource.type%3D%22cloud_composer_environment%22%0Aresource.labels.location%3D%22us-west2%22%0Aresource.labels.environment_name%3D%22calitp-airflow-prod%22%0Atimestamp%3D%222021-04-05T18:53:33.975978126Z%22%0AinsertId%3D%2219sc6eog8rzlfaw%22;timeRange=PT1H?project=cal-itp-data-infra). This is weird, since it's listed as one of the [variables composer uses](https://cloud.google.com/composer/docs/how-to/managing/environment-variables#reserved_names), and …
> fix: use AIRFLOW_ENV to flag dev now

- airflow/data/agencies.yml
This PR starts the process of tracking GTFS RT urls. Based on a dump from Maxime at Mobility Data, this is the valid-ish URLs I could find. 
Next batches to process
- TransitLand
- GRaSS Clients
> add MobilityData list of initial GTFS-RT urls

- airflow/dags/gtfs_downloader/download_data.py
Addresses #56, in the sense that the task now succeeds. I'm not sure what's going on with the urls. I tried one on my laptop, and it worked okay--but they may be blocking our pipeline's IP / user-agent?
> Fix download data failing due to http retries

- airflow/dags/gtfs_downloader/download_data.py
- airflow/dags/gtfs_downloader/email_failures.py
addresses #48, and adds an html table of results. Note that sendgrid isn't configured in the container, so I have tested that it attempts to send (and viewed the contents). Since this is the only email we're sending, I'd vote for merging, and wait to get things set up on dev if/when we start sending more emails.
> feat: add table of urls, errors to email

- airflow/README.md
- airflow/dags/dags.py
- airflow/dags/gtfs_downloader/download_data.py
- airflow/dags/gtfs_loader/METADATA.yml
- airflow/dags/gtfs_loader/agency_staging.yml
- airflow/dags/gtfs_loader/calitp_files_process.py
- airflow/dags/gtfs_loader/calitp_files_staging.yml
- airflow/dags/gtfs_loader/calitp_load_errors_staging.yml
- airflow/dags/gtfs_loader/calitp_status_staging.yml
- airflow/dags/gtfs_loader/move_to_destination.yml
- airflow/dags/gtfs_loader/routes_staging.yml
- airflow/dags/gtfs_loader/stop_times_staging.yml
- airflow/dags/gtfs_loader/stops_staging.yml
- airflow/dags/gtfs_loader/trips_staging.yml
- airflow/dags/gtfs_loader/valid_agency_paths.py
- airflow/docker-compose.yaml
- airflow/plugins/calitp.py
- airflow/plugins/operators.py
This PR adds the loading of the 5 required GTFS static tables for agencies: agency, stops, stop_times, routes, trips. More can be added by adding simple yaml files to the `gtfs_loader` DAG.
Notes:
* data loaded to `gtfs_schedule` dataset at the moment (e.g. `gtfs_schedule.stops`, `gtfs_schedule.agency`)
* tables columns are loaded with mostly STRING types, so analysts can diagnose misspec'd agencies.
* wrangling airflow's BigQuery operators took a lot of work; we should move away from it down the road!
* changed the paths to be {itp_id}_{url_number}, instead of {itp_id}/{url_number}. This makes it easy to use with bigquery, which only allows a single wildcard in paths.
Going to punt loading validation data to https://github.com/cal-itp/data-infra/issues/59.
* prepare to package calitp.py. …
> Load gtfs schedule data into bigquery

- airflow/dags/gtfs_downloader/validate_gcs_bucket.yml
- airflow/requirements.txt
Should address #66. I tested locally by running gtfs-validator-api manually, and on the dev airflow. Unless there's some issue specific to the KubernetesPodOperator that we run on composer only, then should resolve!
> Fix validator

- airflow/dags/gtfs_downloader/validate_gcs_bucket.yml
see https://github.com/MobilityData/gtfs-validator/issues/858. The validator takes a feed name argument of form "{iso_country_code}-{agency_name}". The gtfs-validator-api wrapper was passing in "na-na", but the first piece affects validation behavior (I originally thought it was just being stored somewhere in the results).
After running this, I'll double check the phone numbers that @mcplanner flagged as false positives (https://github.com/MobilityData/gtfs-validator/issues/856), in case this corrects it.
edit: here is the call made by the validator: https://github.com/cal-itp/gtfs-validator-api/blob/v0.0.5/gtfs_validator_api.py#L33-L39
> fix: use correct country code in validator

- airflow/dags/dags.py
- airflow/dags/gtfs_loader/METADATA.yml
- airflow/dags/gtfs_loader/move_to_destination.yml
- airflow/dags/gtfs_loader/validation_report_process.py
- airflow/dags/gtfs_loader/validation_report_staging.yml
- airflow/dags/gtfs_views/METADATA.yml
- airflow/dags/gtfs_views/validation_codes.yml
- airflow/dags/gtfs_views/validation_notices.yml
- airflow/docker-compose.yaml
- airflow/plugins/calitp.py
- airflow/plugins/operators.py
Addresses #59:
* loads the validation reports into bigquery (1 row per itp_id)
* create a views dag, to handle transformation, and two convenient tables:
- `views.validation_codes`: unnesting validation into 1 row per agency x code
- `views.validation_details`: unnesting validation into 1 row per agency x code x individual code violation
* creates custom airflow macros, so we can handle loading into our test datasets by...
- writing `SELECT * FROM { "gtfs_schedule.agency" | table }`
- generating `SELECT * FROM cal-itp-data-infra.test_gtfs_schedule.agency`.
* bigquery requires an aggregation in its materialized views, so I've implemented a MaterializedViewOperator, but don't use it 😭.
* bigquery's api feels very low level, so I'm still leaning on the airflow bigquery hook
* I'm keen on …
> feat: load validation report, and unnest

- airflow/dags/gtfs_loader/validation_report_staging.yml
Currently, the validator schema is based on codes I was able to observe in our data. However, today's validator produced a new code, so I've updated the schema.
(@hunterowens going to merge, since missing these breaks the task, and it takes a while for the dev airflow to get caught up. Down the road, may be a quick way to pull these out of the gtfs-validator java app?)
> fix: add missing codes to validator schema

- airflow/data/agencies.yml
Turns out I was inconsistent of my use of `gtfs_rt_url` vs `gtfs_rt_urls`. This settles on the plural because their are multiple types
> Fix "GTFS_RT" keys

- airflow/data/agencies.yml
Carson Circuit is defunct post-covid.
I also added the GMV feeds for Commerce.
> Removed Carson Circuit + Added Commerce GTFS

- airflow/data/agencies.yml
Per discussion with Commerce today, they prefer their GMV data over Trillium.
> Corrected Commerce feeds

- airflow/requirements.txt
Includes pybigquery pypi dependency (see #111). I've been keeping an eye on the extraction DAG (gtfs_download), which has been running, so thought I had merged this already..! Going to merge, since gtfs_loader needs this to run
> Fix dep pybigquery

- airflow/dags/gtfs_schedule_history/calendar.yml
- airflow/dags/gtfs_schedule_history/calendar_dates.yml
- airflow/dags/gtfs_schedule_history/calitp_included_gtfs_tables.py
- airflow/dags/gtfs_schedule_history/fare_attributes.yml
- airflow/dags/gtfs_schedule_history/fare_rules.yml
- airflow/dags/gtfs_schedule_history/frequencies.yml
- airflow/dags/gtfs_schedule_history/shapes.yml
This PR adds these remaining tables from the GTFS schedule spec:
* calendar
* calendar_dates
* fare_attributes
* fare_rules
* frequencies
* shapes
I think more are necessary for the GTFS report in #75. Data is currently up on the dev schemas!
> feat: add remaining tables from gtfs spec

- airflow/dags/gtfs_loader/validation_report_process.py
- airflow/dags/gtfs_schedule_history/validation_report.yml
- airflow/dags/gtfs_views/dim_date.yml
- airflow/dags/gtfs_views/gtfs_agency_names.yml
- airflow/dags/gtfs_views/gtfs_status_latest.yml
- airflow/dags/gtfs_views/validation_codes.yml
- airflow/dags/gtfs_views/validation_notice_fields.py
- airflow/dags/gtfs_views/validation_notices.yml
- airflow/plugins/calitp.py
Addresses #128 #90, and adds additional view tables:
* `views.gtfs_status_latest` - data from the last ingested agencies.yml
* `views.gtfs_agency_names` - has itp id, url number, and agency name (derived from table above)
* `views.validation_notice_fields` - has a row for each error code x validation field, so you can look up what fields belong to which codes
* `dim_date` - a calendar table, to make it easier to do date stuff
Also makes `calitp.write_table` a singledispatch function, so that it can write DataFrames to bigquery.
> Update validation schema

- .github/workflows/lint.yml
The `lint.yml` workflow is named `build` -- seems like maybe some copy-pasta. I renamed it to `lint` which shows while the lint workflow is initializing and is the name used to require the check. Looks like github repo branch settings will need to be updated when this gets merged to make `lint` the required check instead of `build`
> style(ci): rename lint workflow to match  filename

- docs/README.md
Adds links and notes for using documentation features. Also shortens title of main page to "Welcome"
> docs: add documentation features references

- .pre-commit-config.yaml
- airflow/dags/dags.py
- airflow/dags/gtfs_loader/METADATA.yml
- airflow/dags/gtfs_schedule_history2/METADATA.yml
- airflow/dags/gtfs_schedule_history2/merge_updates.py
- airflow/dags/gtfs_views/METADATA.yml
- airflow/dags/gtfs_views/gtfs_schedule_history_calendar_long.yml
- airflow/dags/gtfs_views/gtfs_schedule_service_daily.yml
- airflow/dags/gtfs_views/gtfs_schedule_service_daily_metrics.yml
- airflow/dags/gtfs_views/gtfs_schedule_service_daily_trips.yml
- airflow/dags/gtfs_views/gtfs_schedule_stop_times.yml
- airflow/debug.py
- airflow/plugins/calitp.py
This PR builds out the tables needed for #75, and also fixed a few small things along the way. Main features:
* daily snapshots of gtfs schedule data (merge_updates.py)
* added views for describing daily service schedules (e.g. on a specific date, what does the most recent feed before that date say service is like in the calendar)
* fixed an issue with gusty configuration that was causing wait_for tasks to fail everyday #133 
* added a `query_yaml` function, which can take the name of a task file
* add a debug.py file that makes it easy to import from airflow plugins, dag tasks
TODO (but likely not urgent): 
* Change loading in `gtfs_loader/gtfs_schedule_tables_load.py` to load the latest data from the snapshots, move to history2 dags
* I'd go for renaming the current …
> Feat snapshots

- airflow/dags/dags.py
- airflow/dags/gtfs_schedule_history2/merge_updates.py
Going to merge, so I can get prod up to date for #137. I needed to use the shortened version of execution date in a SQL merge, so need to convert the execution_date airflow passes in to operators (it shows up like `2021-01-01T00:00:00+00:00`, but we need `2021-01-01`).
> Fix schedule merge

- airflow/dags/gtfs_schedule_history2/merge_updates.py
Alright, sorry--one last fix for getting #137 up. I ran this on dev to double check. Once we tame copying all datasets over to dev (#143), it should be a lot easier to spin up. (As part of that, I'll likely need to move all external tables into their own dataset..).
(But also once these tables are up on prod, 99% of the time, should only need to copy them over.)
> fix(airflow): missed shortening a date in merge

- script/docs-server
v1.2.0 was released yesterday with broken livereload
See: https://github.com/mkdocs/mkdocs/issues/2448
> fix(docs): pin mkdocs to v1.1.2

- airflow/dags/gtfs_views/gtfs_schedule_service_daily.yml
- airflow/dags/gtfs_views/gtfs_schedule_service_daily_metrics.yml
- airflow/dags/gtfs_views/gtfs_schedule_service_daily_trips.yml
Main issues were..
* gtfs_schedule_service_daily needed to take into account calendar start_date and end_date
* service hours calculation for report is the service window available on a given day (ie. 24 hours or less); named service_window for now in data, since previous calculations are still in there.
(added some extra comments)
> views: fix service_daily related tables

- airflow/dags/dags.py
This should hopefully fix #133 the `wait_for` tasks failing once and for all. I recently lengthened their wait time to 2.5 hours, but the validator took a bit longer than that this morning. Going to try waiting for 4 hours.
For context, waiting for other DAGs to finish is set on a short timer in gusty by default, in order to prevent extraction tasks from rolling over to the following day (i.e. they need to complete somewhat quickly or fail!). But our loading tasks can wait longer..
edit: note that once we upgrade to airflow 2, I can create a "task group" operator that splits validation into several batches running in parallel (not urgent).
> fix(airflow): wait longer for external dependencies

- airflow/dags/gtfs_schedule_history/validation_report.yml
This PR adds fields for a previously unseen validator error. Tested on dev. Details below...
Looks like [Santa Clara Valley Transportation Authority](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml#L793) triggered a new validator error: invalid_row_length. This is because they did not correctly quote entries with commas in them (see North,South and East,West at the far right of data).
```
route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,route_sort_order,ext_route_type
500,VTA,Rapid 500,San Jose Diridon Station - Berryessa BART,"Rapid buses may depart up to five minutes earlier than the time shown, if traffic allows.",3,https://www.vta.org/go/routes/rapid-500,e4002b,FFFFFF,4,North,South,702 …
```
> feat(airflow): support invalid_row_length validation error

- airflow/dags/gtfs_downloader/generate_provider_list.py
This PR fixes an error caused by a task returning xcom values that are too big (byte-wise) for airflow's mysql setup.
I cut out the RT url columns for now, since the values are just used to download static schedule data. Going to merge and re-run task, so we can get save today's feed data.
```
sqlalchemy.exc.DataError: (_mysql_exceptions.DataError) (1406, "Data too long for column 'value' at row 1"
[SQL: INSERT INTO xcom (`key`, value, timestamp, execution_date, task_id, dag_id) VALUES (%s, %s, %s, %s, %s, %s)
[parameters: ('return_value', b'[{"agency_handle": "ac-transit", "agency_name": "AC Transit", "itp_id": 4, "gtfs_schedule_url": "https://api.actransit.org/transit/gtfs/download?tok ... (66677 characters truncated) ... reaferries-ca-us.zip", "gtfs_rt_vehicle_positions_url": null, …
```
> fix(airflow): xcom values too big for mysql

- airflow/dags/gtfs_loader/calitp_files_updates_load.yml
- airflow/dags/gtfs_schedule_history2/merge_updates.py
- airflow/dags/gtfs_schedule_history2/validation_notices_load.yml
- airflow/dags/gtfs_views/gtfs_schedule_service_daily_metrics.yml
* Has the SQL merge statement that makes a big historical table of gtfs schedule data wait until the loading DAG is completed
* Correctly sets `views.gtfs_schedule_service_daily_trips` as the parent of `views.gtfs_schedule_service_daily_metrics`
* Fixes gtfs_loader to depend on the past when detecting whether files have updated (will make it easier to re-run history if we have to)
* Adds a `validator_notices` table with full history to `gtfs_schedule_type2`, so we can start on https://github.com/cal-itp/notebooks/issues/20
> fix(airflow): fix task dependencies for a view; merges

- .github/workflows/push_to_gcloud.yml
- airflow/data/.gitignore
- airflow/data/agencies.yml
- airflow/data/schema_agencies_entry.yml
- docs/warehouse/01_agencies.md
- script/agencies_convert.py
- script/agencies_validate.py
This PR supplants #144 basedon the new agencies.yml file, but uses named keys rather logic so it is easier to template.
> Use Named Keys for API keys

- airflow/data/schema_agencies_entry.yml
cc @hunterowens this is a quick addition. Based on the discussion on having valid `agencies.yml`, I added quick validation with jsonschema to #172. However, it also needed to fail when properties were misnamed / omitted, which is added here!
(Whenever someone pushes a change to the airflow subdirectory it will run the validation)
> feat(airflow): require all agencies.yml fields

- docs/README.md
Minor change, but we can use the `docs.calitp.org` domain now.
> Point to vanity docs site URL

- airflow/dags/gtfs_views/reports_gtfs_schedule_index.yml
This new view contains one row for each agency on each date a new report would be generated, along with the start and end dates need for a report. See `description` and `fields` in the yaml for more info.
Critically, it uses agency info as it existed on each publishing date, so that changes to `agencies.yml` will not affect report generation for previous months.
cc @Nkdiaz, let's go over when pairing today
> feat(views): add reports_gtfs_schedule_index

- .github/workflows/push_to_gcloud.yml
- airflow/dags/gtfs_downloader/generate_provider_list.py
- airflow/dags/gtfs_schedule_history/calitp_feeds.yml
- airflow/dags/gtfs_schedule_history/calitp_feeds_raw.yml
Tested by running airflow locally. Saves the DataFramed version of agencies.yml as feeds_raw.csv, and feeds.csv (where API token is filled in).
e.g. to cloud storage:
* gs://gtfs-data-test/schedule/2021-06-30T00:00:00+00:00/metadata/feeds_raw.csv
* gs://gtfs-data-test/schedule/2021-06-30T00:00:00+00:00/metadata/feeds.csv
Also creates external tables for feeds, so they can be queried from `gtfs_schedule_history.calitp_feeds` (and feeds_raw)!
> feat: daily extract unpacked agencies.yml as feeds.csv, feeds_raw.csv

- airflow/dags/catalogs/catalog.yml
- airflow/dags/dags.py
- airflow/dags/gtfs_loader/calitp_files_process.py
- airflow/dags/gtfs_schedule_history/stops.yml
- airflow/dags/gtfs_schedule_history/validation_report.yml
- airflow/dags/sandbox/METADATA.yml
- airflow/dags/sandbox/create_dataset.py
- airflow/dags/sandbox/op_csv_to_warehouse.yml
- airflow/dags/sandbox/op_external_table.yml
- airflow/dags/sandbox/op_python_to_warehouse.py
- airflow/dags/sandbox/op_sql_query.sql
- airflow/dags/sandbox/op_sql_to_warehouse.sql
- airflow/dags/sandbox/query_external.py
- airflow/dags/sandbox/save_external_table_data.py
- airflow/plugins/operators/__init__.py
- airflow/plugins/operators/csv_to_warehouse_operator.py
- airflow/plugins/operators/external_table.py
- airflow/plugins/operators/sql_query_operator.py
- airflow/plugins/operators/sql_to_warehouse_operator.py
- airflow/requirements.txt
This PR moves the pipeline development environment to use the `cal-itp-data-infra-staging` project, and pays down longstanding tech debt.
* old airflow bigquery hooks removed (only uses python-bigquery or sqlalchemy dialect)
* removed old catalog folder from DAGs
* DAGs automatically discovered for gusty
* added sandbox DAG, to test and demo each custom operator we use
* upgrade calitp to v0.0.2, as part of the move to a staging project 
TODO: release version and update requirements.
> Feat staging project

- airflow/plugins/operators/csv_to_warehouse_operator.py
This is a small fix, to stop pulling project_id out of the table name in one of the operators. I tested the sandbox locally before merging before, so not sure what happened....
> fix(airflow): do not split table name in CsvToWarehouse

- airflow/data/agencies.yml
* removed the broken link from Tri Delta Transit, since it was a duplicate anyway.
* corrected Burbank's to their GMV links.
* replaced the regional MTC feed links with the URLs that hide the API key.
SLORTA is still broken, and I contacted the agency to ask for the correct link.
> attempted to resolve missing feed issues

- docs/kubernetes/README.md
- docs/services/gtfs-rt-archive.md
- kubernetes/apps/manifests/gtfs-rt/app.yaml
- kubernetes/apps/manifests/gtfs-rt/kustomization.yaml
- kubernetes/apps/manifests/gtfs-rt/ns.yaml
- kubernetes/apps/overlays/gtfs-rt-prod/kustomization.yaml
- services/gtfs-rt-archive/Dockerfile
- services/gtfs-rt-archive/requirements.txt
These changes capture the Kubernetes manifests and deployment steps for the gtfs-rt-archive service now running on the Kubernetes cluster. Part of #202
> Deployment for gtfs-rt-archive service

- airflow/dags/gtfs_schedule_history/validation_report.yml
Small and classic fix to add missing validation report fields to schema. Going to merge, so I can make sure we can pull all the data needed for reports.
> fix(airflow): add missing validation schema fields

- airflow/dags/sandbox/op_csv_to_warehouse.sql
- airflow/dags/sandbox/op_python_to_warehouse.py
- airflow/dags/sandbox/op_sql_to_warehouse.sql
- airflow/plugins/operators/sql_to_warehouse_operator.py
Fixes #325
Adds functionality for a `fields_from` block in the `SqlToWarehouseOperator`, and includes usage example in sandbox DAG task `op_sql_to_warehouse.sql`.
Two ways designate fields from:
```
fields_from:
table_a:
-  individual
-  fields
-  here
table_b: any
```
Where "any" is a special keyword.
`fields_from` checks that fields listed exist in the destination table and prioritizes fields listed from top to bottom. So if there are two tables that feature "any", the one listed first will get preference. Fields listed in the operator's `fields` blocked are prioritized over any fields listed in `fields_from`.
> fields_from implementation

- airflow/dags/gtfs_views/dim_date.yml
- airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feed_files.sql
Interpolates files over days where did not do any extraction. This will allow us to fill in metrics for missing days. I flagged these dates using the `is_interpolated` column.
This is important because we are using a fixed date (first day of quarter) for quarterly metrics
> feat(content): interpolate daily feed files

- airflow/dags/gtfs_schedule_history2/merge_updates.py
- airflow/dags/sandbox/merge_create_merge_target.sql
- airflow/dags/sandbox/merge_query_table.py
- airflow/dags/sandbox/merge_run.py
- airflow/dags/sandbox/op_external_table.yml
- airflow/dags/sandbox/save_external_table_data.py
- airflow/plugins/merge_sql.py
Fixes #295. Going to run now, so that it can backfill the gtfs schedule type 2 tables for the next few hours. Saved a backup to the staging project, as the gtfs_schedule_type2_prod dataset.
This PR also adds a working version to the sandbox DAG with tests.
> fix(content): fix gtfs schedule merge missing re-added entries

- airflow/docker-compose.yaml
Two changes here:
* Pin the docker-compose file version to 3.8 to require a minimum docker-compose version of [1.25.5](https://docs.docker.com/compose/release-notes/#1255) and minimum docker version of [19.03.0](https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix)
* Remove the fixed external port for `redis` service, as it may collide with any Redis servers already locally installed.
> Pin docker compose file version

- airflow/dags/rt_loader/METADATA.yml
- airflow/dags/rt_loader/dummy_task.yml
- airflow/dags/rt_loader_files/METADATA.yml
- airflow/dags/rt_loader_files/dummy_task.yml
- airflow/dags/rt_views/METADATA.yml
- airflow/dags/rt_views/dummy_task.yml
From pairing w/ @ccjarvus, this PR creates two DAGs for GTFS RT work:
* rt_loader_files: for creating a big table of all our RT files extracted (and their md5 hash)
* rt_loader: other loading tasks (e.g. parquet for external tables; validation)
* rt_views: views for transforming loaded data
Note that I would have used `gtfs_rt` as a prefix, but we have some dags named `gtfs_loader` and `gtfs_downloader` that should have used `gtfs_schedule_*`, and it's helpful to see all the `gifs_schedule_*` dags together.
> feat(gtfs-rt): stub out loading DAGs

- airflow/dags/gtfs_views/dim_metric_date.sql
- airflow/dags/gtfs_views/gtfs_schedule_fact_route_id_changes.sql
- airflow/dags/gtfs_views/gtfs_schedule_fact_stop_id_changes.sql
This PR tweaks the metric calendar, to use names starting with `metric_*`. Going to push so I can replace the manual id change calculations in reports with these ones. The gist is that dim_metric_dates allows people to perform calculations across
* daily
* rolling windows
* calendar periods (e.g. monthly, quarterly)
This is especially important when calculations are non-additive (e.g. distinct ids in some period, changes between two discrete dates).
> feat(content): tweak names used by metric_views, cleanup

- airflow/data/agencies.yml
This updates the LADOT gtfs url to avoid us their feed.
> fix: update LADOT GTFS url, remove commuter express

- airflow/dags/gtfs_views/gtfs_schedule_dim_routes.sql
This PR fixes an error in modeling our routes dimensional table, that caused route_keys with no agency.txt to be omitted from `gtfs_schedule_fact_daily_feed_routes`. Basically, dim routes denormalizes in agency data, but needed more coalescing to ensure extracted at, deleted at, and keys were not NULL.
Added fixes to code and checks for inappropriate nulls in columns above.
(Note: this dynamic of GTFS Schedule data discussed a bit here: https://github.com/cal-itp/data-infra/issues/70#issuecomment-832089250)
> fix(content): gtfs schedule dim routes missing when no agency.txt

- airflow/dags/gtfs_views/gtfs_schedule_stg_daily_service.sql
This PR addresses https://github.com/cal-itp/data-infra/issues/382 by removing duplicate entries from calendar_dates in the relevant CTE. Tests appear to be passing locally.
> fix(content): remove redundant entries from calendar_dates for daily service

- airflow/dags/transitstacks_views/transitstacks.sql
After digging a bit more, I realized that transitstacks only needs to join on itp_id. Because it was also using NTD_ID, which can be NULL, the joins were producing many NULL values (e.g. in county).
> fix(transitstacks): transitstacks view join issue when ntd_id is null

- airflow/dags/payments_loader/calitp_included_payments_tables.py
- airflow/dags/payments_loader/micropayment_adjustments.yml
- docs/datasets/mst_payments.md
The miropayments_adjustments data has fare cap values, which will be used in reporting metrics. This work is in relation to:
* #361 
* #372 
Ran the `payments_loader` DAG locally to check that everything flows correctly. New table is loaded into staging.
> Ingest micropayments_adjustments Littlepay data

- airflow/dags/payments_loader/METADATA.yml
- airflow/dags/payments_loader/customer_funding_source.yml
- airflow/dags/payments_loader/device_transactions.yml
- airflow/dags/payments_loader/micropayment_adjustments.yml
- airflow/dags/payments_loader/micropayment_device_transactions.yml
- airflow/dags/payments_loader/micropayments.yml
- airflow/dags/payments_loader/preprocess_columns.py
* Introduce a new function in the `preprocess_columns` task to handle preprocessing of a given littlepay data source. If need be, we can move this into a new operator in the future.
* Add SBMTD Littlepay data to be preprocessed. The SBMTD data is being synced to the same bucket as the MST data, but into a different folder. ~~The MST data is still being synced to the root, but should also be changed to use a different folder. We may have to create a new sync task to do so, as there doesn't appear to be a way to modify the bucket/folder being synced to. After merging this code, we should:~~
1. ~~Delete the old transfer task for MST~~
2. ~~Create a new transfer task for MST pointing to a subfolder of the Littlepay data bucket~~
3. ~~Submit a new PR changing the `preprocess_columns` task to …
> Update the proprocess_columns task to support multiple providers

- airflow/dags/payments_views/mst_transactions_gtfs_enhanced.sql
Small change: when there are changes to the `payments_feeds` table, we want those to run before doing anything with the `mst_transactions_gtfs_enhanced` view.
> Add dependency on `payments_feeds` for the transactions view

- airflow/dags/payments_loader/preprocess_calitp.py
- airflow/dags/payments_loader/preprocess_mst.py
- airflow/dags/payments_loader/preprocess_sbmtd.py
- airflow/dags/payments_views/payments_feeds.sql
- airflow/plugins/libs/littlepay.py
Pre-processing one source takes enough time that it makes sense to have all the processes run in parallel, especially for testing. Instead of creating an operator, I added a `plugins/libs/` package and created `littlepay.py` to hold the common code. I don't have strong opinions about the names, though I do appreciate the non-operator approach.
> Split Littlepay processing into separate for each source

- airflow/dags/rt_loader/parse_rt_vehicle_positions.py
Noticed tasks still fail intermittently, going very conservative and only allow 1 of these tasks to run at a time
> fix(gtfs-rt): lower task concurrency to 1

- kubernetes/apps/manifests/gtfs-rt-archive/app.yaml
By default, when updating deployments kubernetes will create new
containers before terminating old ones. This behavior is undesirable
for the archiver since we want to ensure there is never more than one
instance running at a time.
> fix(kubernetes/gtfs-rt-archive): use recreate strategy to deploy changes

- airflow/dags/rt_loader/parse_rt_vehicle_positions.py
Now that the cluster is beefed up, it should be able to handle running a few more gtfs rt parsing tasks at a time
> fix(gtfs-rt): up concurrency to 3 on new cluster

- airflow/requirements.txt
- docs/_toc.yml
- docs/warehouse/01_agencies.md
- docs/warehouse/jupyterhub.md
* updates dependency on calitp, so we can use sql magic in the docs (related to https://github.com/cal-itp/data-infra/issues/618; should make current doc build successfully run code)
* adds screencasts for using jupyterhub (#548 ), and adding entries to agencies.yml (#614 )
> Doc screencasts

- airflow/dags/dags.py
This will be helpful (and necessary) for deduplicating the `customer_funding_source` data, and is generally useful. It allows us to see the source of each record even downstream of the raw ingested tables.
> Enrich with payments export account and datetime info

- airflow/dags/payments_views_staging/stg_cleaned_micropayment_device_transactions.sql
- airflow/dags/payments_views_staging/validate_cleaned_micropayment_device_transactions.sql
- airflow/plugins/testing.py
This PR contains the following code. The first item is the meat of the PR, and the later two are new functionality allowing us to validate that the data was produced correctly:
* **Ensure no duplicate transaction ids in cleaned `micropayment_device_transactions`**
This resolves #647
* **Add test for table emptiness**
Creates a new table test. This test is useful for validation of a general query for invalid data. The way to use it is to create a view that selects some invalid records. If that view materializes to an empty table (i.e., there are no invalid records) then the test passes. If the view materializes some non-empty records (i.e., there are invalid records), then the test fails. This is based off of similar concepts like DBT's [bespoke …
> Ensure no duplicate transaction ids in cleaned micropayment_device_transactions

- .github/workflows/push_to_gcloud.yml
Following-up on the conversation in https://github.com/cal-itp/data-infra/pull/539#discussion_r741987162, I have moved the discussion about using repository secrets to obtain API keys.
Fixes #247
Fixes #622
> Retrieve agency secrets from repository secret

- kubernetes/apps/charts/metabase/templates/metabase.yaml
- kubernetes/apps/values/metabase.yaml
Metabase will use the internal container IP by default to form its
configured site url. This causes issues such as users receiving broken
links in account activation emails. This changeset adds the capability
to the chart to set the site url to whatever hostname is configured in
the ingress configuration.
> charts/metabase: inject default MB_SITE_URL from ingress

- airflow/dags/payments_views/payments_rides.sql
- airflow/dags/payments_views_staging/stg_cleaned_device_transaction_types.sql
- airflow/dags/payments_views_staging/stg_enriched_device_transactions.sql
This view is in service of #312. It consolidates information about each ride taken. Variable fare rides have information about the first tap as well as the second tap in separate fields prefixed with `off_`, whereas rides with a single tap simple have `null` values in all of the `off_` fields.
> Add a payments_rides view

- docs/_config.yml
Porting the same ID from the `mkdocs` site
> Docs: add Google ID

- airflow/dags/payments_views/payments_rides.sql
- airflow/dags/payments_views/validate_payments_ride_adjustments.sql
- airflow/dags/payments_views/validate_payments_ride_counts.sql
- airflow/dags/payments_views_staging/stg_cleaned_device_transaction_types.sql
- airflow/dags/payments_views_staging/stg_cleaned_micropayment_adjustments.sql
- airflow/dags/payments_views_staging/stg_cleaned_product_data.sql
- airflow/dags/payments_views_staging/stg_enriched_micropayment_adjustments.sql
- airflow/dags/payments_views_staging/stg_enriched_product_data.sql
- airflow/dags/payments_views_staging/validate_cleaned_device_transaction_pairs_common_fields.sql
- airflow/dags/payments_views_staging/validate_cleaned_micropayment_adjustments_applied.sql
This would allow us to add to the [payments dashboard](https://metabase.k8s.calitp.jarv.us/dashboard/29) metrics such as number of riders hitting fare caps (#372).
Includes the following validations which should be added to the [payments validation dashboard](https://metabase.k8s.calitp.jarv.us/dashboard/28):
* **Ride adjustments:** Make sure that all rides where the amount paid is not equal to the nominal amount have adjustments, and rides where the amount paid is equal to the nominal amount do not have adjustments.
* **Ride counts:** Make sure that we did not lose any transactions while joining for the rides table.
* **Paired device transaction (tap on/off) common fields:** Ensure that fields that are expected to be consistent across tap on/off transactions are actually consistent. …
> Add adjustment and product information to payments_rides

- .github/workflows/publish-docs.yml
The previous version was having some problems with Sphinx 4.3.0 (see CI run here). The package depending on pydata-sphinx-theme hasn't updated their requirement of pydata-sphinx-theme to be above 0.6.x, so this pins the version to 0.7.2 (one that is compatible with Sphinx 4.3.0).
> Pin pydata-sphinx-theme in publish-docs GitHub Action Workflow

- airflow/dags/gtfs_loader/calitp_files_process.py
- airflow/dags/gtfs_loader/gtfs_schedule_history_load.py
- airflow/dags/gtfs_loader/gtfs_validation_history_load.py
- airflow/dags/gtfs_loader/valid_agency_paths.py
- airflow/dags/gtfs_loader/validation_report_process.py
- airflow/dags/gtfs_schedule_history/calitp_feed_parse_result.yml
- airflow/dags/gtfs_schedule_history/calitp_feed_tables_parse_result.yml
- airflow/plugins/constants.py
- airflow/plugins/utils.py
This PR works on the items mentioned in #694 and #695 by doing the following:
- Extracting the validation loading (copying to bucket acting as external table) out of gtfs_schedule_history_load
- Tolerating and tracking CSV parse errors that occur when loading a CSV file.
This PR hasn't yet percolated the parse error information into dim and fact tables (as recommended in #695) as it seeks to first resolve the matter of a DAG task failing completely due to a CSV parse error.
> Tolerate corrupted feeds

- docs/analytics_examples/02_sql_snippets.md
worth mentioning that the script executes and the result is displayed in jupyterbook but the query is no longer displayed. Possibly another bug with how sql magic is returning the input.
> feat:documentation updated jupyterbook documentation page of sql snippets to use the sql magic 

- docs/analytics_onboarding/overview.md
- docs/analytics_welcome/03_how_we_work.md
**Added to 'How We Work' section:**
* Loom video on how to open issues in GitHub
_Other small changes in this PR in Docs_
**Added to:**
* 'How We Work' section:
* Missing Slack channel: data-office-hours
* Missing meeting: Lunch & Learn
* 'Meeting standards' section (agendas, etc - can remove if not needed)
* 'Netiquette' section (can remove if not needed)
* 'Technical Onboarding' Section:
* Missing meeting: Lunch & Learn, w/ internal link
* Missing Slack channel: data-office-hours, w/ internal link to Slack documentation
**Renamed (in both the above sections):**
* 'Week one meeting' name
**Edited for clarity:**
* H2s
* Headers within the GitHub section
> 'How to Open Issues' screencast

- docs/analytics_examples/02_sql_snippets.md
added requested '%%sql -m -o * --quiet' tag so the output is not displayed
> feat:documentation added tag for sql output to be quieted

- docs/analytics_onboarding/overview.md
- docs/analytics_welcome/03_how_we_work.md
* Removed meetings information from the technical onboarding overview page as it wasn't very technical, is covered in the page before, and made the page less concise
* Also tweaked how urls display in collaboration section
* Moved a message related to meetings from technical onboarding to the how we work page, tweaked wording of the meetings table
> Technical onboarding tweaks

- airflow/data/agencies.yml
The previous URL has been having download errors for multiple days. This new URL should be the correct one.
> Fix SLORTA GTFS URL

- airflow/dags/dags.py
It took me a while to figure out why the `calitp_export_account` and `calitp_export_datetime` fields were empty. Then I realized we were using curly braces inside of the regex, and the regex string was inside of a format string.
This issue is relevant to #617, as we need to know the export file for resolving the funding source IDs.
> fix(payments): Escape regex parameters in formatted string

- airflow/dags/gtfs_views/reports_gtfs_schedule_index.sql
cc @holly-g . This PR fixes a minor issue in reports_gtfs_schedule_index. This table should record one row per agency gtfs feed that *could* be reported on in reports.calitp.org.
In addition it has the following columns:
* has_feed_info - does the feed have a feed_info.txt for the last day of the month being reported?
* use_for_report - should it be used to generate a report? This is true when a feed has url number = 0 and has feed info. (note that reports currently break if an agency does not have feed_info.txt, https://github.com/cal-itp/reports/issues/26#issuecomment-883630244)
Note that use_for_reports is referenced in this line of the reports repo: https://github.com/cal-itp/reports/blob/main/reports/1_generate_ids.py#L7
The issue is that this table was accidentally filtering out …
> fix(reports): reports index was filtering those without feed info

- airflow/dags/gtfs_downloader/email_failures.py
This updates the contents of the email that gets sent off each night when all feeds download successfully so that a nice message is generated instead of an empty box.
> Include nice message upon successful feed downloads

- airflow/dags/payments_views_staging/stg_enriched_customer_funding_source.sql
This adds **6** fields to the enriched `customer_funding_source` table:
* calitp_funding_source_id_ranking_size
* calitp_funding_source_id_rank
* calitp_funding_source_vault_id_ranking_size
* calitp_funding_source_vault_id_rank
* calitp_customer_id_ranking_size
* calitp_customer_id_rank
For each of the `..._rank` fields, if the value is `1` then it is the latest occurrence of the corresponding ID. Instances are arranged in desc order by the export datetime.
> feature(payments): Add ID dupe order for each ID in funding sources

- airflow/dags/payments_views/payments_rides.sql
- airflow/dags/payments_views_staging/validate_cleaned_device_transaction_pairs_common_fields.sql
* **Update payments view to use non-'Route Z' route_id** - In cases where the route IDs don't match between tap on and off 
transactions, use the route ID that is not 'Route Z'
* **Remove test from validate transaction pairs task** - It is helpful to have the table with potentially invalid rows still generated, and we can set this table up in another platform to alert, but the data is currently a little unreliable to have failures hold up the rest of the pipeline. In particular, [this question](https://metabase.k8s.calitp.jarv.us/question/180-which-correlated-tap-on-and-off-transactions-have-differing-information) in Metabase can be set up with alerts for when there are any results in the table.
This PR resolves #796
> Remove failing device transaction data test in payments pipeline

- airflow/dags/rt_loader/parse_rt_vehicle_positions.py
* fixes intermittent download errors in task runs, by pulling rt files in bulk (vs run 1 request per file). AFAICT the task now finishes in half the time.
* enforces schema types by running pandas type conversions (https://github.com/cal-itp/data-infra/issues/811).
> fix(gtfs-rt): vehicle positions loaded types

- airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feed_files.sql
Our interpolation incorrectly did not partition on file name, so we ended up not correctly interpolating all previous files. Instead what happened is on days with interpolation a single file would show up.
I found a problematic case by running this  query:
```
SELECT * FROM `cal-itp-data-infra.views.gtfs_schedule_fact_daily_feed_files`
JOIN views.gtfs_schedule_dim_feeds USING (feed_key)
WHERE date="2021-05-23" AND calitp_itp_id=294
ORDER BY date
```
Then verified it works by adding this to the last line in the new full SQL in the task
```
WHERE date="2021-05-24" AND calitp_itp_id=294
```
> fix(gtfs-schedule): daily feed files view wrong interpolation

- airflow/dags/rt_loader_files/calitp_files_process.py
Pairing with @Nkdiaz -- the table schema has ids like calitp id as integers. however, the loader is loading strings. going to merge, since it's a pretty small change and will let us re-run / check everything
> fix(gtfs-rt): parse internal ids to ints to match schema

- airflow/data/agencies.yml
In order to validate the new Tuolumne County Transit GTFS feed, it needs to be in the `agencies.yml` in our Airflow pipeline.
This entry currently points to a publicly accessible feed that is temporarily stored on Drive.  The end-goal is to have this stored on the Tuolumne website, but while that is in the words this should probably point to somewhere on GCS (@evansiroky and Team DS – this is your purview )
> Add Tuolumne gtfs entry to agencies.yml

- airflow/data/agencies.yml
Previous URL was pointing to a zip file with a subfolder. This one has no subfolder.
> Update TCTA URL

- airflow/dags/gtfs_schedule_history2/validation_notices_load.sql
Checked by confirming that the external task dependency was created (but did not run the DAG):
Note that if gusty can not find a task dependency, then it does not fail, but silently drops the dependency. This has bit us a couple times, so I've opened an issue!: https://github.com/chriscardillo/gusty/issues/38
> fix(gtfs-schedule): update validation type 2 dependencies

- docs/analytics_tools/python_libraries.md
/analytics_tools/python_libraries 
- Add information for library `calitp`
- Removed 'WIP'
> Docs: close out analytics_tools/python_libraries 

- docs/analytics_tools/saving_code.md
Clarifies instructions for creating an ssh key and adds command to set permissions for private key if needed.
Addresses issue [792](https://github.com/cal-itp/data-infra/issues/792)
> clarify ssh instructions

- airflow/dags/gtfs_loader/gtfs_schedule_history_load.py
This fixes a regression created in 926fa255331d440a30b0031a189e0f542fd9fd3e that is now resulting in numerous feeds not being properly loaded in subsequent DAG tasks.
Since DAGs need to reran, I am saying this refs #848 and #849 instead of fixes them.
> Fix regression causing data to not be loaded

- docs/services/gtfs-ckan-uploader.md
Quick fix for a broken link in our docs (that I added a while ago 😬)
> fix(docs): correct gtfs ckan readme link

- airflow/data/agencies.yml
This PR manually adds a bunch of RT URLs that were present in the transit database that didn't make their way into the agencies.yml file yet.
> Update agencies.yml with latest RT URL info

- .github/workflows/push_to_gcloud.yml
- airflow/Dockerfile
- airflow/dags/gtfs_views/METADATA.yml
- airflow/plugins/operators/__init__.py
- airflow/plugins/operators/csv_to_warehouse_operator.py
- airflow/plugins/operators/once_off_external_task_sensor.py
- airflow/plugins/operators/python_taskflow_operator.py
- airflow/plugins/operators/python_to_warehouse_operator.py
- airflow/plugins/operators/sql_query_operator.py
This PR makes some small tweaks to make our pipeline airflow v2 compatible. Note that because we are on airflow v1.10.14 (and not v1.10.15) AFAIK this code is not compatible with our current setup. We will need to push this to the new cluster, and once it's working, disable the original one.
TODO before ready:
* appears resolved. Chris has never seen this, and they started working. (may have been startup quirks?)
TODO for release:
* inspect download logs
* glance at gtfs-data/schedule/<execution date>
* query for agency.txt from gtfs_schedule_history.calitp_files_updates
(Note that gtfs_download is the only DAG to use xcom)
> refactor(airflow): upgrade to airflow v2

- airflow/data/agencies.yml
Clean Air Express' link is now at https instead of http. I also added in some RT feeds for agencies that were missing, and matched up various 511 RT feeds with their 511 static feed.
> Update Clean Air express feed, add in RT feeds

- airflow/dags/sandbox/op_python_to_warehouse.py
- airflow/dags/sandbox/op_sql_to_warehouse.sql
This PR adds examples to two sandbox tasks, which show the use of airflow v2's doc_md argument. Resolves https://github.com/cal-itp/data-infra/issues/661.
This argument allows you to add documentation that is visible from the airflow UI. It is not the most prominent, but on the upside can be styled with lists, headers, etc..!
> feat(airflow): add examples of doc_md to sandbox

- airflow/data/agencies.yml
Ridemvgo was one of the RT feeds giving an "error fetching url https://ridemvgo.net/gtfs-rt/alerts". After some research, I realized that ridemvgo is now using .org rather than .net domain name. I updated the yml file accordingly.
> Update ridemvgo RT URLs

- airflow/data/agencies.yml
The Dumbarton Express RT URLs had some erroneous characters that resulted in an invalid API key being created.
> Fix Dumbarton Express URLs

- airflow/data/agencies.yml
LACMTA is now in charge of maintaining and publishing feeds in LA County which are not currently hosted by the agencies themselves. They maintain these feeds at https://github.com/LACMTA/los-angeles-regional-gtfs.
This PR:
1.  Updates `agencies.yml` to point to the LACMTA hosted feed zip files (rather than Trilliums, which are deprecated) 
2. Adds two feeds not currently in `agencies.yml`: Cities of South Gate and Sierra Madre
> Update gtfs feeds now hosted by LACMTA

- airflow/dags/rt_views/gtfs_rt_extraction_errors.sql
- docs/datasets_and_tables/gtfs_rt.md
Created a new table in BigQuery Views to visualize gtfs_extraction_errors from the cloud gtfs_rt_logs.std_out 
Gtfs_rt_Extraction_errors was added to cal-itp-data-infra sandbox, Then linked up Metabase to show the GTFS RT Extraction Errors by Day in metabase for easy visualization.  Rather than counts we decided to keep the raw rows so people could drilldown from summaries in metabase. We tested out two tables in metabase, Count of all errors by day (GTFS RT || Feed Extraction Errors by Day), and Count of distinct errors by day (GTFS RT || Distinct Feed Extraction Errors by Day)
@evansiroky it is worth mentioning that the urls might include the api keys which are in the URL. Not sure how you want to handle that.
> feat(gtfs-rt) SQL script to have airflow view for metabase

- airflow/dags/rt_views/gtfs_rt_extraction_errors.sql
https://github.com/cal-itp/data-infra/pull/879 had a change that include invalid YAML in the Gusty top matter. Unfortunately, it appears nobody (myself included) tested whether airflow would start after adding a change to one of the DAG tasks. This change fixes it and the local sandbox DAG has ran successfully (as opposed to production which failed today).
> Fix broken yaml

- CODEOWNERS
- docs/kubernetes/JupyterHub.md
- kubernetes/apps/charts/jupyterhub/values.yaml
This PR updates the hub image to what should be the current version. I'd forgotten to commit it, and noticed recently the version must have reverted back to the one committed here.
Added @charlie-costanzo to CODEOWNERS, and am recording a screencast right now on the process of building an updating images.
edit: rolled in documentation to address https://github.com/cal-itp/data-infra/issues/668
> restore jupyterhub image, and commit to this repo

- docs/analytics_publishing/how_to_publish.md
- docs/analytics_tools/notebooks.md
- docs/analytics_tools/overview.md
- docs/analytics_tools/python_libraries.md
- docs/analytics_tools/saving_code.md
- docs/analytics_welcome/how_we_work.md
This PR will include:
/analytics_welcome/how_we_work
* Adding link to past lunch n learn recordings
/analytics_tools/python_libraries
* _shared_utils: add that you may need to restart the kernel after making
/analytics_tools/welcome
* add URL to querying with SQL section in /analytics_tools/notebooks
/analytics_tools/saving_code:
* per  Laurie - "I think this line is unnecessary? At least for me it failed fatally and said that the remote origin was already set"
* `git remote add origin git@github.com:cal-itp/data-analyses.git`
* (Step 9)
/analytics_tools/notebooks
* Link to a resource on how to use the markdown cells or best practices (like being able to view 2 notebooks at once, re-arranging cells, splitting cells, etc)
* @amandaha8 found that "these little tricks were not so obvious to …
> Misc Docs Fixes - Review Findings

- docs/_config.yml
- docs/analytics_tools/python_libraries.md
This PR will:
/analytics_tools/python_libraries:
* Fix broken code cells in queries in siuba section caused by tables that no longer exist
/.config
*  Change 'allow errors' to false in config
> Fix broken code cells in python_libraries

- .gitignore
Adding [.DS_Store](https://en.wikipedia.org/wiki/.DS_Store) to the gitignore.
> chore: gitignore Mac .DS_Store files

- kubernetes/apps/charts/jupyterhub/values.yaml
Updates the version of Jupyterhub running on the k8s cluster from hub-v2 to hub-v3. This update includes the backlog of packages requested by analysts.
> Update version of jupterhub image running on k8s cluster

- CODEOWNERS
Updating the Code Owners now that Michael has moved on to a different position. It might be worth further discussion if we want to change the owners we currently have and/or add @lauriemerrell @chriscauley @charlie-costanzo as reviewers
> Update Code Owners- remove former code owners

- airflow/data/agencies.yml
- airflow/data/headers.yml
This PR does 2 things:
- Adds the Swiftly RT URLs for San Joaquin Regional Transit District
- Refactor the headers file.
- Add San Joaquin Regional Transit District
- Use a single super Swiftly auth key. It appears that all the other transit agencies associated with our Caltrans Swiftly key have been given access via the Cal-ITP key. 
- Order agencies by ITP ID
> Add San Joaquin Swiftly RT URLs

- .github/workflows/update_gcloud_requirements.yml
Something missed in https://github.com/cal-itp/data-infra/pull/851 was making sure the reinstallation of requirements was done in the airflow v2 instance instead of in the v1 instance. This fixes that.
> Make update airflow requirements point to airflow v2 instance

- kubernetes/gke/config-nodepool.sh
Ongoing investigations in light of infrastructure-related reliability issues found that two of our three cluster nodes appeared to be flapping between a healthy and unhealthy state. This ultimately resulted in problems with workloads running, as GKE was repeatedly rebooting these nodes in an attempt to repair them. This change reflects a rotation of the node pool in order to cycle out these unhealthy nodes.
> Nodepool apps v2

- kubernetes/apps/manifests/gtfs-rt-archive/app.yaml
A memory leak has been discovered in the currently running 1.2-r2
release. In order to mitigate risk to colocated workloads while the
memory leak is worked on, memory consumption limits are being applied to
the archiver deployment.
> gtfs-rt-archive/app.yaml: apply memory limits

- airflow/dags/gtfs_views/gtfs_schedule_stg_daily_service.sql
For calitp_id 170, 16, and 48, extracted at/deleted values were null in gtfs_schedule_fact_daily_trips, this was due to those columns not being selected in a calendar_dates subtable prior to the join with calendar_dates that is used to populate gtfs_schedule_fact_daily_trips. By adding those to the select column and the join column, we are able to populate those values for calitp_id 170, 16, and 48. I also verified that it did not alter other calitp result values. Tested with calitp_id 98 to verify it didn't alter other results.
> bug(extracted/deleted): added Coalesce for each subtable(calendar/calendar_dates) to remove null values 

- docs/_toc.yml
- docs/airflow/dags-maintenance.md
- docs/datasets_and_tables/gtfs_rt.md
- docs/datasets_and_tables/gtfs_schedule.md
- docs/datasets_and_tables/mst_payments.md
- docs/datasets_and_tables/transitdatabase.md
- docs/datasets_and_tables/views.md
Moving the DAG maintenance information from the `Analysts/Datasets and Tables` chapter of Data Services documentation to the new `Developers/Airflow/DAGs Maintenance` section of docs
As detailed in issue #783 :
> - move the airflow sections into the dedicated airflow part of the docs
> - put a link to the corresponding airflow section from each datasets page
> - match up the names of corresponding datasets and airflow docs
> chore(docs): Moving DAG maintenance information

- airflow/docker-compose.yaml
The original value is pointing at our airflow-v1 cluster which is due for retirement soon
I'm not positive this is the only place we need to make any change, as I'm not sure where people have been getting the service account auth file they use for this and whether that service account has the same access to the v2 cluster as it did to the v1 cluster
Before this get merged, could someone who already had a working local setup for running airflow jobs that run on k8s switch to this branch and restart your docker containers (e.g. `docker-compose down && docker-compose up`) and verify everything still works as expected
> fix(airflow): use v2 cluster in local dev envs

- airflow/docker-compose.yaml
Re-add the Airflow Google Cloud Default connection ID to allow local running of PodOperator DAG tasks (specifically, to allow testing of #991).
> chore(airflow): restore google cloud connection ID

- airflow/docker-compose.yaml
I'm brand new to Airflow development, and have no sense of best practices, but while I was trying to get up and running locally I found it really annoying in my venture to run DAGs that activating any DAG immediately starting spawning months worth of backfilling task instances.
Setting this as part of the local dev environment defaults seemed to make sense to me. This won't affect deployed environments at all since the `docker-compose.yaml` only defines the local dev environments. It seems to successfully prevent activated DAGs from immediately spawning tons of catchup tasks so you can, as a local dev, start with just spawning one task
> fix(airflow/local): disable catchup by default

- airflow/data/agencies.yml
The AC Transit 511 agency key was incorrectly set to the Capitol Corridor agency key. This fixes #1017.
This PR updates `agencies.yml` in order to....
Update the following gtfs datasets:
- AC Transit 511 feeds
- static
- trip updates
- vehicle positions
> Use correct AC transit 511 agency key

- .github/workflows/push_to_gcloud.yml
- airflow/data/agencies.yml
- script/agencies_verify.py
- script/requirements.txt
- script/yml_convert.py
- services/gtfs-rt-archive/src/gtfs_rt_archive/mapperfns.py
Fixes #908. This adds an action to the push_to_gcloud workflow that runs `git diff airflow/data/agencies.yml OLD_HASH NEW_HASH` to get a list of all urls that have been added to the agencies.yml file. It then loads the actual agencies.yml file and downloads any urls matching the domains found in the diff.
Update: As you can see from the lovely column of red X's in the commit history, I did eventually get the workflow to run successfully. I didn't modify any actual urls so it passed with 0/0 urls checked.
* Checkout this branch and run `python script/agencies_verify.py /path/to/agencies.yml /path/to/headers.yml` to verify all urls. Note that on my current list (taken from the google bucket yesterday) the api.actransit.org urls cause 3xHTTP404 errors.
* Now do `git diff agencies.yml f18ac09 …
> adding script for testing urls

- .github/workflows/check-requirements.yml
- .gitignore
- airflow/requirements.txt
I broke the Airflow requirements.txt; for some reason, the composer install failed even though typer should be compatible with click 8.0.0; this should? fix things.
I think we need a CI/CD task to test installing the requirements.
> fix: pin click 8.0.0

- airflow/plugins/operators/realtime_to_flattened_json_operator.py
- airflow/requirements.txt
Adds retries and exception handling to the rt_loader job. Fixes https://github.com/cal-itp/data-infra/issues/1049.
Currently, the RT parsing operator does not retry on any errors, which includes intermittent issues interacting with GCS. This PR adds a single retry to specifically handle ClientResponseError from aoihttp, but also generically captures all exceptions (without retrying) to prevent any one exception from stopping the whole job. Any exceptions are still thrown after all feeds are processed.
Some example output:
```
[2022-02-08 13:53:31,831] {_common.py:104} INFO - Backing off handle_one_feed(...) for 0.1s (aiohttp.client_exceptions.ClientResponseError: <unprintable ClientResponseError object>)
[2022-02-08 13:53:31,905] {_common.py:119} ERROR - Giving up handle_one_feed(...) …
```
> Add feed-level retries and exception handling to RT parsing operator

- airflow/dags/rt_loader/external_service_alerts.sql
- airflow/dags/rt_loader/external_trip_updates.sql
- airflow/dags/rt_loader/external_vehicle_positions.sql
Resolves #1051 by:
* Explicitly defining the JSON schema in `external_vehicle_positions.sql`
* Adding the [`ignore_unknown_values` flag](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json#json_options) to all the external table tasks here; this will allow rarely-used fields to be ignored instead of preventing access to the table (I am not sure if we want this to be enabled long-term, but it seemed like it would help smooth things out here in the short term)
**Note that this PR _narrowly_ resolves the issue by focusing only on vehicle positions data.** I wanted to unblock @edasmalchi and vehicle positions is significantly simpler than trip updates. If this approach works out well, we can apply it to service alerts and trip updates as well in a subsequent PR. 
Heads up …
> fix(gtfs-rt): define json schema for vehicle positions external table

- docs/_toc.yml
- docs/airflow/local-setup.md
- docs/analytics_onboarding/overview.md
Adding how to check the logs of PodOperators when running airflow locally
This PR updates the `docs/developers/airflow/local-setup` in order to....
Add the information outlined in #1055 related to:
* navigating GCP to find logs for PodOperators in the airflow UI when running locally
* fiding the name of the pod when you don't know it
Misc Changes
* reordered TOC to make more sense in the airflow section
* updated phrasing on the `technical onboarding` chapter welcome page
> docs(airflow): adding how to check the logs of PodOperators

- airflow/dags/rt_loader/external_vehicle_positions.sql
Some of the data types I picked in #1056 were wrong (I misunderstood how the data types in the [GTFS documentation](https://gtfs.org/reference/realtime/v2/) mapped to the [BigQuery data types](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric_types)), and I didn't catch them because of the limited testing data I used in the `gtfs-data-test` bucket. 
This PR fixes `NUMERIC` (and one `INT64`) to be the correct `FLOAT64` type. 
To test this, I ensured that queries that were failing with the current definition succeed with the new definitions on the actual prod data by making an external table in `staging` that still reads data from the prod RT bucket (table is: `cal-itp-data-infra-staging.gtfs_rt.vehicle_positions_test_prod_source`)
This PR updates the …
> fix(gtfs-rt): fix data types for vehicle positions external table schema

- airflow/data/agencies.yml
Change the static URL for Foothill Transit; the URL we were using was out of date. Added the new URL from [their website](http://foothilltransit.org/about/developer-resources/) (shoutout @edasmalchi for grabbing that 🙂).
This PR updates `agencies.yml` in order to....
Update the following gtfs datsets:
- Foothill Transit (ITP ID 112) static data -- change the URL as described above
> fix(gtfs-schedule): fix foothill transit static url

- airflow/README.md
- airflow/dags/gtfs_loader/calitp_feed_latest.sql
- airflow/dags/gtfs_loader/calitp_feed_status.sql
- airflow/dags/gtfs_loader/gtfs_schedule_tables_load.py
- airflow/dags/rt_loader/create_validation_params.py
- airflow/dags/rt_loader/external_calitp_validation_params.sql
- airflow/dags/rt_loader/load_rt_validations.yml
- airflow/dags/sandbox/op_pod_operator.yml
Addresses #787
(Andrew)
Realizing I don't have the Airflow template here.
The pertinent tasks
I've tested and confirmed that this runs successfully on an hour of data in approximately 30 minutes across all feeds. I'd like to merge this in so we get at least some data going across the board. We can follow-up with the following.
1. Make validation data queryable via bigquery
2. Change how we sample, and/or validate more data
3. Point at the new validator image one https://github.com/cal-itp/gtfs-rt-validator-api/pull/5 is merged
4. Maybe most importantly, be aware of the validity periods of GTFS schedules; this shouldn't really be a problem right now, but does have implications for backfilling, especially
> Validate an hour of data across all feeds

- airflow/dags/gtfs_views_staging/feed_info_clean.sql
Resolves #1079 by changing `feed_info_clean` to use `SELECT DISTINCT` rather than `SELECT` to drop the full duplicate rows in the current Foothill Transit feed. This issue is causing the GTFS Guidelines dashboard to not populate because of the `vews.gtfs_schedule_dim_feeds` failure (and then subsequent downstream failures). 
I submitted #1093 as a follow up for this, however that seemed less important than getting this data flowing again (and, as noted in #1093, Foothill Transit *is* throwing a `more_than_one_entity` validation warning from the GTFS validator for this file, as it should be; that validation is preserved even if the duplicate is dropped here.)
I confirmed that the only row removed with this change is the one Foothill Transit duplicate; no other rows are affected (table …
> fix(gtfs schedule): remove duplicate feed_info entries

- airflow/dags/rt_loader/load_rt_validations.yml
See https://cal-itp.slack.com/archives/C0332307HKM/p1645073980149109 for discussion.
Currently, the RT validator Airflow job fails after all multiprocessing is finished, as the final status JSON file is uploaded with a double-prefixed GCS URL, i.e. `gs://gs://gtfs-data-test...`. This removes the prefix since `get_bucket()` already returns a protocol prefix.
> fix: avoid double prefixing gcs bucket url

- airflow/dags/rt_loader_files/calitp_files_process.py
- airflow/dags/rt_loader_files/external_calitp_files.sql
- airflow/dags/rt_loader_files/rt_views_gtfs_rt_fact_files.sql
- script/requirements.txt
Expose the existing `gtfs_rt.calitp_files` table in `views` so we can use it in Metabase. I also reordered the dependencies so that they make sense (we identify the files, then we recreate the external table, then we make the view.)
Notes about things I've done that reviewers may find controversial:
- I left this in the `rt_loader_files` DAG rather than the `views` DAG. I did this because I think we will want this `views` table to update more often than daily. After this merges I think we should consider changing this DAG to run hourly or similar. 
- I pre-extracted date, hour, minute from `calitp_extracted_at`. This is kind of duplicative but I really think everyone is going to need these columns and working with them manually in Metabase all the time would be annoying. 
This PR updates …
> feat(gtfs-rt): add calitp files to views

- airflow/dags/rt_loader_files/rt_views_gtfs_rt_fact_files_wide_hourly.sql
Make a wide hourly view (count by hour by day) of file saves for GTFS RT data.
This is to facilitate visualization in Metabase.... I tried really hard to do it with pivot tables in Metabase and it just was too slow and doesn't allow much flexibility. Decided it was worth just doing on the BQ side. 
This PR updates the `rt_loader_files` DAG in order to add the following DAG tasks:
- `rt_views_gtfs_rt_fact_files_wide_hourly`: takes existing `gtfs_rt_fact_files` and creates a wide hourly view of it
> feat(gtfs-rt): wide hourly view of calitp files

- airflow/dags/rt_views/gtfs_rt_fact_daily_feeds.sql
This creates a table listing all the RT URLs from `agencies.yaml` by date. This can be left-joined with the other RT files views to help identify feeds that are missing data entirely (i.e., feeds that we had URLs for on the given date but didn't get any data pulled).
**Note that this table pulls from the _schedule_ pipeline** -- I didn't see any reason to duplicate a bunch of existing logic. The RT URLs from `gtfs_schedule_fact_daily_feeds` come from `agencies.yaml`, which is what we want. 
`extraction_errors` fails because it hits the query limit, unrelated.
This PR updates the `rt_views` DAG in order to add the following DAG tasks:
- `gtfs_rt_fact_daily_feeds`: A long view of all RT URLs present by feed by date
> feat(gtfs-rt): create fact_daily_feeds

- airflow/dags/airtable_views/california_transit_gtfs_datasets.sql
- airflow/dags/airtable_views/california_transit_gtfs_service_data.sql
- airflow/dags/airtable_views/california_transit_map_gtfs_datasets_aggregated_to_x_self.sql
- airflow/dags/airtable_views/california_transit_map_gtfs_datasets_dataset_producers_x_organizations_gtfs_datasets_produced.sql
- airflow/dags/airtable_views/california_transit_map_gtfs_datasets_dataset_publisher_x_organizations_gtfs_datasets.sql
- airflow/dags/airtable_views/california_transit_map_gtfs_datasets_gtfs_service_mapping_x_gtfs_service_data_gtfs_dataset.sql
- airflow/dags/airtable_views/california_transit_map_gtfs_service_data_reference_static_gtfs_service_x_self.sql
- airflow/dags/airtable_views/california_transit_map_organizations_mobility_services_managed_x_services_provider.sql
- airflow/dags/airtable_views/california_transit_map_organizations_mobility_services_operated_x_services_operator.sql
- airflow/dags/airtable_views/california_transit_map_organizations_parent_organization_x_self.sql
- airflow/dags/airtable_views/california_transit_map_services_gtfs_services_association_x_gtfs_service_data_services.sql
- airflow/dags/airtable_views/california_transit_map_services_paratransit_for_x_self.sql
- airflow/dags/airtable_views/california_transit_organizations.sql
- airflow/dags/airtable_views/california_transit_services.sql
- airflow/dags/airtable_views/dummy_airtable_loader.yml
Restructure dependencies for the `airtable_views` DAG to resolve #1080. Basically, it seems likely that there's a gusty bug such that specifying multiple `external_dependencies` is not working correctly. 
Also, it seems that elsewhere in our pipeline when we have a "staging" and  "views", we usually have the views depend on a `DummyOperator` that waits for the entire staging DAG to complete. 
So, I am making the Airtable flow align with that convention, which also addresses the original problem. 
This PR updates the `airtable_views` DAG in order to standardize the external dependency handling.
Adds the following DAG tasks:
- `dummy_airtable_loader.yml` - waits for `airtable_loader` to complete, following pattern from elsewhere in our codebase
Updates the following DAG tasks:
- all …
> fix(airtable): add dummy airtable loader for external dependencies

- airflow/dags/rt_views/gtfs_rt_fact_daily_feeds.sql
Fixes dependency reference.
This PR updates the `rt_views` DAG in order to updates the following DAG tasks:
- `gtfs_rt_fact_daily_feeds` - fixes the dependency to be an external dependency (so this will actually wait for the `gtfs_schedule` task to run)
> fix(gtfs-rt): fix external dependency reference

- airflow/dags/rt_loader/external_service_alerts.sql
- airflow/dags/rt_loader/external_trip_updates.sql
Resolves #1104 (and therefore resolves #1002) by defining schemas for trip updates and service alerts data. 
This PR updates the `rt_loader` DAG in order to update the following DAG tasks:
- `external_trip_updates`: define schema 
- `external_service_alerts`: define schema
> Fix gtfs rt define schemas for trip updates & service alerts

- airflow/dags/payments_views/payments_rides.sql
- airflow/dags/payments_views/sbmtd_transactions.sql
- airflow/dags/payments_views_staging/stg_cleaned_micropayment_device_transactions.sql
- airflow/dags/payments_views_staging/stg_cleaned_micropayments.sql
- airflow/dags/payments_views_staging/validate_cleaned_micropayment_device_transactions.sql
We're currently enforcing that a transaction (essentially a tap) is only associated with one micropayment (essentially, we thought, a trip). However, transactions _can_ be associated with multiple micropayments. Normally we would expect only 1 micropayment per transaction except in the case of refunds, where we will see an additional micropayment with `type='CREDIT'`. This PR takes the distinction between DEBIT and CREDIT micropayments into account.
Resolves #1068
This PR updates tasks across the `payments_views_staging` and `payments_views` DAGs.
* `payments_views`
* `payments_rides`
* Only count DEBIT micropayments as rides
* Add a `refund_amount` column to account for refunds
* `sbmtd_transactions`
* Only count DEBIT micropayments
* `payments_views_staging`
* …
> fix(payments): Correct cardinality for micropayments:transactions

- airflow/dags/rt_loader_files/calitp_files_process.py
- airflow/dags/rt_loader_files/rt_views_gtfs_rt_fact_files_wide_hourly.sql
Add a "daily total" column to the wide hourly view of the RT files. This will allow us to sort dashboards on this column to more easily identify issues. 
Also makes the `calitp_files` loading use `get_bucket` so we can actually run it on test files. 
This PR updates the `rt_loader_files` DAG in order to update the following DAG tasks:
- `fact_files_wide_hourly`: Adds a daily total column for easier summarizing/sorting
- `calitp_files_process`: Uses `get_bucket` instead of hard-coding production path
> Feat gtfs rt daily file total

- airflow/data/agencies.yml
@atvaccaro and I discovered that the SacRT RT URLs that we currently have in `agencies.yml` no longer work. They currently direct to a login page. On the [SacRT website](http://www.sacrt.com/schedules/gtfs.aspx), they link to new URLs that seem to work (we manually verified that `vehicles` produces a valid proto file.) 
- Changed the URLs for the trip updates and vehicle positions; added the new service alerts URL and added all its service relationships (I copied the structure of all the relationships that trip updates had)
This PR updates `agencies.yml` in order to fix add the following gtfs datasets:
- Sacramento Service Alerts
Update the following gtfs datsets:
- Sacramento Trip Updates (new URL)
- Sacramento Vehicle Positions (new URL)
> fix(agencies.yaml): correct sacrt rt urls

- airflow/dags/rt_loader/create_validation_params.py
- airflow/dags/rt_loader/external_validation_service_alerts.sql
- airflow/dags/rt_loader/external_validation_trip_updates.sql
- airflow/dags/rt_loader/external_validation_vehicle_positions.sql
- airflow/dags/rt_loader/load_rt_validations.yml
- airflow/plugins/operators/sql_query_operator.py
Step towards closing https://github.com/cal-itp/data-infra/issues/787 and essentially closes https://github.com/cal-itp/data-infra/issues/786. This PR changes the RT validation to use v0.0.4 of the RT validator wrapper which will write out files identified with the itp_id, url, and entity type. It also points the external tables at the new, proper output paths for each entity type.
This takes awhile to run fully but I've confirmed with running approximately 10 files.
```
[2022-02-23 23:31:10,160] {pod_launcher.py:149} INFO - idx=8 gtfs_schedule_path='gs://gtfs-data-test/schedule/2022-02-11T00:00:00+00:00/259_0' gtfs_rt_glob_path='gtfs-data/rt/2022-02-11T00:*/259/0/*vehicle_positions*' out_dir=None result_bucket='gs://gtfs-data-test/rt-processed/validation/2022-02-11/validation_results/259/ …
```
> generate and use new validation params and arguments for RT validation, and load into bigquery

- airflow/data/agencies.yml
After a check performed by @o-ram ([see doc](https://docs.google.com/spreadsheets/d/1bBF2xoE2Qxps0aYrIW_VNv1CiYH_Ysoc/edit#gid=926147007)), this PR updates and removes a number of agencies to reflect the current state of feeds.
This PR updates `agencies.yml` in order to....
Via a conversation with @antrim and examination of their website, they're no longer running fixed-route service.
Does not exist anymore (see https://www.ci.ceres.ca.us/220/Ceres-Area-Transit-CAT). Became part of Stanislaus Regional Transit Authority (their website shows [ROUTE 44 - FORMERLY CERES AREA TRANSIT](https://www.stanrta.org/275/Route-44-Formerly-Ceres-Area-Transit)).
Confirmed via email that it's now a part of SacRT feed.
[Its website](https://www.lawndalecity.org/government/departments/community_services/lawn …
> Fix some expired feeds in agencies.yml

- airflow/data/agencies.yml
Updates Amtrak's GTFS Schedule  URI in `agencies.yml` to be a permalink on the amtrak.com website.
Closes #1143
This PR updates `agencies.yml` in order to:
-  update Amtrak's GTFS Schedule  URI in `agencies.yml` to be a permalink on the amtrak.com website.
> data(gtfs): update Amtrak

- airflow/data/agencies.yml
We were using the wrong URL for the AC Transit API! This fixes that.
This PR updates `agencies.yml` in order to update all the AC Transit API GTFS-RT URLs to the correct URL.
> Correct AC Transit API URLs

- airflow/data/agencies.yml
Some consolidation of data about certain transit agencies have occurred within Tulare County.
With the new aggregated feed made available via Tulare County Regional Transit Agency, this PR serves as both a status update and correction to the GTFS data being downloaded from Tulare County transit agencies. This update makes `agencies.yml` up-to-date for the 5 transit services (6 if you count both of Dinuba Area Regional Transit services) serving Tulare County as follows:
- removed from agencies.yml
- data can now be found in agencies.yml feed associated with ITP ID 474 (Tulare County Regional Transit Agency)
- *Airtable needs to be updated to reflect that the Dinuba Area Regional Transit services can now be found in the Tulare County Regional Transit Agency gtfs dataset*
- removed from …
> Update agencies.yml to reflect current Tulare County operations

- airflow/dags/gtfs_views/gtfs_schedule_dim_feeds.sql
- airflow/dags/gtfs_views/gtfs_schedule_dim_pathways.sql
- airflow/dags/gtfs_views/gtfs_schedule_dim_routes.sql
- airflow/dags/gtfs_views/gtfs_schedule_dim_stop_times.sql
- airflow/dags/gtfs_views/gtfs_schedule_dim_stops.sql
- airflow/dags/gtfs_views/gtfs_schedule_dim_trips.sql
- airflow/dags/gtfs_views/gtfs_schedule_stg_calendar_long.sql
- airflow/dags/gtfs_views/gtfs_schedule_stg_daily_service.sql
- airflow/dags/gtfs_views/reports_gtfs_schedule_index.sql
- airflow/dags/gtfs_views/validation_dim_codes.sql
- airflow/dags/gtfs_views/validation_fact_daily_feed_notices.sql
- airflow/dags/gtfs_views_staging/agency_clean.sql
- airflow/dags/gtfs_views_staging/attributions_clean.sql
- airflow/dags/gtfs_views_staging/calendar_clean.sql
- airflow/dags/gtfs_views_staging/calendar_dates_clean.sql
- airflow/dags/gtfs_views_staging/calitp_feeds.sql
- airflow/dags/gtfs_views_staging/fare_attributes_clean.sql
- airflow/dags/gtfs_views_staging/fare_rules_clean.sql
- airflow/dags/gtfs_views_staging/feed_info_clean.sql
- airflow/dags/gtfs_views_staging/frequencies_clean.sql
- airflow/dags/gtfs_views_staging/levels_clean.sql
- airflow/dags/gtfs_views_staging/pathways_clean.sql
- airflow/dags/gtfs_views_staging/routes_clean.sql
- airflow/dags/gtfs_views_staging/stop_times_clean.sql
- airflow/dags/gtfs_views_staging/stops_clean.sql
- airflow/dags/gtfs_views_staging/transfers_clean.sql
- airflow/dags/gtfs_views_staging/translations_clean.sql
- airflow/dags/gtfs_views_staging/trips_clean.sql
- airflow/dags/gtfs_views_staging/validation_notices_clean.sql
_🚨 Note that I am requesting to merge this into the `refactor-gtfs-views-staging` branch. We need to do a bunch of PRs that should move together (see #1137). I would like to get them reviewed by merging into this placeholder branch, and then just merge that whole branch at once into main to avoid having to be concerned with the timing of merging a bunch of PRs one by one into main._ 
This PR does three things:
1. **New dataset:** Creates a `gtfs_views_staging` BigQuery dataset, updates all the `gtfs_views_staging` tasks creating `_clean` data to write to this dataset, and updates all `gtfs_views` consumers of this data to reference this new dataset. This separates the `clean` GTFS schedule data out from the `type2`. 
* See open question on #1073 -- I think we should just set the variable …
> Refactor gtfs views staging cleaning

- airflow/dags/gtfs_schedule_history/stops.yml
- airflow/dags/gtfs_views_staging/stops_clean.sql
This PR refactors how data types are applied for `stop_lat` and `stop_lon` to resolve #1148. 
Currently we assert that they are floats in `gtfs_schedule_history`, but there's no standard way for the pipeline to handle data type violations at that point. 
This PR specifically casts them as floats in `gtfs_views_staging` instead, which is the appropriate place to handle data typing issues. This will allow the bad Amtrak data into the warehouse as a null (there will be a record with a latitude but no longitude), but we thought that was a good first step to unblock the pipeline.
See #1151 for thoughts on subsequent steps we might want to take.
🚨 **After merging this PR, we will need to take the following manual steps _in this order_:**
1. Manually re-run the `gtfs_schedule_history` DAG to get …
> Hotfix stops typing

- airflow/dags/gtfs_schedule_history2/merge_updates.py
`merge_updates` processes all the different GTFS data types but doesn't really give any indication of progress, which is annoying when testing. This just adds a single logging statement to let us know what file type it's working on. 
It can't actually complete because of stop_times but here's a screenshot of it running showing the logging statements
This PR updates the `gtfs_schedule_history2` DAG in order to updates the following DAG tasks:
- `merge_updates`: add logging
> chore(gtfs-schedule): add minimal logging to merge_updates

- airflow/dags/airtable_views/california_transit_gtfs_datasets.sql
This PR adds the `uri` and `future_uri` fields to the `views.airtable_california_transit_gtfs_datasets` dataset.
This PR updates the `airtable_views.california_transit_gtfs_datasets` DAG in order to add the `uri` and `future_uri` fields to the `views.airtable_california_transit_gtfs_datasets` dataset.
> Add uri and future uri to airtable gtfs dataset view

- airflow/dags/rt_views/gtfs_rt_fact_daily_validation_errors.sql
Adds a rolled-up daily view of validation errors for RT feeds.
Closes https://github.com/cal-itp/data-infra/issues/357
Adds a new DAG task `gtfs_rt_fact_daily_validation_errors` under `rt_views`.
```
field                    test  passed
0                                           error_id              check_null    True
1                                               date              check_null    True
2                                        occurrences              check_null    True
3                                  calitp_url_number              check_null    True
4                                      calitp_itp_id              check_null    True
5                                       rt_feed_type              check_null    True
0  calitp_itp_id, calitp_url_number, …
```
> add new daily validation errors fact table

- airflow/data/agencies.yml
Add RT URLs for 4 GRaaS agencies. These are not production rt feeds yet - all are in testing/development. For this reason, we are hiding the server URL within a GH secret. Here is the request to add the secret, which blocks one of the tests from passing: https://github.com/cal-itp/data-infra/pull/1163
Note that the url is formatted in the way that it is because the yml value needs to start with a string (not a variable) in order to pass the tests.
- [x ] Run `pre-commit run --all-files` to make sure markdown/lint passes
- [ x] Link this pull request to all issues that it will close using keywords (see GitHub docs about [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-reque …
> Gtfs add graas rt urls

- kubernetes/apps/manifests/gtfs-rt-archive/archiver-app-vars.yaml
Per conversation on slack, change calitp_log_level to info instead of debug to help free up some space for RT-Archiver. Debug is a lower level than info, any message logged with info gets printed if the root level set is debug. So by changing it to info, we shall trim some extraneous logs.
> change calitp_log_level to info instead of debug

- kubernetes/apps/charts/jupyterhub/values.yaml
This PR effects:
`kubernetes/apps/charts/jupyterhub/values.yaml`
* Bumps up release version of jupyterlab image on kubernetes cluster to include new version of `calitp` package
> jupyterhub(image): bumped up calitp in jupyter image

- kubernetes/apps/charts/jupyterhub/values.yaml
Revision of PR 1171
This PR effects:
`kubernetes/apps/charts/jupyterhub/values.yaml`
* Bumps up release version of jupyterlab image on kubernetes cluster to include new version of calitp package
Checklist for all PRs
> jupyterhub(image): revised - bumped up version of jupyter image

- airflow/data/agencies.yml
Refs #1181
This PR updates `agencies.yml` in order to properly associate Burbank Bus's RT URLs with the appropriate type.
> Correct Burbank Bus's RT URLs

- docs/_toc.yml
- docs/architecture/architecture_overview.md
Migrating the Google Drawing about the data services architecture to Mermaid / Markdown to integrate it into the docs. (Updated version of #1173 where I messed up the git tree, seemed easier to just make a new PR).
Resolves #1134 
This PR updates `architecture/architecture_overview` in order to integrate our existing architecture diagram into the docs. It also updates the TOC to get the page into navigation.
> docs(developers): add architecture diagram

- kubernetes/apps/manifests/gtfs-rt-archive/app.yaml
- kubernetes/gke/config-nodepool.sh
- kubernetes/gke/nodepool-up.sh
After getting a chance to dig through Grafana, we found substantial evidence that there may be a node-based CPU bottleneck with the archiver. To address this, we have deployed a node pool which:
1. Does not run any other workloads, allowing the archiver to fully utilize all cores for its own work
2. Doubles CPU capacity to 8 cores from 4
3. Moves to dedicated core instances rather than shared cores
This PR reflects the work performed to implement these changes.
> Gtfs rt archiver upsize

- airflow/dags/rt_views/gtfs_rt_fact_daily_validation_errors.sql
Brings back service alert validation output into the unioned validations table. Previously, we didn't have any errors, so BigQuery threw a mismatching column error.
> enable service alert validations in the unioned table

- airflow/dags/payments_views_staging/stg_cleaned_authorisations.sql
Add a first draft of a cleaned version of the littlepay authorisations table, based on investigation in [this notebook](https://github.com/cal-itp/data-analyses/blob/main/littlepay_data_issues/authorisations.ipynb).
Closes #797 
This PR updates the `payments_views_staging` DAG in order to add a step to create a cleaned version of the littlepay authorisations table: `payments.stg_cleaned_authorisations`
Adds the following DAG tasks:
- `payments.stg_cleaned_authorisations`
> feature(payments): Add cleaned authorisations table

- services/gtfs-rt-archive/src/gtfs_rt_archive/threads/ticker.py
Currently the loop is `while True: sleep(20); tick()`. But since `tick()` isn't infinitely fast the actual delay is slightly larger than 20 seconds. This just says "sleep however much time until time.time() is a multiple of 20". This will stop the drift and make it so every timestamp is a multiple of 20.
> only tick when seconds are evenly divisible by 20

- airflow/data/agencies.yml
This adds Elk Grove Transit to agencies.yml.
This PR updates `agencies.yml` in order to add Elk Grove Transit.
Even though this agency is now being operated by SacRT, it is not showing up in SacRT's feed. I confirmed this by running SacRT's feed and Elk Grove's feed through [gtfs-to-geojson](https://github.com/BlinkTagInc/gtfs-to-geojson) and then comparing the outputted stops and shapes in QGIS:
@e-lo as the airtable data maintainer, the `gtfs service data` table should be updated to note that the Sacramento Regional Schedule and RT feeds do not yet contain Elk Grove Transit.
> Add Elk Grove Transit

- airflow/data/agencies.yml
This updates the Soltrans trip updates URL to be the one on their website.
As discussed in https://github.com/cal-itp/data-infra/issues/1178#issuecomment-1069383947, this updates the Soltrans trip updates URL to be the one in airtable and the one on their website. The other URL does work, but this other one seems to have more info.
> Use different Soltrans trip updates URL

- airflow/dags/payments_views/mst_transactions_gtfs_enhanced.sql
- airflow/dags/payments_views/payments_rides.sql
- airflow/dags/payments_views/sbmtd_transactions.sql
- airflow/dags/payments_views_staging/stg_cleaned_device_transactions.sql
_🚨 Merging into refactor_gtfs_views_staging to merge all #1137 fixes together._
This PR removes all references to `gtfs_schedule` data in `payments_views` and replaces them with references to more appropriate `views` data. This will address #1140 once it merges as part of #1157. 
Making this adjustment requires:
1. Changing the tables (to reference `views.gtfs_schedule_dim_routes` instead of `gtfs_schedule.routes`, for example)
2. Making the merges date-aware (since `gtfs_schedule` is latest-only, joins with it don't have to account for dates; joins with `dim` tables need to take account of the slowly-changing dimension)
3. Trimming IDs on the payments side. I did this as a precaution; I don't think that this data is affected by leading/trailing whitespace issues based on a few diagnostic …
> Fix payments point to gtfs views

- airflow/dags/gtfs_schedule_history/attributions.yml
- airflow/dags/gtfs_views_staging/attributions_clean.sql
_🚨 Note that I am requesting to merge this into the `refactor-gtfs-views-staging` branch. We need to do a bunch of PRs that should move together (see https://github.com/cal-itp/data-infra/issues/1137). I would like to get them reviewed by merging into this placeholder branch, and then just merge that whole branch at once into main via https://github.com/cal-itp/data-infra/pull/1157 to avoid dealing with the timing of merging a bunch of PRs one by one into main._
Will address #1155 once #1157 is merged. 
Stops asserting that a bunch of fields in `attributions` are integers on ingest (in the `gtfs_schedule_history` external table) and instead ingest them as strings and `CAST` to integers on `_clean`. We can change this to `SAFE_CAST` if we ever need to. 
**Note: When this is merged, we need …
> fix(gtfs-schedule): attributions - don't assume integers on ingest

- airflow/dags/macros.py
_🚨 Merging into `refactor_gtfs_views_staging` to merge all of #1137 fixes together._ 
Realized that my logic in #1162 might lead to unexpected outcomes because of issues like #1184 (ideally they **should** be equivalent, but right now they're not). I refactored the "get latest" logic to better match the way that it is done currently. 
Technically this doesn't touch any DAG task objects directly (just the macro that they call), but I did confirm that `gtfs_schedule` still runs (except `stop_times` which hits the query limit):
> fix(gtfs-schedule): fix get-latest logic

- airflow/dags/gtfs_views/gtfs_schedule_dim_shapes.sql
- airflow/dags/gtfs_views/gtfs_schedule_dim_shapes_geo.sql
- airflow/dags/gtfs_views_staging/shapes_clean.sql
This PR does three things to resolve #1210:
* In `gtfs_views_staging.shapes_clean`, it safe-casts `shape_pt_lat` and `shape_pt_lon` to floats and `shape_pt_sequence` to int (so they are appropriate numeric types)
* In `gtfs_views`, it creates two new tasks: 
* `gtfs_schedule_dim_shapes` -- following the existing `dim` tables, it is a `SELECT *` on `shapes_clean` (i.e., it contains the columns from the underlying GTFS with minimal processing)
* `gtfs_schedule_dim_shapes_geo` -- this table aggregates each shape into an array of WKT points (in order), which can be consumed downstream to create a LINESTRING geography
See [these](https://github.com/cal-itp/data-infra/issues/1210#issuecomment-1068525146) [comments](https://github.com/cal-itp/data-infra/issues/1210#issuecomment-1069532014) from …
> Feature - GTFS schedule: Add dim_shapes and dim_shapes_geo

- airflow/dags/gtfs_schedule/agency.sql
- airflow/dags/gtfs_schedule/attributions.sql
- airflow/dags/gtfs_schedule/calendar.sql
- airflow/dags/gtfs_schedule/calendar_dates.sql
- airflow/dags/gtfs_schedule/dummy_views_staging.yml
- airflow/dags/gtfs_schedule/fare_attributes.sql
- airflow/dags/gtfs_schedule/fare_rules.sql
- airflow/dags/gtfs_schedule/feed_info.sql
- airflow/dags/gtfs_schedule/frequencies.sql
- airflow/dags/gtfs_schedule/levels.sql
- airflow/dags/gtfs_schedule/pathways.sql
- airflow/dags/gtfs_schedule/routes.sql
- airflow/dags/gtfs_schedule/shapes.sql
- airflow/dags/gtfs_schedule/stop_times.sql
- airflow/dags/gtfs_schedule/stops.sql
- airflow/dags/gtfs_schedule/transfers.sql
- airflow/dags/gtfs_schedule/translations.sql
- airflow/dags/gtfs_schedule/trips.sql
- airflow/dags/gtfs_schedule/validation_notices.sql
This PR addresses this issue identified by @evansiroky [on Slack](https://cal-itp.slack.com/archives/C0332307HKM/p1648095081505499):
> The new gtfs_schedule DAG has A LOT of "wait" tasks that are all running at the same time. I believe this is causing a lot of other tasks to not get queued up. So the wait tasks merely running may be preventing other tasks that they are waiting on from getting completed on time.
Basically, many DAGs failed to run last night (3/23/22) because all the "wait for" dependency tasks stalled out, presumably because too many were running at once. 
This PR refactors the dependencies for the `gtfs_schedule` DAG task so that all tasks just wait for one dummy task that waits for the entire `gtfs_views_staging` DAG instead of each DAG task waiting for its own external …
> Fix - GTFS Schedule: Reduce wait tasks for gtfs_schedule DAG

- .github/workflows/cleanup-release-candidates.yml
The git flow changes merged in #1197 introduced the concept of a "release candidate" as an auto-built deployment branch. That changeset did not however include a method to cleanup these branches when no longer required. This changeset introduces said cleanup method.
> Release candidate pruning workflow

- .github/workflows/service-release-candidate.yml
A new "release candidate branch" concept was introduced in #1179, but the workflow which builds these branches errors out when attempting to create a new release candidate branch (as opposed to updating an existing one). This hotfix resolves that issue.
> service-release-candidate.yml: fix first time candidate build

- docs/ci/Git-Flow-Services.md
It was not obvious enough in the previous quick start deployment section that there are very separate processes for deploying to prod vs preprod. This update makes the delineation far more clear, in addition to more fully describing the production deployment process.
> Clarify git flow for production deployments

- airflow/dags/rt_loader/load_rt_validations.yml
- airflow/plugins/operators/pod_operator.py
Points the RT validation job at new node pool, separate from the composer workers.
I will move the parsing jobs next, though they are not pod operators yet.
> run RT validations on new node pool

- airflow/dags/rt_views/gtfs_rt_fact_daily_validation_errors.sql
Attempted mitigation (not proper fix) for #1180. Removing the `rt_loader` dependency for the RT validations fact table.
Rationale: 
1. This dependency is not needed (nothing about the task uses execution date, so it is safe to let it get out of sync with `rt_loader` in the interest of experimentation).
2. This dependency has been causing the fact table task to fail a majority of the time recently:
To better understand issue #1180, we want to remove this confounding variable so that the task can run more frequently and we can get a handle on the prevalence of the underlying issue. 
^ This task runs into #1180 when I try to run it in test, so I am not able to test it locally. However since it mostly doesn't run already, I am confident that removing this dependency isn't going to make …
> fix(rt): remove validation errors dependency on rt loader

- airflow/dags/macros.py
It looks like c6f1c8c09d5b02e343fb65fee44150145940f8e5 (and its follow up c6d23b4e028182d32955ec19d8b6f45471c9f760) was wrong and caused #1267. Basically, the original `get_latest` logic was right -- we need to check for `2099-01-01` deleted at, because the way that we do `merge_updates` means that the `calitp_extracted_at` for individual rows won't necessarily line up with the latest feed/file extract (.... I know I'm a broken record about this at this point but row-level versioning strikes again.)
Basically, with the current logic, we are missing current rows that should be present because their `extracted_at` date (post-`merge_updates`) doesn't align with the latest *feed* update. 
Going back to using `calitp_deleted_at` opens us up to #1184 (so we will have some data present that …
> fix(gtfs schedule): fix get latest logic.... again

- airflow/dags/amplitude_benefits/jsonl_bigquery.sql
- airflow/dags/macros.py
- airflow/plugins/operators/amplitude_to_flattened_json.py
close #1240 part of #960 #1116 
- Save `jsonl` file from Amplitude into new `ingest_amplitude_raw_dev` or `ingest_amplitude_raw_prod` bucket
- Read `jsonl` file from new buckets
- Add `is_development` function to macros, so that operators can use it
This PR updates the `amplitude_benefits` DAG in order to....
- Update `api_to_jsonl`: Save the JSONL file to `gs://ingest_amplitude_raw_dev` or `gs://ingest_amplitude_raw_prod` bucket
- Update `jsonl_bigquery `: Get the JSONL file from `gs://ingest_amplitude_raw_dev` or `gs://ingest_amplitude_raw_prod` bucket, as determined by `is_development()` macro, as defined in [airflow/dags/macros.py](https://github.com/cal-itp/data-infra/pull/1279/files#diff-a9dc672975f537be6f0ec7ec039c377c09ee4fa15c24bed81c7306ccd0753308)
>  Amplitude DAG: Save JSONL in ingest_amplitude_raw_* bucket

- ci/steps/release-helm-changes.sh
Helm template has some weird behaviors which the development team has opted to not change or offer alternatives for which prevent its output from being useful in the context of performing a `kubectl diff`. This changeset implements a workaround which will provide idempotency for helm-based deployments.
> Better diffing of helm deployments for the CI pipeline

- docs/ci/Git-Flow-Services.md
This will help avoid confusion by anyone who is unaware that a release candidate will need to complete a possibly slow build step before it is available to be fetched in its most current form
> Explicitly state the need to wait on a release candidate build action

- ci/steps/release-helm-changes.sh
The exclusion of X characters in the tmpdir name template causes the command, and consequently the [deployment job](https://github.com/cal-itp/data-infra/runs/5774090158?check_suite_focus=true), to fail.
> Fix tmpdir creation in helm CI step

- kubernetes/apps/values/metabase.yaml
The upgrade in #1293 only effected the upgrade for preprod deployments. This effects the upgrade for prod deployments as well.
> Upgrade prod metabase to v0.42.3

- airflow/dags/gtfs_views/gtfs_schedule_dim_shapes_geo.sql
Fixes #1289.
1. Correctly handles shape-level versioning in `gtfs_schedule_dim_shapes_geo` by treating an entire shape as deleted and re-extracted any time that any of its constituent points change. 
2. Add tests for `gtfs_schedule_dim_shapes_geo` (null checks and composite uniqueness)
This PR updates the `gtfs_views` DAG in order to make the fixes listed above in `gtfs_schedule_dim_shapes_geo`.
> fix(gtfs schedule): dim shapes geo versioning again

- kubernetes/apps/charts/metabase/values.yaml
- kubernetes/apps/values/metabase-preprod.yaml
- kubernetes/apps/values/metabase.yaml
- kubernetes/apps/values/postgresql-backup-metabase.yaml
These changes address problems discovered in the process of completing the metabase rollback deployed in #1294. A summary of the problems:
- Due to a hard coded value in the chart, the preprod metabase was inadvertently connected to/using the production metabase DB. This is likely what caused the failed migrations to begin with.
- The postgresql client version used by the backup job was far newer than the postgresql server version used by metabase. This was causing DB restore attempts to fail.
- The postgresql client version used by the backup job was not version-pinned. This created a situation which would allow client and server versions to drift out of compatibility.
This changeset resolves all of these issues.
> Remediate failed upgrade to metabase v0.42.3

- .github/workflows/service-release-candidate.yml
This bases candidate branch history on prod, which both results in the originally intended history tracking effect and has the added benefit of always showing how candidate branch changes would be effected on prod.
> Fix git history for candidate branches

- warehouse/dbt_project.yml
🚨 _Merging to `dbt-mvp` not `main`_
Small PR to set the `persist_docs` flag so that documentation is written to BigQuery in addition to the dbt docs.
> dbt: persist docs

- docs/_toc.yml
- docs/github/contribute_to_repos.md
As the data services team has grown, we thought it would be prudent to put together some "official" GitHub contribution guidelines. Once this is added to the docs site, it can be linked from `CONTRIBUTING.md` files in all repos that want to opt in to these norms. 
This draft is based heavily on Jarvus's internal GitHub guide, but with some updates to make it applicable to Cal-ITP.
This PR creates `github/contributing_to_repos.md` in order to document GitHub contribution guidelines.
> Docs GitHub contributions

- .github/workflows/publish-docs.yml
The build docs workflow was previously set up to run on both `push` and `pull request`, causing the docs to build too frequently. The `build on push` setting was removed as `build on pull request` seems more appropriate for a docs workflow.
**Files effected**:
`workflows/publish-docs.yml`
* removed build on push workflow
Flagged by @themightychris in [this thread](https://jarvus.slack.com/archives/G01R32T28BT/p1648242158416259)
> fix(workflow): removed duplicate build-docs workflow

- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- warehouse/macros/generate_schema_name.sql
- warehouse/profiles.yml
This PR has the prod Airflow dbt run write to `cal-itp-data-infra` by default to maintain compatibility with existing architecture (for example, data availability in Metabase) during the transition. Previously it was writing to `cal-itp-data-infra-staging` by default, which caused the RT files views to become stale even though the dbt Airflow task ran successfully (🎉).
> Point prod Airflow dbt task to cal-itp-data-infra rather than staging

- airflow/dags/gtfs_schedule_history2/validation_notices_load.sql
Fixes #1334. `gtfs_schedule_history2.validation_notices_load` was populating `calitp_deleted_at` by `LEAD`-ing `calitp_extracted_at` to the next row. However, it was not partitioning the window by `calitp_url_number`, so `calitp_extracted_at` dates were being comingled across `url_number` boundaries. This PR fixes that by adding `calitp_url_number` to the `PARTITION BY`.
See PR description
> fix(gtfs schedule): Partition validation notices by `calitp_itp_id` AND `calitp_url number`

- .github/workflows/publish-docs.yml
Fixes https://github.com/cal-itp/data-infra/issues/1326 by making sure the doc publishing GitHub action is ran on the main branch.
> Make sure docs get published from main branch

- airflow/dags/airtable_loader/METADATA.yml
- airflow/dags/airtable_views/METADATA.yml
Fixes #1325. Moves `airtable_loader` and `airtable_views` DAGs to run at 0200 UTC instead of midnight UTC. 
**Note:** This also changes the file location-- files will now be written to `<date>T02:00:00+00:00/` instead of `<date>T00:00:00+00:00/ ` (timestamp change). Nothing reads from the GCS files right now so I don't think this is a big deal. 
Loader:
Views:
See description
> Airflow: change Airtable DAG execution time to 0200 UTC

- airflow/dags/macros.py
Fixes #235 by only including data in `gtfs_schedule` (`GTFS Schedule Feeds Latest`) where that agency appears in the current `agencies.yml`. 
Also partially addresses #988.
As usual `stop_times` does not run due to query limit
This PR updates the `gtfs_schedule` DAG (via its macro in `macros.py`) in order to only pull data from agencies that are still in `agencies.yml`
> Fix filter gtfs schedule to is in latest

- airflow/data/agencies.yml
Modesto Area Express (MAX) + Stanislaus Regional Transit (StaRT) have consolidated to Stanislaus Regional Transit Authority (StanRTA).  This update deletes MAX and STaRT and adds StanRTA with a new Cal-ITP ID
NOTE: current feed for StanRTA is really just a copy-over of Modesto Area Express' and doesn't include Stanislaus Regional Transit - yet.  However, Stansilaus Regional Transit feed is outdated at this point.
This PR updates `agencies.yml` in order to....
Add the following gtfs datasets:
- Stanislaus Regional Transit Authority
Deletes the following gtfs datsets:
- Modesto Area Express
- Stanislaus Regional Transit
> Consolidate Modesto and StaRT into Stanislaus Regional Transit Authority

- airflow/data/agencies.yml
This PR changes a few GTFS Schedule URLs so that the GMV Schedule URLs are always associated with the GMV Realtime URLs.
This PR updates `agencies.yml` in order to align the GMV Schedule URLs with the GMV Realtime URLs. This affects the following transit services:
- Emery Go-Round
- Merced The Bus
- MVGO
- Sonoma-Marin Area Rail Transit
- Union City Transit
- Victor Valley Transit
> Use GMV schedule URLs

- airflow/dags/airtable_views/california_transit_gtfs_datasets.sql
I forgot to initially add field-level documentation for these fields in https://github.com/cal-itp/data-infra/pull/1160.
This PR updates the `airtable_views.california_transit_gtfs_datasets` DAG task in order to add proper field-level documentaiton.
> Add additional field documentation to California Transit GTFS Datasets BigQuery Dataset

- airflow/dags/rt_loader/external_validation_service_alerts.sql
- airflow/dags/rt_loader/load_rt_validations.yml
- airflow/plugins/operators/sql_query_operator.py
This image also downloads schedule data _after_ RT, so we will avoid downloading schedule data that has no corresponding RT data.
> run the fixed RT validator API image in airflow

- .github/workflows/publish-docs.yml
- docs/analytics_welcome/overview.md
@lauriemerrell noticed that her docs updates weren't building on merge from main, so I'm reverting to the previous workflow settings
We can revisit this and try to address the duplicate build process again soon
Files effected:
`.github/workflows/publish-docs.yml`
* reverted previous workflow settings
`docs/analytics_welcome/overview`
* trivial change to get docs to build on merge
> fix(build-docs): reverting workflow to fix docs build on merge issue

- kubernetes/apps/charts/jupyterhub/values.yaml
- kubernetes/apps/manifests/gtfs-rt-archive/app.yaml
Adjust both JupyterHub and RT resource requests based on [Grafana charts](https://monitoring.k8s.calitp.jarv.us/d/967c0gU7k/jupyterhub-monitoring) and https://github.com/cal-itp/data-infra/issues/1323#issuecomment-1090764303.
Require JupyterHub user pods to schedule on the proper node pool. We want to enable this so that as we add resource requests that may spread out pods, we don't accidentally spread to other node pools.
Bumps hub to use v10 of the jupyter image to get the resource usage library.
closes https://github.com/cal-itp/data-infra/issues/592
related to https://github.com/cal-itp/data-infra/issues/1323
> adjust apps resource requests and node pool assignments

- airflow/dags/gtfs_downloader/validate_gcs_bucket.yml
deploys https://github.com/cal-itp/gtfs-validator-api/pull/3 and _actually_ closes https://github.com/cal-itp/data-infra/issues/1078 (oops)
> use newer version of schedule validator api

- docs/analytics_tools/notebooks.md
- docs/analytics_tools/saving_code.md
Added new information on how to persist SSH keys, clarified information on generating adding SSH key and adding to GitHub, restructured the 'Saving Code' page, linked to 'Saving Code' page from 'Notebooks' page and added additional detail
`Analytics Tools/ Notebooks`
* Added new description with link to `Saving Code` page
`Analytics Tools/ Saving Code`
* Added information on perisisting SSH keys and enabling extensions
* Clarified process for generating SSH key and adding to GitHub
* Revised page structure to make more sense, created internal references, added new sections to top page TOC
> docs(ssh): added information on persisting SSH keys clarified creating SSH keys

- airflow/dags/check_feed_aggregators/METADATA.yml
- airflow/dags/check_feed_aggregators/check_aggregators.yml
- jobs/gtfs-aggregator-checker/Dockerfile
- jobs/gtfs-aggregator-checker/README.md
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/__init__.py
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/__main__.py
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/cache.py
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/config.py
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/transitfeeds.py
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/transitland.py
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/utils.py
- jobs/gtfs-aggregator-checker/poetry.lock
- jobs/gtfs-aggregator-checker/pyproject.toml
closes https://github.com/cal-itp/data-infra/issues/924
Moving code over from https://github.com/cal-itp/gtfs-aggregator-checker, packaging it in an image, and running it via a pod operator. Output is written hive-style to the gtfs data bucket.
I'm not sure I love this image/podoperator pattern for simpler stuff but it's fine and this may grow in complexity over time.
some example ndjson/jsonl output
```
{"url": "https://api.actransit.org/transit/gtfs/download", "url_type": "gtfs_schedule_url", "itp_id": 4, "url_number": 0, "transitfeeds": {"status": "missing"}, "transitland": {"status": "present", "public_web_url": "https://transit.land/feeds/f-9q9-actransit"}}
{"url": "https://api.actransit.org/gtfsrt/vehicles", "url_type": "gtfs_rt_vehicle_positions_url", "itp_id": 4, "url_number": 1, …
```
> Put aggregator checker into airflow

- .holo/branches/release-candidate/kubernetes/apps/charts/loki.toml
- .holo/branches/release-candidate/kubernetes/apps/charts/promtail.toml
- .holo/sources/jarvus-cluster-template.toml
- ci/vars/releases/prod-loki.env
- ci/vars/releases/prod-promtail
The current deployment stack for loki is outdated, which causes labels to not properly parse. This change pulls in more current versions of the components of the loki stack to enable its full log parsing power.
> Replace loki-stack with current loki and promtail charts

- warehouse/scripts/run_and_upload.py
Pathlib is super useful, but unfortunately path objects don't implement `__iter__` so we can't do checks like `if some_str in path`. I failed to test this properly prior to deploying https://github.com/cal-itp/data-infra/pull/1383.
> fix bad type usage

- ci/vars/releases/prod-promtail.env
- kubernetes/apps/values/promtail.yaml
The default loki server value for promtail instances does not work in the context of the data-infra-apps cluster
> Point promtail instances to loki server

- .github/workflows/cleanup-release-candidates.yml
This workflow would previously fail when there were no candidate branches returned from the `git ls-remote` command due to an attempt to iterate once with empty values.
> Fix cleanup-release-candidates workflow failures

- kubernetes/apps/values/promtail.yaml
no assumptions are made regarding loki's default port number; it must be explicitly specified
> Fix port number in lokiAddress

- kubernetes/apps/values/promtail.yaml
The prometheus node-exporter instances already run with a wildcard toleration which allows them to run across all node pools. This adds a similar wildcard toleration to promtail instances to do the same for log collection.
> Fix monitoring tolerations

- kubernetes/apps/charts/jupyterhub/values.yaml
`kubernetes/apps/charts/jupyterhub/values.yaml`
* removed service key gcloud-auth for jupyter users to in `values.yml` disassociate jupyter from the warehouse and facilitate use by a larger group of caltrans users
closes #1376
> fix(jupyter): removed service key gcloud-auth for jupyter users in values.yml

- warehouse/README.md
Tiny docs change for the dbt README -- I accidentally used just `python -m` in #1419 which will have people running things with Python 2.
> dbt docs reference python 3

- airflow/dags/parse_rt/parse_rt_service_alerts.yml
- airflow/dags/parse_rt/parse_rt_trip_updates.yml
- airflow/dags/parse_rt/parse_rt_vehicle_positions.yml
Real quick fix. I had removed the default `glob` value, so we don't use the option flag anymore.
> fix args for pod operators

- airflow/dags/parse_rt/parse_rt_service_alerts.yml
- airflow/dags/parse_rt/parse_rt_trip_updates.yml
- airflow/dags/parse_rt/parse_rt_vehicle_positions.yml
After watching the new RT jobs run in production, I want to reduce the CPU request from 1 to 0.5 as they don't consume very much at all. (Lots of network, not so much CPU.)
> only request 0.5 cpu so we can fit more jobs on a node

- warehouse/models/gtfs_views_staging/calitp_feeds.sql
This PR changes `gtfs_views_staging.calitp_feeds` to use "safe" URLs with API keys suppressed instead of using URLs with API keys written out. 
I'm changing the name of the accompanying column to `raw_gtfs_schedule_url` in keeping with convention. 
After this merges I will post on Slack notifying people about the changes, but I think it's desirable even if it inconveniences some people. 
Also after this merges I will run the following query to overwrite the defunct `views.gtfs_status_latest` table to suppress its API key values too. 
<details>
<summary>query</summary>
```
WITH old_table AS (
SELECT *
FROM `cal-itp-data-infra.views.gtfs_status_latest`
),
raw_feed_urls AS (
SELECT
*,
PARSE_DATE(
'%Y-%m-%d',
REGEXP_EXTRACT(_FILE_NAME, ".*/([0-9]+-[0-9]+-[0-9]+)")
) AS calitp_extracted_at …
```
> fix(gtfs schedule): suppress API keys in tables

- kubernetes/apps/charts/jupyterhub/values.yaml
Add notebooks.calitp.org ingress to the jupyterhub cluster.
Resolves #[675](https://github.com/cal-itp/data-infra/issues/675)
Recommendations are very welcome
> feat(jupyter):add notebooks.calitp.org to ingress

- jobs/gtfs-rt-parser/Dockerfile
- jobs/gtfs-rt-parser/README.md
The old S3 file location of the RT validator jar is returning 403s, so I'm just vendoring a copy and using it in the Dockerfile.
> vendor jar in github and copy in dockerfile

- docs/airflow/production-maintenance.md
Documenting the re-run considerations for three new DAGs:
* `check_feed_aggregators`
* `create_external_tables`
* `parse_and_validate_rt`
And clarifies documentation related to deprecated DAGs.
> docs: document new airflow dags

- jobs/gtfs-rt-parser/gtfs_rt_parser.py
This PR fixes two problems that popped up during the backfill.
1. Sometimes, there are no validation notices output for a given hour of RT data (usually service alerts). Currently we upload empty files, but BigQuery fails when parsing these. Instead, we should write a single newline character since the data is JSONL.
2. Our schedule data is keyed via Airflow logical execution date in GCS, so we have to subtract a day from the RT ticks to find it.
Locally via docker-compose.
> More RT refactor fixes

- airflow/dags/create_external_tables/rt_service_alerts_outcomes.yml
- airflow/dags/create_external_tables/rt_service_alerts_validations.yml
- airflow/dags/create_external_tables/rt_service_alerts_validations_outcomes.yml
- airflow/dags/create_external_tables/rt_trip_updates_outcomes.yml
- airflow/dags/create_external_tables/rt_trip_updates_validations.yml
- airflow/dags/create_external_tables/rt_trip_updates_validations_outcomes.yml
- airflow/dags/create_external_tables/rt_vehicle_positions_outcomes.yml
- airflow/dags/create_external_tables/rt_vehicle_positions_validations.yml
- airflow/dags/create_external_tables/rt_vehicle_positions_validations_outcomes.yml
- airflow/dags/parse_and_validate_rt/METADATA.yml
- airflow/dags/parse_and_validate_rt/parse_rt_service_alerts.yml
- airflow/dags/parse_and_validate_rt/parse_rt_trip_updates.yml
- airflow/dags/parse_and_validate_rt/parse_rt_vehicle_positions.yml
- airflow/dags/parse_and_validate_rt/validate_rt_service_alerts.yml
- airflow/dags/parse_and_validate_rt/validate_rt_trip_updates.yml
- airflow/dags/parse_and_validate_rt/validate_rt_vehicle_positions.yml
- airflow/plugins/operators/external_table.py
- jobs/gtfs-rt-parser/gtfs_rt_parser.py
The new RT pipeline has been running for a few days now successfully! We only backfilled to the beginning of May, so we could catch up quickly and keep new data flowing in roughly realtime. Now, we are ready to backfill back to the start of RT data in July.
This PR also has a few small tweaks.
1. It splits up parsing and validation into separate pools. We can run much more parsing at once than validation, so we can get historical RT _data_ backfilled much more quickly by having a larger pool.
2. It skips uploading single-newline gzip files to represent zero validation notices; BigQuery does not like these.
3. Adds a retry on ServerDisconnectedError, which we didn't before.
4. It uses post-hooks to test that external tables are queryable after creation.
Resolves …
> Full RT backfill, separate pools, and a couple tweaks

- kubernetes/apps/charts/jupyterhub/values.yaml
Issue #1480 identified a bug in the new jupyterhub domain introduced by issue #1460 where an `OAuth state missing from cookies` error appears because the URL on the callback URL (hubtest.k8s.calitp.jarv.us) is different from the initial visit (notebooks.calitp.org).
**All analysts and other users of Jupyterhub have been notified to begin using the new notebooks.calitp.org URL starting 5/11/22**
Resolves #1480
* Still not sure if this invalidates hubtest.k8s.calitp.jarv.us from being used to oauth to github
* Still not sure if this invalidates hubtest.k8s.calitp.jarv.us from being used to oauth to github
* Need to update helm chart after this is merged
> jupyter values.yaml: updated oauth_callback_url from hubtest to notebooks.calitp.org

- kubernetes/apps/charts/jupyterhub/values.yaml
Re-updating the JupyterHub heml oauth_callback to point to notebooks.calitp.org
Resolves #1492 #1489
> jupyter(helm): re-updating the heml oauth_callback to point to notebooks.calitp.org

- airflow/dags/airtable_loader/california_transit_county_geography.yml
- airflow/dags/airtable_loader/california_transit_eligibility_programs.yml
- airflow/dags/airtable_loader/california_transit_fare_systems.yml
- airflow/dags/airtable_loader/california_transit_funding_programs.yml
- airflow/dags/airtable_loader/california_transit_gtfs_datasets.yml
- airflow/dags/airtable_loader/california_transit_gtfs_service_data.yml
- airflow/dags/airtable_loader/california_transit_ntd_agency_info.yml
- airflow/dags/airtable_loader/california_transit_organizations.yml
- airflow/dags/airtable_loader/california_transit_place_geography.yml
- airflow/dags/airtable_loader/california_transit_rider_requirements.yml
- airflow/dags/airtable_loader/california_transit_services.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_county_geography.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_eligibility_programs.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_fare_systems.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_funding_programs.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_gtfs_datasets.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_gtfs_service_data.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_ntd_agency_info.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_organizations.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_place_geography.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_rider_requirements.yml
- airflow/dags/create_external_tables/external_airtable_california_transit_services.yml
- airflow/dags/sandbox/load_airtable_child.yml
- airflow/dags/sandbox/op_airtable_to_warehouse.yml
- airflow/plugins/operators/airtable_to_warehouse.py
- airflow/requirements.txt
🚨 _This is merging into the `airtable-updates` branch, not `main`, to prepare for a bundle of related changes_
This PR establishes the groundwork for the "new" Airtable pattern, in line with the RT pipeline and to prepare for #1159.
It refactors the Airtable operator to:
* Stop writing simultaneously to GCS & BigQuery and instead only write to hive-partitioned GCS buckets 
* Use Pydantic typing to enforce data types
In doing so, I had to add a bunch of handling for arrays that contain nulls because BigQuery does not allow them. Specifically, if an array only has null values, this just return an empty array -- this collapses the distinction between [null] and [] which may be meaningful in cases where the array is the result of a lookup in Airtable, but the distinction should be recoverable …
> Airtable operator refactor

- docs/analytics_examples/new_tutorial.md
- docs/analytics_examples/overview.md
- docs/analytics_examples/warehouse_tutorial.md
- docs/analytics_onboarding/overview.md
- docs/analytics_publishing/where_reports_live.md
- docs/analytics_tools/data_catalogs.md
- docs/analytics_tools/knowledge_sharing.md
- docs/analytics_tools/notebooks.md
- docs/analytics_tools/overview.md
- docs/analytics_tools/python_libraries.md
- docs/analytics_tools/tools_quick_links.md
- docs/analytics_welcome/how_we_work.md
- docs/analytics_welcome/overview.md
- docs/architecture/architecture_overview.md
- docs/intro.md
- docs/warehouse/adding_oneoff_data.md
- docs/warehouse/overview.md
- docs/warehouse/sql_snippets.md
With the new analytics tool URLs, taking the time to replace the old URLs in the docs as well as any others outdated or broken. Also making small misc improvements/edits as I see them.
Also adding `analysis.calitp.org` to docs in several places
Resolves #1502 
Also running tests in command line to verify all URLs in the jupyterbook resolve
> docs(audit): identify and fix broken or outdated links, misc quick improvements

- airflow/data/agencies.yml
Per https://github.com/cal-itp/data-infra/issues/499#issuecomment-1125519047, we now have an accurate GTFS Schedule link for LAX FlyAway. 
Resolves #499
**Feeds added:** Just LAX FlyAway, ITP ID 165 per Olivia in comment linked above.
> agencies.yml: add LAX FlyAway

- warehouse/models/gtfs_views_staging/calitp_feeds.sql
Bug fix for #1030 -- see issue for context. Basically, BigQuery didn't correctly handle an equality check where one of the values was null. I had been *not* fixing this issue because the only affected feed was an erroneous feed (Capitol Corridor data that had been downloaded under AC Transit). But now a correct, current Elk Grove Transit feed is also being affected (#1329), so fixing.
Resolves #1030, resolves #1329
Ensured that there are only two new rows in `calitp_feeds`, the two noted (AC Transit and Elk Grove). Ran `dbt test` and ensured that tests passed on all affected data (after running `dbt run --select +calitp_feeds+` so all affected data was up to date)
> fix(gtfs schedule): handle feed removal gaps in gtfs_views_staging.calitp_feeds

- airflow/data/agencies.yml
Per conversation with staff at the City of Culver City, this is the proper stable URL to be fetching their GTFS Schedule from.
> Update to stable URL for Culver City

- warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml
Noticed that the `{file}_key` columns had the wrong description in dbt:
Fixes this by referencing the correct macro. 
Ran `dbt docs generate` locally, confirmed it's updated to the correct thing:
> docs: fix which macro is being used in gtfs schedule feed latest

- airflow/data/agencies.yml
Per #1514, updates `agencies.yml` information for Anaheim and Santa Maria agencies.
**Questions for @evansiroky and @o-ram:**
* I am using the name `Anaheim Regional Transportation` here because that's what's in the new feed's `agency.txt`. Formerly (and in Airtable) we have used `Anaheim Resort Transportation`. 
* Just to fully confirm -- I am **replacing** the Santa Maria Trillium schedule link with the new link. 
Resolves #1514
- Manually hit each new URL and confirmed that they work and return the expected type of data
- Confirmed that the trip IDs matched between the VP feeds and their respective schedules
> agencies.yml: add/update Anaheim and Santa Maria agency info

- airflow/data/agencies.yml
Adds some realtime URLs for Culver City.
Locally verified that the URLs all could download and had parseable GTFS-RT.
> Add Culver City GTFS-RT URLs

- airflow/requirements.txt
The composer requirements github action failed on a recent PR merge https://github.com/cal-itp/data-infra/runs/6557522098?check_suite_focus=true.
This PR pins a version of google-api-core that will hopefully resolve this issue.
Ran `pip install` to install the latest good version.
> try to pin a good version of google api core

- airflow/data/agencies.yml
**Before merging I want to confirm with @evansiroky, @o-ram, and @edasmalchi that this is appropriate**
Remove OCTA non-Swiftly URLs; they are deprecated per @edasmalchi (and they have been returning invalid data as of this week).
N/A
> agencies.yml: remove deprecated octa feeds

- airflow/data/headers.yml
In #1520, I didn't realize I had to also update `headers.yml` because the OCTA Swiftly feeds use header-based authorization and that relationship was based on URL number (.... argh!) We didn't get OCTA data yesterday because we're getting an invalid header (`401`) response.
> headers.yml: fix octa header reference

- airflow/dags/airtable_loader/california_transit_gtfs_datasets.yml
`airtable_loader.california_transit_gtfs_datasets` DAG task is failing in production (and therefore causing the `airtable_views` DAG to fail) because new Airtable columns in the `gtfs datasets` contain illegal punctuation. This PR renames those fields. More structural changes to the Airtable operator to make it slightly more robust are coming in PR #1509, hope to merge ~next week.
Ran in local Airflow, confirmed updated DAG task runs successfully:
> airtable: rename gtfs dataset columns to be BQ friendly

- airflow/data/agencies.yml
Adds a newly-discovered GTFS Feed for the City of West Hollywood
> Add City of West Hollywood GTFS Schedule

- airflow/dags/transform_warehouse_full_refresh/METADATA.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
- warehouse/models/gtfs_schedule_latest_only/feed_info.md
- warehouse/scripts/run_and_upload.py
`gtfs_rt_fact_daily_validation_errors` is our first incremental model, and it currently fails to build as the job is trying to MERGE on a unique key that doesn't exist yet. To create that key, we need to be able to run dbt with `--full-refresh` as needed in Airflow (this is a common pattern). This PR creates a non-scheduled DAG to make this happen.
```
Database Error in model gtfs_rt_fact_daily_validation_errors (models/rt_views/gtfs_rt_fact_daily_validation_errors.sql)
Name key not found inside DBT_INTERNAL_DEST at [68:57]
compiled SQL at target/run/calitp_warehouse/models/rt_views/gtfs_rt_fact_daily_validation_errors.sql
```
It also fixes an issue where `feed_info` throws an error when trying to set the column comments, as the doc-block for `feed_lang` was longer than BigQuery's limit …
> create full-refresh DAG to run manually as needed; couple other fixes

- airflow/data/agencies.yml
MST RT URLs started failing on Tuesday evening and failed all through yesterday (Wednesday). When I checked this morning, I was unable to access the URLs we were using. 
Checking [their website](https://mst.org/about-mst/developer-resources/), it seems that they have new RT URLs.
@o-ram and @evansiroky -- I just wanted to confirm that there's nothing special here because of Payments or anything else? (Like, just wanted to make sure that we weren't using some special URL before for some other reason?) 
I hit the new URLs manually and verified that I can parse the resulting proto files. 
I updated the Airtable too:
> agencies.yml: fix MST RT urls

- airflow/dags/create_external_tables/rt_service_alerts_outcomes.yml
- airflow/dags/create_external_tables/rt_service_alerts_validations_outcomes.yml
- airflow/dags/create_external_tables/rt_trip_updates_outcomes.yml
- airflow/dags/create_external_tables/rt_trip_updates_validations_outcomes.yml
- airflow/dags/create_external_tables/rt_vehicle_positions_outcomes.yml
- airflow/dags/create_external_tables/rt_vehicle_positions_validations_outcomes.yml
- warehouse/models/staging/audit/stg_audit__cloudaudit_googleapis_com_data_access.sql
- warehouse/models/staging/rt/_src_gtfs_rt_external_tables.yml
This PR makes a couple fixes based on an investigation into high bigquery billing last week.
1. Removes very expensive and largely useless freshness checks on outcomes files. (BigQuery does not efficiently select the pseudo-columns in hive-partitioned external tables.)
2. Fixes the audit table to increment properly and also include more information, including the dbt node name.
3. Requires partition filters for outcomes external tables; they got bigger than expected.
Locally via dbt CLI.
> Audit and followups

- docs/datasets_and_tables/views.md
As part of deploying dbt we benefit from new, automatically generated, table-level documentation that is easier to maintain, lives close to the code, and serves as our source of truth.
To make this useful, we need to remove the current documentation (keeping what doesn't yet live in dbt) and link out to the dbt site.
It is important to note that **there are some docs that should not yet be deprecated** including airtable, transit database, and anything not yet in dbt.
Datasets included in this PR:
* external_gtfs_rt
* gtfs_rt
* gtfs_rt_logs
* gtfs_schedule
* gtfs_schedule_history
* gtfs_schedule_type2
* gtfs_views_staging
* information_schema
* staging
* views
Resolves #1499
> docs(datasets and tables): added markdown table with new links to dbt docs

- warehouse/poetry.lock
- warehouse/pyproject.toml
Relax python version in `warehouse/pyproject.toml` to any Python 3.9, since it's difficult to install minor versions.
Simplifies dbt setup, and avoids need for complex tools like conda for local python environments.
Successfully ran `poetry install`, dbt after making change
> relax python to ~3.9, poetry update

- kubernetes/apps/manifests/gtfs-rt-archive/app.yaml
The limit of 512Mi was causing restarts at an interval which resulted in
over-collection of data, downgrading quality. This modest increase
provides more headroom while still attempting to bludgeon runaway memory
spikes as early as possible.
> gtfs-rt-archive: increase memory limit to 640Mi

- airflow/data/agencies.yml
Updates to the correct Tri-Valley Wheels GTFS Schedule link
Saw new URL on transit agency's website: https://www.wheelsbus.com/about/developer/
Downloaded locally to verify that it is current.
> Update Tri-Valley Wheels GTFS Schedule link

- airflow/data/agencies.yml
Montebello Bus Lines was able to give us a publicly-available URL to download data from.
> Update Montebello Schedule URL

- warehouse/models/gtfs_views/_gtfs_views.yml
- warehouse/models/gtfs_views/reports_daily_service_routes_stops.sql
- warehouse/models/test_general/reports_daily_service_routes_stops.sql
New table to consolidate and improve metric generation for reports. Replaces complex Siuba code in reports notebook and allows for visibility into service hour changes before the report generation process.
Resolves https://github.com/cal-itp/reports/issues/129
Ran for 2 months via dbt, that processed 1.4GB.
> Reports to warehouse

- warehouse/models/gtfs_views/_gtfs_views.yml
- warehouse/models/gtfs_views/reports_gtfs_schedule_index.sql
Removes the requirement that `feed_info.txt` be present to generate the `use_for_report` flag in `reports_gtfs_schedule_index`. 
Will be accompanied with a content change to the report to highlight the importance of `feed_info.txt` if missing.
Resolves [reports #153](https://github.com/cal-itp/reports/issues/153)
Ran via dbt in staging, works as intended.
> Reports feed info optional

- warehouse/models/mart/transit_database/map_services_x_products.sql
- warehouse/models/staging/transit_database/stg_transit_database__contracts.sql
- warehouse/models/staging/transit_database/stg_transit_database__service_components.sql
_🚨 merging into feature branch not main_
Fixes unnesting-- switches from `CROSS JOIN` to `LEFT JOIN` where applicable to stop dropping rows where the unnested array is null.
> fix: transit tech stacks -- fix unnesting

- airflow/data/agencies.yml
After inspecting all current agencies that 511 claims to support, I'm adding the ones that were missing in agencies.yml.
Locally download missing agencies.
> Add all current MTC 511 agencies

- warehouse/models/gtfs_views/_gtfs_views.yml
- warehouse/models/gtfs_views/gtfs_schedule_fact_daily_feeds.sql
_updated 6/27 based on discussing the original implementation with @atvaccaro_
Add a `status_since` column to `gtfs_schedule_fact_daily_feeds` so we can track continuous errors to address #1205.
~**🚨 Question for reviewers:**~
* ~Should it just be `status_since` and track continuous success OR failure? I wasn't sure if we have a reason to potentially want to track both. The request in the motivating ticket is specific to failures but I guess we could want to track successes too or make the column more generic?~
* ^ yes, done
> feat(schedule): track continuous download errors

- airflow/data/agencies.yml
Reverts cal-itp/data-infra#1591
We think we've hit a throughput limit; [seeing a step function in Grafana](https://monitoring.k8s.calitp.jarv.us/d/xPWY4jL7z/gtfs-rt-achiver?orgId=1&from=1656328443522&to=1656347186379) that started when this was deployed.
> Revert "Add all current MTC 511 agencies"

- airflow/data/agencies.yml
SacRT is now maintaining and hosting the South County Transit Link URL.
Confirmed new email via email and on SacRT website. Downloaded locally.
> Update SCT Link URL

- warehouse/models/gtfs_views/_gtfs_views.yml
- warehouse/models/gtfs_views/gtfs_schedule_fact_daily_feeds.sql
While we preferred the implementation in #1590, Metabase limitations (can't do `DATE_DIFF`) have led us to need to do the date subtraction requested in #1205 directly in the warehouse. So this PR refactors #1590 to instead return the `DATE_DIFF` directly.
> feat(schedule): days in status -- refactor status_since

- kubernetes/apps/manifests/gtfs-rt-archive/app.yaml
We want to test uncapping the memory limit for the RT archiver.
> remove mem limit on archiver

- kubernetes/apps/manifests/gtfs-rt-archive/app.yaml
We want to hand memory management issues directly to the kernel and remove them entirely from the purview of the control plane
> Deploy unlimited archiver memory into production

- airflow/data/agencies.yml
Adds GTFS-RT URLs for AVTA.
Received URLs from agency, downloaded locally.
> Add RT URLs for AVTA

- warehouse/macros/farm_surrogate_key.sql
- warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml
- warehouse/models/gtfs_views/_gtfs_views.yml
- warehouse/models/gtfs_views/dim_date.sql
- warehouse/models/gtfs_views/gtfs_schedule_dim_shapes.sql
- warehouse/models/gtfs_views/gtfs_schedule_dim_shapes_geo.sql
- warehouse/models/gtfs_views_staging/agency_clean.sql
- warehouse/models/gtfs_views_staging/attributions_clean.sql
- warehouse/models/gtfs_views_staging/calendar_clean.sql
- warehouse/models/gtfs_views_staging/fare_attributes_clean.sql
- warehouse/models/gtfs_views_staging/fare_rules_clean.sql
- warehouse/models/gtfs_views_staging/feed_info_clean.sql
- warehouse/models/gtfs_views_staging/frequencies_clean.sql
- warehouse/models/gtfs_views_staging/levels_clean.sql
- warehouse/models/gtfs_views_staging/pathways_clean.sql
- warehouse/models/gtfs_views_staging/routes_clean.sql
- warehouse/models/gtfs_views_staging/shapes_clean.sql
- warehouse/models/gtfs_views_staging/stop_times_clean.sql
- warehouse/models/gtfs_views_staging/stops_clean.sql
- warehouse/models/gtfs_views_staging/transfers_clean.sql
- warehouse/models/gtfs_views_staging/translations_clean.sql
- warehouse/models/gtfs_views_staging/trips_clean.sql
- warehouse/models/rt_views/_rt_views.yml
Adds a bunch of semantic types! We should be using non-specific FKs to prevent auto-binning of numerical identifiers such as `calitp_itp_id`.
One opinion in this PR: every table should have an explicit primary key column with not-null and unique tests, rather than just a unique-combination-of-columns test. This is useful when using YAML anchors.
Resolves https://github.com/cal-itp/data-infra/issues/1107
> start typing and anchoring important columns

- airflow/dags/download_gtfs_schedule_v2/METADATA.yml
- airflow/dags/download_gtfs_schedule_v2/download_feeds.py
- airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py
- airflow/dags/macros.py
- airflow/plugins/utils.py
- airflow/requirements-dev.txt
- airflow/requirements.txt
Must wait on https://github.com/cal-itp/data-infra/pull/1509!
This PR creates some initial Pydantic models to faciliate easy reading/writing of hive-partitioned artifacts in GCS. It also creates a new DAG `download_gtfs_schedule_v2` with a single task to download GTFS Schedule feeds based on Airtable records.
1. Raw GTFS Schedule zip files are saved in GCS
2. Pydantic bases classes drive the GCS I/O, and the subclasses configure metadata, partitions, etc.
3. GCS files keep metadata (defined in #2) describing the configuration that led to their creation
I've also set up the [Airflow variables](https://o1d2fa0877cf3fb10p-tp.appspot.com/variable/list/) containing our existing secrets.
Locally! Right now I'm testing with an Airtable extract from 2022-06-10 as that was the last time that task …
> GTFS downloader v2 - download_feeds task and Pydantic/GCS work!

- airflow/dags/gtfs_schedule_history/validation_report.yml
We had a failure last night in `validation_notices_load` due to bad JSON parsing. A new schedule feed is resulting in a new validation notice (specifically, a non-ASCII character) which has a field called `columnName` which we haven't used before. I'm unsure how this differs from `fieldName`.
tbd
> add missing columnName column to schedule validation notices schema

- airflow/data/agencies.yml
- script/agencies_verify.py
Updates the AVTA URL to a new URL that is on their website. (See https://www.avta.com/gtfs.php).
Received communication to use the URL found on the referenced page, downloaded locally.
> Update AVTA URL

- airflow/dags/airtable_loader_v2/california_transit_county_geography.yml
- airflow/dags/airtable_loader_v2/california_transit_eligibility_programs.yml
- airflow/dags/airtable_loader_v2/california_transit_fare_systems.yml
- airflow/dags/airtable_loader_v2/california_transit_funding_programs.yml
- airflow/dags/airtable_loader_v2/california_transit_gtfs_datasets.yml
- airflow/dags/airtable_loader_v2/california_transit_gtfs_service_data.yml
- airflow/dags/airtable_loader_v2/california_transit_ntd_agency_info.yml
- airflow/dags/airtable_loader_v2/california_transit_organizations.yml
- airflow/dags/airtable_loader_v2/california_transit_place_geography.yml
- airflow/dags/airtable_loader_v2/california_transit_rider_requirements.yml
- airflow/dags/airtable_loader_v2/california_transit_services.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_components.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_contracts.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_data_schemas.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_organizations.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_products.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_properties_features.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_relationships_service_components.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_service_components.yml
- airflow/dags/airtable_loader_v2/transit_tech_stacks_services.yml
- airflow/dags/parse_and_validate_rt/parse_rt_service_alerts.yml
- airflow/dags/parse_and_validate_rt/parse_rt_trip_updates.yml
- airflow/dags/parse_and_validate_rt/parse_rt_vehicle_positions.yml
- airflow/dags/parse_and_validate_rt/validate_rt_service_alerts.yml
- airflow/dags/parse_and_validate_rt/validate_rt_trip_updates.yml
- airflow/dags/parse_and_validate_rt/validate_rt_vehicle_positions.yml
- airflow/dags/sandbox/load_airtable_child.yml
Fixes a bug I introduced around prefix_bucket; in some places, the caller adds the protocol, but we should just let prefix_bucket handle it.
Locally via Airflow.
```
...
Downloading airtable data for transit_technology_stacks.services
Uploading to GCS at gs://test-calitp-airtable/transit_technology_stacks__services/dt=2022-07-07/time=14:05:38/services.jsonl.gz
[2022-07-07 14:05:39,611] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=airtable_loader_v2, task_id=transit_tech_stacks_services, execution_date=20220707T020000, start_date=20220707T140443, end_date=20220707T140539
[2022-07-07 14:05:39,637] {dagrun.py:477} INFO - Marking run <DagRun airtable_loader_v2 @ 2022-07-07T02:00:00+00:00: backfill__2022-07-07T02:00:00+00:00, externally triggered: False> successful
[2022-07-07 …
```
> let the prefix_bucket macro also add the gs protocol

- airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py
- airflow/plugins/operators/airtable_to_gcs.py
- airflow/requirements.txt
Refactoring GTFS schedule and Airtable to use timestamps in partitions instead of "time" strings. 
Local Airflow. 
```
tY2EtdXMvYmVsbGZsb3dlci1jYS11cy56aXA=/ts=2022-07-14T19:26:22.469787+00:00/bellflower-ca-us.zip
took 6 minutes ago to process 178 records
[2022-07-14 19:26:23,734] {storage.py:255} INFO - saving 581.4 kB to gs://test-calitp-gtfs-schedule-raw/download_schedule_feed_results/dt=2022-07-14/ts=2022-07-14T19:19:28.126183+00:00/results.jsonl
successfully fetched 177 of 178
Failures:
404 Client Error: Not Found for url: http://data.trilliumtransit.com/gtfs/taft-co-us/taft-ca-us.zip
Skipping since in development mode! Would have emailed 1 failures.
[2022-07-14 19:26:24,872] {python.py:151} INFO - Done. Returned value was: None
[2022-07-14 19:26:24,878] {taskinstance.py:1212} INFO - …
```
> Timestamp hive partitions

- warehouse/models/gtfs_views/_gtfs_views.yml
- warehouse/models/gtfs_views/gtfs_schedule_fact_daily_trips.sql
- warehouse/models/gtfs_views/gtfs_schedule_fact_daily_trips_inc.sql
Makes a test version of the `gtfs_schedule_fact_daily_trips` table that is incrementally materialized. We will let this run for about a week in test to confirm it is accurately replicating the current behavior and, if so, replace the old table (which currently takes 20+ minutes to run every day and causes our dbt run DAG task to fail.)
This also updates the documentation & tests on the main `gtfs_schedule_fact_daily_trips` table to:
1. Fix the failing uniqueness test -- this partially addresses #1471, though not entirely. 
2. Correctly identify the (composite) primary key 
`dbt run` and `dbt test` both pass locally for this new table
> Fact daily trips incremental

- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/poetry.lock
* Comments out relationship tests that were causing the dbt-Metabase connection to fail for the `mart_transit_database` dataset -- planning to reinstate these next week via an alias or similar, but they are not critical 
* Updates the dbt-Metabase version to address a bug 
Ran dbt-Metabase exposures locally, verified that error that was occurring before has stopped
> dbt-metabase updates

- kubernetes/gke/config-nodepool.sh
Apparently I never actually PR'd this. My bad; good thing I checked cause this new node pool is already called gtfsrt-v3.
> switch rt node pool to c2 instances

- warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml
- warehouse/scripts/dbt_artifacts.py
- warehouse/scripts/publish.py
Adds additional CKAN IDs for the GTFS Schedule data set. Also updates dictionary and rounds lat/lon to 5 digits as required by the open data portal precision guidelines.
Resolves https://github.com/cal-itp/data-infra/issues/284
Running locally for now.
> Expand GTFS schedule data published to CKAN

- airflow/data/agencies.yml
Update Mountain Transit's schedule URL
Confirmed via email with Juliet from Trillium that this is the proper URL to use, downloaded locally.
> Update Mountain Transit URL

- docs/analytics_tools/notebooks.md
Bug: While onboarding to JupyterHub and granting GCS permissions, the gcloud commands are out of date and can't successfully install. 
Resolves [Slack convo](https://cal-itp.slack.com/archives/C02KH3DGZL7/p1659551211529189)
> (analyst_docs): update gcloud commands

- warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml
- warehouse/scripts/dbt_artifacts.py
Per email from Conveyal, the [latest GTFS open dataset on the CA open data portal](https://data.ca.gov/dataset/cal-itp-gtfs-ingest-pipeline-dataset) is missing the `calitp_itp_id` and `calitp_url_number` attributes. Upon inspection we were also publishing the `calitp_hash` and `<file name>_key` fields, which are not in the data dictionary and not intended to be published. 
This PR:
* Updates the column metadata so that `calitp_itp_id` and `calitp_url_number` *will* be published, and `calitp_hash` and `<file name>_key` will *not*
* Updates the Pydantic dbt Manifest parsing to make the `TestMetadata` attribute optional -- when I tried to dry-run the publish workflow, it failed because some [newly-defined](https://github.com/cal-itp/data-infra/pull/1418) [singular …
> Fix CA Open Data Columns

- warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml
When attempting to publish an updated version of the GTFS latest-only data, my upload failed because the stop_times data is too large for the CKAN API. We will need to reach out to the CKAN admin folks for support (already have one inquiry out to them); in the meantime I am suppressing stop_times so we can re-publish everything else with the correct columns.
See #1669; we actually successfully re-published agency and routes but then stop_times failed because of data size.
> fix(open data): suppress publishing stop_times because of size limit

- airflow/data/agencies.yml
Update FCRTA and add Escalon Transit information in agencies.yml
Resolves #1672 
**Question for @evansiroky and @o-ram:** In #1672, Olivia said to list the agency_name as `Escalon Transit`. In `agency.txt` and on their website it seems that they always use the `eTrans` branding. Do we want to list the `calitp_agency_name` (the `agency_name` field in agencies.yml) as `eTrans`, or leave it as `Escalon Transit`?
* Tried each download link, verified they work
* Checked `gtfs_schedule_dim_feeds` to confirm that ITP ID `107` has never been used
> agencies.yml: add FCRTA and Escalon Transit

- runbooks/change_partitions_runbook.ipynb
Notebook we used to change how some data files were partitioned in GCS. Good code to have around.
n/a
> add notebook used to re-name a partition

- airflow/plugins/utils.py
Fixes #1675 by ignoring non-UTF-8 characters in our copy operation (this is the task that copies new GTFS data from one CSV location to a second CSV location with only the known subset of columns.) 
I have chosen to use the `replace` pandas error handling, which replaces the illegal character with a defined unknown.
Alternatives would be:
- Trying to find an encoding that works for the Foothill Transit data on 2022-07-26. 
- Use `ignore` instead of `replace` (see [docs](https://docs.python.org/3/library/codecs.html#error-handlers)); this would replace with an empty space instead of a placeholder character
I liked the placeholder character because it preserves the fact that some data was present. 
Resolves #1675
- Tested in a notebook and manually confirmed that this option works for the …
> fix(airflow/gtfs_loader): replace non-utf-8 characters

- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/bridge_organizations_x_funding_programs.sql
- warehouse/models/mart/transit_database/bridge_organizations_x_gtfs_datasets_produced.sql
- warehouse/models/mart/transit_database/dim_gtfs_service_data.sql
- warehouse/models/mart/transit_database/dim_organizations.sql
- warehouse/models/mart/transit_database/dim_services.sql
- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
- warehouse/models/staging/transit_database/stg_transit_database__services.sql
Adding new columns to `mart_transit_database` tables per request #1674. Resulting (post-PR) tables can be viewed in `cal-itp-data-infra-staging.laurie_mart_transit_database` for testing. 
Rundown by requested column:
- `reporting_category`: added to `dim_organizations`
- `ntp_id` (ntd_id): added to `dim_organizations`
- `alias`: added to `dim_organizations`
- `fares_v2_status`: added to `dim_gtfs_service_data` -- join to `organizations` via `bridge_organizations_x_services_managed`
- `gtfs_schedule_status`: added to `dim_services` -- join to `organizations` via `bridge_organizations_x_services_managed`
- `gtfs_static_status`: added to `dim_organizations`
- `gtfs_realtime_status`: added to `dim_organizations`
- `mobility_services_managed`: this is what the …
> feat(airtable): add new columns per request #1674

- airflow/data/agencies.yml
- airflow/data/headers.yml
Adds new RT URLs and associated header info for City of West Hollywood.
Downloading RT feeds locally.
> Add WeHo RT URLs

- warehouse/scripts/publish.py
I noticed that when running `poetry run python scripts/publish.py generate-exposure-documentation california_open_data`, fields that had `publish.ignore = True` were still being included in the data dictionary. This PR fixes that by adding a check that a field is supposed to be published before adding it to the data dictionary.
Tested by running `poetry run python scripts/publish.py generate-exposure-documentation california_open_data` and confirming that resulting files do not contain `calitp_hash` and other fields that were suppressed in #1669.
> fix(ckan publishing): only add columns to data dictionary if they're supposed to be published

- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml
- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-ticker.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/archiver-channel-vars.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/archiver-channel-vars.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- services/gtfs-rt-archiver-v3/docker-compose.yml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/metrics.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/ticker.py
- services/gtfs-rt-archiver-v3/poetry.lock
- services/gtfs-rt-archiver-v3/pyproject.toml
Brings the new archiver up to date with some new practices (i.e. env vars to define buckets) as well as loads secrets in the ticker.
Resolves https://github.com/cal-itp/data-infra/issues/1686
It's already deployed to dev and prod.
> Use env vars to configure RT archiver and include updated calitp with various fixes

- docs/datasets_and_tables/transitdatabase.md
The Transit Technology Stacks header was not properly being linked to in the overview table. This fixes that.
Previewed with GitHub
> Correct Transit Technology Stacks title

- airflow/data/agencies.yml
Per discussion with the GRaaS project manager, the following changes are made:
- Removal of the following agencies that were in a demo that are no longer producing data
- Desert Roadrunner
- Glenn County Transit
- Tulare County Regional Transit Agency
- Daylighting the URL for Santa Ynez Valley Transit as it is now in production.
Further updates to GRaaS URLs that require masking URLs will now mask the URL parameters instead of the server domain.
Verified via conversations with the GRaaS product manager.
> Update GRaaS URLs

- airflow/requirements.txt
The new version of gcsfs has a [regression](https://github.com/fsspec/gcsfs/issues/486) that is affecting our Airflow jobs. I've deployed a [new version](https://github.com/cal-itp/calitp-py/pull/73) of calitp-py that pins us to an older gcsfs version.
```
Installing collected packages: gcsfs
Successfully installed gcsfs-2022.5.0
```
> use new version of caltip py with good gcsfs

- airflow/requirements.txt
Deploys https://github.com/cal-itp/calitp-py/pull/74 but also pins a specific fsspec directly in the Composer requirements file.
```
(.venv) ➜  airflow git:(hotfix-gcsfs-version) ✗ gcloud composer environments update calitp-airflow2-prod --update-pypi-packages-from-file requirements.txt --location us-west2 --project cal-itp-data-infra
Waiting for [projects/cal-itp-data-infra/locations/us-west2/environments/calitp-airflow2-prod] to be updated with [projects/cal-itp-data-infra/locations/us-west2/operations/b7fb32bf-6b3b-4fbb-9d8e-9b4c62bf8dca]...done.
```
> Hotfix gcsfs version

- ci/vars/releases/prod-sftp-ingest-elavon.env
- kubernetes/apps/manifests/sftp-server/intranet-service.yaml
- kubernetes/apps/manifests/sftp-server/kustomization.yaml
- kubernetes/apps/manifests/sftp-server/sshd_config
- kubernetes/apps/manifests/sftp-server/workload.yaml
- kubernetes/apps/overlays/base-sftp-ingest-elavon/kustomization.yaml
- kubernetes/apps/overlays/base-sftp-ingest-elavon/sftp-user.yaml
- kubernetes/apps/overlays/dev-sftp-ingest-elavon/kustomization.yaml
- kubernetes/apps/overlays/dev-sftp-ingest-elavon/ns.yaml
- kubernetes/apps/overlays/dev-sftp-ingest-elavon/sftp-user-config.yaml
- kubernetes/apps/overlays/prod-sftp-ingest-elavon/internet-service.yaml
- kubernetes/apps/overlays/prod-sftp-ingest-elavon/kustomization.yaml
- kubernetes/apps/overlays/prod-sftp-ingest-elavon/ns.yaml
- kubernetes/apps/overlays/prod-sftp-ingest-elavon/patch-volume-size.json
- kubernetes/apps/overlays/prod-sftp-ingest-elavon/sftp-user-config.yaml
This changeset introduces an SFTP server infrastructure component which is then exposed on a stable public IP and port to receive enriched data from Elavon.
Resolves #1667 
Locally, using a kind cluster
> Create SFTP ingest component for Elavon data

- airflow/dags/unzip_and_validate_gtfs_schedule/validate_gtfs_schedule.yml
I forgot to add a pool to control how many schedule pipeline jobs can run at once during the backfill.
> limit schedule validation jobs with a pool

- airflow/plugins/operators/external_table.py
In the event we provide a schema for a BigQuery external table, we should not also be setting schema autodetection as it will override the provided schema.
Necessary and tested in https://github.com/cal-itp/data-infra/pull/1691
> disable autodetect if schema is specified

- airflow/plugins/operators/amplitude_to_flattened_json.py
This PR makes it so that if the `amplitude_benefits` DAG's `api_to_jsonl` task sees a 404 from the Amplitude API, the task will be marked as Skipped instead of Failed. (A 404 from the API just means that there was no data, and there are valid cases for that, such as the application being down or analytics not being enabled.)
Resolves #1682
Manually with my local Airflow Docker container (set `start_date` to `2022-08-05` and `end_date` to `2022-08-06`).
**Tree view:**
**Task logs:**
> Fix: skip amplitude_benefits DAG if 404

- airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py
- airflow/dags/unzip_and_validate_gtfs_schedule/unzip_gtfs_schedule.py
- airflow/docker-compose.yaml
- airflow/requirements.txt
This PR partially addresses #1533 -- it takes a zipfile, extracts its constituent files, and writes those files to GCS in hive-partitioned paths. This PR does **not** cover converting the raw data to JSONL. That will be a subsequent task/PR. 
Stray notes about implementation / PR contents:
* @atvaccaro also updated the new downloader to use the latest (as of 8/25) version of `calitp`
* In general here I am saving only the **path** of the prior / subsequent artifacts and not their entire metadata
Example outputs from this new DAG task:
* [Results file](https://console.cloud.google.com/storage/browser/_details/test-calitp-gtfs-schedule-unzipped/unzipping_results/dt%3D1901-01-01/results.jsonl;tab=live_object?project=cal-itp-data-infra&supportedpurview=project)
* [stops.txt …
> Gtfs schedule unzip v2

- jobs/gtfs-rt-parser-v2/.dockerignore
- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
Brings the RT outcomes in alignment with https://github.com/cal-itp/data-infra/pull/1696; in general, we're moving towards just saving paths to source data instead of the entire source data container pydantic type.
Locally.
```
saving 8939 outcomes to gs://test-calitp-gtfs-rt-validation/service_alerts_validation_outcomes/dt=2022-08-15/hour=2022-08-15T16:00:00+00:00/service_alerts.jsonl
fin.
```
> Clean up RT outcomes

- warehouse/macros/create_row_access_policy.sql
- warehouse/models/payments_views/payments_rides.sql
I didn't realize that row access policies (introduced in https://github.com/cal-itp/data-infra/pull/1697) meant 0 rows were shown if a user failed to match any criteria. This PR restores full access to `payments_rides` to the appropriate users.
This has already been deployed and I've confirmed in Metabase.
> grant access to payments_rides for non-agency users

- airflow/dags/macros.py
- airflow/dags/publish_open_data/METADATA.yml
- airflow/dags/publish_open_data/publish_california_open_data.yml
- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
- airflow/docker-compose.yaml
- docs/publishing/sections/8_ckan.md
- warehouse/.dockerignore
- warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml
- warehouse/models/gtfs_schedule_latest_only/stop_times.sql
- warehouse/scripts/publish.py
- warehouse/scripts/run_and_upload.py
Finally gets large files uploading to CKAN and defines an Airflow task to run weekly! The task uses the latest manifest artifact in GCS to pick the tables to select and upload. I don't think we can automate metadata unfortunately, as that's a manual process with human review.
Closes https://github.com/cal-itp/data-infra/issues/283
Progress towards https://github.com/cal-itp/data-infra/issues/427, I think we need to get the updated metadata/dictionary sent first.
Locally... lots.
```
[2022-08-26 20:26:27,203] {pod_launcher.py:311} INFO - Event with job id publish-california-open-data.cfb34c7982874d3fb9191dcd70c66297 Succeeded
[2022-08-26 20:26:27,301] {pod_launcher.py:198} INFO - Event: publish-california-open-data.cfb34c7982874d3fb9191dcd70c66297 had an event of type Succeeded
[2022-08-26 …
```
> Run CKAN weekly, with multipart uploads as needed

- warehouse/dbt_project.yml
- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/mart/gtfs_guidelines/_gtfs_guidelines.yml
- warehouse/models/mart/gtfs_guidelines/fact_daily_guideline_checks.sql
- warehouse/models/mart/gtfs_guidelines/gtfs_schedule_fact_daily_guideline_checks.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__feed_guideline_index.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__no_validation_errors_in_last_30_days.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__schedule_downloaded_successfully.sql
- warehouse/scripts/run_and_upload.py
This PR addresses #1688 by creating an initial table following [the schema](https://docs.google.com/spreadsheets/d/1v5nPowMi0EzQpfDd9d0ZluWnKX8JKm8E2nGMmuUvDRE/edit#gid=1164332414) requested, with slight modification -- `agency-id` is implemented as the combination of `calitp_itp_id`, `calitp_url_number`, and `calitp_agency_name` (for readability).
Specifically, this table implements two guideline checks:
* GTFS schedule downloaded successfully: checks whether there was a download error for a given GTFS schedule feed 
* No validation errors in last 30 days: checks for number of validation notices with "error" severity in the last 30 days -- >0, fail, if 0, pass 
I'd like both @atvaccaro and @owades to review before merging. 
TODO after merge:
* Sync the `mart_gtfs_guidelines` dataset to …
> Initial dbt models to support GTFS guidelines checks

- warehouse/models/rt_views/_rt_views.yml
- warehouse/models/rt_views/gtfs_rt_vs_sched_routes.sql
- warehouse/models/rt_views/gtfs_rt_vs_schedule_trips_sample.sql
Adding a table that looks at the number of scheduled trips and trips with vehicle position data. This table currently has two operators (ITP_ID 300 Big Blue Bus and ITP_ID 290 SamTrans) and compares data for two months. 
The table currently lives in rt_views but can be changed! 
To come after GTFS rewrite: additional operators and more dates - NOT urgent. 
Works towards #[263](https://github.com/cal-itp/data-analyses/issues/263) in data-analyses
*note:* column agency_name not always merging right. looking into this. 
Tested using dbt tables in natalie_views
> Add RT VP vs Sched Table

- warehouse/Dockerfile
- warehouse/Dockerfile.local
- warehouse/dbt.sh
Creates a Dockerfile specific to running dbt locally and adds a bash script to facilitate using the image.
Resolves https://github.com/cal-itp/data-infra/issues/1715
Locally.
```
➜  warehouse git:(dbt-docker) ✗ ./dbt.sh debug
[+] Building 0.7s (18/18) FINISHED
=> [internal] load build definition from Dockerfile.local                                                                          0.0s
=> => transferring dockerfile: 43B                                                                                                 0.0s
=> [internal] load .dockerignore                                                                                                   0.0s
=> => transferring context: 34B …
```
> Create local Dockerfile and bash script for dbt development

- warehouse/models/gtfs_views/_gtfs_views.yml
Adds metadata for `calitp_itp_id`, `calitp_url_number`, `calitp_extracted_at`, and `calitp_deleted_at` to a bunch of dimensional tables. 
Resolves -- No ticket but @owades ran into this earlier where he couldn't create an ID filter on `calitp_itp_id` for `dim_stops` because the column didn't have the correct Metabase Type.
Ran dbt locally for the affected columns, verified it succeeded, spot checked that everything was appearing as expected in BQ.
> warehouse documentation: add some column metadata to dimensional tables

- airflow/dags/create_external_tables/external_airtable_california_transit_organizations.yml
- airflow/dags/create_external_tables/external_airtable_transit_tech_stacks_organizations.yml
This PR partially addresses #1731 by defining a schema for the organizations external tables that will suppress the `fare_systems` field entirely. 
Schema for the `california_transit` copy of the table was generated by running `bq show --schema --format=json cal-itp-data-infra:external_airtable.california_transit__organizations | pbcopy` and converting that to YAML via https://www.json2yaml.com/.
Tested locally in Airflow, generated new external tables, and ran dbt locally pointed at the staging external tables to confirm that dbt models can run with this change.
> Organizations external table: define schema

- airflow/dags/airtable_loader_v2/METADATA.yml
@lauriemerrell has been noticing instability in the nightly AIrtable downloads. We've paused the old v1 DAGs now but I want to also limit the new DAG since it's composed of ~20 tasks.
> add pool for airtable

- airflow/plugins/operators/__init__.py
In #1699 I forgot to delete this import, which resulted in a DAG Import error & stopped Airflow running for the last ~day
N/A
> fix: delete broken airtable import, cleanup from PR #1699

- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__feed_guideline_index.sql
I observed that after 12am UTC (4pm pacific), guideline check dashboard in metabase shows skewed results, as it shows incomplete data from the current day.
This PR addresses this by preventing feed_guideline_index from ever including the current date.
I ran this change on today's data, visible in `cal-itp-data-infra-staging.owades_mart_gtfs_guidelines.fact_daily_guideline_checks`. Verified that the most recent data is yesterday, while the main table contains data from today.
> Omit current date from fact_daily_guideline_checks

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/mart/gtfs_guidelines/fact_daily_guideline_checks.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__feed_guideline_index.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__no_rt_critical_validation_errors.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__service_alerts_feed_present.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__trip_id_alignment.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__trip_updates_feed_present.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__vehicle_positions_feed_present.sql
5 new checks:
**no_rt_critical_validation_errors**: If the feed has >0 RT files on the given day AND no critical errors in the RT validator, then PASS. If either condition isn't met, FAIL 
**trip_id_alignment**: If the feed has >0 RT files on the given day AND didn't not have an error in the validator related to mismatched trip_id's, then PASS. If either condition isn't met, FAIL. The specific conditions for the validator check are: "All trip_ids provided in the GTFS-rt feed must exist in the GTFS data, unless the schedule_relationship is ADDED"
**vehicle_positions_feed_present**, **trip_updates_feed_present**, & **service_alerts_feed_present**: If the given feed is present at least once on the day, PASS. else, FAIL
no_rt_critical_validation_errors:
manually cross-check output with values …
> 5 new draft checks for rt feed

- airflow/dags/publish_open_data/METADATA.yml
We noticed that the `publish_open_data` DAG has not actually ever had a scheduled run since it got merged in August. It looks like the `start_date` setting was tripping it up. Hard-coding the start date should resolve. 
N/A, having a hard coded start date is standard
> fix publish_open_data dag's start date so it will actually run

- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/agency_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/areas_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/attributions_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/calendar_dates_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/calendar_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/fare_attributes_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/fare_leg_rules_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/fare_products_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/fare_rules_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/feed_info_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/frequencies_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/levels_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/pathways_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/routes_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/shapes_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/stop_areas_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/stop_times_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/stops_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/transfers_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/translations_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/convert_to_json/trips_txt.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/unzip_gtfs_schedule.py
- airflow/plugins/operators/gtfs_csv_to_jsonl.py
- airflow/plugins/utils.py
Cleanups post #1754 before turning schedule parse & unzip in prod.
* Add dependency between unzip & parse DAG tasks
* Stop saving filepaths, instead save whole extract objects
* Stop putting metadata header in JSONL files (undoes change from #1754 that we no longer want)
* Give each parsing task its own results file
* Handle case where no files are found to convert to JSON
Ran locally in Airflow with @atvaccaro as my witness
> Json depend on unzip

- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/pyproject.toml
I'm not 100% sure what happened, I assume the cluster didn't re-pull the latest for prod? But I'm not sure what happens if the nodes were pulling the latest for the test deployment? I need to learn some more.
> image pull policy is confusing!!!

- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
```
➜  gtfs-rt-parser-v2 git:(handle-no-rt-files) poetry run python gtfs_rt_parser.py validate service_alerts 2021-09-15T17:00:00 --progress --verbose
listing all files in gs://test-calitp-gtfs-rt-raw/service_alerts/dt=2021-09-15/hour=2021-09-15T17:00:00+00:00/
WARNING: found no files to process for service_alerts 2021-09-15T17:00:00+00:00, exiting
```
> cleanly return if no rt files to process

- airflow/data/agencies.yml
These URLs appear to work without a static IP address now.
Sent requests in Postman and received a successful response for each.
> Add Foothill's RT URLs

- airflow/dags/transform_warehouse/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
`transform_warehouse.dbt_test` has been failing for a while in prod because of a missing environment variable (and I missed it because it had been failing for a while before that due to actual test failures, so I was not checking the failure details as regularly as I should have been.)
Also setting it in the full-refresh DAG task since it was missing there
Confirmed I can now run `test_dbt` in local Airflow:
```
[2022-09-19 14:32:06,836] {pod_launcher.py:198} INFO - Event: dbt-test.5acd7d9d7de24adf837b182829c0dc84 had an event of type Running
[2022-09-19 14:32:10,046] {pod_launcher.py:149} INFO - 14:32:10  Running with dbt=1.1.1
[2022-09-19 14:32:10,047] {pod_launcher.py:149} INFO - 14:32:10  Partial parse save file not found. Starting full parse.
[2022-09-19 14:32:12,608] …
```
> Set missing dbt bucket env var

- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/docker-compose.yml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/poetry.lock
- services/gtfs-rt-archiver-v3/pyproject.toml
Now that we're processing new RT data in Airflow, we're seeing some missing metadata. My initial theory is that metadata is sometimes failing to be written, though I haven't been able to find errors in the logs. This PR both adds logging as well as a single retry on the save call.
It's deployed to test.
> add a retry and a specific log for RT archiver saving exceptions

- warehouse/models/gtfs_views/gtfs_schedule_dim_feeds.sql
This is a slightly hacky fix for #1471. This has been an issue for a while but now that we have RT data for Foothill Transit (#1794) it is causing the `gtfs_rt_fact_daily_validations_errors` incremental table to fail to build. This is a more significant effect than anything else so far so I think it's worth fixing this ASAP to get that table working. 
Resolves #1471
I ran the updated version in my local dbt to create `cal-itp-data-infra-staging.laurie_views.gtfs_schedule_dim_feeds` and then compared that with the prod table:
```
SELECT  
t1.feed_key,
t1.calitp_itp_id,
t1.calitp_url_number,
t1.calitp_extracted_at,
t2.feed_key,
t2.calitp_itp_id,
t2.calitp_url_number,
t2.calitp_extracted_at
FROM `cal-itp-data-infra.views.gtfs_schedule_dim_feeds` AS t1
FULL OUTER JOIN …
```
> fix two-row feed info issue

- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml
in addition to those retries, I realized deploys were causing issues because huey forcefully stops workers on a SIGTERM; this can mean a worker is stopped in between writing a file and updating the metadata
this is applied to test and I will apply to prod on merge
```
INFO:huey:gtfs_rt_archiver_v3.tasks.fetch: 4bd3550a-0aea-4d66-98c1-26277d0f5f6d exp=5 (2022-09-19 17:44:25.085849) executed in 3.607s
[2022-09-19 17:44:25,627] INFO:huey.consumer:MainThread:Received SIGINT
INFO:huey.consumer:Received SIGINT
[2022-09-19 17:44:25,627] INFO:huey.consumer:MainThread:Shutting down gracefully...
INFO:huey.consumer:Shutting down gracefully...
[2022-09-19 17:44:25,639] INFO:huey.consumer:MainThread:Received SIGTERM
INFO:huey.consumer:Received SIGTERM
saving 245.3 kB from …
```
> send sigint to huey for graceful exists and give 5 seconds grace period

- warehouse/models/rt_views/gtfs_rt_fact_daily_validation_errors.sql
The `transform_warehouse_full_refresh.dbt_run_and_upload_artifacts` DAG task is failing because you can't run a query over the RT validations data without any date partition: 
`Database Error in model gtfs_rt_fact_daily_validation_errors (models/rt_views/gtfs_rt_fact_daily_validation_errors.sql)
Cannot query over table 'cal-itp-data-infra.external_gtfs_rt.service_alerts_validations' without a filter over column(s) 'dt', 'hour', 'itp_id', 'url_number' that can be used for partition elimination`
This PR fixes this by hard-coding a start date of `2021-01-01`. In general we **do** want people to specify actual date partitions that will filter out data but for `--full-refresh` to actually re-process all the data, we need to set a fake partition date that won't actually exclude anything. 
Ran …
> fix: make full refresh of gtfs rt fact daily validations table work

- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- kubernetes/apps/manifests/airflow-jobs/dbt-priority-class.yaml
- kubernetes/apps/manifests/airflow-jobs/kustomization.yaml
May help prevent situations where dbt pods take too long to start.
> create a priority class for dbt run pods and use it

- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
Quick fix, mistake found during external table creation.
Locally.
```
[2022-09-20 16:24:19,188] {pod_launcher.py:149} INFO - writing 1021739 lines to gs://test-calitp-gtfs-rt-parsed/trip_updates/dt=2022-09-15/hour=2022-09-15T18:00:00+00:00/base64_url=aHR0cHM6Ly9hcGkuZ29zd2lmdC5seS9yZWFsLXRpbWUvbGFtZXRyby9ndGZzLXJ0LXRyaXAtdXBkYXRlcw==/trip_updates.jsonl.gz
[2022-09-20 16:24:21,515] {pod_launcher.py:149} INFO - saving 14675 outcomes to gs://test-calitp-gtfs-rt-parsed/trip_updates_outcomes/dt=2022-09-15/hour=2022-09-15T18:00:00+00:00/trip_updates.jsonl
[2022-09-20 16:24:24,146] {pod_launcher.py:149} INFO - fin.
[2022-09-20 16:24:26,387] {pod_launcher.py:198} INFO - Event: parse-rt-trip-updates.6b2039a27a28420094b6b07e7c3132cf had an event of type Succeeded
[2022-09-20 16:24:26,387] …
```
> save extract not extract path on rt processing outcomes

- airflow/dags/create_external_tables/METADATA.yml
I think firing off the 40+ tasks at once overloads our celery workers. I've created `external_table_pool` so we can limit but adjust vs a hard-coded concurrency limit.
> add an external table creation pool

- airflow/requirements.txt
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/poetry.lock
- services/gtfs-rt-archiver-v3/pyproject.toml
Resolves https://github.com/cal-itp/data-infra/issues/1817
Retries were also attempting a write, which fails because of the retention policy. I made a change in calitp to just retry on the metadata and provide a flag (does not retry by default).
This is deployed to test RT and I have tested with schedule. Will deploy to prod on merge.
```
[2022-09-21 15:54:15,892] {storage.py:259} INFO - saving 276.2 kB to gs://test-calitp-gtfs-schedule-raw-v2/download_schedule_feed_results/dt=2022-09-21/ts=2022-09-21T15:45:30.045952+00:00/results.jsonl
successfully fetched 210 of 211
Failures:
404 Client Error: Not Found for url: http://data.trilliumtransit.com/gtfs/taft-co-us/taft-ca-us.zip
Skipping since in development mode! Would have emailed 1 failures.
[2022-09-21 15:54:17,414] {python.py:151} INFO …
```
> use newest calitp to let it handle metadata retries, and deploy to test

- warehouse/models/mart/gtfs_guidelines/fact_daily_transitland_url_check.sql
As noted by @owades [in this PR thread](https://github.com/cal-itp/data-infra/pull/1737#issuecomment-1253021585), the `calitp_url_number` is providing incorrect values. This PR represses the column until a fix is completed.
A fix will come during the process of migrating the feed aggregator checker to use Airtable, as represented by this issue #1825 that @lauriemerrell created.
Once #1825 is complete we can reverse this PR.
Tested locally in dbt dev environment
> Remove column calitp_url_number from fact_daily_transitland_url_check

- warehouse/models/mart/gtfs_guidelines/_gtfs_guidelines.yml
- warehouse/models/staging/gtfs_guidelines/_stg_gtfs_guidelines.yml
In #1827 we suppressed the `calitp_url_number` column due to bugs found (fix represented in #1825, bug identified in #1737), however we didn't revise the tests in `fact_daily_transitland_url_check` and `stg_gtfs_guidelines__fact_daily_transitland_url_check`.
This PR removes the `calitp_url_number` and `url_type` columns from the `Unique Combination of Columns` tests on both tables, and adds the `url` column.
`dbt test` has been run locally in the dbt test environment
> Revised tests on transitland url check tables

- warehouse/models/rt_views/gtfs_rt_vs_schedule_trips_may4_sample.sql
- warehouse/models/rt_views/gtfs_rt_vs_schedule_trips_metro_sample.sql
- warehouse/models/rt_views/gtfs_rt_vs_schedule_trips_sample.sql
Create a new table mirroring `gtfs_rt_vs_schedule_trips_sample.sql` but for all operators on a single date. 
Resolves # [1834](https://github.com/cal-itp/data-infra/issues/1834)
> Rt sched may 4 sample

- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/dim_services.sql
- warehouse/models/staging/transit_database/stg_transit_database__services.sql
Resolves #1782 by making the `services.gtfs schedule quality` field available in the warehouse in the `mart_transit_database.dim_services` table. Per Slack ([thread](https://cal-itp.slack.com/archives/C040XD9UB33/p1663115063896459)), this is intended to be a temporary solution until more automated data is easily available. See [this comment](https://github.com/cal-itp/data-infra/issues/1782#issuecomment-1256345628) for limitations of this data. 
Resolves #1782
Ran in staging dbt, confirmed that column is available. See `cal-itp-data-infra-staging.laurie_mart_transit_database.dim_services` table.
> temporarily add services.gtfs schedule quality column

- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
Laurie noticed I left out the actual RT extract timestamp from the final metadata, which we do need since the header timestamp is the last updated time (I think).
> add ts to rt metadata

- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_service_alerts.yml
- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_service_alerts_validations.yml
- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_trip_updates.yml
- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_trip_updates_validations.yml
- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_vehicle_positions.yml
- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_vehicle_positions_validations.yml
Small followup PR to #1851 to get the new field in the relevant external tables. 
Ran it locally: 
There isn't actually data available yet in the backfill with the new attribute, we can hold until there is to confirm this works if needed
> add extract_ts to metadata schema for RT data & validations

- airflow/dags/airtable_loader_v2/generate_gtfs_download_configs.py
- airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py
- airflow/dags/transform_warehouse/dbt_test.yml
- airflow/docker-compose.yaml
- kubernetes/apps/charts/sentry/values.yaml
- kubernetes/apps/manifests/gtfs-rt-archiver-v3/archiver-app-vars.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/archiver-channel-vars.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/archiver-channel-vars.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/docker-compose.yml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/pyproject.toml
- warehouse/scripts/run_and_upload.py
Also I'm moving towards `cal-itp-data-infra`, `test`, and `development` as our three environments, which roughly mirrors our actual "environments" in-so-far as we have them.
This is deployed to test and I've tested in docker-compose.
> Sentry followups - fixing email/DSNs, logging more events, using env vars, and fixing fetch exception grouping

- airflow/data/agencies.yml
mysmartbus.com is actually a URL for South Metro Area Regional Transit out of Wilsonville, Oregon. This reverts the URL to be what it was before this erroneous data was added.
Examined contents of downloaded feed, verified routes present in Gtfs Schedule Dim Routes.
> Remove erroneous SMART URLs

- airflow/dags/airtable_loader_v2/generate_gtfs_download_configs.py
- airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/pyproject.toml
This lumps together a couple changes to deploy at once.
1. Adds a new RT key to read from secrets manager
2. Removes default fingerprinting from RT fetch failures so stacktrace changes do not affect grouping
3. Adds more tags and context to various Sentry scopes
see https://sentry.calitp.org/organizations/sentry/issues/427/events/9ae9974a6c664c7d83cab348e854fffd/?environment=test&project=2 for the new sentry context
> More Sentry improvements and load a new RT key

- kubernetes/apps/manifests/sftp-server/sshd_config
- kubernetes/apps/manifests/sftp-server/workload.yaml
- kubernetes/apps/overlays/prod-sftp-ingest-elavon/internet-service.yaml
The vendor was not able to effectively support troubleshooting of keyed login, so this changeset adds password support to the SFTP server, which should simplify troubleshooting if not outright resolve the problem.
> Add password support for SFTP server

- airflow/data/agencies.yml
Updates identified by @o-ram in #1864.
🚨 Can @o-ram and @evansiroky confirm that we don't need to list any of these URLs in any additional locations? It seems like the Humboldt Trillium schedule feed applies to a few other ITP IDs, just wondering if we know if the service alerts should too. 
Resolves #1864
Confirmed I can download from all the URLs provided. Defer to @o-ram and @evansiroky that the service/agency mapping is correct.
> Schedule alerts url updates

- warehouse/models/mart/gtfs/fct_vehicle_positions_messages.sql
- warehouse/models/staging/gtfs/_stg_gtfs.yml
One more follow up for #1836 / #1870:
> It seems that the reason that our tests are failing in the new `fct_vehicle_positions_messages` table is the MTC regional (combined / RG) feed doesn't give each message entity a unique id.
> So, for example, if 3 different agencies have a message with id = 5, MTC doesn't seem to do anything to make those IDs unique and in the RG feed we just get three messages with that same ID.
To work around this, adding additional fields to synthetic key generation.
Also fixes column name in staging table test.
Verified that this new key should be *actually* unique:
<details> <summary>test SQL</summary>
```
with dbt_test__target as (
select key as unique_field, base64_url, vehicle_id, trip_id
from (select * from …
```
> Add new columns to fct_vehicle_positions_messages key generation & fix column name in staging test

- warehouse/models/mart/gtfs/fct_vehicle_positions_messages.sql
- warehouse/models/staging/gtfs/_stg_gtfs.yml
Alas, the attempt in #1872 to make the keying unique failed in prod (realized this morning that when I tested on 10/3, I was getting weekend data in the date filter -- presumably it failed overnight because of more plentiful weekday data coming in for Monday which introduced dups.) 
Switching to use lat/long as part of the key, confirmed no dups for this set of attributes in yesterday's data for 0 hour UTC. Also bringing staging into alignment. 
Resolves dbt test failures / Sentry issues: 
Ran `dbt run -s +fct_vehicle_positions_messages` / `dbt test -s +fct_vehicle_positions_messages`, both complete with 100% success
SQL also pasted below that was used to determine that this set of attributes was in fact unique; confirmed no dups
<details><summary>SQL details</summary>
```
with …
```
> switch keying for vp messages

- airflow/data/agencies.yml
Adds some more URLs as provided by Avail Technologies. The Petaluma Transit GTFS Schedule URL was failing when I tried, and I'm following up about that.
Downloaded from all URLs locally.
> Add some more URLs

- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/pyproject.toml
Following #1879, this PR adds the `TORRANCE_TRANSIT_API_KEY` to the v3 archiver. The key's value has been added in Secret Manager. I have deployed this change to test & confirmed it worked, can deploy to prod when PR approved.
Note that this API key is not yet referenced in Airtable; this change would be to get out ahead of that so we don't get authorization errors when the URLs **are** added.
Deployed to test. Also this is not a functional change, just adding another key. 
Huey task signals in test showing recovery after restart
> Add Torrance api key for RT

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_gtfs_datasets.yml
Quick fix, a column was removed from Airtable so the auto-detected schema removed the column.
Locally, pointed at the staging version.
> specify the schema for gtfs datasets airtable

- .github/workflows/build-gtfs-aggregator-checker-image.yml
- .github/workflows/build-gtfs-rt-parser-image.yml
- .github/workflows/build-gtfs-rt-parser-v2-image.yml
- .github/workflows/build-gtfs-schedule-validator-image.yml
- .github/workflows/build-warehouse-image.yml
Noticed these didn't actually trigger in the last PR merge; I had renamed these awhile ago for clarity but failed to update their globbing to reflect those changes.
> I never updated these

- kubernetes/apps/charts/sentry/values.yaml
This has already been deployed, but we're switching to a new Postmark email instead of Sendgrid. I've also updated Airflow to use `bot@calitp.org` via Postmark.
> Sentry email changes

- airflow/data/agencies.yml
Adds UCLA Bruin Bus URLs to agencies.yml per #1896.
I also manually added ITP ID 486 to the UCLA record in the `organizations` table in Airtable. 
Resolves #1896
Confirmed all URLs work by downloading locally.
> agencies.yml: add ucla bruin bus

- airflow/data/agencies.yml
Add missing `h` to Bruin Bus URL in `agencies.yml`.
Resolves: issue caught by @aly-medina on Slack 🙏 
Confirmed fixed URL downloads data
> fix ucla bruin bus alerts url

- airflow/data/headers.yml
Removing service alerts feed in headers.yml for Humbolt Transit Authority.
Confirmed feed does not require header authorization.
> Remove Humboldt service alert URL from headers.yml

- script/agencies_verify.py
Quick fix for what @lauriemerrell observed in that failed requests in `agencies_verify.py` that use query auth params end up logging those keys under certain exception types. We need to start the process of rotating keys anyways.
n/a
> only print the type and status code if applicable

- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml
already deployed; grafana told us tasks were expiring, so I bumped consumers to 4; that 4th consumer was unschedulable because we were maxing out the node pool and I had neglected to turn on auto-scaling; that node pool will auto-scale now so we will be good until we hit 6 nodes worth of requirements (3 previously)
> add a 4th prod archiver consumer

- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/intermediate/gtfs/int_gtfs_schedule__daily_scheduled_service_index.sql
- warehouse/models/intermediate/gtfs/int_gtfs_schedule__long_calendar.sql
- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs/fct_daily_scheduled_service.sql
- warehouse/models/mart/gtfs/fct_daily_scheduled_trips.sql
Progress towards #1761. Creates a `fct_daily_scheduled_trips` table. Also creates `int_gtfs_schedule__daily_scheduled_service_index` (and, in the process, `int_gtfs_schedule__long_calendar.sql`) to support further service and trip summary work. For example the current (v1) `fact_daily_service` table contains information about first stop, last stop on that service. I think that would be part of a `fct_daily_scheduled_service` table in the mart based on `fct_daily_scheduled_trips`. We can add further summary information in follow-up PRs, but this creates the skeleton. 
I think we will need to clean up/iterate the interplay between mart and intermediate tables here, but I think that can come with time and isn't prohibitive.
dbt run & dbt test on the two new tables succeeds.
> Fct daily scheduled trips

- warehouse/models/intermediate/gtfs/int_gtfs_schedule__joined_feed_outcomes.sql
- warehouse/models/intermediate/transit_database/_int_transit_database.yml
- warehouse/models/intermediate/transit_database/int_transit_database__urls_to_gtfs_datasets.sql
- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs/fct_daily_schedule_feeds.sql
- warehouse/models/mart/gtfs/fct_daily_scheduled_trips.sql
- warehouse/models/mart/gtfs/fct_schedule_feed_downloads.sql
- warehouse/models/mart/gtfs/fct_vehicle_positions_messages.sql
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/staging/transit_database/stg_transit_database__gtfs_datasets.sql
- warehouse/poetry.lock
- warehouse/pyproject.toml
Adds an intermediate table to provide a URL-to-gtfs_dataset mapping; can provide an interface for eventual versioned/historical Airtable. The key new column is `gtfs_dataset_key` on `dim_schedule_feeds`, allowing users to look up current Airtable data via `<some gtfs data> => dim_schedule_feeds => dim_gtfs_datasets => <some airtable data>`.
One note: Since Airtable is currently latest-only; there are a handful of records `SMART` missing, as they were deleted. Therefore, the tests use a small error threshold that can be removed once Airtable is made historical.
Supports https://github.com/cal-itp/data-infra/issues/1761
Locally; `poetry run dbt run -m +fct_daily_scheduled_trips && poetry run dbt test -m fct_daily_scheduled_trips dim_schedule_feeds stg_transit_database__gtfs_datasets …
> Allow historical feeds to map to current gtfs_dataset records

- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs/fct_schedule_feed_downloads.sql
PR #1937 introduced two issues:
* Merged with tests referencing `gtfs_dataset_key` column in `dim_schedule_feeds` table, but that column is no longer actually present in that table 
* Deleted reference to `dim_schedule_feeds` in `fct_schedule_feed_downloads` but that reference was still needed; did not actually substitute in the reference to the new URL mapping table correctly
This PR fixes both of these issues. This PR also adds a `where` qualifier in the `not_null` test on `fct_schedule_feed_downloads` clarifying that `feed_key` is only present if the feed download actually succeeded.
Fixes the following Sentry alerts:
https://sentry.calitp.org/organizations/sentry/issues/8305/?project=2
```
DbtTestError
test.calitp_warehouse.not_null_dim_schedule_feeds_gtfs_dataset_key.8507969a6a - …
```
> Hotfixes for missing refs (fct_schedule_feed_downloads & dim_schedule_feeds)

- warehouse/models/mart/gtfs/_mart_gtfs.yml
In #1942, I accidentally added a `where: download_success` check in YAML that was tagged as the anchor for the `feed_key` column. This caused failures in the references to that anchor where that `download_success` column is not present. 
This PR fixes this issue & also adds use of this `feed_key` YAML anchor ref to all dimension tables (i.e., it was incorrect that only `calendar` and `calendar_dates` failed -- all the schedule dimension tables should have had this issue.) Also removes erroneous ref to `ts` column in `dim_stop_times`.
Resolves Sentry errors:
https://sentry.calitp.org/organizations/sentry/issues/8310/?project=2
```
test.calitp_warehouse.not_null_dim_calendar_feed_key.0daf07590f - Database Error in test not_null_dim_calendar_feed_key (models/mart/gtfs/_mart_gtfs.yml) …
```
> fix anchor yaml for feed_key column

- airflow/dags/create_external_tables/gtfs_schedule_v2/validation_notices.yml
I am working on v2 validation models and found this typo in the external table. I need it deployed since dbt sources (correctly) point at the production version of external tables.
```
Deleting external table if exists: cal-itp-data-infra-staging.external_gtfs_schedule.validation_notices
Creating external table: cal-itp-data-infra-staging.external_gtfs_schedule.validation_notices Table(TableReference(DatasetReference('cal-itp-data-infra-staging', 'external_gtfs_schedule'), 'validation_notices')) ['gs://test-calitp-gtfs-schedule-validation/validation_notices/*.jsonl.gz'] {'mode': 'CUSTOM', 'source_uri_prefix': 'validation_notices/{dt:DATE}/{ts:TIMESTAMP}/{base64_url:STRING}/'}
[2022-11-01 15:20:08,694] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=create_external_tables, …
```
> fix gtfs validator version external table schema column name

- warehouse/models/staging/gtfs_guidelines/_stg_gtfs_guidelines.yml
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__technical_contact_listed.sql
I found two issues in `stg_gtfs_guidelines__technical_contact_listed.sql` that were impacting the downstream fact table:
- Because a dedupe wasn't performed, a fanout situation was created
- Because the check was defined prior to the join with `feed_guideline_index`, there existed unintentional nulll values in the status column
Note that this is one of the checks I built before I started including tests for each check.
I spot checked several passing and failing values, and queried to make sure there are no longer null values being created.
I added a dbt test for this table, confirmed that it failed prior to the fix, and passed after the fix.
I wrote a query to compare the features statuses between the staging table on my schema and the main staging table, and found that the they were …
> update tech contact check to get rid of nulls and dedupe

- warehouse/scripts/run_and_upload.py
Want to sync v2 GTFS data to Metabase systematically (rather than just add manually via Metabase admin UI).
Not sure if/how to test, @atvaccaro open to suggestions
> add v2 mart_gtfs to metabase sync

- warehouse/packages.yml
Quick update for bug in union_relations macro in dbt_utils. See [Slack](https://cal-itp.slack.com/archives/C0332307HKM/p1667995528016589) and [GitHub issue](https://github.com/dbt-labs/dbt-utils/issues/505) for more details.
Locally, project compiles with relations not existing yet.
> update dbt utils to fix bug from 0.8.1

- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs/fct_daily_scheduled_trips.sql
Meant to include this in #1974 but forgot. Just adding the foreign key to the assembled shape geometry to the fact daily trip entry. 
`poetry run dbt run -s fct_daily_scheduled_trips` and `poetry run dbt test -s fct_daily_scheduled_trips`
> add shape array foreign key to scheduled trips

- warehouse/models/docs/_docs_gtfs_outcomes.md
- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/intermediate/gtfs/int_gtfs_schedule__keyed_parse_outcomes.sql
- warehouse/models/staging/gtfs/_stg_gtfs.yml
@owades asked how to join `stg_gtfs_schedule__file_parse_outcomes` to implement my proposal in #1968 and I realized that there isn't really a great way to do this. This PR creates a new intermediate table with individual parse outcomes joined with feed_key. PR also adds documentation for the existing table because it wasn't documented.
Questions for @atvaccaro:
- `dim_schedule_feeds` depends on parse outcomes via `joined_feed_outcomes` already, so this is creating a weird dependency graph.... How worried are we about that? I think at some point we will want to push a feed versioning table into the intermediate and have stuff inherit from that, because if we want to add any actual attributes to `dim_schedule_feeds` (like calendar date ranges etc.) that would require a circular dependency …
> make keyed parse outcomes intermediate table

- docs/airflow/production-maintenance.md
Removed doc information for `payments_views_staging` and `payments_views` DAGs from Airflow production maintenance docs now that the DAGs have been deleted
File changed:
* docs/airflow/production-maintenance.md
> Update airflow production maintenance doc

- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/scripts/run_and_upload.py
Sync the `mart_gtfs_quality` dataset to Metabase and set a few data types to facilitate use in Metabase. 
@owades: This would let you start working on a v2 dashboard if you want?
Don't think there's a great way to test this locally; changes should be low-risk.
> sync gtfs quality to metabase

- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs/dim_schedule_feeds.sql
This PR addresses #1985 by changing the way that `dim_schedule_feeds` (v2 warehouse) handles download and unzip failures. Previously, we used `where download_success and unzip_success is not null` as a way to skip the most recent rows where data has been downloaded but not unzipped yet, but this led to the issue described in #1985.
This PR changes the logic to the following: 
```
When data fails to download, we do not interpolate it unless an identical zipfile is subsequently
downloaded. So for example, say we download zipfile A from URL X on January 1, then the download
or unzip operation fails for any reason on January 2, and then we download zipfile A from URL X
again on January 3. If you check this table on January 3 before the new data has appeared in the
warehouse, it will show …
```
> Dim schedule feeds better handle unzip

- warehouse/poetry.lock
- warehouse/pyproject.toml
- warehouse/requirements.txt
Quick follow-up to https://github.com/cal-itp/data-infra/pull/1971, I thought backoff was already in the warehouse project but it was not.
Verified that the `publish_california_open_data` task starts successfully.
```
[2022-11-21 19:12:01,735] {pod_launcher.py:149} INFO - reading manifest from gs://test-calitp-dbt-artifacts/latest/manifest.json
[2022-11-21 19:12:02,165] {pod_launcher.py:149} INFO - writing 17 rows to gs://test-calitp-publish/california_open_data__metadata/dt=2022-11-21/ts=2022-11-21T19:12:02.200905Z/metadata.csv
[2022-11-21 19:12:02,547] {pod_launcher.py:149} INFO - writing 172 rows to gs://test-calitp-publish/california_open_data__dictionary/dt=2022-11-21/ts=2022-11-21T19:12:02.200905Z/dictionary.csv
[2022-11-21 19:12:02,885] {pod_launcher.py:149} INFO - handling agency …
```
> add missing backoff for publishing

- warehouse/dbt_project.yml
- warehouse/macros/gtfs_rt_stg_outcomes.sql
- warehouse/macros/gtfs_rt_stg_validation_notices.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__no_rt_critical_validation_errors.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_feed_guideline_index.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_validation_notices.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_validation_outcomes.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_validation_severities.sql
- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs/fct_daily_rt_feed_files.sql
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql
- warehouse/models/mart/gtfs_quality/fct_daily_schedule_feed_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_daily_schedule_feed_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_implemented_checks.sql
- warehouse/models/rt_views/_rt_views.yml
- warehouse/models/rt_views/gtfs_rt_validation_code_descriptions_legacy.sql
- warehouse/models/staging/gtfs/gtfs_quality/_stg_gtfs_quality.yml
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__rt_validation_code_descriptions.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__no_rt_critical_validation_errors.sql
- warehouse/scripts/run_and_upload.py
- warehouse/seeds/_seeds.yml
- warehouse/seeds/gtfs_rt_validation_code_descriptions.csv
- warehouse/seeds/gtfs_schedule_validation_code_descriptions.csv
Follow-up to https://github.com/cal-itp/data-infra/pull/1945, progress towards https://github.com/cal-itp/data-infra/issues/1904. Creates the infrastructure necessary to develop feed-level checks for RT up through `fct_daily_rt_feed_guideline_checks` with one example check implemented.
Still working on it locally, tests pass but unsure if the models are good yet.
```
➜  warehouse git:(v2-rt-validations-framework) poetry run dbt build -s +fct_daily_rt_feed_guideline_checks+
20:12:18  Running with dbt=1.2.1
...
20:15:05  Finished running 19 view models, 103 tests, 1 seed, 6 table models, 3 incremental models in 0 hours 2 minutes and 38.91 seconds (158.91s).
20:15:05
20:15:05  Completed with 3 warnings:
20:15:05
20:15:05  Warning in test …
```
> Create RT validations index and daily facts, and implement a single check on top of notices

- runbooks/rotating-littlepay-aws-keys.md
This adds instructions for rotating the keys for the AWS accounts that are used to sync data from LittlePay's S3 buckets into Cal-ITP's GCS buckets. This is a task that's done regularly but infrequently, enough that it's difficult to remember the details from the last time it was done.
These are the steps that were taken during the key rotation earlier today.
> Add a new runbook documenting AWS key rotation process

- jobs/gtfs-rt-parser-v2/poetry.lock
- jobs/gtfs-rt-parser-v2/pyproject.toml
- jobs/gtfs-rt-parser/poetry.lock
- jobs/gtfs-rt-parser/pyproject.toml
poetry updated us to protobuf version 4+ which breaks the realtime bindings; this PR pins protobuf where necessary. v2 is actually running fine right now, as it happens to lock a good version of protobuf.
There's an open PR in the realtime bindings repo to fix this by pinning the deps required by the realtime bindings library https://github.com/MobilityData/gtfs-realtime-bindings/pull/91
```
[2022-11-22 18:30:11,818] {pod_launcher.py:149} INFO - saving 6962 outcomes to gs://test-calitp-gtfs-rt-parsed/service_alerts_outcomes/dt=2022-11-15/hour=2022-11-15T18:00:00+00:00/service_alerts.jsonl
[2022-11-22 18:30:13,807] {pod_launcher.py:149} INFO - fin.
[2022-11-22 18:30:20,056] {pod_launcher.py:198} INFO - Event: parse-rt-service-alerts.881310a1c5fc498f84e45a7f0256e01f had an event of type …
```
> pin proper versions of protobuf

- docs/airflow/production-maintenance.md
Docs updates that should have been made in #1699, my bad. Removes references to now-deprecated Airtable Airflow DAGs.
> docs: remove references to deprecated airtable dags

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_gtfs_datasets.yml
- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_gtfs_service_data.yml
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/dim_gtfs_datasets.sql
- warehouse/models/mart/transit_database/dim_gtfs_service_data.sql
- warehouse/models/mart/transit_database/dim_ntd_agency_info.sql
- warehouse/models/staging/transit_database/_stg_transit_database.yml
- warehouse/models/staging/transit_database/stg_transit_database__gtfs_datasets.sql
- warehouse/models/staging/transit_database/stg_transit_database__gtfs_service_data.sql
This PR:
* Creates a `mart_transit_database.dim_ntd_agency_info` table, to address a request from @juliama0780 on Slack. 
* Ingests the new `gtfs_service_data.customer_facing` field and adds it to the relevant staging and mart tables
* Ingests the new `gtfs_datasets.regional_feed_type` field and adds it to the relevant staging and mart tables
Ran `create_external_tables` in local Airflow and then `dbt run` and `dbt test` for the affected tables. (Changed my Airtable source to point at the staging project locally to pick up the new columns.)
> Airtable schema updates

- kubernetes/apps/manifests/gtfs-rt-archiver-v3/archiver-app-vars.yaml
- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml
- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-ticker.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/liveness.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/ticker.py
- services/gtfs-rt-archiver-v3/pyproject.toml
Closes https://github.com/cal-itp/data-infra/issues/2013
Initial implementation of liveness checks on the v3 archiver ticker and consumer pods. Will deploy in prod once merged.
This is deployed to test; I've tested by turning off the ticker and confirming that the consumers are restarted.
> create liveness script, deploy in test

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__no_rt_critical_validation_errors.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__trip_id_alignment.sql
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.md
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Migrate trip-id-alignment check to v2
This checks that no trip_ids appear in RT that aren't in the associated schedule. Note that we also need to do a more in depth check that sees whether all trips in schedule appear in RT.
./dbt test
Looked at aggregate data to confirm that most feeds pass and a subset fails
> Add v2 check v2 trip alignment

- kubernetes/apps/manifests/gtfs-rt-archiver-v3/archiver-app-vars.yaml
- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/archiver-channel-vars.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/archiver-channel-vars.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/consumer.patch.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/docker-compose.yml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/pyproject.toml
1. Disables backoff and sets max_delay to 1, i.e. huey clients will always wait 1 second between task checks rather than scaling backoff
2. Switches from non-blocking workers to blocking; this means workers will block for up to 20 seconds (i.e. at minimum through the next tick) while reading from an empty queue; this should reduce the delay metric.
Also various clean-up such as making environment variable prefixes consistent and moving some hard-coded configs to env vars.
See https://github.com/cal-itp/data-infra/issues/1948#issuecomment-1334018195 for why I chose not to add a read-from-redis metric.
Deploying tweaks to test as I make them.
> RT performance tweaks

- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/cache.py
- jobs/gtfs-aggregator-checker/gtfs_aggregator_checker/transitfeeds.py
- jobs/gtfs-aggregator-checker/poetry.lock
- jobs/gtfs-aggregator-checker/pyproject.toml
use requests and backoff to work around incomplete reads, and catch a keyerror when a tag is missing href
Handles failure seen in https://cal-itp.slack.com/archives/C0332307HKM/p1669905414238899
local airflow
```
[2022-12-01 17:50:46,485] {pod_launcher.py:149} INFO - saving results to gs://gtfs-data-test/feed_aggregator_checks/dt=2022-09-21/checks.jsonl
[2022-12-01 17:50:46,606] {pod_launcher.py:149} INFO - Results saved to gs://gtfs-data-test/feed_aggregator_checks/dt=2022-09-21/checks.jsonl
Fetching individual feed URLs: 100%|██████████| 177/177 [00:37<00:00,  4.70it/s]
[2022-12-01 17:50:48,850] {pod_launcher.py:198} INFO - Event: check-aggregators.98ea5ed01d234792ae2b3b9c3eedca48 had an event of type Succeeded
[2022-12-01 17:50:48,851] {pod_launcher.py:311} INFO - Event with job id …
```
> feed aggregator checker fixes

- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/dim_organizations.sql
- warehouse/models/mart/transit_database/dim_provider_gtfs_data.sql
- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
Noticed that while `NTD ID` column in `organizations` in Airtable displays an NTD ID, what it pulls in is actually the NTD Agency Info record key (it displays as the NTD ID in Airtable because the NTD ID is the "record name" for the NTD Agency Info record, not because it is actually performing a lookup for the ID value.)
This PR:
* Unnests the NTD record in the `organizations` tables (staging and mart) and updates docs accordingly
* Looks up the actual NTD ID value in `dim_provider_gtfs_data`; this is of interest to analysts
Resolves -- bug noticed today
`dbt run` & `dbt test` for staging organizations and dim organizations (confirms no fanout from unnesting)
`dbt build` for dim_provider_gtfs_data
> fix ntd id reference in organizations and dim provider gtfs data

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_organizations.yml
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/dim_organizations.sql
- warehouse/models/mart/transit_database/dim_provider_gtfs_data.sql
- warehouse/models/mart/transit_database/dim_services.sql
- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
- warehouse/models/staging/transit_database/stg_transit_database__services.sql
Add new assessment status columns to `services`, `organizations`, and `dim_provider_gtfs_data` tables. 
Resolves #2034 
`dbt run` and `dbt test` for organizations and services; `dbt build` for `dim_provider_gtfs_data`. I temporarily pointed `_src_airtable` at the staging external tables for testing `organizations` with the new column.
> Add assessments column

- airflow/dags/unzip_and_validate_gtfs_schedule/unzip_gtfs_schedule.py
- airflow/plugins/operators/gtfs_csv_to_jsonl.py
- airflow/requirements.txt
- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
- jobs/gtfs-rt-parser-v2/poetry.lock
- jobs/gtfs-rt-parser-v2/pyproject.toml
- jobs/gtfs-schedule-validator/gtfs_schedule_validator.py
- jobs/gtfs-schedule-validator/poetry.lock
- jobs/gtfs-schedule-validator/pyproject.toml
Related calitp PR is https://github.com/cal-itp/calitp-py/pull/91
Closes https://github.com/cal-itp/data-infra/issues/1980
Rather than raising a single exception, calitp-py will return a tuple of files, blobs missing metadata, and blobs with invalid metadata. Callers can then compare these against a threshold to decide whether to proceed. Most of the time, only a small number of files should be missing metadata (e.g. from a 500 in GCS) and we can process the rest.
Once this is merged, we will need to clear the past failed jobs and ensure they pass.
RT:
```
[2022-12-01 20:23:39,196] {pod_launcher.py:149} INFO - no schedule data found for gs://test-calitp-gtfs-rt-raw-v2/service_alerts/dt=2022-12-01/hour=2022-12-01T16:00:00+00:00/ts=2022-12-01T16:00:20+00:00/base64_url=aHR0cHM6Ly9zYW50YXJvc2F …
```
> handle missing metadata more flexibly in RT parse/validate jobs

- warehouse/macros/gtfs_rt_stg_outcomes.sql
Bug introduced in #2044, final select pulls raw data instead of the renamed stuff. Caused dbt failures overnight, will need to rerun the affected table's lineage once this merges.
`dbt run / dbt test` there are failing downstream tests but I do not think they are caused by this, talking to @atvaccaro offline
> fix issue introduced in #2044; use correct cte in final select

- airflow/data/agencies.yml
Adds some GMV URLs for Vine Transit
> Add GMV URLs for Vine Transit

- warehouse/models/mart/gtfs/dim_calendar_dates.sql
- warehouse/models/staging/gtfs/_stg_gtfs.yml
There are some full duplicate rows in incoming `calendar_dates` files (i.e., `service_id`, `date`, and `exception_type` are identical). This PR:
* Does a `select distinct` in the mart to drop the full duplicates
* Downgrades duplicate test in staging to a warn because of these known duplicates
Resolves Sentry/dbt issues:
* `test.calitp_warehouse.dbt_utils_unique_combination_of_columns_stg_gtfs_schedule__calendar_dates_base64_url__ts__service_id__date.a81b0f78e6 - Got 77 results, configured to fail if != 0`
* `test.calitp_warehouse.dbt_utils_mutually_exclusive_ranges_dim_calendar_dates_required___valid_from__base64_url_service_id_date___valid_to.d9be22059c - Got 66 results, configured to fail if != 0`
* `test.calitp_warehouse.unique_dim_calendar_dates_key.4715b99016 - Got 66 results, …
> remove full duplicates in calendar dates

- warehouse/models/mart/gtfs/fct_daily_rt_feed_files.sql
- warehouse/models/mart/gtfs/fct_hourly_rt_feed_files.sql
- warehouse/models/mart/gtfs/fct_hourly_rt_feed_files_success.sql
This PR updates a few RT archiver monitoring tables to use our incremental lookback variable.
Doing this because of behavior noted in #2064, which is that we did not `--full-refresh` after #2044 merged. After this PR merges I will rerun the `fct_daily_rt_feed_files` table with a lookback period to `2022-11-07`, which is how far the table currently goes.
`dbt run` locally
> Lookback var rt feed files

- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_protobuf_error.sql
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
dbt run job failed today because there were still some references to `best_practices_alignment` macro that was removed in #2072.
`dbt run -s +models/mart/gtfs_quality`
> specify which best practices

- airflow/data/agencies.yml
This PR adds 2 GMV URLs that we did not know about and moves the existing URLs that were associated with the RT GMV URLs to a new URL number.
> Update according to latest info on GMV URLs

- warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__daily_assessed_entities.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__daily_assessment_candidate_entities.sql
- warehouse/models/intermediate/gtfs/int_gtfs_rt__daily_url_index.sql
- warehouse/models/intermediate/transit_database/_int_transit_database.yml
- warehouse/models/intermediate/transit_database/int_transit_database__gtfs_datasets_history.sql
- warehouse/models/intermediate/transit_database/int_transit_database__gtfs_service_data_history.sql
- warehouse/models/intermediate/transit_database/int_transit_database__organizations_history.sql
- warehouse/models/intermediate/transit_database/int_transit_database__service_datasets_pivoted.sql
- warehouse/models/intermediate/transit_database/int_transit_database__service_history.sql
- warehouse/models/intermediate/transit_database/int_transit_database__services_history.sql
- warehouse/models/intermediate/transit_database/int_transit_database__urls_to_gtfs_datasets.sql
- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_organization_combined_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_service_combined_guideline_checks.sql
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/bridge_organizations_x_gtfs_datasets_produced.sql
- warehouse/models/mart/transit_database/dim_gtfs_datasets.sql
- warehouse/models/staging/transit_database/_stg_transit_database.yml
- warehouse/models/staging/transit_database/stg_transit_database__gtfs_datasets.sql
- warehouse/models/staging/transit_database/stg_transit_database__gtfs_service_data.sql
- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
**UPDATE: Per offline discussion with @atvaccaro, some of this needs to be refactored in favor of proper historical dimensions for Airtable. I have reopened #1868 and will do that refactor there. However, per @natam1 and @juliama0780 in Slack they would like to be able to start experimenting with the new tables, understanding that they are in draft form. So I'd like to merge this as-is and do a follow-on.**
This PR creates core functionality needed for the GTFS guideline checks work:
* A `fct_daily_guideline_checks` table that creates every possible assessed entity (organization / service / GTFS service data / GTFS dataset / URL / downloaded schedule feed) for a given date and appends results of all checks performed on that entity. 
* `fct_daily_organization_combined_guideline_checks` and …
> Assessed organization & service indices

- warehouse/models/payments_views/payments_rides.sql
In #2042 we added three dbt custom tests in to `payments_rides` to monitor daily, weekly, and monthly transaction deltas - but the row access policy on the table prevented the tests from being run correctly.
To resolve this, we added the prod service account to the row access policy so that it can query the table and run the tests appropriately.
ran with prod service account
> Added prod service account to payments_rides row access policy

- warehouse/README.md
A few updates to initial tool setup instructions, including a new official source URL for poetry installs, some prompt changes in CLI menus, and general markdown linting. Also includes a little bit of rephrasing and reorganization of one or two of the steps.
Visually previewed the updated README locally and checked against the linting standards used by the VS Code markdownlint extension. Ran through the updated instructions on a fresh install of the associated tools.
> Warehouse setup instructions update

- airflow/requirements.txt
This is already deployed; downgrading us back to gcsfs/fsspec 2022.5.0 but the composer requirements install isn't picking up the fsspec version without it being at the top-level `requirements.txt`.
already deployed
> specify fsspec at the top level

- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/intermediate/gtfs/int_gtfs_rt__daily_url_index.sql
- warehouse/models/mart/gtfs/fct_hourly_rt_feed_files.sql
- warehouse/models/mart/gtfs/fct_hourly_rt_feed_files_success.sql
- warehouse/models/staging/transit_database/_stg_transit_database.yml
In the new RT archiver dashboard tables we were pulling in feeds that are marked as "false" for the data quality pipeline, resulting in empty rows upon join. To resolve this, we added the `data_quality_pipeline` column to `int_gtfs_rt__daily_url_index`, and then filtered the two `fct_hourly_rt_feed_files*` tables where that column is TRUE, also updated yml files
Files changed:
* `int_gtfs_rt__daily_url_index.sql`
* Added the column `use_in_data_quality_pipeline` from `stg_transit_database__gtfs_datasets`
* `fct_hourly_rt_feed_files.sql`
* Filtered for the new column `use_in_data_quality_pipeline` on import of `int_gtfs_rt__daily_url_index.sql` where it is `TRUE`
* `fct_hourly_rt_feed_files_success.sql`
* Filtered for the new column `use_in_data_quality_pipeline` on import of …
> Added data_quality_pipeline column to int_gtfs_rt__daily_url_index

- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs/fct_stop_time_updates.sql
- warehouse/models/mart/gtfs/fct_trip_updates_messages.sql
- warehouse/models/staging/gtfs/_stg_gtfs.yml
- warehouse/models/staging/gtfs/gtfs_quality/_stg_gtfs_quality.yml
- warehouse/models/staging/gtfs/stg_gtfs_rt__trip_updates.sql
Expose trip updates in two mart models: `fct_trip_updates_messages` and `fct_stop_time_updates`
These are view-materialized and require partition filtering, but perform column renaming (🐫 to 🐍 ), record flattening, and array unnesting.
Tests do fail currently due to what I think is bad input data; I've chosen not to filter it out quite yet; changing the test may be better.
> create trip update mart table(s)

- warehouse/dbt_project.yml
- warehouse/models/mart/ad_hoc/_mart_ad_hoc.yml
- warehouse/models/mart/ad_hoc/fct_daily_vehicle_location_feed_trip_counts.sql
Ad hoc table of distinct trip IDs by vehicle locations feed for storm dashboard analysis 
Locally
> create ad hoc vehicle locations table

- warehouse/macros/url_safe_base64.sql
Fixes a bug in base64 encoding macro that caused some joins to fail between Airtable and GTFS data
> fix to_url_safe_base64

- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- warehouse/scripts/run_and_upload.py
Pre-cursor to https://github.com/cal-itp/data-infra/pull/2112 which cannot be merged until the downstream exposures are either disabled or replaced/migrated.
This is a cost-saving measure since there is no new data upstream and we aren't changing these models.
> exclude legacy models from dbt jobs

- warehouse/dbt_project.yml
- warehouse/models/mart/audit/_mart_audit.yml
Due to a copy/paste oversight in YAML, the new column created for `fct_bigquery_data_access_referenced_tables` was given the same name as its unnested array form from the original `fct_bigquery_data_access` table. This has now been fixed. Additionally, `dbt_project.yml` has been modified to move these tables into their proper mart location from staging.
Ran dbt tests locally for the modified model
> Fix unnested referenced_table column name and add audit tables to mart

- warehouse/models/mart/audit/_mart_audit.yml
- warehouse/models/mart/audit/fct_bigquery_data_access_referenced_tables.sql
The version of `fct_bigquery_data_access` with an unnested referenced_tables column, `fct_bigquery_data_access_referenced_tables`, failed tests because of the presence of unnested null arrays in the original table that were expanded into null column values via a left join. Since this unnested table is already not going to be relied upon for a canonical cost accounting (due to row duplication), and is instead oriented toward model-specific accounting, we can simply leave those null values behind in the original table when we unnest.
All dbt tests have been run locally for `fct_bigquery_data_access` and `fct_bigquery_data_access_referenced_tables`, and the tables have been recreated in a staging environment using the updated code and manually inspected for the test condition that broke …
> Remove nulls from referenced tables unnested audit table

- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__feed_guideline_index.sql
- warehouse/models/staging/gtfs_guidelines/stg_gtfs_guidelines__no_rt_critical_validation_errors.sql
dbt job failed today: 
`Compilation Error in model stg_gtfs_guidelines__feed_guideline_index (models/staging/gtfs_guidelines/stg_gtfs_guidelines__feed_guideline_index.sql) - 'no_rt_critical_validation_errors' is undefined. This can happen when calling a macro that does not exist.`
The `no_rt_critical_validation_errors` macro was renamed in #2153 but the references to the macro in the v1 models were not updated.  
hasn't, running affected tables locally seems wasteful because they have a ton of upstream dependencies that I don't have in my namespace
> fix macro ref

- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__no_stale_trip_updates.sql
Noticed this while looking at per-dbt model costs
```
15:25:23  1 of 1 START sql incremental model andrew_staging.int_gtfs_quality__no_stale_trip_updates  [RUN]
15:27:49  1 of 1 OK created sql incremental model andrew_staging.int_gtfs_quality__no_stale_trip_updates  [CREATE TABLE (693.0 rows, 934.6 GB processed) in 146.09s]
15:27:49
15:27:49  Finished running 1 incremental model in 0 hours 2 minutes and 28.34 seconds (148.34s).
15:27:49
15:27:49  Completed successfully
15:27:49
15:27:49  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```
> use trip updates lookback for a trip updates check

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
forgot to remove the hive partitions from the generated yaml
```
Deleting external table if exists: cal-itp-data-infra-staging.external_airtable.california_transit__services
Creating external table: cal-itp-data-infra-staging.external_airtable.california_transit__services Table(TableReference(DatasetReference('cal-itp-data-infra-staging', 'external_airtable'), 'california_transit__services')) ['gs://test-calitp-airtable/california_transit__services/*.jsonl.gz'] {'mode': 'AUTO', 'source_uri_prefix': 'california_transit__services/'}
Successfully ran SELECT *
FROM `cal-itp-data-infra-staging`.external_airtable.california_transit__services
LIMIT 1;
[2023-01-13 17:20:03,361] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=create_external_tables, …
```
> Fix changed column

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
- warehouse/models/intermediate/transit_database/int_transit_database__services_history.sql
I'm not sure why we can't type this as JSON? @evansiroky renamed them so we can just reference the new ones!
Ran Airflow and tested that `int_transit_database__services_history` would build on top.
> Use newly renamed columns

- airflow/dags/create_external_tables/gtfs_schedule_v2/agency.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/areas.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/attributions.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/calendar.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/calendar_dates.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/fare_attributes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/fare_leg_rules.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/fare_products.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/fare_rules.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/fare_transfer_rules.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/feed_info.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/frequencies.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/levels.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/pathways.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/routes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/shapes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/stop_areas.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/stop_times.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/stops.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/transfers.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/translations.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/trips.yml
- airflow/plugins/operators/gtfs_csv_to_jsonl.py
The schedule backfill has caused many dbt tests to start failing, for example [fare rules having duplicate rows](https://sentry.calitp.org/organizations/sentry/issues/4509/?environment=cal-itp-data-infra&project=2&query=is%3Aunresolved+dbt&statsPeriod=14d). We don't really want to filter these out immediately, but we do want to ensure that we're ending up with 1 record per row in the original extract file. Adding a line number to the CSV-to-JSONL conversion task will let us check for a unique combination of ts, url, and line number.
Local Airflow.
> add line number to schedule jsonl files

- warehouse/models/payments_views/_payments_views.yml
- warehouse/models/payments_views/payments_daily_transaction_deltas.sql
- warehouse/models/payments_views/payments_monthly_transaction_deltas.sql
- warehouse/models/payments_views/payments_weekly_transaction_deltas.sql
We've decided to move more of the `payments_rides` test calculations, alerts, and observability into Metabase. This PR accomplishes that by:
* Removing the 3 validations tests on `payments_rides`
* eg `validate_payments_rides__weekly_transaction_deltas`
* Replacing them with tables in `payments_views` 
* eg `payments_weekly_transaction_deltas`
* Removing the 25% relative difference thresholds for alerts that were hardcoded into the tests in favor of handling that in Metabase
* Adding documentation for new tables in `_payments_views.yml`
* Removing the great expectations freshness test on `payments_rides` in favor of adding this to Metabase as a custom SQL question/ alert
locally with `dbt run` and `dbt test`
> payments_rides tests revisions

- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_validations_outcomes.yml
Precursor to fixing https://github.com/cal-itp/data-infra/pull/2171
```
Deleting external table if exists: cal-itp-data-infra-staging.external_gtfs_schedule.validations_outcomes
Creating external table: cal-itp-data-infra-staging.external_gtfs_schedule.validations_outcomes Table(TableReference(DatasetReference('cal-itp-data-infra-staging', 'external_gtfs_schedule'), 'validations_outcomes')) ['gs://test-calitp-gtfs-schedule-validation/validation_job_results/*.jsonl'] {'mode': 'CUSTOM', 'source_uri_prefix': 'validation_job_results/{dt:DATE}/'}
[2023-01-17 21:00:04,024] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=create_external_tables, task_id=gtfs_schedule_validations_outcomes, execution_date=20221012T000000, start_date=20230117T205959, end_date=20230117T210004
```
> add validator version to schedule outcomes external table

- warehouse/models/payments_views/payments_daily_transaction_deltas.sql
- warehouse/models/payments_views/payments_monthly_transaction_deltas.sql
- warehouse/models/payments_views/payments_weekly_transaction_deltas.sql
We recently merged in #2164 which revised the way we handled tests on `payments_rides` (in favor of doing most of the work in Metabase). There were still a couple remaining filters in the warehouse tables that needed to be removed in favor of handling this at the Metabase-level.
Tables modified:
* payments_dailly_transaction_deltas
* Removed the recency filter from warehouse table, added recency column to filter in Metabase instead
* payments_weekly_transaction_deltas
* Removed the recency filter from warehouse table, added recency column to filter in Metabase instead
* payments_monthly_transaction_deltas
* Removed the recency filter from warehouse table, added recency column to filter in Metabase instead
Locally with `dbt run` and `dbt test`
> Removing `payments_rides` tests filters that should be in metabase

- warehouse/models/mart/gtfs_quality/fct_daily_schedule_feed_validation_notices.sql
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_schedule__validation_outcomes.sql
See [Slack](https://cal-itp.slack.com/archives/C02KH3DGZL7/p1673465655505239) and https://github.com/cal-itp/data-infra/pull/2171
Previously, the join logic in daily notices would pull the initial set of validations run for a given feed version, so something like the following could occur.
* feed version starts 2022-10-16 => v3.1.1 validations show up
* validator changes to v4.0.0 on 2022-11-16 => the join still pulls in validations from 2022-10-16
* new feed version starts 2022-01-04 => v4.0.0 validations show up
This PR changes the joins to include the first set of each version's validations per feed version. This also means we will now join in validation notices from anywhere in the feed's validity period rather than explicitly checking for the validations of the extract that started …
> properly join all versions of validations for a given feed version

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/macros/gtfs_rt_stg_outcomes.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.sql
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Checks for presence of modification date for each RT file.
Update macro to properly assign last-modified timestamp (i confirmed that they are being pulled through)
`./dbt.sh build -s int_gtfs_quality__modification_date_present_rt+`
> new check for rt modification date presence
