- warehouse/models/docs/gtfs schedule/transfers.md
- warehouse/models/mart/gtfs/_mart_gtfs.yml
- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
This PR makes some small changes to the columns available for open data publication (namely, ignoring feed_key), and makes sure that field descriptions are filled in for the remaining published fields.
Documentation regenerated locally and provided to CDOT prior to publication
> Patch Missing Docstrings for Open Data Publication

- warehouse/models/docs/gtfs schedule/agency.md
- warehouse/models/docs/gtfs schedule/attributions.md
- warehouse/models/docs/gtfs schedule/calendar.md
- warehouse/models/docs/gtfs schedule/calendar_dates.md
- warehouse/models/docs/gtfs schedule/feed_info.md
- warehouse/models/docs/gtfs schedule/frequencies.md
- warehouse/models/docs/gtfs schedule/routes.md
- warehouse/models/docs/gtfs schedule/stop_times.md
- warehouse/models/docs/gtfs schedule/stops.md
- warehouse/models/docs/gtfs schedule/translations.md
- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
Responsive to feedback from Chad at CDOT during the publishing process, this PR makes some changes to docstrings and exposed columns in the tables that end up published in some form on the state of California data table. This includes substitutions of apostrophes in utf-8 compliant format, plus some other small modifications.
Documentation dictionary for publishing regenerated via publish.py and validated against a utf-8 validator.
> Updates to apostrophe formatting and excluded columns for open data publishing

- warehouse/dbt_project.yml
Makes models under mart/gtfs_schedule_latest available in the mart_gtfs_schedule_latest dataset in BigQuery.
> Connect new open data publication tables to mart

- warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_feeds_present.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_url_guideline_index.sql
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_rt_url_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_daily_rt_url_guideline_checks.sql
New RT url index table to fix rt_feeds_present check. Related to #2192 
I ran `dbt build` on each of the new & updated tables.
Reviewed a failing feed and confirmed it was a bad URL (old GRaaS URL)
> switch rt feed presence check to new daily rt url index

- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__no_stale_trip_updates.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__rt_20sec_tu.sql
- warehouse/models/intermediate/gtfs/int_gtfs_rt__trip_updates_summaries.sql
Doing this in advance of two other checks as well, that will query trip updates. Since the `stop_times_updates` are a large portion of trip update messages, it's relatively performant to incrementally materialize the rest of the fields and use that model for any quality checks that need trip updates. Otherwise, each check would re-read the raw data for each check model, even if those individual check models are made incremental.
Local dbt run; main tests pass on the downstream models
> make trip update quality checks cheaper

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__contact_on_website.sql
- warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.sql
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Fixes bug introduced in https://github.com/cal-itp/data-infra/pull/2201
Built fct_daily_guideline_checks and (soon to be) checked that status is null where expected
```
select *
from `cal-itp-data-infra-staging`.andrew_mart_gtfs_quality.fct_daily_guideline_checks
WHERE organization_key = '87a88b5598e8666c1298092f2cc5df8e' AND date = '2023-01-23' AND check LIKE "%Shapes.txt%"
;
```
Passes on schedule, null on RT
> fix daily guideline checks join

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.sql
- warehouse/models/staging/gtfs/gtfs_quality/_stg_gtfs_quality.yml
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Adds a test to help flag potential bugs in `fct_daily_guideline_checks`; tests that checks can only come from one "source" and that the entities match up as we expect. For example, a check for schedule feeds ends up living on a schedule feed entity grained record, etc.
dbt runs and passes on the changed tables
> Test daily guideline checks

- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- warehouse/dbt_project.yml
- warehouse/models/gtfs_views/_gtfs_views.yml
- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
- warehouse/models/mart/gtfs_schedule_latest/dim_shapes_arrays_latest.sql
- warehouse/models/payments_views/_payments_views.yml
- warehouse/models/payments_views/payments_feeds.sql
- warehouse/models/payments_views/payments_rides.sql
- warehouse/scripts/dbt_artifacts.py
- warehouse/scripts/publish.py
Progress towards https://github.com/cal-itp/data-infra/issues/2109
TODO:
Tested map tiles work. payments_rides passes to the same extent as prod.
> Disable legacy dbt models and migrate tile publishing

- warehouse/macros/make_schedule_file_dimension_from_dim_schedule_feeds.sql
- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_observed_trips.sql
Resolves failing dbt model from last night; have to handle incremental schedule dimensions if the existing table is empty e.g. dim_translations.
Also adds FKs to fct_observed_trips for use in quality checks as requested by @lauriemerrell 
Both full refresh and incremental pass locally.
> handle incremental schedule dimensions if the existing table is empty

- warehouse/models/payments_views/_payments_views.yml
- warehouse/models/payments_views/payments_daily_transaction_deltas.sql
After merging the addition of the date spine in #2232 I needed to refactor the logic to properly sort for the calculations
Contributes to #2208 
local `dbt run`
> Revise logic in daily payments tests to reflect date spine

- kubernetes/apps/manifests/gtfs-rt-archiver-v3/redis.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/metrics.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/poetry.lock
- services/gtfs-rt-archiver-v3/pyproject.toml
Resolves https://github.com/cal-itp/data-infra/issues/2046
Adds redis metrics via a k8s sidecar, more archiver app metrics, and adds a timeout to feed requests. I'm also adjusting the buckets for our Histograms since we don't really care about anything under 100ms.
calitp PR: https://github.com/cal-itp/calitp-py/pull/97
Deployed to test.
[Redis dashboard](https://monitoring.k8s.calitp.jarv.us/d/Qnp8YdAVz/redis-dashboard-for-prometheus-redis-exporter-1-x?orgId=1)
[Updated archiver dashboard](https://monitoring.k8s.calitp.jarv.us/d/N1XVLOe7z/gtfs-rt-archiver-v3?orgId=1&var-namespace=gtfs-rt-v3-test&refresh=30s&from=now-15m&to=now)
> Add more RT metrics and add a download feed request timeout

- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
City of Madera and Cloverdale Transit had incorrect ITP IDs that caused them to be duplicates of Madera County and Long Beach Transit (respectively) which was going to cause issues in the report publishing flow. 
Ran `poetry run dbt run -s stg_transit_database__organizations+` and `poetry run dbt test -s stg_transit_database__organizations+`, only errors are because I am missing `fct_observed_trips` table locally which does not use ITP ID.
> manual correction for duplicate itp ids

- jobs/gtfs-schedule-validator/gtfs_schedule_validator.py
Fixes bug introduced during mypy work that I didn't catch.
Will need to backfill and re-run dbt models after merge.
Local Airflow.
```
[2023-02-03 14:59:36,010] {pod_launcher.py:149} INFO - saving 6 validation notices to gs://test-calitp-gtfs-schedule-validation/validation_notices/dt=2023-02-02/ts=2023-02-02T00:30:57.881473+00:00/base64_url=aHR0cHM6Ly9sYnRyYW5zaXQuYm94LmNvbS9zaGFyZWQvc3RhdGljL2FveWVza3dtc2E5ZzdweWc3OHEzeHVpb2kwbGdxZTRmLnppcA==/validation_notices_v4-0-0.jsonl.gz
[2023-02-03 14:59:37,265] {pod_launcher.py:149} INFO - saving 2 validation notices to gs://test-calitp-gtfs-schedule-validation/validation_notices/dt=2023-02-02/ts=2023-02-02T00:48:40.673559+00:00/base64_url=aHR0cDovL2V0YS5nZXRidXMub3JnL3J0dC9wdWJsaWMvdXRpbGl0eS9ndGZzLmFzcHg=/validation_notices_v4-0-0.jsonl.gz …
```
> Fix pendulum date/datetime comparison in schedule validator

- kubernetes/apps/charts/sentry/values.yaml
I re-installed Sentry to fix the GitHub OAuth 404 and ended up in the same situation as happened during our upgrade. Without this, the Sentry chart will manage the secret; uninstalling will delete the secret but the postgres storage stays there (which is good or we'd lose all our data). On install, Sentry will re-create the secret with a new generated password but has no way to actually set it on the postgres user.
This PR will actually point our Sentry chart at an existing Postgres secret so it doesn't delete and re-create it on re-install.
I've saved the secret in vaultwarden.
Upgraded with this changed values file and the db init job succeeded.
> point sentry at existing postgres secret

- airflow/dags/unzip_and_validate_gtfs_schedule/unzip_gtfs_schedule.py
Ignore MacOS-specific zip file contents for purposes of zipfile validity, but still process them as normal. I've confirmed that the failing feeds no longer throw exceptions in local Airflow. I also set up error reporting to Sentry so we can track and manage invalid zipfiles more easily.
We're going to backfill to 2022-01-25 to fix BART but no further. 
Resolves https://github.com/cal-itp/data-infra/issues/2104
Local airflow.
```
[2023-02-03 18:02:53,092] {storage.py:270} INFO - saving 4.4 MB to gs://test-calitp-gtfs-schedule-unzipped/unzipping_results/dt=2023-02-03/results.jsonl
got 2 exceptions from validating 474 extracts:
(BadZipFile('File is not a zip file'), HttpUrl('https://gtfs.sfmta.com/transitdata/google_transit.zip', scheme='https', host='gtfs.sfmta.com', tld='com', …
```
> Handle __MACOSX folders in zipfiles

- README.md
Updates the repository's README to reflect current practices for PR code owner and review tagging behavior, and fixes a markdown linting error on line 55 while I'm in this file.
The markdown has been validated and passes linting.
> Code owners PR guidance and small linting fix for repo README

- kubernetes/apps/values/grafana-prod.yaml
I think Grafana might be the last service we don't have a CNAME for; the current domain is https://monitoring.k8s.calitp.jarv.us. I've looked at Composer and unfortunately they don't seem to support custom domains still https://stackoverflow.com/questions/65354788/custom-domain-for-google-cloud-composer.
> prep for calitp grafana domain

- warehouse/scripts/publish.py
YAML can give us integers for CKAN precisions; I'm not sure why I thought they were quoted.
Actually ran a full test publish this time.
```
would be uploading to https://data.ca.gov 7abe9256-6cd2-4c1f-9b6a-72108022a382 if --publish
handling dim_trips_latest 0e4da89e-9330-43f8-8de9-305cb7d4918f
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 545805/545805 [00:39<00:00, 13838.71rows/s]
writing 545805 rows (99.9 MB) from andrew_staging.dim_trips_latest to gs://test-calitp-publish/california_open_data__trips/dt=2023-02-06/ts=2023-02-06T15:35:09.114058Z/trips.csv
would be uploading to https://data.ca.gov …
```
> fix incorrect assert

- warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml
This check should pass for all feeds - so we shouldn't be surprised when 100% pass every day. Disabling the "extreme results" test for this check.
Resolves: https://sentry.calitp.org/organizations/sentry/issues/39640/
> disable extreme-results test for check that is easy to pass

- airflow/dags/airtable_loader_v2/california_transit_modes.yml
- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_modes.yml
- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
- warehouse/models/intermediate/transit_database/dimensions/_int_transit_database_dimensions.yml
- warehouse/models/intermediate/transit_database/dimensions/int_transit_database__modes_dim.sql
- warehouse/models/intermediate/transit_database/dimensions/int_transit_database__services_dim.sql
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/bridge_services_x_modes.sql
- warehouse/models/mart/transit_database/dim_modes.sql
- warehouse/models/staging/transit_database/_src_airtable.yml
- warehouse/models/staging/transit_database/_stg_transit_database.yml
- warehouse/models/staging/transit_database/stg_transit_database__modes.sql
- warehouse/models/staging/transit_database/stg_transit_database__services.sql
Export new modes table created in Airtable and create associated dbt models.
Can run it locally in Airflow; dbt tables run. A few of the tests on the bridge table fail but it's hard for me to assess those because I'm running on the staging data because of the new external table; if they fail in prod we can address.
> Import new airtable modes

- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__all_tu_in_vp.sql
By joining on both the vp and tu keys, I was filtering out non-null values in each. This was fine for the tu feed, since the check only cares about trips that appear in the tu feed. I removed the join to the vp feed, and instead joined on the associated schedule feed - I believe this should yield the same result.
Confirmed that some checks both pass and fail.
Ran ` ./dbt.sh build -s int_gtfs_quality__all_tu_in_vp+ `
> resolve bug in check

- airflow/Dockerfile.composer
- airflow/requirements.txt
jupyter-core via gusty was installing platformdirs 3 but we need to keep it below 3. Also update typer and calitp-data-infra while at it, just for responsibility.
Adds pip3 check call in Dockerfile.
This is already deployed.
> add pin to fix version conflicts

- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
- warehouse/scripts/run_and_upload.py
Resolves https://github.com/cal-itp/data-infra/issues/2290
Adds missing Sentry env vars required for reporting dbt failures; they'd only been set in tests, not runs.
Also, I realized while testing locally that the exception types were not distinguished by resource type. This PR maintains the same fingerprints (since `unique_id` is prefixed with the resource type) but adds new exception types, so we can more easily search for issues.
See [this dev issue](https://sentry.calitp.org/organizations/sentry/issues/40540/events/?environment=development&project=2) as an example of an issue that was erroneously flagged as a test failure when it was really a run failure.
I've run the exception reporting directly.
> separate exception types for other types of dbt failures and add Sentry env vars

- warehouse/Dockerfile
- warehouse/Dockerfile.local
- warehouse/poetry.lock
- warehouse/pyproject.toml
- warehouse/scripts/run_and_upload.py
I forgot the warehouse image used requirements.txt; also we can use dbt-metabase directly now so we don't need to point at the Jarvus fork.
This also fixes a bug that can occur when changing incremental tables, where `run` succeeds but `compile` fails. We only need one or the other for docs, etc. to function, so just do one instead of both.
Built image, ran with local Airflow.
> Upgrade warehouse deps one more time

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__no_rt_validation_errors.sql
- warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_implemented_checks.sql
- warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Doing QA, I noticed that our RT validator check used the same check name across the 3 different RT feeds being validated. This PR fixes that. It also fixes the implemented_checks table, which somehow was missing most of the fct tables...
`./dbt.sh build -s int_gtfs_quality__no_rt_validation_errors+   `
> Expand rt validator check

- warehouse/scripts/run_and_upload.py
Follow-up from https://github.com/cal-itp/data-infra/pull/2310, I left out the exclude sources flag. Also, it doesn't run in staging anyways since there's no staging target schemas in Metabase (we could maybe sync them?)
> only run dbt-metabase in prod, and do not sync sources

- airflow/Dockerfile
- airflow/dags/parse_and_validate_rt_v2/parse_rt_service_alerts.yml
- airflow/dags/parse_and_validate_rt_v2/parse_rt_trip_updates.yml
- airflow/dags/parse_and_validate_rt_v2/parse_rt_vehicle_positions.yml
- airflow/dags/parse_and_validate_rt_v2/validate_rt_service_alerts.yml
- airflow/dags/parse_and_validate_rt_v2/validate_rt_trip_updates.yml
- airflow/dags/parse_and_validate_rt_v2/validate_rt_vehicle_positions.yml
- airflow/dags/publish_open_data/publish_california_open_data.yml
- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
- airflow/dags/unzip_and_validate_gtfs_schedule/validate_gtfs_schedule.yml
- airflow/requirements-dev.txt
There was a [breaking change](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html#id22) during the upgrade, so we have to use the new param name for providing PodOperators their resource requests.
Works locally after fix; had reproduce issue pre-fix.
> Post composer upgrade

- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__daily_assessment_candidate_entities.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__naive_organization_service_dataset_full_join.sql
Fixes two issues, identified by [this Sentry issue](https://sentry.calitp.org/organizations/sentry/issues/40764/) / issue #2320. 
We were getting duplicate keys in `int_gtfs_quality__daily_assessment_candidate_entities`. 
1. The cause was that in #2304 I added a flag for whether there are actually RT files on a given day, and apparently those models update before the rest so we were getting empty rows for the current date with only an RT URL filled in and nothing else. I added two `< CURRENT_DATE()` filters to stop this in the immediate precursor `naive join`.
2. In the course of investigating this, I realized that the logic I added in #2304 for checking `gtfs_service_data_assessed` was too generous and was marking rows with just a URL as `assessed`. Fixed that too.
Resolves #2320
`poetry …
> Fix failing assessment candidate key

- warehouse/models/mart/gtfs/fct_daily_scheduled_trips.sql
This PR substitutes `activity_date` for `service_date` when joining to create fct_daily_scheduled_trips, which was causing testing failures after merging #2275 
The following test failure occured:
`DbtTestFail: test.calitp_warehouse.dbt_utils_unique_combination_of_columns_fct_daily_feed_scheduled_service_summary_activity_date__feed_key.b5c3eba0c5 - Got 169 results, configured to fail if != 0`
We realized it was due to a join in `fct_daily_scheduled_trips` that was still using the concept of `service_date`
Resolves #2323 
locally with `dbt run` and `dbt test`
> Substitute activity_date for join on fct_daily_scheduled_trips

- airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py
- airflow/dags/download_gtfs_schedule_v2/email_download_failures.py
Airflow emails via Postmark are not working right now; I'm trying to debug but it's hard locally, so I want to be able to retry just this task. Also, we shouldn't be retrying the actual download task because the failure email failed to send. The v1 pipeline had separate tasks and we just didn't split them up in v2.
Locally.
> split failure emails into separate task again

- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py
- services/gtfs-rt-archiver-v3/pyproject.toml
Resolves https://github.com/cal-itp/data-infra/issues/1897
The exception string looks like this post-replacement: `"HTTPSConnectionPool(host='avl.yctd.org', port=443): Max retries exceeded with url: /RealTime/GTFS_TripUpdates.pb (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at ...>, 'Connection to avl.yctd.org timed out. (connect timeout=30)')) (https://avl.yctd.org/RealTime/GTFS_TripUpdates.pb)"`.
I don't want to just use the exception type by itself because the same exception could be caused by different underlying exceptions. Also, this avoids interacting with the underlying exception(s) except for the purpose of Sentry fingerprinting.
Running locally, will deploy to test.
> remove object memory locations from exception string representation

- warehouse/scripts/run_and_upload.py
> dbt-metabase does not check for hanging slash in url

- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_30_day_feed_expiration.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_7_day_feed_expiration.sql
We have two feed-expiration checks: one looks for feeds that expire within 7 days, and one looks for feeds that expire within 30 days. Both rely on gtfs-validator. I discovered that the two notices are mutually-exclusive from the validator ([source code](https://github.com/MobilityData/gtfs-validator/blob/30e6c69f7c7ca500855c9e698d804f7c7f4ddcbb/main/src/main/java/org/mobilitydata/gtfsvalidator/validator/FeedExpirationDateValidator.java#L64)), which caused our 30day check to pass when the 7day check was failing. This isn't  a validator bug, but it's a bug in the way we're using the validator output. This change causes our 30day expiration check to fail if the 30day OR 7day notice appears in the validator.
It ran successfully, and I confirmed that a feed that was failing the 7day check and …
> update 30day expiration check

- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__authentication_acceptable.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__data_license.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__demand_responsive_routes_match.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__fixed_routes_match.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__link_to_dataset_on_website.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_stale_trip_updates.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__shapes_accurate.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__stable_url.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__trip_planner_rt.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__trip_planner_schedule.sql
When I set up the manual checks last month, we didn't have any results in airtable. Now that we do, I've gone through and updated the logic to reflect the actual values for these checks. I did this by looking at distinct values for each manual check and confirming that each case was covered by the corresponding intermediate check table.
I confirmed that each intermediate table runs successfully.
> Bugfix: update manual check logic based on values entered in airtable

- warehouse/models/mart/gtfs/dim_schedule_feeds.sql
Fixing #2329 which is blocking #2249.
This changes the logic in `dim_schedule_feeds` for this situation, where a feed "goes dark" for a bit and then comes back with different data:
Date | Feed | Result | Zipfile version
--- | --- | --- | ---
1/1 | A | Success | abc
1/2 | A | Success | abc
1/3 | A | Fails | 
1/4 | A | Fails | 
1/5 | A | Fails | 
1/6 | A | Success | def
Previously you would get the following (we would interpolate right up to the beginning of the new version): 
Version | _valid_from | _valid_to
--- | --- | ---
abc | 1/1 | 1/5
def | 1/6 | *future*
Now we get this (don't interpolate past the first extract where it fails):
Version | _valid_from | _valid_to
--- | --- | ---
abc | 1/1 | 1/3
def | 1/6 | *future*
Resolves #2329 
Ran the following SQL and did spot checks, confirmed …
> Fix schedule feed versioning when URL deleted or data changed while offline

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/_int_gtfs_quality_guidelines_checks.yaml
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__feed_listed_sa.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__feed_listed_schedule.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__feed_listed_tu.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__feed_listed_vp.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__trip_planner_rt.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__trip_planner_schedule.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_long.md
- warehouse/models/mart/gtfs_quality/fct_daily_service_guideline_checks.md
- warehouse/models/mart/gtfs_quality/fct_daily_service_guideline_checks.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Create service-level check that says whether each feed is listed.
Resolves #2311 
ran dbt build on all four, and everything down stream.
Looked at aggregate results for 2 days ago:
33% of services pass the schedule check
17% of services pass the trip updates check
17% of services pass the service alerts check
17% of services pass the vehicle positions check
(the above 3 all round to 17&, but are not equactly equal)
> add basic service level check for whether a feed is present

- warehouse/macros/make_end_of_valid_range.sql
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_schedule_feed_validation_notices.sql
- warehouse/tests/mart/gtfs_quality/test_fct_daily_schedule_validation_notices_one_version_per_date_feed.sql
Waiting on https://github.com/cal-itp/data-infra/issues/2329 closure first
Finally stops showing validation notices in the future as well as past the next version's start. Adds a custom test to check there is only 1 validator version present per feed per day.
Closes https://github.com/cal-itp/data-infra/issues/2141
Tests pass after rebase!
> stop validation notices from showing past next version's implementation

- airflow/dags/load-sentry-rtfetchexception-events/load-sentry-rtfetchexception-events.yml
YAML for load-sentry-rtfetchexception-events used a `resources` key instead of the newer `k8s_resources` key. This brings the YAML in line with our current infra versions.
> Update k8s_resources reference in Sentry loader YAML

- airflow/dags/load-sentry-rtfetchexception-events/load-sentry-rtfetchexception-events.yml
Maps the `CALITP_BUCKET__SENTRY_EVENTS` environment variable onto the Sentry -> GCS DAG in Airflow
> Add destination bucket reference to DAG definition for Sentry loader

- jobs/sentry-error-loader/sentry_error_loader.py
From January 15th through January 18th, a configuration issue led to zero reported errors in Sentry. When encountering these intervals, our current Sentry (Clickhouse) sync into BigQuery fails because of issues referencing aspects of an empty Pandas DataFrame. This resolves the issue, should we encounter future days with no Sentry errors.
> Handle zero-error days from Sentry

- airflow/dags/transform_warehouse/METADATA.yml
- warehouse/scripts/run_and_upload.py
Follow-up ticket to do next sprint maybe: https://github.com/cal-itp/data-infra/issues/2362
Removes retry on regular transform job, and stops failing the job if dbt-metabase fails.
Tested locally
> do not retry transform_warehouse and do not fail if dbt-metabase fails

- jobs/sentry-error-loader/sentry_error_loader.py
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/staging/rt/_src_gtfs_rt_external_tables.yml
- warehouse/models/staging/rt/_stg_rt.yml
Two sets of changes contained within:
1. Updates the list cleaning behavior of the Sentry loader script to detect which columns contain list objects, rather than relying on a manual column list as discussed [here](https://github.com/cal-itp/data-infra/pull/2360). Note that we don't just check the datatype of the Pandas column, which interprets lists as an ambiguous `object` type - we check the first element of the column to determine whether it's a list type.
2. Updates the Sentry table docs to fully align with the current schema - there were some leftover outdated docs on the `fct_` table from when we were bringing data through Sentry's API rather than Clickhouse.
The script was tested via local runs into a real bucket, using several example days of Sentry data (including a day that had …
> Sentry Pipeline List Cleaning Automation and Docs Updates

- warehouse/models/docs/_docs_overview.md
Closes https://github.com/cal-itp/data-infra/issues/2328
I'm not sure why it's only erroring on the project-specific overview.
Works locally.
> use top-level overview doc instead of for project

- warehouse/models/intermediate/transit_database/_int_transit_database.yml
- warehouse/models/intermediate/transit_database/dimensions/int_transit_database__service_components_dim.sql
This addresses an issue reported in Slack by @edasmalchi about how certain service/product relationships were not appearing in `dim_service_components`. Also cleans up #2367.
Resolves #2367
Confirmed no new test failures in the updated table or downstream. Confirmed that the specific missing data cited by Eric is now present in my table: `cal-itp-data-infra-staging.laurie_mart_transit_database.dim_service_components`
> fix missing dim service component rows and fix erroring test

- airflow/dags/deploy_dbt_docs/deploy_dbt_docs_site.yml
- airflow/dags/deploy_dbt_docs/sync_dbt_docs_to_metabase.yml
- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
- airflow/plugins/operators/pod_operator.py
We've been seeing more pod start timeouts recently. I set our job nodes pool to minimum 1 per zone, but pods are failing to start and force our current nodes up to that minimum. We already use 300 seconds on dbt pods so let's just do that everywhere.
Locally, ran a pod successfully.
> default all our pod operators to wait 300 seconds to start

- airflow/dags/payments_loader/preprocess_ccjpa.py
- airflow/plugins/libs/littlepay.py
- warehouse/models/payments_views/indexes/payments_feeds.sql
- warehouse/models/payments_views/payments_rides.sql
Step towards https://github.com/cal-itp/data-infra/issues/2385
Adds a CCJPA v1 payments processing task; shouldn't need changes downstream (i.e. external tables/dbt) other than the row-level policy.
I've pre-emptively created a new [Metabase connection](https://dashboards.calitp.org/admin/databases/19) for when this runs in prod.
Running Airflow and dbt locally now.
> add ccjpa to v1 pipeline, and adjust logging

- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__scheduled_trips_in_tu_feed.sql
Fixes #2373:
* The specific issue described in the ticket was actually caused by trips on the same `dt` with different `trip_start_date`, see https://github.com/cal-itp/data-infra/issues/2347#issuecomment-1464500392. I think we might need more refinement on this as #2347 is addressed, but I think the switch to `COUNT(DISTINCT trip_id))` for observed trips should work. 
* I also think that some issues here were being caused by grouping by both schedule and trip updates dataset key as opposed to just schedule in the `compare_trips` CTE, so I simplified that.
* I also did more spot checks and some of the behavior changes here are caused by the fact that the original version filtered to only `guidelines_assessed` quartets, whereas this preserves basically as much as possible. So in the …
> Fix scheduled in TU check bug #2373

- kubernetes/apps/charts/jupyterhub/values.yaml
I think 3 people were all using conda at once; we really should be requesting ~1 CPU per person but our nodes do have have a full 2 CPU allocatable; 0.7 will stop 3 user pods from being scheduled on 1 node.
Already deployed.
> increase jupyterhub singleuser resource request

- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__daily_assessment_candidate_entities.sql
Issue #2320 [reappeared](https://sentry.calitp.org/organizations/sentry/issues/40764/) and brought a friend [`test.calitp_warehouse.dbt_utils_unique_combination_of_columns_int_gtfs_quality__guideline_checks_index_key__date__check.efe3dcfe09 - Got 222 results, configured to fail if != 0`](https://sentry.calitp.org/organizations/sentry/issues/69731/). This fixes it by adding `base64_url` to the key which I thought I had done in #2321 but I guess I missed it.
Both tables' tests now pass with this change. Also confirmed no downstream incremental tables.
> add base64_url to candidate entities key to resolve duplicate key issue

- warehouse/models/intermediate/gtfs_quality/guidelines_checks/_int_gtfs_quality_guidelines_checks.yaml
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_rt_validation_errors.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_stale_vehicle_positions.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__rt_20sec_vp.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__rt_feeds_present.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__rt_https.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__rt_protobuf_error.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_long_new_index.sql
- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_vehicle_positions_messages.sql
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_vehicle_positions_message_age_summary.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_quality__intended_checks.sql
See [Google Doc](https://docs.google.com/spreadsheets/d/15eYntYFoYyHuXYyp4dmqM3g5N18tw2r8dU2S7wDDM4E/edit#gid=1437513597) for list of models migrated here, those with #2379 in the PR column. Once again merging into staging branch, which will merge in #2371.
Notes:
* For RT feed checks on dates before RT files history are available, we might end up with `N/A - NO APPLICABLE ENTITY` instead of `BEFORE CHECK ASSESSED` because they will show has not having RT files (and therefore having no assessed entity). Not sure if this is a problem. 🤔 
* For the vehicle positions & trip updates freshness checks (updates every 20 sec/no updates older than 90 sec), we are creating new incremental fact models so that the check models themselves are not incremental. This should give more flexibility in …
> Batch 3: Migrate guideline check indices

- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
We currently have a gap in RT validation caused by missing schedule extracts during times of day before the current day's schedule extracts have been processed. This PR allows RT validation to look back on the previously extracted version of the schedule, with a delay of up to seven days, before failing.
Resolves #2306
Various pieces of the changed code have been tested locally, but at the time of PR creation the whole GTFS RT Parser job has not yet been run in local Airflow.
> Allow RT Validation to Use Most Recent Available Schedule Feeds (Up to 7 Days)

- airflow/dags/create_external_tables/payments/littlepay/authorisations.yml
- airflow/dags/create_external_tables/payments/littlepay/customer_funding_source.yml
- airflow/dags/create_external_tables/payments/littlepay/device_transaction_purchases.yml
- airflow/dags/create_external_tables/payments/littlepay/device_transactions.yml
- airflow/dags/create_external_tables/payments/littlepay/micropayment_adjustments.yml
- airflow/dags/create_external_tables/payments/littlepay/micropayment_device_transactions.yml
- airflow/dags/create_external_tables/payments/littlepay/micropayments.yml
- airflow/dags/create_external_tables/payments/littlepay/product_data.yml
- airflow/dags/create_external_tables/payments/littlepay/refunds.yml
- airflow/dags/create_external_tables/payments/littlepay/settlements.yml
- airflow/dags/parse_littlepay/METADATA.yml
- airflow/dags/parse_littlepay/cal-itp.yml
- airflow/dags/parse_littlepay/ccjpa.yml
- airflow/dags/parse_littlepay/mst.yml
- airflow/dags/parse_littlepay/sbmtd.yml
- airflow/dags/sync_littlepay/METADATA.yml
- airflow/dags/sync_littlepay/cal-itp.yml
- airflow/dags/sync_littlepay/ccjpa.yml
- airflow/dags/sync_littlepay/mst.yml
- airflow/dags/sync_littlepay/sbmtd.yml
- airflow/docker-compose.yaml
- airflow/plugins/operators/__init__.py
- airflow/plugins/operators/littlepay_raw_sync.py
- airflow/plugins/operators/littlepay_to_jsonl.py
- airflow/requirements-dev.txt
- airflow/requirements.txt
I'm using one bucket each for raw and parsed data, partitioned by instance. Files are also versioned by extract time, and a new version is only created if the etag or last-modified timestamp changes (avoids having to read the whole file and compare hashes, but assumes one of those two fields will change). All external tables use string types, and the staging models will safe_cast to the appropriate type.
Follow-up PR is https://github.com/cal-itp/data-infra/pull/2398
> Littlepay payments v2 sync and parse

- warehouse/models/mart/gtfs_quality/idx_monthly_reports_site.sql
#2338 added dataset URL information to `idx_monthly_reports_site` for the reports site as array structs, which was causing problems when generating the index with `generate_index_report.py`.
To address this, this PR changes the structs in `idx_monthly_reports_site` to JSON strings, which will then be turned into JSON in generate_index_report.py`.
In a notebook
> Convert array/struct to JSON strings in reports index

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/intermediate/gtfs/int_gtfs_rt__trip_updates_no_stop_times.sql
- warehouse/models/intermediate/gtfs/int_gtfs_rt__unioned_parse_outcomes.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/_int_gtfs_quality_guidelines_checks.yaml
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__authentication_acceptable.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__contact_on_website.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__data_license.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__demand_responsive_routes_match.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__fixed_routes_match.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__modification_date_present_rt.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_stale_service_alerts.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_stale_trip_updates.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__rt_20sec_tu.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_index.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_long_new_index.sql
- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_service_alerts_messages.sql
- warehouse/models/mart/gtfs/fct_trip_updates_messages.sql
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_service_alerts_message_age_summary.sql
- warehouse/models/mart/gtfs_quality/fct_daily_trip_updates_message_age_summary.sql
- warehouse/models/mart/gtfs_quality/fct_daily_vehicle_positions_message_age_summary.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Merging into staging branch, will merge to main in #2371 with the rest. 
Continue migrating guideline checks to shared index, see [Google Sheet](https://docs.google.com/spreadsheets/d/15eYntYFoYyHuXYyp4dmqM3g5N18tw2r8dU2S7wDDM4E/edit) for progress.
As in #2379, creates some new fact tables summarizing RT message ages. 
Biggest new functional change here is formally restricting the fixed route and demand responsive checks to only apply to *schedule* GTFS service data records. 
Also restricts columns in the final table (adds columns to include). 
Some follow up will be required in #2401 
Progress towards #2263 
Checked each check individually as it was migrated to ensure reasonable parity with old version. 
Also ran:
```
SELECT check, COUNT(*)
FROM …
```
> Batch 4: Guideline check reindexing

- warehouse/poetry.lock
- warehouse/pyproject.toml
- warehouse/scripts/dbt_artifacts.py
- warehouse/scripts/visualize.py
Removing unuseful dependency on networkx_viewer and improve color palette for run_results.
locally
> remove networkx_viewer, add palettable and use it

- warehouse/dbt_project.yml
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/_int_gtfs_quality_guidelines_checks.yaml
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__lead_time.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__link_to_dataset_on_website.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_30_day_feed_expiration.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_7_day_feed_expiration.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_expired_services.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__passes_fares_validator.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__persistent_ids_schedule.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__scheduled_trips_in_tu_feed.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__shapes_accurate.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__stable_url.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_long_new_index.sql
- warehouse/models/mart/gtfs_quality/fct_daily_service_alerts_message_age_summary.sql
- warehouse/models/mart/gtfs_quality/fct_daily_trip_updates_message_age_summary.sql
- warehouse/models/mart/gtfs_quality/fct_daily_vehicle_positions_message_age_summary.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Yet more guideline migrations, to be merged into main via #2371. Progress documented in the [Google Sheet](https://docs.google.com/spreadsheets/d/15eYntYFoYyHuXYyp4dmqM3g5N18tw2r8dU2S7wDDM4E/edit#gid=1437513597); models with #2417 in the PR column are migrated here.
Ran into the following, so am now materializing all these as tables. Per conversation with @atvaccaro none are too bad on performance except `lead_time`, which I plan to make incremental before final merge as part of final performance and testing tweaks. 
```
Database Error in model int_gtfs_quality__guideline_checks_long_new_index (models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_long_new_index.sql)
Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or …
```
> Batch 5: migrating GTFS guideline checks

- airflow/data/agencies.yml
their vendor, Transnovation, says this is the new URL (as per Ali Attari).
As a reminder, GRaaS still uses agencies.yml as a source of truth, which is why I'm updating it here. 
I believe @evansiroky is making the corresponding update in Airtable, and will look for his confirmation.
> update syvt url, per vendor's instructions

- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__modification_date_present_rt.sql
- warehouse/models/mart/gtfs_quality/fct_daily_organization_combined_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_service_combined_guideline_checks.sql
Resolves #2442 - turns out ticket was wrong, the RT entities *do* check for historical feeds but I had the wrong entity type for the one check, it was supposed to be URL rather than feed.
run & test locally confirmed tests now pass
> Fix failing guideline checks tests

- warehouse/models/mart/gtfs_quality/fct_daily_organization_combined_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_service_combined_guideline_checks.sql
@owades comment made me realize that in the refactor I had accidentally removed the filters that kept only guidelines-assessed feeds in the `_combined` mart tables.
dbt run & test locally, both tables pass. Inspected the following query to confirm that in prod you see all the non-assessed feeds but that post-fix you only see the regional feeds:
```
SELECT organization_name, check, status, service_names_included_array, gtfs_dataset_names_included_array
FROM `cal-itp-data-infra.mart_gtfs_quality.fct_daily_organization_combined_guideline_checks`
WHERE organization_name = 'Alameda-Contra Costa Transit District' AND date = '2023-03-29'
ORDER BY date DESC, check
```
> filter back to only assessed entities

- warehouse/README.md
- warehouse/dbt_project.yml
- warehouse/macros/gtfs_rt_dt_where.sql
- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/intermediate/gtfs/int_gtfs_rt__distinct_download_configs.sql
- warehouse/models/intermediate/gtfs/int_gtfs_rt__unioned_parse_outcomes.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__rt_validation_notices.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__rt_validation_outcomes.sql
- warehouse/models/mart/ad_hoc/fct_daily_trip_update_status_counts.sql
- warehouse/models/mart/ad_hoc/fct_daily_vehicle_location_feed_trip_counts.sql
- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_daily_rt_feed_files.sql
- warehouse/models/mart/gtfs/fct_daily_service_alerts.sql
- warehouse/models/mart/gtfs/fct_hourly_rt_feed_files.sql
- warehouse/models/mart/gtfs/fct_hourly_rt_feed_files_success.sql
- warehouse/models/mart/gtfs/fct_observed_trips.sql
- warehouse/models/mart/gtfs/fct_service_alerts_trip_summaries.sql
- warehouse/models/mart/gtfs/fct_trip_updates_no_stop_times.sql
- warehouse/models/mart/gtfs/fct_trip_updates_summaries.sql
- warehouse/models/mart/gtfs/fct_vehicle_positions_trip_summaries.sql
- warehouse/models/mart/gtfs_quality/fct_daily_service_alerts_message_age_summary.sql
- warehouse/models/mart/gtfs_quality/fct_daily_trip_updates_message_age_summary.sql
- warehouse/models/mart/gtfs_quality/fct_daily_vehicle_positions_message_age_summary.sql
- warehouse/models/mart/gtfs_quality/fct_rt_feed_fetch_errors.sql
Resolves https://github.com/cal-itp/data-infra/issues/2401 once backfill runs
Moves 4 of our incremental tables to be mart-level facts, to encourage usage. Will also be backfilling new columns required for guideline checks models downstream.
I will be performing the following manual steps:
Testing locally.
Dev full refresh:
```
19:44:20  20 of 36 OK created sql incremental model andrew_mart_ad_hoc.fct_daily_vehicle_location_feed_trip_counts  [CREATE TABLE (713.0 rows, 162.8 GB processed) in 77.23s]
19:44:34  15 of 36 OK created sql incremental model andrew_mart_gtfs.fct_vehicle_positions_trip_summaries  [CREATE TABLE (819.2k rows, 162.8 GB processed) in 91.75s]
19:44:49  13 of 36 OK created sql incremental model andrew_mart_gtfs_quality.fct_daily_vehicle_positions_message_age_summary …
```
> Adjust trip updates materializations

- warehouse/models/mart/gtfs/_mart_gtfs_dims.yml
- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
We got a ton of failing dbt tests and warnings over the weekend due to an Auburn feed that uses tabs instead of commas to delimit some feeds, leading to all parsed fields being null. This is a temporary workaround to suppress these failing tests just so that we can get alerted if another issue occurs while we figure out a longer term fix for Auburn. 
Ran `dim_calendar` and confirmed tests pass. I also went through all the fails & warns and confirmed they were associated specifically with tab-delimited Auburn files (`calendar`, `calendar_dates`, `fare_attributes`, `fare_products`, and `routes`).
> Suppress tests on tab-delimited Auburn feed

- warehouse/models/mart/payments/fct_payments_rides_v2.sql
- warehouse/models/mart/payments/reliability/_payments_views_tests.yml
- warehouse/models/mart/payments/reliability/v2_payments_daily_transaction_deltas.sql
- warehouse/models/mart/payments/reliability/v2_payments_monthly_transaction_deltas.sql
- warehouse/models/mart/payments/reliability/v2_payments_reliability_unlabeled_routes.sql
- warehouse/models/mart/payments/reliability/v2_payments_weekly_transaction_deltas.sql
This PR replicates the tables that power the payments reliability dashboard in the v1 pipeline for the v2 pipeline
Question @atvaccaro - is there a better place that this should live?
> V2 payments reliability tables

- docs/analytics_tools/rt_analysis.md
- fix typo in rt_analysis table desciption
copy/pasted a few extra asterisks into the `stop_segment_speed_view` description that should be removed for clarity
> Update rt_analysis.md (typo)

- warehouse/models/mart/ad_hoc/_mart_ad_hoc.yml
- warehouse/models/mart/ad_hoc/fct_scheduled_service_by_daypart.sql
- warehouse/models/mart/gtfs_quality/idx_monthly_reports_site.sql
I missed a few more references to `activity_date` in #2457 which caused the dbt job to fail this morning. This PR fixes them. 
Ran the tables confirmed they now work
> Switch back to service date

- .github/workflows/build-dbt.yml
Stop using CML since it's erroring and overkill anyways; use a specific action for creating/updating comments.
Brings in `max-ts-override` commits for testing.
I've temporarily disabled the actual DAG image; it's addition work to render it without CML, but I want to stop all the Action failures.
CI should pass, then I'll strip out the test commits and merge.
> Switch GitHub comment action

- airflow/dags/deploy_dbt_docs/sync_dbt_docs_to_metabase.yml
- warehouse/scripts/dbt_artifacts.py
- warehouse/scripts/run_and_upload.py
~I actually have mixed feelings about https://github.com/cal-itp/data-infra/issues/2362; my worry is that we don't actually know when Metabase has synced a schema. At best, we could trigger a manual sync and wait for a period of time. I don't think we can actually monitor for sync completion.~
~Actually it looks like we can use https://www.metabase.com/docs/latest/api/notify potentially~
Even better, dbt-metabase already triggers a sync and waits before attempting to update metadata.
Resolves https://github.com/cal-itp/data-infra/issues/2362
See [Sentry](https://sentry.calitp.org/organizations/sentry/issues/70462/?environment=development&project=2&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h) for examples
> log dbt-metabase errors and add enrichment/filepaths

- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_agency_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_areas_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_attributions_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_calendar_dates_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_calendar_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_fare_attributes_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_fare_feed_info_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_fare_leg_rules_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_fare_media_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_fare_products_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_fare_rules_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_fare_transfer_rules_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_frequencies_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_levels_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_pathways_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_routes_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_shapes_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_stop_areas_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_stop_times_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_stops_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_transfers_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_translations_txt_json_outcomes.yml
- airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_json_outcomes/gtfs_schedule_trips_txt_json_outcomes.yml
- airflow/plugins/operators/gtfs_csv_to_jsonl.py
Resolves https://github.com/cal-itp/data-infra/issues/2484
We'll have to run the full Schedule backfill after merging.
I copied the tab-delimited feed into test and confirmed that the file is parsed properly and we see the new dialect in the outcomes.
> sniff csv dialects and save as metadata

- warehouse/models/staging/payments/elavon/stg_elavon__transactions.sql
Partway through the operation of our Elavon data pipeline, we received what appears to be a monthly drop of batch type B (billing) data. These records don't have a `trn_ref_num`, which we previously were able to treat as a unique ID. We are still awaiting more detailed information about the dynamics of these data, but because this pipeline is currently doing a full file download + full reload into an external table every day, we can modify the dbt job that generates the staging table to give us the correct rows for B-batch data while not interrupting the logic that works for other batch types.
Staging table generated from scratch in the staging warehouse
> Bring Elavon batch type B records into staging table

- .github/workflows/sentry-release.yml
Now that the action has been tested, we can only run on main merges (we don't really "deploy" to test anyways).
> only do sentry releases on main

- airflow/dags/create_external_tables/gtfs_schedule_v2/fare_products.yml
- warehouse/models/docs/gtfs schedule/fare_products.md
- warehouse/models/mart/gtfs/_mart_gtfs_dims.yml
- warehouse/models/mart/gtfs/dim_fare_products.sql
- warehouse/models/staging/gtfs/_stg_gtfs.yml
- warehouse/models/staging/gtfs/stg_gtfs_schedule__fare_products.sql
We recently added the new `fare_media` table to the warehouse `mart_` tables in #2509. This PR adds the newly implemented `fare_media_id` field in the preexisting `fare_products` table, and updates the YAML for GTFS schedule staging tables to include information about `stg_gtfs_schedule__fare_products`, documentation which was missed in the previous PR.
Resolves #2432
External table successfully updated in staging, and dbt tests run on the staging external table
> Add fare_media_id to fare_products table + update related docs

- warehouse/models/mart/payments/elavon_littlepay__daily_history_transactions_deposits_billing.sql
In #2482 the table `elavon_littlepay__daily_history_transactions_deposits_billing` had a breaking character causing the dbt run to fail
Locally with `dbt run`
> Fix broken elavon/ littlepay transaction history comparison table

- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/pyproject.toml
Resolves https://github.com/cal-itp/data-infra/issues/2478
1. Get the top-level exception type for the fingerprint; avoids object hashes in (potentially very nested) exception bodies
2. Strips agency query params from end of URL (to combine 511 issues)
I've also added masking in the [Sentry UI](https://sentry.calitp.org/settings/sentry/security-and-privacy/) but it doesn't seem to be entirely working yet.
fixes CAL-ITP-DATA-INFRA-24S9
(testing that)
Deployed to test now.
See [this issue](https://sentry.calitp.org/organizations/sentry/issues/70957/?environment=development&project=2&query=is%3Aunresolved&referrer=issue-stream) as an example of a new issue with the updated exception body and the 511 change.
> RT fingerprint adjustments

- .github/pull_request_template.md
I've noticed an increasing number of PRs that require some kind of additional post-merge action (for example, running a full refresh of a given model, or running a backfill of some kind, or perhaps merging another PR in a related repo). I wanted to create a place to record such requirements in a standardized way.
Also, I am removing the `screenshots` section since it is not regularly used and deprecating the `agencies.yml` PR type since we no longer regularly update agencies.yml. 
N/A
> Update PR template to include post-merge actions

- docs/analytics_tools/rt_analysis.md
- warehouse/models/intermediate/gtfs_quality/_int_gtfs_quality.yml
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__daily_assessment_candidate_entities.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_index.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__organization_dataset_map.sql
- warehouse/models/mart/gtfs_quality/fct_daily_organization_combined_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_daily_reports_site_organization_scheduled_service_summary.sql
- warehouse/models/mart/gtfs_quality/fct_daily_service_combined_guideline_checks.sql
- warehouse/models/mart/gtfs_quality/fct_monthly_reports_site_organization_gtfs_vendors.sql
- warehouse/models/mart/gtfs_quality/fct_monthly_reports_site_organization_validation_codes.sql
- warehouse/models/mart/gtfs_quality/fct_monthly_route_id_changes.sql
- warehouse/models/mart/gtfs_quality/fct_monthly_stop_id_changes.sql
- warehouse/models/mart/gtfs_quality/idx_monthly_reports_site.sql
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/dim_provider_gtfs_data.sql
Responsive to #2464, renames two columns used in quality tables to reflect a more commonsense understanding of those columns' meanings.
Resolves #2464
Working through dbt tests at the time of PR creation.
Downstream references to the old columns (e.g. in Metabase) will need to be switched out.
> New column names for quality tables

- .github/CODEOWNERS
As a no-longer defacto code owner, being listed makes it unclear when a review is actually needed from me vs when it is a routine change which may proceed with or without my review. Making all review requests explicit removes this ambiguity.
> CODEOWNERS: remove @lottspot

- runbooks/pipeline/sentry-triage.md
Updates the default search link in the Sentry runbook to actually filter to only new issues from last 24 hours (old link was not actually filtering to `firstSeen:-24hr`). When I clicked the existing link this morning for triage I got 144 issues; updated link yields only 9 (which I think is more what we would expect?)
Confirmed the link works.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone …
> update sentry search link

- .github/pull_request_template.md
- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
Adds missing duplicate primary key handling in the `_latest` mart views. Also adds more spacing in the PR template. 
* Fixes CAL-ITP-DATA-INFRA-14JE ([link](https://sentry.calitp.org/organizations/sentry/issues/37484/))
* Fixes CAL-ITP-DATA-INFRA-14JD ([link](https://sentry.calitp.org/organizations/sentry/issues/37483/))
* Fixes CAL-ITP-DATA-INFRA-14JC ([link](https://sentry.calitp.org/organizations/sentry/issues/37482/))
* Fixes CAL-ITP-DATA-INFRA-17QT ([link](https://sentry.calitp.org/organizations/sentry/issues/40761/))
Resolves #2498
Confirmed these tests pass now.
_Document any actions that must be taken post-merge to …
> account for known duplicates in latest-only views

- warehouse/macros/rt_sampled_where_clause.sql
- warehouse/macros/test_unique_proportion.sql
- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
Resolves https://github.com/cal-itp/data-infra/issues/2499
Switches RT tests to be almost unique, as our keys are intended to be unique if the spec is followed (based on our understanding). We want tests to pass, but indicate to users that those keys should _generally_ be unique as 99.9% uniqueness is a pretty high bar.
Unsure if this will mark these as resolved, but trying again.
fixes CAL-ITP-DATA-INFRA-13R8
fixes CAL-ITP-DATA-INFRA-13Q0
fixes CAL-ITP-DATA-INFRA-248R
fixes CAL-ITP-DATA-INFRA-13EG
fixes CAL-ITP-DATA-INFRA-13EH
fixes CAL-ITP-DATA-INFRA-2458
fixes CAL-ITP-DATA-INFRA-H4G
_Document any actions that must be …
> create an almost-unique test, and use it in currently failing places

- warehouse/models/mart/payments/reliability/v2_payments_reliability_unlabeled_routes.sql
The calculation to find unlabeled `route_id`s  in `v2_payments_reliability_unlabeled_routes` didn't include those with empty strings
locally with dbt run and in metabase
* Going to add the unlabeled routes question to the SBMTD dashboard once it runs
> revise empty route_id calculation to include empty strings

- warehouse/models/mart/gtfs/_mart_gtfs_dims.yml
Fixes CAL-ITP-DATA-INFRA-24K3 ([link](https://sentry.calitp.org/organizations/sentry/issues/70511/))
```
test.calitp_warehouse.unique_dim_fare_media_key.4f70bd2c4a - Database Error in test unique_dim_fare_media_key (models/mart/gtfs/_mart_gtfs_dims.yml)
Unrecognized name: warning_duplicate_primary_key
```
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create …
> fix fare media pk test

- warehouse/models/mart/transit_database/dim_organizations.sql
#2582 introduced a missing parenthesis that broke `dim_organizations`, due to last-minute changes that were merged without additional dbt test runs. This PR solves the problem introduced by those changes.
Resolves #2586
dbt test run completed on existing code to verify the same error occurs locally, then run after changes to verify its resolution.
Will mark the Sentry issue generated by this bug as `resolve on next release`.
> HOTFIX missing parenthesis on dim_organizations

- warehouse/models/mart/payments/elavon_littlepay__daily_history_transactions_deposits_billing.sql
Based on feedback, we're adding an MVP dashboard for CCJPA so as to compare Littlepay and Elavon revenue data. This PR makes that data available for CCJPA.
locally with dbt run and in Metabase
This data should automatically be available in the CCJPA metabase dashboard but we may need to modify filters and do some QC etc
> Modified littlepay/elavon transaction comparison table to include ccjpa

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_service_alerts_messages_unnested.sql
* Was adding `active_period_start_ts` in #2489 and realized it should just go on the main fct table 
* Cleaning up some YAML I missed before in #2583 
Full refreshed `fct_service_alerts_messages_unnested` and confirmed new columns appear and seem reasonable. New test passes and I looked at the executed SQL and confirmed that `__rt_sampled__` is compiling as expected. 
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will …
> add active period start/end timestamp columns and cleanup yaml

- warehouse/models/mart/transit_database/_mart_transit_database.yml
Two columns were added and then removed in the course of #2383 but they weren't removed from the YAML so they are throwing Metabase sync errors every day
Fixes CAL-ITP-DATA-INFRA-24JW ([link](https://sentry.calitp.org/organizations/sentry/issues/70504/events/ff8e54f7fb234018830767d14231510e/?project=2))
```
DbtMetabaseSyncFailure
WARNING Column HQ_COUNTY_GEOGRAPHY not found in MART_TRANSIT_DATABASE.DIM_ORGANIZATIONS
```
Fixes CAL-ITP-DATA-INFRA-24JX ([link](https://sentry.calitp.org/organizations/sentry/issues/70505/events/034c716d1c3e45fb8ff8e6ceb1ca006a/?project=2#tags))
```
DbtMetabaseSyncFailure
WARNING Column OPERATING_COUNTY_GEOGRAPHIES not found in …
```
> remove references to obsolete columns

- airflow/dags/create_external_tables/amplitude/benefits_events.yml
- Fixes this Sentry issue: https://sentry.calitp.org/organizations/sentry/issues/71166/?project=2&referrer=assigned_activity-email
- Resolves #2597 
- There is a `group_properties` column in the Amplitude data (and the corresponding Mart and Fact Table), but it's not in the External Table. This pull request adds the `group_properties` column as into the External Table.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to track …
> fix(benefits): add group_properties column to external table

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
Due to missing older data before our ingestion and modeling were evolved, fct_daily_rt_feed_files doesn't currently test a .999-threshold not null test for the `gtfs_dataset_key`. This lowers the threshold to .998 in order to pass, while keeping it high enough that newly introduced issues should still trip up alarms.
Resolves #2571
dbt tests run locally, using the production table as a reference.
Eventually, as this table grows, we should likely move this back to a .999-threshold test.
> Reduce not-null test threshold for fct_daily_rt_feed_files

- warehouse/models/mart/benefits/_mart_benefits.yml
- warehouse/models/staging/amplitude/_amplitude.yml
An incorrect reference to a nonexistent `groups` column in benefits events tables was causing errors when writing table metadata to Metabase. This resolves the issue by removing the erroneous column reference from the two YAML files in which it appeared.
Resolves #2597 (previously marked as resolved due to shared fingerprinting with another issue)
Column lists inspected by hand and compared to production tables in the warehouse.
> Remove erroneous "groups" column reference from benefits YAML

- runbooks/infrastructure/disk-space.md
Some commands in our Disk Space Usage runbook had a mislabeled filename - this fixes the issue.
New commands tested for validity
> Correct .sh file labels in disk-space.md

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
We were seeing Metabase failures on each of the models touched here, due to mismatches between observed columns and expected columns. Only one of the three sets of errors will be resolved entirely by this PR, since we need to backfill `fct_trip_updates_summaries` and `fct_vehicle_positions_trip_summaries` to bring in new columns on each of those models before their respective Metabase errors will go away, but they needed YAML adjustments nonetheless.
Alignment between tables in warehouse and YAML confirmed by hand inspection (except in the case of the two column additions to `fct_trip_updates_summaries` and `fct_vehicle_positions_trip_summaries`, which are expected to differ).
We will need to resolve [this Sentry issue](https://sentry.calitp.org/organizations/sentry/issues/71495/events/56c …
> Update YAML for several models to align with warehouse

- warehouse/models/mart/transit_database/_mart_transit_database.yml
Responding to [this Sentry issue](https://sentry.calitp.org/organizations/sentry/issues/71537/), which stemmed from docstring length limits in BigQuery.
Resolves #2646 
New character count verified below the allowable threshold.
> Revise gtfs_schedule_quality description for character count

- .github/workflows/build-dbt.yml
- warehouse/macros/gtfs_rt_unnest_column_count_distinct.sql
- warehouse/models/intermediate/gtfs/int_gtfs_rt__service_alerts_trip_day_map_grouping.sql
- warehouse/models/intermediate/gtfs/int_gtfs_rt__trip_updates_trip_day_map_grouping.sql
- warehouse/models/mart/gtfs/fct_service_alerts_trip_summaries.sql
- warehouse/models/mart/gtfs/fct_trip_updates_messages.sql
- warehouse/models/mart/gtfs/fct_trip_updates_summaries.sql
- warehouse/scripts/dbt_artifacts/__init__.py
- warehouse/scripts/templates/ci_report.md
- warehouse/scripts/visualize.py
Resolves https://github.com/cal-itp/data-infra/issues/2569
Note: I've rebased off handle-stop-times-enums to test the visualization; need to undo before merging.
CI should run and display.
> Bring back cml CI and change what we print

- warehouse/models/payments_views_staging/_payments_views_staging.yml
- warehouse/models/payments_views_staging/int_cleaned_device_transaction_pairs_common_fields.sql
- warehouse/models/staging/payments/littlepay/_littlepay.yml
- warehouse/models/staging/payments/littlepay/int_device_transaction_pairs_common_fields.sql
As described in the discussion around #2592, there were a couple payments tests that weren't serving our needs well - they began failing on new data not because something was wrong with the pipeline, but because we don't know enough about the constraints on the data to begin with. We decided to move these to models so that somebody could feasibly build dashboards off of them if desired.
Resolves #2592
New models built via dbt runs in staging
If we want to actually have a dashboard in place to monitor the phenomena previously measured by the tests, we'll need to create some non-staging models after this PR and base the dashboard on those, since staging datasets aren't meant to underpin prod dashboards.
> Move failing payments common fields tests to models

- warehouse/macros/transit_database_many_to_many.sql
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/bridge_fare_systems_x_services.sql
Fixes #2658 by dropping rows from bridge tables where one table's key is not present (i.e., dangling references). #2658 was caused by deleted services being present in a bridge table with a current-only table, so there were two rows with the same `service_key` and null `fare_systems_key`. 
I also updated the relevant table descriptions to explicitly describe the most confusing case here. 
Resolves #2658
`dbt run -s +models/mart/transit_database` & `dbt test -s +models/mart/transit_database`
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a …
> Drop rows from bridge tables where one key is missing 

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- _typos.toml
- docs/airflow/dags-maintenance.md
- docs/analytics_new_analysts/07-spatial-analysis-intermediate.md
- docs/analytics_tools/overview.md
- docs/analytics_tools/rt_analysis.md
- docs/backups/metabase.md
- docs/ci/README.md
- docs/contribute/content_types.md
- docs/datasets_and_tables/transitdatabase.md
- docs/kubernetes/architecture.md
- docs/publishing/overview.md
- docs/publishing/sections/4_analytics_portfolio_site.md
- docs/publishing/sections/5_notebooks_styling.md
- warehouse/models/payments_views_staging/stg_cleaned_customer_funding_source_vaults.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_quality__intended_checks.sql
- warehouse/poetry.lock
- warehouse/pyproject.toml
- warehouse/scripts/publish.py
- warehouse/scripts/run_and_upload.py
- warehouse/scripts/visualize.py
Adds a couple new CI checks and brings back sqlfluff; tighter typos scope than https://github.com/cal-itp/data-infra/pull/2515.
Also, now that dbt 1.5.1 is out with a necessary bugfix, we can use it instead of the 1.6 pre-release.
CI must pass except for check dbt; unfortunately since this downgrades dbt to a version that uses the v9 manifest, we can't compare state with production artifacts with the v10 manifest.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more …
> CI tweaks, use new dbt 1.5.1 release

- warehouse/models/mart/payments/reliability/_payments_views_tests.yml
- warehouse/models/mart/payments/reliability/v2_payments_reliability_monthly_unlabeled_routes.sql
- warehouse/models/mart/payments/reliability/v2_payments_reliability_weekly_unlabeled_routes.sql
create new weekly unlabeled routes tracking table `v2_payments_reliability_weekly_unlabeled_routes`, rename original title from `v2_payments_reliability_unlabeled_routes` to `v2_payments_reliability_monthly_unlabeled_routes`
Once this is merged, we can create the alert in the SBMTD dashboard as requested in #2619
tested locally with dbt
Set up alerts in Metabase
> create new table to track weekly unlabeled routes for payments

- warehouse/macros/incremental_where.sql
Resolves the currently failing `dim_translations`; handles situations where the table is empty but exists.
I'm a bit worried this means we could theoretically continue to query upstream data if a bug means that we don't ever _insert_ any queried rows. I just don't know a good way to check whether there's any upstream data without actually querying for upstream data. We don't have rowcounts or anything in the outcomes, unfortunately.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these …
> handle cases where gtfs dims are empty

- airflow/dags/publish_open_data/publish_california_open_data.yml
After adding several new tables to open data publishing, we are seeing failures similar to those reported in #2596. This PR ups the memory provided to the open data publishing job in order to accommodate what we assume is a memory limitation. In the future, we may want to take a closer look at table-by-table memory management in this job.
We likely want to investigate other strategies for breaking up memory use on this job in the future.
> Up memory request on open data publication DAG

- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
- warehouse/scripts/dbt_artifacts/__init__.py
- warehouse/scripts/publish.py
In order to facilitate smoother addition of new columns to tables that are present in open data publishing, this PR defaults to non-publication and adds a mechanism by which we can manually designate columns for publication. This flips the previous logic, which attempted to publish all columns which weren't explicitly excluded via a `publish.ignore` meta entry.
Resolves #2651
Tested for column parity against currently published tables by generating a manifest locally and using that to generate local dictionary and metadata files.
On the original Issue, [Andrew mentioned](https://github.com/cal-itp/data-infra/issues/2651#issuecomment-1572794033) eschewing the `_latest` models altogether and making the qualifying logic for publication into a `where` clause on the models from which our …
> Default to non-publication for new columns on open data tables

- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_service_alerts_validation_outcomes.yml
- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_trip_updates_validation_outcomes.yml
- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_vehicle_positions_validation_outcomes.yml
- jobs/gtfs-rt-parser-v2/Dockerfile
- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
- jobs/gtfs-rt-parser-v2/test_gtfs_rt_parser.py
- warehouse/macros/gtfs_rt_stg_outcomes.sql
Resolves https://github.com/cal-itp/data-infra/issues/2643
Resolves https://github.com/cal-itp/data-infra/issues/2609
Adds stderr to outcomes and Sentry; adds tags to Sentry; and changes fingerprint for Sentry to distinguish ZLIB errors from others.
pytest passes, and tested via local run.
Here's an example [Sentry event](https://sentry.calitp.org/organizations/sentry/issues/71961/?environment=local&project=2&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h) and I've verified that outcomes contain the stderr.
```sql
select *
from cal-itp-data-infra-staging.external_gtfs_rt_v2.trip_updates_validation_outcomes
where …
```
> add more rt validation information to sentry and outcomes

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
Noticed while working on GTFS quality dashboard updates that this field should have been a boolean in the external table for consistency. 
Ran the Airflow DAG locally, ` poetry run dbt run -s +stg_transit_database__services+2 --vars "{'SOURCE_DATABASE':'cal-itp-data-infra-staging'}"`, ` poetry run dbt test -s +stg_transit_database__services+2 --vars "{'SOURCE_DATABASE':'cal-itp-data-infra-staging'}"`
Confirmed no issues.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take …
> Changed `fixed_route` to boolean in external table

- airflow/dags/create_external_tables/airtable/external_airtable_transit_tech_stacks_components.yml
- airflow/dags/create_external_tables/airtable/external_airtable_transit_tech_stacks_products.yml
Adds schemas to the components & products external tables. 
Resolves #2705, although it is possibly a short-term fix 
Ran the create external tables DAG task locally, verified it runs. The broken column is not even present in the staging tables in the warehouse so it really affects very little. 
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a …
> Remove broken column from external tables

- warehouse/scripts/run_and_upload.py
assert `mb_host` is not empty for mypy, ignore library `dbtmetabase.models.interface` that lacks stubs
locally
> assert mb_host is not empty for mypy, ignore library that lacks stubs

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_scheduled_trips.sql
This PR is one of two that will implement the changes requested in #2639, renaming `fct_daily_scheduled_trips` to `fct_scheduled_trips`. It creates a new `fct_scheduled_trips` model with complete parity to the existing `fct_daily_scheduled_trips` model, which will run during the transition period while people switch over references to the new table.
Partially resolves #2639
New model creation and updates tested in staging warehouse
After this PR merges, we will announce the upcoming table name switch so that people can begin changing their references. A second PR will be created and merged which will deprecate the old `fct_daily_scheduled_trips` model and switch all references to that model over to the new table on the day of the announced switchover.
> fct_scheduled_trips part 1 - create new table

- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
In a recent PR, new tests were added to open data publishing tables when new columns were added to those tables. This isn't in line with our recent approach to these tables, where we've chosen to rely on the tests from underlying models instead. This PR removes the tests in question in order to silence a set of active related Sentry issues like [this one](https://sentry.calitp.org/organizations/sentry/issues/71679/?project=2). These models will soon be discontinued altogether via #2701, so this PR is essentially a convenience for the moment to prevent overzealous Sentry alerting.
Publishing models and tests (or lack thereof) run in staging after the YAML changes made in this PR
> Remove tests from _latest models used for open data publishing

- warehouse/scripts/run_and_upload.py
Resolves https://github.com/cal-itp/data-infra/issues/2718
I think the exclude sources flag got left out when moving to the Python API
Ran via local docker-compose.
> exclude metabase sources from sync, and couple other cleanups

- warehouse/macros/gtfs_rt_messages_keying.sql
- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_service_alerts_messages.sql
- warehouse/models/mart/gtfs/fct_trip_updates_messages.sql
- warehouse/models/mart/gtfs/fct_vehicle_positions_messages.sql
Pulling this out of #2489 for scope/size. This PR adds a bunch of new keys to RT messages models:
* schedule dataset key
* schedule feed key
* schedule dataset name 
* schedule feed time zone 
These (schedule time zone in particular) facilitate better date/time handling in downstream models, to be implemented in #2489.
I ran an incremental run on top of models run from `main` (`poetry run dbt run -s source:external_gtfs_rt+,models/mart/gtfs`) and confirmed that this is backwards-compatible on its own, i.e., no full refresh or any special handling required. 
_Document any actions that must be taken post-merge to deploy or …
> add more keying to underlying rt messages models

- runbooks/pipeline/sentry-triage.md
Reflecting an additional duty for the person on triage for a given sprint, this adds a reference to Monday morning checks of the performance dashboard and fillout of the associated spreadsheet to the triage runbook.
README markdown validated
> Add performance dashboard/spreadsheet check to triage runbook

- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
Chad Baker let us know that we were seeing weird behavior within CKAN for the agency table (errors indicating an imcomplete upload, which don't align with any such issues on our side or any observed incompleteness of the resulting public files), so he created a new resource ID for that table. We believe that simply using this new resource ID should resolve the problem.
Cannot be fully tested until an upload is made to the new destination.
After merge, I will kick off a one-off run of publishing to see if we've managed to resolve the CKAN issue.
> Update agency CKAN destination resource ID

- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
We are experiencing an issue with our publication script wherein fields on our models that don't have associated YAML entries are ending up in publication. I am investigating the underlying logic and will create an issue and submit a fix for that later, but in the meantime, this corrects the YAML for several published tables that were missing the `_feed_valid_from` column and tripping up the issue as a result.
Models recreated in staging - full publication can't be tested without an updated manifest, which will be done after merge.
Run the `run_and_upload` and `publish` scripts in prod to create new open data tables and determine whether there are other remaining mismatches.
> Document the existence of _feed_valid_from in schedule_latest models

- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
Follow-up work to #2786, using new destinations for two tables to wipe out cached information for those tables. Chad suggested leaving `stop_times` alone for now since it's not producing active errors in the portal, so its download issues may self-resolve quickly.
Cannot be tested until run.
A new publication run will be kicked off following merge
> New CKAN destinations for shapes and translations

- docs/architecture/architecture_overview.md
Resolves https://github.com/cal-itp/data-infra/issues/2672
Creates a couple of high-level architecture diagrams and adds some additional service/environment docs. Should set us up for service/folder-specific READMEs in the next sprint.
see docs preview
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to track …
> start on new infra/arch docs

- warehouse/profiles.yml
Full refresh from #2489 [timed out](https://o1d2fa0877cf3fb10p-tp.appspot.com/dags/transform_warehouse_full_refresh/grid?dag_run_id=manual__2023-07-13T16%3A27%3A51.422835%2B00%3A00&task_id=dbt_run_and_upload_artifacts) on the new trip day map grouping models. Increasing timeout to hope they can complete. 
Hasn't, no great way to test locally (local dev env caps history at 7 days; seems wasteful to try to calibrate too closely in test vs. try to get it to work in prod.)
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some …
> increase timeout in dbt profile

- warehouse/models/mart/gtfs/fct_vehicle_locations.sql
- warehouse/profiles.yml
Second attempt to full-refresh post #2489 [also timed out](https://o1d2fa0877cf3fb10p-tp.appspot.com/log?execution_date=2023-07-13T18%3A12%3A07%2B00%3A00&task_id=dbt_run_and_upload_artifacts&dag_id=transform_warehouse_full_refresh&map_index=-1) so this increases the timeout even more. Also fixes an error: `ST_GeogPoint failed: Latitude must be between -90 and 90 degrees. Actual value was 436.47925` that was raised.
Ran vehicle locations locally and confirmed that values are still populated when valid. 
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this …
> address full refresh run failures

- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/intermediate/gtfs/int_gtfs_rt__service_alerts_day_map_grouping.sql
- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/profiles.yml
After #2804, we still continued to see a small number of failures across models created/modified in #2489. This PR adjusts testing thresholds to get the tests passing; at this point the number of failures (a few hundred out of tens of millions of rows, in the cases of trip updates) is such that the ROI on a more structural fix is low. The failure conditions are pretty well understood. 
Fixes CAL-ITP-DATA-INFRA-268D ([x](https://sentry.calitp.org/organizations/sentry/issues/72312/))
Fixes CAL-ITP-DATA-INFRA-268E ([x](https://sentry.calitp.org/organizations/sentry/issues/72313/))
Fixes CAL-ITP-DATA-INFRA-268M ([x](https://sentry.calitp.org/organizations/sentry/issues/72319/) …
> More cleanup post-#2489

- ci/tasks.py
- kubernetes/apps/charts/sentry/values.yaml
https://github.com/cal-itp/data-infra/pull/2850 is failing to show changes to jupyterhub; it looks like the kustomize/kubectl diff workaround isn't working. This PR uses a helm diff plugin instead.
We should see proper CI diffs in a candidate PR.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to track …
> use helm diff plugin vs kustomize workaround

- docs/analytics_onboarding/overview.md
- docs/analytics_welcome/how_we_work.md
Updating introductory pages on docs site to reflect:
- Updates to meetings/processes with the creation of Div of DDS
- Caltrans-specific technical resources that may be useful for analysts
- Commonly used acronyms analysts should know
Will review netlify preview link
> Analyst Docs Updates: Caltrans employee edition

- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml
- kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-ticker.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/README.md
- services/gtfs-rt-archiver-v3/docker-compose.yml
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py
- services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/ticker.py
- services/gtfs-rt-archiver-v3/pyproject.toml
Resolves https://github.com/cal-itp/data-infra/issues/1938
(see https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1691601423249999)
Note: I'm choosing an easier/simpler implementation that uses the ticker to grab and pass auth keys in task calls. This means secrets are serialized into Redis, but it's not a huge deal since we don't persist/backup Redis.
~Also, fetching secrets when we fetch configs does add to the fetch delay every 5 minutes. The alternative would be a separate scheduled function call, which I am going to experiment with. (We could use this same scheduled call to update the configs and reduce delay even more).~
I implemented this; the same scheduler that …
> Fetch latest RT secrets every minute

- kubernetes/apps/charts/sentry/Chart.yaml
Reverts cal-itp/data-infra#2871
I'm hitting an issue around existingSecret for the underlying postgres chart. Going to see if I can revert.
> Revert "upgrade sentry helm chart"

- kubernetes/apps/charts/sentry/Chart.yaml
- kubernetes/apps/charts/sentry/values.yaml
- kubernetes/apps/values/postgresql-backup-sentry.yaml
Resolves the post-upgrade sentry issues. The upgrade changed a couple defaults that I failed to override before now. Also, the postgres backup takes ~1.5 hours to run, so with the cron default of hourly, it was running constantly and stopping long-running database migrations from being able to run. I've changed it to run 2x a day.
Sentry is up and running.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be …
> try sentry upgrade again; change backup frequency

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_monthly_routes.sql
Fixes failing test by re-keying table and refactoring the join with GTFS datasets. Also adds a bit of documentation.
Fixes CAL-ITP-DATA-INFRA-26BK ([x](https://sentry.calitp.org/organizations/sentry/issues/72428/?project=2))
``` 
laurie ~/git/data-infra/warehouse [fix-monthly-routes-keying] $ poetry run dbt test -s fct_monthly_routes
18:48:02  Running with dbt=1.5.1
18:48:04  Found 324 models, 843 tests, 0 snapshots, 0 analyses, 839 macros, 0 operations, 7 seed files, 126 …
```
> Fix failing test on fct monthly routes

- ci/channels/prod.yaml
- kubernetes/apps/values/grafana-prod.yaml
- kubernetes/apps/values/loki-prod.yaml
Step towards unblocking GKE automatic upgrade to k8s v1.25.
I've deployed both of these and confirmed `kubectl get psp` no longer shows anything, and the upgrades themselves do not show the deprecation warnings.
I'll have deployed this …
> disable psp in both grafana and loki

- warehouse/macros/gtfs_rt_messages_keying.sql
This morning, the AC Transit schedule feed failed to download. As a result, we got a bunch of errors on the RT side, because the RT data had no schedule data to map to. The specific symptom that caused the alerting was that the AC Transit feed uses timezone `US/Pacific` and our default fallback is `America/Los_Angeles` so we got some fanout where the same trip was mapping to two time zones across the 3am UTC boundary when the schedule feed download failure registered.
Fixes CAL-ITP-DATA-INFRA-2682 ([x](https://sentry.calitp.org/organizations/sentry/issues/72301/))
Fixes CAL-ITP-DATA-INFRA-2695 ([x](https://sentry.calitp.org/organizations/sentry/issues/72337/))
Fixes …
> Change GTFS RT / schedule mapping to handle schedule download failures

- warehouse/models/mart/gtfs/fct_daily_scheduled_stops.sql
- warehouse/tests/mart/gtfs/validate_fct_daily_tables.sql
Since we want `fct_daily_scheduled_stops` to show stops for all days available, move `fct_scheduled_trips` to use as base table on which `dim_stop_times` is joined.
Resolves #2900 
`poetry run dbt run --select fct_daily_scheduled_stops`
`poetry run dbt test --select fct_daily_scheduled_stops`
Also, checked Big Query to make sure there are more feeds available in Aug. 
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will …
> bug fix: missing `mart_gtfs.fct_daily_scheduled_stops`

- warehouse/models/mart/payments/fct_payments_rides_v2.sql
In our Metabase dashboards, missing `form_factor` values appear as several different values including `Null`s and empty strings. This PR converts them all to 'Unidentified'
bigquery/ local dbt
> renaming missing form_factor values to 'Unidentified'

- warehouse/models/mart/payments/indexes/payments_tests_daily_date_spine.sql
- warehouse/models/mart/payments/indexes/payments_tests_monthly_date_spine.sql
- warehouse/models/mart/payments/indexes/payments_tests_weekly_date_spine.sql
Since merging the PR which includes payments rides that have `off` taps but don't have `on` taps, we introduced rides with no transaction date which is interfering with the date spine we created. This PR excludes null values for transaction dates in the date spine.
locally with dbt
> revise payments date spine to exclude null values

- airflow/dags/parse_littlepay/atn.yml
- airflow/dags/sync_littlepay/atn.yml
- warehouse/models/mart/payments/fct_payments_rides_v2.sql
- warehouse/seeds/payments_gtfs_datasets.csv
Adds code to bring Anaheim Transportation Network LittlePay data (already available in a vendor-controlled S3 bucket) into the warehouse. The agency is referred to here as `atn` for consistency with the name of the vendor data at the source (the bucket is `littlepay-prod-atn-datafeed`, rather than using an expanded form of the agency's name). That can be changed if we prefer to use the full name - I see there's a mixture of names and acronyms among the current LittlePay syncs.
Tested on local Airflow from raw data ingestion to external table creation
> Add Anaheim Transportation Network to LittlePay pipeline

- warehouse/models/mart/payments/fct_payments_rides_v2.sql
After comparing HTA's July littlepay statement to the Metabase dashboard we realized that transactions were missing. After investigating, we realized that it was a result of an inner join on the `customer_id`field in `fct_payments_rides_v2`. This Pr changes that inner join to a left join, which causes the transaction values to match much more closely.
locally in Bigquery and dbt
> change fct_payments_rides_v2 join to include missing transactions

- airflow/dags/parse_littlepay/METADATA.yml
- airflow/dags/sync_littlepay/METADATA.yml
- airflow/dags/transform_warehouse/METADATA.yml
- airflow/plugins/operators/littlepay_to_jsonl.py
The freshness issues we've observed in payments data appear to be correctable with more frequent payments dag runs. This PR changes dag runs to hourly. 
TODO: run transaform_warehouse dag on `--select +fct_payments_rides_v2` hourly at the 45 minute mark ?
> make payments dags run hourly

- airflow/dags/create_external_tables/gtfs_schedule_v2/validation_notices.yml
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__schedule_validator_rule_details_unioned.sql
- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/seeds/_seeds.yml
- warehouse/seeds/gtfs_schedule_validator_rule_details_v4_1_0.csv
A few changes to fully encapsulate the logic we previously put in place to reference validator version 4.1.0, plus a fix for an incorrect bucket reference previously used for the `validation_notices` external table. 
Tested with local Airflow and local dbt runs/tests of impacted models.
Regenerate external table in prod, run relevant dbt models, and create updates to the documentation for the validator to cover some additional parts of the version upgrade process.
> GTFS Validator Upgrade Follow-Up

- warehouse/models/staging/payments/littlepay/int_littlepay__device_transaction_types.sql
Adds incomplete variable fares to device transaction types so they will appear in fct payments rides. 
Confirmed `littlepay_transaction_id` is populated for all but one incomplete variable fare rows with this change (342/343 rows):
```sql
SELECT  
charge_type,
littlepay_transaction_id IS NULL AS missing_id,
COUNT(*)
FROM `cal-itp-data-infra-staging.laurie_mart_payments.fct_payments_rides_v2`
GROUP BY 1,2
ORDER BY 1,2 
```
We can do further investigation on the one row where it's still missing. Also confirmed that no new tests fail on models downstream of this change.
_Document any actions that must be taken post-merge to …
> Add incomplete variable fares to device transaction types so they willl appear in payments rides

- .github/CODEOWNERS
With the data services contract winding down it seems timely to remove `@charlie-costanzo` from `codeowners`.
> remove @charlie-costanzo from codeowners

- packages/calitp-data-analysis/calitp_data_analysis/calitp_color_palette.py
- packages/calitp-data-analysis/calitp_data_analysis/geography_utils.py
- packages/calitp-data-analysis/calitp_data_analysis/styleguide.py
- packages/calitp-data-analysis/calitp_data_analysis/utils.py
- packages/calitp-data-analysis/poetry.lock
- packages/calitp-data-analysis/pyproject.toml
* We are moving some of the `shared_utils` scripts to `data-infra` so we can use them across different repos. 
Resolves [#870](https://github.com/cal-itp/data-analyses/issues/870)
- [x ] New feature
> Updated calitp-data-analysis

- warehouse/macros/littlepay_staging_transforms.sql
- warehouse/models/staging/payments/littlepay/_littlepay.yml
- warehouse/models/staging/payments/littlepay/stg_littlepay__authorisations.sql
Per feedback from @SorenSpicknall, removes the overly aggressive file-deduping from authorisations staging model and refactors `_key` column accordingly.
Compared against prod table to confirm that this restores legitimate unique rows.
> Payments: Remove over-aggressive file deduping

- airflow/dags/create_external_tables/payments/littlepay/settlements.yml
Adds 6 new columns to the Payments settlements external table to facilitate future work deduping & settlements.
Five of the columns are specific to Anaheim because they have a new data schema from Littlepay:
- `record_updated_timestamp_utc`
- `acquirer_response_rrn`
- `settlement_status`
- `request_created_timestamp_utc`
- `response_created_timestamp_utc`
And one is a column that we just missed before:
- `settlement_type`
Confirmed new columns are available in staging after running the updated DAG task locally:
```sql
SELECT *
FROM `cal-itp-data-infra-staging.external_littlepay.settlements`
WHERE participant_id = 'atn'
``` …
> Payments settlements: add missing columns for Anaheim and all agencies

- warehouse/models/mart/transit_database/_mart_transit_database.yml
This column is not included in the SQL and should be looked up via a bridge table anyways. This is resulting in an error when synching metabase.
It was not. See https://github.com/cal-itp/data-infra/issues/3004
> Remove Caltrans District from transit data quality issues table

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_funding_programs.yml
Fixes #3003 and fixes the data type issues that were still present in  `external_airtable_california_transit_funding_programs`. Arrays need to use the `mode: REPEATED`, so use this for all array columns.
Evan tested on local Airflow and it succeeded 
> Fix data type in transit funding programs schema

- warehouse/models/mart/payments/_payments.yml
- warehouse/models/mart/payments/fct_payments_rides_v2.sql
As requested by HTA, an organization that operates multiple transit 'agencies', we are pulling in agency-related columns `agency_id` and `agency_name` to `fct_payments_rides_v2` so that they can distinguish agency information among rides.
Part of #2976 
locally in dbt
> Add agency information to fct_payments_rides_v2

- warehouse/models/staging/payments/littlepay/stg_littlepay__settlements.sql
At midnight UTC on 10/10-10/11, one specific settlement record seems to have had a duplicate created. There are two rows that are totally identical except for `settlement_requested_date_time_utc`, which differ by 12 seconds (one just before midnight, the other just after). It seems clear that these are just accidental duplicates and it seems safe to suppress the earlier update. 
Resolves #3010 
```
laurie ~/git/data-infra/warehouse [fix-failing-settlements-test] $ poetry run dbt build -s stg_littlepay__settlements
Trying to find and use a …
```
> Suppress duplicate row that is causing settlements test to fail

- warehouse/models/mart/payments/fct_payments_rides_v2.sql
PR #3008 included an incorrect join on `feed_key` in `fct_payments_rides_v2` when looking to pull in the `agency_name` field, resulting in duplicate rows and failing tests. This PR resolves that.
Resolves: #3015 
Fixes CAL-ITP-DATA-INFRA-26PC
locally with `dbt run` and `dbt test`
> Payments: fix join on feed_key for agency_name in fct_payments_ride_v2

- warehouse/models/docs/_docs_littlepay.md
- warehouse/models/intermediate/payments/_int_payments.yml
- warehouse/models/intermediate/payments/int_payments__settlements_summarized.sql
- warehouse/models/staging/payments/littlepay/_littlepay.yml
- warehouse/models/staging/payments/littlepay/stg_littlepay__settlements.sql
More progress towards #2958 by summarizing settlements data to the aggregation/retrieval reference number level. 
```
laurie ~/git/data-infra/warehouse [intermediate-settlements] $ poetry run dbt build -s +int_payments__settlements_summarized 
19:17:15  Running with dbt=1.5.1
19:17:16  Unable to do partial parsing because profile has changed
19:17:30  Found 329 models, 898 tests, 0 snapshots, 0 analyses, 846 macros, 0 operations, 8 seed files, 126 sources, 4 exposures, 0 …
```
> Payments: Intermediate settlements model

- warehouse/models/staging/payments/littlepay/stg_littlepay__customer_funding_source.sql
- warehouse/models/staging/payments/littlepay/stg_littlepay__device_transaction_purchases.sql
- warehouse/models/staging/payments/littlepay/stg_littlepay__device_transactions.sql
- warehouse/models/staging/payments/littlepay/stg_littlepay__micropayment_device_transactions.sql
Fully resolves Sentry issue [72530](https://sentry.calitp.org/organizations/sentry/issues/72530/), and partially resolves [71485](https://sentry.calitp.org/organizations/sentry/issues/71485/) and [71486](https://sentry.calitp.org/organizations/sentry/issues/71486/). A customer record in `customer_funding_source` data, one with very little activity (appears to have been used for testing), was associated with multiple instances. This PR suppresses rows related to one of those instances, which didn't see any micropayment activity for that customer record and therefore doesn't map to other resources anyways, resolving several dbt test violations.
Since this appears to a be a one-off situation stemming from a data quality or testing issue, I took the single-row suppression approach that we …
> Suppress Bad Littlepay Customer Funding Source Row

- warehouse/seeds/_seeds.yml
In #3024, we intentionally add rows to the seed `payments_gtfs_datasets` without `littlepay_participant_id` to include all Elavon `customer_name`s. However, we we didn't remove the `not null` test. This PR removes the test.
locally with `dbt test`
> remove not null test from littlepay_participant_id in payments seed

- warehouse/models/mart/payments/_payments.yml
- warehouse/models/mart/payments/fct_elavon__transactions.sql
- warehouse/models/mart/payments/fct_payments_aggregations.sql
Working with the Elavon & LP aggregations data in Metabase, it seems like having a common date column would be helpful to standardize. This PR just extracts a common "end of month" date that can be used across data types.  
```
laurie ~/git/data-infra/warehouse [add-elavon-eom-date] $ poetry run dbt build -s fct_payments_aggregations fct_elavon__transactions
14:02:55  Running with dbt=1.5.1
14:02:56  Unable to do partial parsing because profile has changed
14:03:09  Found …
```
> Payments: Add end of month date columns

- warehouse/models/mart/payments/_payments.yml
dbt Airflow job failed today because of mismatched column names between YAML and `fct_payments_aggregations`. This PR fixes the mismatches.
Not aware of an easy way to test the Metabase docs sync locally; safe to merge and then confirm fix in prod tomorrow I think
```
laurie ~/git/data-infra/warehouse [fix-nominal-amt-col-name] $ poetry run dbt build -s fct_payments_aggregations
16:30:58  Running with dbt=1.5.1
16:31:01  Found 331 models, 907 tests, 0 …
```
> Fix payments aggregation column names in YAML

- warehouse/models/intermediate/payments/_int_payments.yml
- warehouse/models/mart/payments/_payments.yml
This PR:
* Changes a foreign key test that pointed from mart settlements to intermediate settlements to point from mart settlements to mart aggregations, which should be logically equivalent. Foreign key test pointing from mart to intermediate causes dbt Metabase sync to fail because intermediate table is not available in Metabase. 
* Adds an exception to authorisations test for an authorisation from 2021 that only has one update with a null status. Since it's so old and there are no other cases we are comfortable excluding it from the test. 
Fixes CAL-ITP-DATA-INFRA-26T9 ([x](https://sentry.calitp.org/organizations/sentry/issues/73029/?project=2))
Fixes …
> Fix two problematic Payments model tests

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_fare_systems.yml
This PR updates the `fare_systems` external table with new columns that have been added to the table's schema in Airtable and changes the type of existing columns that were change from strings to multi-select in Airtable to be JSON typed in the external table. This will stop a `dbt ModelError` that has been causing the daily dbt job to fail. 
Resolves #3063
Ran the updated external table locally pointed at prod data bucket (so that it sees the current schemas for the exported data)
Then ran the downstream data models.
```
laurie ~/git/data-infra/warehouse [fare-systems-reduced-fare-category-column-type] $ poetry run dbt …
```
> Fare systems: Update columns & types

- warehouse/models/mart/payments/_payments.yml
- warehouse/models/mart/payments/fct_payments_rides_v2.sql
Adds `aggregation_id` to `fct_payments_rides_v2` per request
Resolves #3076
*The tests failing here are already failing in prod and under separate investigation / are not caused by the changes in this PR*
```
laurie ~/git/data-infra/warehouse [add-aggregation-id] $ poetry run dbt build -s fct_payments_rides_v2                                    
20:05:15  Running with dbt=1.5.1
20:05:18  Found 338 models, 918 tests, 0 snapshots, 0 analyses, 847 macros, 0 operations, 8 …
```
> Add aggregation ID to fct payments rides

- warehouse/models/mart/payments/_payments.yml
- warehouse/models/mart/payments/fct_payments_rides_v2.sql
This PR addresses an outstanding bug with the same root cause as #647. Rows that were specifically being dropped from `int_littlepay__cleaned_micropayment_device_transactions` were not actually being dropped from `fct_payments_rides_v2` because of the order in which the joins are performed. This PR also adjusts the relevant tests accordingly so that we won't have any failures. 
The remaining rows identified in #3038 are caused by upstream data issues from the raw data which have been spun out into new issues #3085 and #3086. Also identified one more data issue to be written up shortly after which we can make a full uniqueness test for the `littlepay_transaction_id` (i.e., …
> Fix missing Littlepay transaction ids

- .github/workflows/deploy-apps-maps.yml
- .github/workflows/publish-docs.yml
- images/jupyter-singleuser/Dockerfile
- warehouse/Dockerfile
- warehouse/Dockerfile.local
When [Netlify CLI 17.2.0 ](https://github.com/netlify/cli/releases/tag/v17.2.0) released, we began seeing an as-of-yet undiagnosed error in our warehouse image build runs. This PR pins our version to 17.1.0 across the board in order to keep these CI runs passing while we investigate. A new Issue will be opened for a longer-term resolution that allows us to hopefully unpin the version that's currently causing us problems.
Previous CI runs using this version of `netlify-cli` were successful
Create follow-up Issue for a fuller investigation and longer-term resolution to the underlying issue.
> HOTFIX: Pin version of Netlify CLI used in docs publication

- runbooks/workflow/payments/add_agency_dashboard_data_source.md
This documentation addresses two workflows:
- Add a New Agency Data Source to Metabase and Create Permissions
- Create a New Agency Dashboard and the Comprising Questions
Resolves #2981 and #2982
> Payments documentation: Adding new agencies to Metabase

- .github/workflows/deploy-apps-maps.yml
- .github/workflows/publish-docs.yml
- images/jupyter-singleuser/Dockerfile
- warehouse/Dockerfile
- warehouse/Dockerfile.local
Undoes f47d67735322d4c577d880845b4dc896fc23c50d to use the latest patch release (17.2.1) of the `netlify-cli` npm package, which resolved the issue we experienced with the initial 17.2.0 release.
Resolves #3088
Tested on PR via CI runs
> Restore Unpinned netlify-cli Version In Deps and Dockerfiles

- images/jupyter-singleuser/Dockerfile
- warehouse/Dockerfile
- warehouse/Dockerfile.local
Following #3089, we discovered that an operator used in a dependency is [not supported](https://github.com/vercel/next.js/discussions/49923) by the version of node we were trying to use to load the `netlify-cli` package. The brings in a later version of node in order to successfully build, which also involved a move to a new install system.
The build-push action for Jupyterhub tested relevant functionality here, but a full build of everything will not take place until merging.
Monitor for regressions in prod post-merge.
> Use More Recent nodejs Version In Build Tasks

- warehouse/Dockerfile
- warehouse/Dockerfile.local
On Thursday, I made a series of changes to various Dockerfiles that have nodejs dependencies in the interest of resolving #3088. Those changes were made too casually - I tested the build for one of the Dockerfiles I was working with, but did not test the build from scratch (with `--no-cache` set) for each of them every time I made changes. This meant that the warehouse build failed when merged because the `npm` command was unrecognized immediately after the nodejs install. This resolves the issue, and has been fully tested with a cleared cache for each impacted image.
Tested locally with test builds of each modified Dockerfile. The previous state of the file would fail to build [just as it does in CI](https://github.com/cal-itp/data-infra/actions/runs/6818544770/job/18544334693), and the …
> Resolve npm command non-recognition on warehouse build

- apps/maps/package-lock.json
- apps/maps/poetry.lock
- jobs/gtfs-rt-parser-v2/poetry.lock
- warehouse/poetry.lock
Bumps a handful of minor version dependencies, responsive to dependabot alerts. This PR was created separate from the original dependabot PRs to run GitHub Actions that require elevated permissions (i.e. access to Google Secret Manager secrets). Since dependabot itself is not a contributor to the Cal-ITP organization, CI runs from the bot that require secrets access fail. Recreating the work here allows us to test with the fully functional CI/CD pipeline.
Deps examined locally for related conflicting changes, CI/CD will test builds, local builds tested where relevant
> Update minor deps that require heightened access for CI runs

- warehouse/models/intermediate/payments/int_payments__refunds_deduped.sql
I am running into issues testing #3123 because the sorting in the refunds dedupe logic is not deterministic (there are a bunch of ties on export timestamp). I'd like to make the sorting deterministic separately in this PR so I can test #3123 and more accurately assess the impact of logic changes being introduced there (i.e., it's hard to compare staging and prod right now because there is this nondeterministic sorting that introduces variation that is not actually meaningful. By making this sorting deterministic, I can compare between staging and prod and know that the differences are due to actual logic differences as opposed to just sorting ties.)  …
> Add line number to refunds dedupe sorting to make it deterministic

- airflow/dags/create_external_tables/payments/littlepay/settlements.yml
Adds the new `refund_id` field to the external settlements table. Larger changes deferred to #3150. 
Other new fields were already added in #2992
(Want to make this change in one PR and get it merged so subsequent modeling updates can be tested using the production external tables.)
Progress towards #3073. 
Ran it in local Airflow, confirmed data is queryable in BQ:
```sql
SELECT * 
FROM `cal-itp-data-infra-staging.external_littlepay.settlements`
WHERE refund_id != ""
```
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some …
> Add new refund ID field to external table

- warehouse/models/docs/_docs_littlepay.md
- warehouse/models/intermediate/payments/_int_payments.yml
- warehouse/models/intermediate/payments/int_payments__settlements_to_aggregations.sql
- warehouse/models/mart/payments/_payments.yml
- warehouse/models/mart/payments/elavon_littlepay__transaction_reconciliation.sql
- warehouse/models/mart/payments/fct_payments_aggregations.sql
- warehouse/models/mart/payments/fct_payments_settlements.sql
- warehouse/models/staging/payments/littlepay/_littlepay.yml
- warehouse/models/staging/payments/littlepay/stg_littlepay__settlements.sql
Handles Littlepay settlements schema updates.
Resolves #3073 
`poetry run dbt build -s +fct_payments_aggregations` passes. 
The following query's results look reasonable; there are no refunds since the schema change so can't test that part yet. 
```sql
SELECT aggregation_is_settled,credit_is_settled,debit_is_settled, COUNT(*)
FROM `cal-itp-data-infra-staging.laurie_mart_payments.fct_payments_aggregations`
GROUP BY 1,2,3
```
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will …
> Settlements schema updates

- airflow/dags/create_external_tables/amplitude/benefits_events.yml
Previously, the Amplitude Data Destination was pulling data from Benefit's _Test environment application_ into Google Cloud Storage, and this _Test environment data_ was being processed via Airflow, and getting cleaned, transformed and ultimately sent to Metabase. But we need Production data, not Test data.
Last week, we updated the Amplitude Data Destination to send data from Benefit's **Production** environment application into Google Cloud Storage, and we started and completed a data backfill job to get all data from August 2022 from Production into this same bucket. The previous Test site data was saved in a folder called `304109/ `, while this new Production data now goes into a new folder called `304110/ `:
This pull request changes the Airflow DAG to pull data from this _new …
> fix(amplitude): change folder from test app to production app

- kubernetes/apps/charts/sentry/values.yaml
- runbooks/workflow/disk-space.md
A Grafana alert has been consistently firing as of late about one of Sentry's storage volumes hovering around 80% utilization. Investigating this I found that this was _not_ to do with Zookeeper which [routinely needs old log/snapshot data purged](https://github.com/cal-itp/data-infra/blob/main/runbooks/workflow/disk-space.md), but rather was an issue with Clickhouse's data volume which stores Sentry's events legitimately growing over time. Reducing disk usage here would require actually deleting some of Sentry's event history. Given the long time period covered by the initially-provisioned 30Gi of data storage (the [upstream default](https://github.com/sentry-kubernetes/charts/blob/20.0.0/sentry/values.yaml#L990) for the Helm chart we use to deploy Sentry) and relative cost of storage, I …
> fix(k8s): increase Sentry Clickhouse storage to 50Gi

- warehouse/models/docs/_docs_littlepay.md
- warehouse/models/staging/payments/littlepay/stg_littlepay__settlements.sql
Resolves #3186
`poetry run dbt run -s stg_littlepay__settlements+` and `poetry run dbt test -s stg_littlepay__settlements+` passes
> Backfill CCJPA settlement status

- warehouse/models/mart/ntd_validation/fct_ntd_rr20_service_checks.py
Solves breaking dbt model that errors on finding a null value as a denominator. I had put this fix in the [ntd-modernization repo](https://github.com/cal-itp/ntd-modernization/blob/main/validation_tool/rr20_service_check.py#L261-L263) (which is where we developed these functions and have them as standalone Python scripts) but forgot to carry that over here. 
Succeeded locally.
> replace nas with 0

- warehouse/models/staging/payments/littlepay/stg_littlepay__settlements.sql
After receiving the revised data feed from Littlepay and performing a manual backfill, we've discovered several Littlepay `aggregation_id`s for the month of November that are incorrectly attributed as `settlement_status = SETTLED`, when they should be `= REJECTED`.
This PR expands the aggregations manually identified as `REJECTED` for the month of October resolved in #3187 (and described in #3186) to include four more from the month of November.
Resolves #3193
poetry run dbt run -s stg_littlepay__settlements+ and poetry run dbt test -s stg_littlepay__settlements+ passes
> expand aggregations where `settlement_status` should be `REJECTED`

- warehouse/models/staging/audit/stg_audit__cloudaudit_googleapis_com_data_access.sql
Google recently rolled out several new top-level columns and nested fields in the data access audit log that drives our `stg_audit__cloudaudit_googleapis_com_data_access` model. Because we use a `UNION ALL` to process older data up to a 90-day threshold, this caused failures stacking query results on top of each other.
This PR resolves the issue by specifying a set of columns and fields to bring in that satisfy the desired outcomes for the resulting fact table. It will also be able to be fully undone 90 days after the audit log changes were made by Google (~February 2024), allowing us to return to a simpler `SELECT *` approach because the schemas of older logs under consideration by the union will be consistent with newer logs at that point.
Resolves #3179 
Tested with local dbt runs on …
> Align schemas between old and new cloudaudit data access logs

- .github/workflows/build-calitp-data-analysis.yml
- .github/workflows/build-calitp-data-infra.yml
- .github/workflows/build-warehouse-image.yml
- .github/workflows/deploy-airflow.yml
- .github/workflows/lint.yml
- .github/workflows/publish-docs.yml
- .github/workflows/sentry-release.yml
- .github/workflows/service-release-channel.yml
- .github/workflows/service-release-diff.yml
- .github/workflows/terraform-deploy.yml
- .github/workflows/terraform-report.yml
Resolves #3203 by upgrading the `google-github-actions/setup-gcloud` Action to use a supported version, which also required adding the `google-github-actions/auth` action since the current version of `setup-gcloud` cleaves away authentication.
Additionally, moves our linting step back to use Python 3.11.7 instead of 3.12 due to [PEP 632](https://peps.python.org/pep-0632/) impacting an underlying tool that we don't have direct control over.
Many of the relevant workflows were tested automatically within this PR. Changes made in the others are identical, and those workflows have access to the same creds, so no differing behavior is expected.
> Move setup-gcloud to floating V2 release

- kubernetes/apps/charts/sentry/values.yaml
The Sentry helm chart's default configuration already adds this annotation, so including it here too results in a duplicate key and invalid YAML
I'm going to merge and deploy this right away as it is part of my work to reconcile the state of the k8s cluster and I need to push the change through the GitHub Action workflow to verify
> fix(sentry): remove duplicate annotation

- airflow/plugins/operators/airtable_to_gcs.py
- airflow/requirements.txt
As described in #2187, Airtable is deprecating API Keys for Personal Access Tokens at the end of this month (January 2024). This PR:
* Updates the python client that we use for the Airtable API (`pyAirtable`) from `v1.0` to `v2.2.1`
* Migrate to new syntax used in updated `pyAirtable API`
Resolves #2187 
Tested using prod PAT and secrets manager
> Switch Airtable fetch to use PAT instead of API Key

- airflow/requirements.txt
When we upgraded to use pyairtable V2 in our Composer PyPI package list for auth reasons, it introduced a dependency conflict: pyairtable has a version-unbounded pydantic requirement that in turn brings in typing-extensions. Because the pydantic version being fetched relied on a newer version of typing-extensions than the one that comes with our Composer-Airflow instance (which we can't modify), we need to pin the pydantic version imported in Composer to avoid the conflict. I used 1.9, which is used elsewhere in `data-infra`.
Merging this PR will also conveniently allow us to test some additional current behavior related to #3215 - does the Action fail to run when a new _package_ is added to the requirements list, or just when the package version numbers are changed?
Tested via rollout on …
> Add pydantic 1.9 to Composer PyPI Packages

- .github/workflows/deploy-airflow.yml
It appears that changes to /airflow/requirements.txt weren't making their way to Composer's PyPI package list automatically because `deploy-airflow.yml` used an incorrect rule formulation to detect relevant merges to main. This should resolve the issue.
Resolves #3215
This can't be fully tested until merge. Upon merge, the `changed-requirements` task in the Airflow deployment CI workflow should fire, and then the next task should be skipped because the requirements list isn't changed by this PR. Seeing the first task fire will be enough to determine that the deployment bug has been fixed.
Monitor the CI run upon merge to ensure behavior is as expected.
> Update criteria used to deploy package list changes to Composer

- ci/channels/prod.yaml
- ci/tasks.py
Resolves issue with Sentry's postgresql version override stubbornly persisting by preventing previously applied value overrides persisted by Helm from being brought forward automatically into new releases. This also necessitates activating the sensitive values file for Sentry to replace bringing the existing PostgreSQL user password forward
> Reset helm values

- warehouse/scripts/publish.py
As described in #3182, when trying to upload data to the open data portal (CKAN), if one file fails (specifically, stop times tends to fail because of its size), then the subsequent files (in alphabetical order) are not even attempted.
This PR adds exception handling to `warehouse/scripts/publish.py` so that if one file upload fails the others are attemped.
Resolves #3182 
Will have to test in prod as this is an error generated by Caltrans servers
> add exception handling to ckan upload script

- warehouse/macros/create_row_access_policy.sql
- warehouse/models/mart/payments/fct_payments_adjustment_transactions.sql
- warehouse/models/mart/payments/fct_payments_aggregations.sql
- warehouse/models/mart/payments/fct_payments_billing_transactions.sql
- warehouse/models/mart/payments/fct_payments_chargeback_transactions.sql
- warehouse/models/mart/payments/fct_payments_deposit_transactions.sql
- warehouse/models/mart/payments/fct_payments_rides_v2.sql
- warehouse/models/mart/payments/fct_payments_settlements.sql
- warehouse/models/mart/payments/reliability/v2_payments_reliability_weekly_unlabeled_routes.sql
In order to expose Elavon-related data in Metabase for use in agency-specific dashboards and by agencies, we need to implement a row-access policy similar to what we previously implemented for Littlepay data. This PR accomplishes that by creating a new macro called `payments_elavon_row_access_policy` and adding it to the tables that consume Elavon data which will be exposed in Metabase (`fct_payments_deposit_transactions`, `fct_payments_chargeback_transactions`, `fct_payments_billing_transactions`, `fct_payments_adjustment_transactions`)
Note: This row access policy groups broadly by organization, so that all of their their sub-Elavon `customer_name`s are included in the filter (ex `Humboldt Transit Authority` includes `HTA TAP TO PAY`, `HTA OFFICE SALES`, `HTA PARATRANSIT`, `HTA …
> Add row access policy for Elavon data

- jobs/gtfs-schedule-validator/README.md
Following up on #3152, updates the upgrade documentation for the GTFS validator version we use internally to use that PR as an example of the upgrade steps necessary to take in code. This replaces some links to specific commits on an older, messier PR.
New docs and their links tested and linted successfully.
> Update Validator Upgrade Instructions with New Example PR

- docs/analytics_tools/jupyterhub.md
- docs/requirements.txt
Adds instructions for resizing JupyterHub instance storage to the general JupyterHub docs, next to existing instructions for increasing a user's query limit. This is a follow-up to the issue coming up [here](https://cal-itp.slack.com/archives/C015B2EBHU0/p1704394556368449) - it was resolved live in Slack at that time, but this gives the resolution process a permanent home.
Resolves #3235
Docs linted locally and in CI, and process tested for existing JupyterHub users.
> Document JupyterHub Storage Increase Process

- warehouse/models/intermediate/gtfs/int_gtfs_schedule__frequencies_stop_times.sql
In today's transform_warehouse DAG run, the dbt_run_and_upload_artifacts task tripped up on the `int_gtfs_schedule__frequencies_stop_times` model because two `headway_secs` values of 0 came in from an LAX FlyAway `frequencies.txt`, violating a GTFS standard rule that all such values need to be positive integers. This broke some array creation code.
This fix ignores `dim_frequencies` rows with improper 0-value headways when making the `frequencies_stop_times` model. No valid data will be ignored by the fix, since none of the impacted rows are compliant with the GTFS spec.
Model built and tested in the staging warehouse environment.
After merging, I'll clear and rerun today's transform_warehouse DAG run.
> Ignore frequency rows with 0-value headways in frequencies_stop_times

- .github/ISSUE_TEMPLATE/new-team-member.md
- CONTRIBUTING.md
- airflow/dags/dags.py
- docs/airflow/dags-maintenance.md
- docs/transit_database/transitdatabase.md
- runbooks/workflow/disk-space.md
In late 2023, several Cal-ITP Slack channels were renamed as part of a Slack reorganization effort. This PR updates some channel references in docs and in code comments, and also cleans up a couple older channel name typos (and one instance where the `data-infra` _repo_ was inadvertently referenced with a hashtag on the front as if it was a Slack channel.
Note that this PR focuses on Slack channels within the orbit of the Data Services team, so it's possible that references to Caltrans internal channels that I do not have access to may remain in need of changes.
Resolves #3167
Docs linted successfully locally
> Update outdated Slack channel references in repo

- kubernetes/apps/charts/jupyterhub/values.yaml
Following up on #3265 now that the new `jupyter-singleuser` image is merged and published, this changes the version of that image automatically brought in by our JupyterHub chart for notebooks.calitp.org.
This will be tested upon rollout, and can be rolled back if needed. The changes to the image itself were tested in the previous PR.
Monitor rollout to ensure no breakages of people's workflows.
> Update jupyter-singleuser version referenced in JupyterHub chart

- kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
- kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml
- services/gtfs-rt-archiver-v3/poetry.lock
- services/gtfs-rt-archiver-v3/pyproject.toml
This PR, when merged, will publish a new version of the image underlying the RT archiver to make use of the latest version of the `calitp-data-infra` Python package. Changes to the archiver itself are applied by hand using `kubectl`, as a safety mechanism.
Code pathways were inspected by hand for any impacts from the change to `google-cloud-secret-manager` function calls that were implemented as part of the most recent `calitp-data-infra` release. The image was built successfully locally, and will be test-built by the PR CI, as well.
Archiver service changes are made by hand using `kubectl`. After merge, I'll attempt to make the relevant change to the test Archiver. Then, if successful, we'll roll out the same change to the prod archiver in the morning.
> Publish RT Archiver Images That Uses New calitp-data-infra Version

- airflow/dags/transform_warehouse/METADATA.yml
Littlepay recently updated the cadence of their data publishing to better support our analytics needs, but in doing so threw the cadence of our payments ingest/parse/transform jobs out of sync. This PR pushes the running of the `transform_warehouse` DAG back 4 hours (14:00 UTC).
A follow-up ticket will be created to break apart our `transform_warehouse` DAG runs so that all other models are run earlier in the morning (as they were previously), and payments is run at 14:00 UTC.
docker image builds locally
> transform_warehouse DAG to run after new Littlepay publishing time

- airflow/dags/sync_elavon/elavon_to_gcs_raw.py
This moves a function call to `get_secret_by_name()` out of the top level of the `sync_elavon` DAG's Python code, where it was getting run regularly as Airflow parsed each DAG. The previous behavior was fine in prod, but stymied local developers who lacked permissions on the Google Secret Manager secret being fetched by that function call, preventing the DAG from loading correctly. This solution has the added advantage of reducing the number of API calls to Google Secret Manager, since this function won't be run under the hood by Airflow anymore.
Resolves #3289 
Tested function of the new code placement via local Airflow
> Move Elavon Secret Fetch Away from Top Level of Raw Sync DAG

- .github/workflows/lint.yml
Resolves #3184 now that dbt-core officially supports Python 3.12 as of [v1.79.0](https://github.com/dbt-labs/dbt-core/releases/tag/v1.7.9).
As described in the initial Issue description, we take slightly different approaches to managing Python version deps in different places, including in other CI tasks. This PR solves the Issue as planned, but we should likely more broadly scope a "standard" approach (or set of approaches) to version management across the `data-infra` ecosystem of images, services, and tasks sometime in the future.
Linting tested locally, and CI task tested on the PR during draft phase.
> Unpin Python version used by lint Action now that dbt-core supports 3.12

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_monthly_route_service_by_timeofday.sql
Add all the columns, `source_record_id`, all route columns, `day_type`, and `time_of_day` into generating the key. 
Resolves #3301 
* Create table: `poetry run dbt run -s fct_monthly_route_service_by_timeofday`
* Test table for uniqueness `poetry run dbt test -s fct_monthly_route_service_by_timeofday`
> Fix primary key for `fct_monthly_route_service_by_timeofday` 

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_vehicle_locations.sql
We recently encountered an issue in which a time zone change in a schedule feed caused semi-duplicate entries to appear in our raw GTFS-RT data, which mapped to true duplicate keys using our current key generation logic in models like `fct_vehicle_positions_trip_summaries` and prevented runs of the `fct_vehicle_locations` model. That issue is described in more detail in #3299.
We cannot change the behavior of raw incoming data, so this requires a workaround in modeling. Initially I believed that it might be possible to solve relatively early in the modeling process by choosing the incoming rows with the "correct" updated time zone, but implementing logic to do so would rely on too much guesswork about how the related data is being generated and sent by feed providers to arrive at a …
> Fuzzy Key Uniqueness Threshold for fct_vehicle_locations

- .github/workflows/lint.yml
We use a source code spell checker to audit our `/docs` folder during each run of our linting CI task. Its most recent release, v1.20, introduced a false positive on variations of the "png" file extension, causing failed CI runs like [this one](https://github.com/cal-itp/data-infra/actions/runs/8514299791/job/23319759609). An Issue is open on the typos repository [here](https://github.com/crate-ci/typos/issues/967), but in the meantime we should revert to the previous version until a fix is out.
Will test live in CI, since this impacts the linting GitHub Action
Unpin once the open issue about this problem on the typos repository is resolved in a new release.
> Temporarily pin crate-ci/typos to avoid broken alerting on "png"

- airflow/dags/copy_prod_archiver_configs_to_test/METADATA.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/METADATA.yml
In #2626 and #3110, we created two weekly DAGs whose dynamic values for `start_date` tripped up scheduler expectations for the data interval. Setting `start_date` dynamically [is not generally recommended](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#what-s-the-deal-with-start-date), but we've historically used the !days_ago setting in a few daily DAGs. The typical !days_ago configuration we used for daily DAGs don't work the same way for weekly DAGs.
This PR sets an explicit `start_date` for the two impacted DAGs, which have failed to start since they were first merged because their data interval and start date were misaligned (you can read more about the "why" in [this blog post](https://whigy.medium.com/why-my-scheduled-dag-does-not-run-9e2811b5030b)). Once merged, we …
> Designate a real start_date for two weekly DAGs that previously used unworkable dynamic values

- airflow/README.md
- airflow/dags/create_external_tables/airtable/external_airtable_transit_data_quality_issues_services.yml
- airflow/requirements.txt
Changes the packages of requirements.txt for the airflow and changes the schema of external_airtable_transit_data_quality_issues_services.yml.  This allows us to handle column names from airtable that might start with a number.
Resolves #3283 (again)
Needed to run these commands:
```
docker-compose down --rmi all
docker build . --no-cache
docker-compose run airflow tasks test airtable_loader_v2 transit_data_quality_issues_services
docker-compose run airflow tasks test create_external_tables external_airtable_transit_data_quality_issues_services
```
Afterwards this table:
`SELECT * FROM `cal-itp-data-infra-staging.external_airtable.transit_data_quality_issues__services` LIMIT 1000`
Goes from having 5 columns to all the columns from the airtable including `_2021_ntd_id__from_provider_`
Also …
> Test calitp-data-infra package changes with Airflow

- warehouse/models/mart/benefits/fct_benefits_events.sql
Follow up to #3325 / #3329.
`json_extract_column` normalizes the JSON structure and flattens to columns named with underscores. There was a bug in how some of these JSON extracted columns were being selected.
Fixes DAG failure for this job, see e.g. https://b2062ffca77d44a28b4e05f8f5bf4996-dot-us-west2.composer.googleusercontent.com/log?execution_date=2024-04-25T14%3A00%3A00%2B00%3A00&task_id=dbt_run_and_upload_artifacts&dag_id=transform_warehouse&map_index=-1
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental …
> Fix: correct column names in Benefits backfill CTE

- airflow/dags/create_external_tables/ntd_data_products/monthly_ridership_with_adjustments_voms.yml
- airflow/dags/create_external_tables/ntd_data_products/monthly_ridership_with_adjustments_vrh.yml
- airflow/dags/create_external_tables/ntd_data_products/monthly_ridership_with_adjustments_vrm.yml
- warehouse/models/intermediate/ntd/int_ntd.yml
- warehouse/models/intermediate/ntd/int_ntd__monthly_ridership_with_adjustments_joined.sql
- warehouse/models/intermediate/ntd/int_ntd__monthly_ridership_with_adjustments_upt.sql
- warehouse/models/intermediate/ntd/int_ntd__monthly_ridership_with_adjustments_voms.sql
- warehouse/models/intermediate/ntd/int_ntd__monthly_ridership_with_adjustments_vrh.sql
- warehouse/models/intermediate/ntd/int_ntd__monthly_ridership_with_adjustments_vrm.sql
- warehouse/models/mart/ntd/_mart_ntd.yml
- warehouse/models/mart/ntd/dim_monthly_ntd_ridership_with_adjustments.sql
- warehouse/models/mart/ntd/dim_monthly_ntd_ridership_with_adjustments_upt.sql
- warehouse/models/staging/ntd/_src.yml
- warehouse/models/staging/ntd/_stg_ntd.yml
- warehouse/models/staging/ntd/stg_ntd__monthly_ridership_with_adjustments_voms.sql
- warehouse/models/staging/ntd/stg_ntd__monthly_ridership_with_adjustments_vrh.sql
- warehouse/models/staging/ntd/stg_ntd__monthly_ridership_with_adjustments_vrm.sql
1. Cleans up some of the column names in upt, taking them from floats to strings
2.  Copies these changes to vrm, vrh, and voms
3.  Joins all this data in an intermediate table then pulls from a final ridership table
4. Adds a little bit of documentation for these fields
Continues work on #3164
`poetry run dbt run -s +dim_monthly_ntd_ridership_with_adjustments --full-refresh`
```
SELECT * FROM `cal-itp-data-infra-staging.vb_mart_ntd.dim_monthly_ntd_ridership_with_adjustments` 
where upt is null
```
Returns no data, so all the joins worked correctly.
> Enhance ridership data - add vrm, vrh, and upt columns

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- .sqlfluff
- .sqlfluffignore
- airflow/dags/create_external_tables/ntd_data_products/annual_database_service.yml
- script/scrape_ntd.py
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__feed_aggregator.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__include_tts.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__lead_time.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__no_expired_services.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__passes_fares_validator.sql
- warehouse/models/intermediate/payments/int_payments__latest_authorisations_by_aggregation.sql
- warehouse/tests/mart/gtfs/validate_fct_daily_tables.sql
Resolves #3343
Updates sqlfluff to deal with a new issue.  I think this all started because dbt-bigquery in the pre-commit was not pinned down, it updated and then caused a some python errors related to the new version of dbt.  If I tested with a much older version of dbt-bigquery (1.2.1), I get a different error.  Thus my approach was to pin down sqlfluff to the newest version which fixes the error.
Consequently sqlfluff added some new rules:
- I updated the configuration to use the file and not command line
- ignored some rules that didn't seem helpful
- Did some minor lint fixes to our sql codebase
`pre-commit run --all-files --verbose sqlfluff-lint`
`poetry run dbt run` from local.
Also pushing this to github on this branch and seeing the PR pass.
> Updates sqlfluff version, minor linting fixes, and updates github CI caching

- images/jupyter-singleuser/Dockerfile
Should fix a necessary [follow-up step](https://z2jh.jupyter.org/en/stable/administrator/upgrading/index.html#custom-docker-images-jupyterhub-version-match) to our JupyterHub upgrade, as evidenced by notebooks complaining during startup:
YOLO
> Upgrade custom image base to :python-3.11.6

- packages/calitp-data-analysis/poetry.lock
- packages/calitp-data-analysis/pyproject.toml
Upgrades `calitp-data-analysis` Python package to Python 3.11
`python lock` worked—YOLO
> Upgrade calitp-data-analysis to Python 3.11

- .github/workflows/build-calitp-map-utils.yml
- apps/maps/README.md
We need to use Python 3.11 to build and publish updated Python libraries
> Upgrade python publish workflows

- packages/calitp-data-analysis/poetry.lock
- packages/calitp-data-analysis/pyproject.toml
- This is part of the upgrade from python 3.9 to python 3.11.6
- This is so when building jupyter-single-user-image, the dask packages match and everything builds.  
continues work on #3352
poetry lock
poetry install
When deployed we need to test things.
> Update dask versions in calitp-data-analysis

- airflow/.gitignore
- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_organizations.yml
- warehouse/models/intermediate/transit_database/dimensions/int_transit_database__organizations_dim.sql
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/dim_organizations.sql
- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
In a previous https://github.com/cal-itp/data-infra/pull/3364 PR a formula was used to generate ntd_id_2022, but it's better to put it in airtable.  This way joins from airtable table have this id available easily especially when one might want to join to other more recent ntd data.
Separately using a csv join ntd_id_2022 was calculated and added to the orgs table.  This also removes that calculation.
local airflow
poetry run dbt run -s +dim_organizations
> Updating ntd_id_2022 using airtable

- airflow/dags/create_external_tables/METADATA.yml
- airflow/dags/deploy_dbt_docs/METADATA.yml
- airflow/dags/download_gtfs_schedule_v2/METADATA.yml
- airflow/dags/download_gtfs_schedule_v2/email_download_failures.py
- airflow/dags/parse_and_validate_rt_v2/METADATA.yml
- airflow/dags/parse_littlepay/METADATA.yml
- airflow/dags/publish_open_data/METADATA.yml
- airflow/dags/scrape_feed_aggregators/METADATA.yml
- airflow/dags/sync_littlepay/METADATA.yml
- airflow/dags/transform_warehouse/METADATA.yml
- airflow/dags/transform_warehouse_full_refresh/METADATA.yml
- airflow/dags/unzip_and_validate_gtfs_schedule_hourly/METADATA.yml
- apps/maps/pyproject.toml
- ci/pyproject.toml
- packages/calitp-data-analysis/pyproject.toml
- packages/calitp-data-infra/pyproject.toml
> Offboarding - clean up email references

- warehouse/models/mart/ntd/_mart_ntd.yml
- warehouse/models/mart/ntd/dim_annual_ntd_agency_service.sql
- warehouse/models/mart/ntd/dim_monthly_ntd_ridership_with_adjustments.sql
Enhances NTD ridership tables to make it easier to use for analysts
Fixes #3371  and #3373
My notes on the different modes:
https://www.transit.dot.gov/ntd/ntd-data-products-frequently-asked-questions#Fixed%20Route
https://www.transit.dot.gov/ntd/national-transit-database-ntd-glossary
Motor Bus (MB), Commuter Bus (CB), Bus Rapid Transit (RB), Jitney (JT), and Publico (PB). All Rail modes and Ferry Boat (FB) are also considered fixed route services. 
Rail Modes
Transit modes whose vehicles travel along fixed rails - bars of rolled steel - forming a track. The vehicles are usually electrically propelled typically through motors onboard the vehicles, but motors may also be at a central location not onboard the vehicles to pull the vehicles by cables (cable car (CC), inclined plane (IP)). For …
> Minor ridership fixes

- warehouse/models/intermediate/ntd/int_ntd__modes.sql
- warehouse/models/mart/ntd/_mart_ntd.yml
- warehouse/models/mart/ntd/dim_annual_ntd_agency_service.sql
- warehouse/models/mart/ntd/dim_monthly_ntd_ridership_with_adjustments.sql
- warehouse/seeds/_seeds.yml
- warehouse/seeds/ntd_modes_to_full_names.csv
Adds ntd modes seed file and easy conversions from two letter ntd modes to the full name.
Makes it easier to make dashboards.
Chose not to extend [dim_modes](https://github.com/cal-itp/data-infra/blob/main/warehouse/models/mart/transit_database/dim_modes.sql) since that describes more California modes, not national modes.
Uses descriptions from https://github.com/cal-itp/data-infra/pull/3378
```
poetry run dbt seed
poetry run dbt run -s +dim_monthly_ntd_ridership_with_adjustments --full-refresh
poetry run dbt run -s +dim_annual_ntd_agency_service --full-refresh
```
> Adds ntd modes seed file and easy conversions from two letter ntd modes

- warehouse/models/staging/payments/littlepay/stg_littlepay__customer_funding_source.sql
This pull request alters the Littlepay payments staging table `stg_littlepay__customer_funding_source` table to force one value related to the `issuer_country` field for the United States.
Previously, two values existed: ‘UNITED STATES’ and ‘UNITED STATES OF AMERICA (THE)’. This PR adds SQL code to change both fields to the ‘UNITED STATES’ value.
Resolves #3392 
local `dbt run` and `dbt test`
> payments: merge United States issuer_country values in stg_littlepay__customer_funding_source

- docs/publishing/sections/2_static_files.md
- docs/publishing/sections/4_notebooks_styling.md
As part of our Summer Refactor 2024 efforts, I have been updating our docs page.
1. Updated the _static documents_ section with code that demonstrates how to convert a notebook to a PDF, link to a script that parameterizes a notebook and then turns everything to a PDF, and tips and tricks.
2. Updated the the _portfolio_ section to state that the `%%capture_parameter` cell  cannot contain even commented out code. 
3. More copyediting. Deleted extra semicolons off of headers. Made sure sample code blocks are denoted correctly.
> Portfolio Docs

- warehouse/seeds/payments_entity_mapping.csv
As requested in #3398, we updated the mapping of Elavon entities to organization names to facilitate analysis for:
- Mendocino Transit Authority/MTA DIAL A RIDE
- San Joaquin RTD/SAN JOAQUIN REGIONAL TRANSIT DIS
- Lake Transit Authority/LTA DIAL A RIDE
Resolves #3398 
local dbt run, dbt test
> Updated seed mapping of elavon payments entities to organization names

- warehouse/macros/create_row_access_policy.sql
Update payments row access polices in macro [create_row_access_policy](https://github.com/cal-itp/data-infra/blob/main/warehouse/macros/create_row_access_policy.sql) to include new GCP group: `mov-project-team@jarv.us` to facilitate querying and contributions to row access policy-protected tables (primarily [fct_payments__rides_v2](https://github.com/cal-itp/data-infra/blob/fd71594f3a59cc7fa44e2a128a45b034cfd090a7/warehouse/models/mart/payments/fct_payments_rides_v2.sql#L2) and [fct_elavon__transactions](https://github.com/cal-itp/data-infra/blob/fd71594f3a59cc7fa44e2a128a45b034cfd090a7/warehouse/models/mart/payments/fct_elavon__transactions.sql#L2))
> update payments row access policy to include new contributors

- warehouse/macros/create_row_access_policy.sql
- warehouse/models/staging/payments/elavon/_elavon.yml
- warehouse/models/staging/payments/elavon/int_elavon__adjustment_transactions.sql
- warehouse/models/staging/payments/elavon/int_elavon__chargeback_transactions.sql
This PR creates new unique intermediate tables for the two remaining batch types of Elavon transactions found in `stg_elavon__transactions` that are not yet exposed in tables
New batch types and tables:
* `A` found in new table `int_elavon__adjustment_transactions`
* `C` found in new table `int_elavon__chargeback_transactions`
the YML file for these tables have also been updated in the dbt project
This PR also adds the service account for `metabase-payments-team` to the create_row_access_policy macro to more easily facilitate access to payments tables with row access policies by payments data team members
Resolves #3411 
As some background:
we used batch types `B` and `D` when creating the `fct_elavon__transactions` table. When constructing that, we tried to incorporate these other two …
> payments: expose remaining elavon batch types and modify row access policy

- kubernetes/apps/charts/jupyterhub/values.yaml
Updates admins and increases disk size for new jupyterhub images.
Resolves #3421
YOLO (I really don't know how)
Check if default disk sizes are updated with `df -h`
Currently it looks like:
```
jovyan@jupyter-vevetron:~/data-analyses$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          95G   17G   78G  18% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G …
```
> fix(jupyterhub): updated admin and increases disk size

- docs/contribute/content_types.md
- docs/publishing/sections/5_analytics_portfolio_site.md
Simple docs edit to add reminders and links to mermaid in both the portfolio and docs contribution sections.
> add mermaid reference, link to docs:

- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_trip_updates_vehicle_positions_completeness.sql
A query for use in [reports](https://github.com/cal-itp/reports).  
Recreates:
[tu completeness](https://dashboards.calitp.org/question#eyJjb2xsZWN0aW9uX2lkIjoxNzIsImRhdGFzZXQiOmZhbHNlLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1siYWdncmVnYXRpb24tb3B0aW9ucyIsWyIqIixbIi8iLFsiY291bnQtd2hlcmUiLFsiPiIsWyJmaWVsZCIsMjU2MDYseyJqb2luLWFsaWFzIjoiRmN0IE9ic2VydmVkIFRyaXBzIn1dLDBdXSxbImNvdW50Il1dLDEwMF0seyJkaXNwbGF5LW5hbWUiOiIlIG9mIHRyaXBzIHdpdGggVFUgbWVzc2FnZXMiLCJuYW1lIjoiJSBvZiB0cmlwcyB3aXRoIFRVIG1lc3NhZ2VzIn1dXSwiYnJlYWtvdXQiOltbImZpZWxkIiw0NTEzOCx7InRlbXBvcmFsLXVuaXQiOiJkYXkifV1dLCJmaWx0ZXIiOlsiYW5kIixbInRpbWUtaW50ZXJ2YWwiLFsiZmllbGQiLDQ1MTM4LG51bGxdLC0zMCwiZGF5Iix7ImluY2x1ZGUtY3VycmVudCI6ZmFsc2V9XSxbIj0iLFsiZmllbGQiLDQ1MDk4LG51bGxdLCJBbmFoZWltIFJlc29ydCBTY2hlZHVsZSJd …
> Reports Update: Adds a query that produces gtfs rt and vp completeness

- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database_latest/dim_gtfs_datasets_latest.sql
Preventing private datasets to be published to [california_open_data](https://data.ca.gov/dataset/cal-itp-gtfs-ingest-pipeline-dataset/resource/e4ca5bd4-e9ce-40aa-a58a-3a6d78b042bd) portal .
Resolves https://github.com/cal-itp/data-infra/issues/3416
`poetry run dbt run -s +dim_gtfs_datasets_latest`
`18:55:39  Completed successfully`
`18:55:39  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5`
> Preventing private datasets to be published to california_open_data portal.

- .github/workflows/deploy-apps-maps.yml
I noticed while working on #3452 that rebasing any branch would cause this workflow to run and then deploy to a netlify preview site with the PR # missing. The issue was that the branches event runs on any branch and then the deploy preview event is only filtered to the branch not being main rather than the event being a pull request. Since that step makes use of the PR number, it doesn't make sense for it to ever run on a non-PR event as the PR number will be blank. These updates bring the triggers in line with other workflows
This PR should trigger the workflow to run since it includes a change to the workflow script which is now included in the triggers.
> fix(ci): only deploy maps app previews on relevant pull requests

- .github/workflows/build-gtfs-rt-archiver-v3-image.yml
- services/gtfs-rt-archiver-v3/README.md
The docs on how to deploy the `gtfs-rt-archiver-v3` image were out of date, and the workflow was prone to unexpectedly updating the already-deployed container image if the `pyproject.toml` version hadn't been manually updated.
For example, upon merging a dependabot PR that makes changes to `services/gtfs-rt-archiver-v3/*` and new image would get built and pushed over the already-deployed container image tag, leading production instances to start using the new version without any verification step or the designed manual new version deployment.
This change appends the short SHA to the container tag as a build number suffix, ensuring that each is build is uniquely identified and must be intentionally deployed to production. 
In a forked repo
> fix(ci): update gtfs-rt-archiver-v3 tagging and docs

- kubernetes/apps/charts/sentry/values.yaml
Redis was configured to run 3 replicas + 1 master, as this is the default for the upstream Redis chart that the Sentry chart utilizes. Newer versions of the Sentry chart than we're running right now override the default to 1 replica.
Further, by default no resource limits are applied to the Redis instances
As a result, we have 4 Redis instances running with unlimited memory which they will gradually use as much as they can over time. Our cluster is configured to autoscale between 3 and 6 nodes. The 4 redis instances would fight to eat all the memory on the 3 nodes. Eventually GCP's autoscaler would kick in and add a 4th node and move one of the Redis instances there. The fresh Redis instance we start off with low memory usage, and then the autoscaler would remove the 4th node and shove …
> fix(sentry): limit redis to 1 replica and add resource limits

- airflow/dags/sync_ntd_data_api/METADATA.yml
- airflow/dags/sync_ntd_data_xlsx/METADATA.yml
- airflow/plugins/operators/scrape_ntd_api.py
In PR #3415, the object for an extract in JSON format was incorrectly named `CSVExtract`. This PR clarifies the object created by renaming it `JSONExtract ` and improves some description
local airflow environment
> correct inaccurate NTD extract object name

- kubernetes/apps/values/metabase-test.yaml
- kubernetes/apps/values/metabase.yaml
- runbooks/workflow/upgrade-metabase.md
Metabase is currently out of date (0.48 vs v0.50) and the Slack integration surfaces a warning.
Resolves #3451
This PR was tested according to the steps documented in `runbooks/workflow/upgrade-metabase.md`
The new version will need to be rolled out to the cluster.
> Upgrade Metabase to v0.50.26.1

- airflow/dags/transform_warehouse/METADATA.yml
- airflow/dags/transform_warehouse/README.md
The transform_warehouse DAG is not running on Mondays and this PR is intended to fix the issue #3420.
Based on Airflow concept, Mondays should be running the data interval Saturday-Sunday, but since the `start_date` is configured to only One Day Ago, it does not have anything to run on Mondays because Sundays are not part of the schedule.
As @mjumbewu mentioned on the Issue and going through the problem with him, we found out that setting up a real start date would fix the problem.
There is also a previous issue that was fixed the same way: https://github.com/cal-itp/data-infra/pull/3323
For more information about the problem see the screenshot bellow that shows (on the left side) a list of dates from Mondays to Fridays, but they are actually running from Tuesdays to Saturdays as the …
> Fix transform_warehouse schedule to run on Mondays

- kubernetes/apps/charts/metabase/templates/metabase.yaml
While watching the latest Metabase update deploy, I noticed that we don't have the Metabase deployment explicitly set to use the `Recreate` strategy, allowing replicas of different versions to run at the same time under the default rolling strategy
While deploying new versions, it is lower risk to shut down all the old version instances before spinning up the first new version instance and running migrations. This will result in a longer period of Metabase not being available (low minutes) but ensure no issues are created by Metabase's config database being simultaneously written to by different versions of Metabase.
PR preview action will show applied change
> fix(k8s): use Recreate strategy to deploy updates

- warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml
- warehouse/models/mart/gtfs_quality/fct_daily_vendor_vehicle_positions_message_age_summary.sql
Resolves issue  https://github.com/cal-itp/data-infra/issues/3478
Yes,
_poetry run dbt run -s +fct_daily_vendor_vehicle_positions_message_age_summary_
`20:17:15  Finished running 12 view models, 11 table models, 1 incremental model in 0 hours 4 minutes and 39.96 seconds (279.96s).
20:17:15  
20:17:15  Completed successfully
20:17:15  
20:17:15  Done. PASS=24 WARN=0 ERROR=0 SKIP=0 TOTAL=24
`
> Creating an incremental table for vendor vehicle message age by day.

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
Adds a few columns relevant to holiday research to make sure they appear in external tables - airtable
Resolves #3487 
Nope
Rerun airtable loading, make sure everything is okay.
> fix(airtable_transit_services): add relevant fields to yml to populate them in bigquery

- warehouse/models/intermediate/ntd_validation/int_ntd_a10_facilitiesdata.sql
- warehouse/models/intermediate/ntd_validation/int_ntd_rr20_financial_fare_revenues.sql
- warehouse/models/intermediate/ntd_validation/int_ntd_rr20_financial_specific_funds.sql
- warehouse/models/intermediate/ntd_validation/int_ntd_rr20_financial_total_exp.sql
- warehouse/models/intermediate/ntd_validation/int_ntd_rr20_service_1alldata.sql
- warehouse/models/intermediate/ntd_validation/int_ntd_rr20_service_3ratios_wide.sql
- warehouse/models/intermediate/ntd_validation/int_ntd_validation.yml
- warehouse/models/mart/ntd_validation/_mart_ntd_validation.yml
- warehouse/models/mart/ntd_validation/fct_ntd_rr20_funds_checks.sql
- warehouse/models/mart/ntd_validation/fct_ntd_rr20_service_checks.sql
- warehouse/models/staging/ntd_validation/stg_ntd_2022_rr20_exp_by_mode.sql
- warehouse/models/staging/ntd_validation/stg_ntd_2022_rr20_financial.sql
- warehouse/models/staging/ntd_validation/stg_ntd_2022_rr20_service.sql
- warehouse/models/staging/ntd_validation/stg_ntd_rr20_urban_tribal.sql
Use dynamic years (`this_year` and `last_year`) instead of fixed years on models used for NTD Validation.
I am using the same logic from [fct_ntd_rr20_service_checks.sql](https://github.com/cal-itp/data-infra/blob/a6016224c15d58c6176a8c8025c9d1e9caa09e2a/warehouse/models/mart/ntd_validation/fct_ntd_rr20_service_checks.sql#L9) that was already created using those dynamic years. So the variable `this_year` is based on the date that the DAG run started and the `last_year` is just a previous year.
I also turn `int_ntd_rr20_service_1alldata` into a materialize view as requested by previous Github Warehouse report.
This change also make the models ready for use on next years without having to change it again.
Tested creating all models running locally:
```
poetry run dbt run --select …
```
> Use dynamic years instead of fixed years on models used for NTD Validation

- warehouse/models/mart/gtfs_quality/fct_daily_with_trip_vehicle_positions_message_age_summary.sql
Creating a new incremental table for with-trip vehicle position message age by day. A new Boolean column was added to the table which is TRUE if the vehicle is on a trip and FALSE if it is not on a trip.
Here is a sample of the result:
Resolves #3491
`poetry run dbt run -s fct_daily_with_trip_vehicle_positions_message_age_summary.sql`
- [x ] No action required
> Creating a new incremental table for with-trip vehicle position message age by day

- warehouse/models/intermediate/ntd_validation/int_ntd_rr20_financial_specific_funds.sql
The query for `int_ntd_rr20_financial_specific_funds` was returning blank Organizations when the previous year returns more Organizations than the current year.
It was fixed by returning the organization on the other side of the full join (last year's information) when the this year organization is blank.
It also fixes blank organizations on `fct_ntd_rr20_funds_checks`.
[#3483]
Tested locally and models properly created on staging:
* `cal-itp-data-infra-staging.erika_staging.int_ntd_rr20_financial_specific_funds`
* `cal-itp-data-infra-staging.erika_mart_ntd_validation.fct_ntd_rr20_funds_checks`
After the next `transform_warhouse` runs, confirm the Organization field has no blank records on `staging.int_ntd_rr20_financial_specific_funds` and `mart_ntd_validation.fct_ntd_rr20_funds_checks`.
> Bug Fix Display the organization name from last year if this year does not exist

- warehouse/models/mart/ntd/_mart_ntd.yml
- warehouse/models/mart/ntd/dim_annual_funding_sources.sql
This new model `dim_annual_funding_sources` details federal, state, and local funding sources for each applicable agency reporting to the NTD in Report Year 2022.
[#3405]
Tested locally using command: `poetry run dbt run --select "models/mart/ntd/dim_annual_funding_sources.sql"`
Model was generated on staging: `cal-itp-data-infra-staging.erika_mart_ntd.dim_annual_funding_sources`
Confirm the creation of `mart_ntd.dim_annual_funding_sources` on `cal-itp-data-infra` after the next `transform_warehouse` runs.
> New NTD mart table dim_annual_funding_sources

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
This should fix the dbt bug.
I think what is happening is that in June we used the column named holiday_website_status for an array, [Current] [Missing] [Off-Season], etc.  But starting a few weeks ago we made it a string (“Current Implicit Dates”., etc).
Last night I declared that `holiday_website_status` should be a string.
But dbt and our pipeline is processing data from months ago and thinking it’s a string, when it used to be an array.
Thus in airtable we changed the column name to `holiday_website_condition`.
Resolves #3487
Not really
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a …
> Fixes dbt errors around transit - services - holiday_website_status

- airflow/dags/create_external_tables/ntd_report_validation/external_table_all_ntdreports.yml
- warehouse/models/intermediate/ntd_validation/int_ntd_a30_voms_vins_totals.sql
- warehouse/models/mart/ntd_validation/fct_ntd_a30_vomscheck.sql
- warehouse/models/mart/ntd_validation/fct_ntd_rr20_service_checks.sql
This PR is a continuation of the work on #3483 to update the NTD validation models for 2024 and next years:
* Added new columns requested by Christian Suyat on external table `all_ntdreports`.
* Fixed some issues on NTD validation models:
- Division by zero error: Added new clauses on `fct_ntd_rr20_service_checks` to verify if the values are not NULL or Zero before the calculation, and fixed ROUND function to use only at the end of the calculation.
- Blank `value_checked` results: Replaced NULL values by " " (space) to make the Concatenation function to return the existing values on `fct_ntd_rr20_service_checks`, `fct_ntd_a30_vomscheck`.
- Blank Organizations: Return Organization names from last year table when the Organization does not exist in the current year on …
> Review NTD Validation models

- airflow/dags/create_external_tables/gtfs_rt_v2/rt_v2_service_alerts.yml
- warehouse/models/intermediate/gtfs/int_gtfs_rt__service_alerts_fully_unnested.sql
Bigquery can't unnest the activePeriod to int since 18446744011787391616 is too big.  Thus change the datatype to String and then safe_cast to INT.  This seems to parse correctly.
Resolves #3498 
1. Inserted the bad data in testing at the [testing bucket](https://console.cloud.google.com/storage/browser/test-calitp-gtfs-rt-parsed/service_alerts/dt%3D2024-10-09/hour%3D2024-10-09T04:00:00%2B00:00/base64_url%3DaHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L3NlcnZpY2VhbGVydHM_YWdlbmN5PVND?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=cal-itp-data-infra)
2. Tested SQL to recreate bug.
3. Updated SQL/Yamls
4. poetry run dbt run -s +fct_service_alerts_messages_unnested+ (which didn't work before with the bad data)
```
(poetry_env) VevePro:warehouse vivek$ poetry run dbt run …
```
> Changes a datatype to accommodate bad service alert data

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
This field `holiday_website__from_provider_` is causing problems with ingestion.  I don't think we need it so let's remove it to resolve the errors:
`19:36:31    Error while reading table: cal-itp-data-infra-staging.external_airtable.california_transit__services, error message: JSON parsing error in row starting at position 4758: Array specified for non-repeated field: holiday_website__from_provider_. File: gs://test-calitp-airtable/california_transit__services/dt=2024-10-15/ts=2024-10-15T17:37:25.484855+00:00/services.jsonl.gz
19:36:31    compiled Code at target/run/calitp_warehouse/models/intermediate/transit_database/dimensions/int_transit_database__services_dim.sql` …
> Remove a field that isn't parsing to resolve dbt errors

- kubernetes/apps/charts/jupyterhub/values.yaml
Changing the `values.yaml` related to JupyterHub so it can spawn up new pods as needed. [Slack discussion](https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1729016823532919) decided we'd go down to 2 zones  and 2 min nodes
Resolves 
Don't know how
> Remove outdated or incorrect users for Hub values.yaml

- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql
This PR optimizes `fct_daily_rt_feed_validation_notices` for issue #3481.
The structure of the query:
1) Get all daily feeds (a record of retrievals per URL and day)
2) For each URL/day, create a row for each error code (there are 57)
3) For each URL/day/code, aggregate the validation runs, aggregate the warning/error messages, and calculate some metrics
After pairing with @ohrite we believe the issue is the location of the CROSS JOIN, and are investigating moving the cross join out to a CTE with the daily feeds table, resulting in a query that finishes at about the 50 minute mark.
After removing the join to notices, the query finishes at the 20 minute mark. Re-adding the join to notices bumps up to just under 40 minutes. Our ongoing investigation will be into speeding up the notice …
> Optimize fct_daily_rt_feed_validation_notices

- kubernetes/apps/charts/jupyterhub/values.yaml
Defines a profiles list in order to create a new "Power User" profile with increased CPU/memory guarantees
> feat(jupyterhub): define power user profile

- kubernetes/apps/charts/jupyterhub/values.yaml
> fix(jupyterhub): correct data type of new cpu_guarantee

- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql
This PR is a second pass on optimizing fct_daily_rt_feed_validation_notices to fix issue #3481.
@ohrite and I split the query into 4 CTEs
* outcomes -> notices
* daily_feeds x codes
* daily_feed aggregate calculations per day/url
* outcome aggregate calculations per day/url
This reduced the runtime to < 1m. Since the restructure represents a fundamental change in how the data is aggregated, we are working on validating the output.
We've queried both production and staging tables, compared row values for 2023-12-28, and generated csv files for 2024-10-16, comparing both files through DIFF and had zero differences.
Used SQLFluff to check the query:
```
sqlfluff lint warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql
All Finished 📜 🎉!
```
The table was successfully …
> Add CTEs and optimize fct_daily_rt_feed_validation_notices

- warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql
Optimization done on 'fct_daily_rt_feed_validation_notices' for issue #3481 worked and DAG is passing, but I noticed errors on tests while checking the logs:
So I run tests locally and noticed we were missing one column "key":
To fix I simply added the column back and the tests passed:
Tested locally and table created on Staging:
```
❯ poetry run dbt run -s "models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql"
17:09:42  Running with dbt=1.5.1
17:09:44  Found 420 models, 949 tests, 0 snapshots, 0 analyses, 852 macros, 0 operations, 12 seed files, 175 sources, 4 exposures, 0 metrics, 0 groups
17:09:44
17:09:46  Concurrency: 8 threads (target='dev')
17:09:46
17:09:46  1 of 1 START sql table model erika_mart_gtfs_quality.fct_daily_rt_feed_validation_notices  [RUN]
17:09:55  1 of …
```
> Add missing column "key" to fct_daily_rt_feed_validation_notices

- warehouse/models/mart/benefits/_mart_benefits.yml
- warehouse/models/mart/benefits/fct_benefits_events.sql
We recently completed a big refactor of the models in Benefits, see cal-itp/benefits#1666 for more background.
The last piece of this refactor is updating our new and historic analytics events. The following PRs update the logic for generating new events:
And this PR is for the warehouse side, to handle the new fields and adjust historical data already captured in GCS.
We don't want to merge this PR until all of the above PRs are merged _and_ released to our `prod` environment.
Closes cal-itp/benefits#2247
Closes cal-itp/benefits#2248
Closes cal-itp/benefits#2249
Closes cal-itp/benefits#2390
```shell
poetry run dbt run -s +fct_benefits_events
```
```console
$ poetry run dbt run -s +fct_benefits_events
19:38:34  Running with dbt=1.5.1
19:38:35  [WARNING]: Configuration paths exist in your …
```
> Refactor: Benefits Amplitude events

- .github/pull_request_template.md
Include additional guidance on how to test changes made to dbt models.
N/A
Make announcement in change in procedure to slack.
> Update pull_request_template.md to include testing instructions for changes to dbt models

- warehouse/models/mart/benefits/fct_benefits_events.sql
~This PR is currently on top of #3515, so I could test this locally more easily. Once that PR is merged, this can be rebased on `main`.~
Follow up to #3468.
The `UNION DISTINCT` was producing strange results, e.g. combining results from different columns into the same output column.
This was due to one or both of:
1. The order of the columns not being the same between the baseline and transform CTE
2. Some columns missing from the transform CTE
This PR alphabetizes the fields in both `SELECT` statements, and ensures that the transform `SELECTS` all fields from the baseline CTE.
A minor side effect of this cleanup was to remove the transform CTE in favor of a direct `SELECT` statement. This simplifies the back-and-forth to keep the field order straight.
This is a full list of the fields in …
> Fix: reorder Benefits mart fields

- warehouse/models/mart/benefits/fct_benefits_events.sql
TLDR; we can filter out about 26.5 million records (of roughly 27 million total!) from the raw Amplitude data that we don't need in the final warehouse fact table / model.
Full details in Slack thread: https://cal-itp.slack.com/archives/C037Y3UE71P/p1731533304019569
```console
$ poetry run dbt run -s +fct_benefits_events
22:04:44  Running with dbt=1.5.1
22:04:46  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.calitp_warehouse.mart.ad_hoc
22:04:46  Found 422 models, 963 tests, 0 snapshots, 0 analyses, 852 macros, 0 operations, 12 seed files, 174 sources, 4 exposures, 0 metrics, 0 groups
22:04:46  
22:04:49  Concurrency: 8 threads (target='dev')
22:04:49  
22:04:49  1 of 2 START sql view …
```
> Fix: filter Benefits bot events

- apps/maps/src/routes/+page.svelte
Add two new `layerType` in Svelte map app to match the new `rt_segment_speeds` derived speedmap data schema. Improves display of speed segment info via tooltips. Old `layerType` from legacy speedmaps retained for now.
Required for https://github.com/cal-itp/data-analyses/issues/1186 
Successfully ran locally, including actual state and speedmap geojson on GCS.
> New speedmap and speed variation maps

- warehouse/models/staging/ntd_annual_data_tables/_src.yml
Add year 2023 on tests for staging NTD service tables as part of the rename and fix tests for issue #3523.
Tested locally:
```
❯ poetry run dbt test -s models/staging/ntd_annual_data_tables/
19:09:20  Running with dbt=1.5.1
19:09:21  Found 418 models, 987 tests, 0 snapshots, 0 analyses, 852 macros, 0 operations, 12 seed files, 170 sources, 4 exposures, 0 metrics, 0 groups
19:09:21
19:09:23  Concurrency: 8 threads (target='dev')
19:09:23
19:09:23  1 of 10 START test accepted_values_stg_ntd_annual_data__service_by_agency_report_year__2022__2023  [RUN]
19:09:23  2 of 10 START test accepted_values_stg_ntd_annual_data__service_by_mode_and_time_period_report_year__2022__2023  [RUN]
19:09:23  3 of 10 START test accepted_values_stg_ntd_annual_data__service_by_mode_and_time_period_time_period__Annu …
```
> Include year 2023 on test for staging NTD service tables

- airflow/dags/sync_ntd_data_xlsx/METADATA.yml
This PR changes the schedule of the NTD monthly ridership scrape (`sync_ntd_data_xlsx` DAG ) to run once a week (every Monday) instead of every day.
There is no need to run every day since it is a monthly file, but having the process running once a week give us a better window to add and process new files once it is released.
Part of the issue #3519.
Tested running airflow locally.
After merge, check the schedule for `sync_ntd_data_xlsx` to see if the next run is for Monday.
> Change NTD ridership schedule to run once a week

- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
- jobs/gtfs-rt-parser-v2/tests/test_gtfs_rt_parser.py
@ohrite and I refactored the code on `gtfs_rt_parser.py` using the tests created on the previous PR to then fix the issue #2780 to properly skip duplicate extracts instead of generating the error.
Tested locally:
```
❯ poetry run pytest --gcs
================================================ test session starts ================================================
platform darwin -- Python 3.9.19, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/erikaypacheco/Documents/workspace/data-infra/jobs/gtfs-rt-parser-v2
configfile: pyproject.toml
plugins: env-1.1.5
collected 10 items
tests/test_gtfs_rt_parser.py ..........                                                                       [100%]
================================================= warnings summary …
```
> Fix Errno2 on GTFS RT validation

- warehouse/models/mart/gtfs_schedule_latest/dim_stops_latest.sql
Realized the column name for the state highway network boolean on the dim_stops_latest table was misleading, renamed to: `on_state_highway_network`
locally with dbt
run table in production as requested
> revise misleading name of state highway network flag column on dim_stops_latest

- jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
- jobs/gtfs-rt-parser-v2/poetry.lock
- jobs/gtfs-rt-parser-v2/pyproject.toml
Provide a better message when GTFS-RT validator jar skips a file. Previously, the `validation_exception` logged was a raw byte string representing the MD5 of a file evaluated by the gtfs-realtime-validator jar file.
This has been amended to print the message "No validator output" instead, mirroring the command line output.
Resolves #2780 
Monitor `cal-itp-data-infra.staging.int_gtfs_quality__rt_validation_outcomes` to ensure that friendly error messages appear rather than byte strings.
> Refine GTFS-RT validator error messaging

- airflow/dags/create_external_tables/ntd_data_products/annual_database_agency_information.yml
Somehow the process to create external tables are not creating the new columns for `external_ntd_data_products.annual_database_agency_information`.
I changed the order of those new columns on the configuration file to try to force it creation.
[#3497]
Tested locally creating the table on staging.
Check if the DAG was able to create the table with the new columns
> Change order of new columns on External Annual Agency Information to try to force it creation

- docs/analytics_onboarding/overview.md
- docs/analytics_tools/saving_code.md
- docs/contribute/submitting_changes.md
- docs/publishing/sections/7_gcs.md
Fixing docs from errors generated from previous pr #3554
Adds a little documentation for how to build the docs site locally on jupyterhub
Resolves #3569
```
jovyan@jupyter-vevetron:~/data-infra$ jb build docs --warningiserror
Running Jupyter-Book v1.0.0
Source Folder: /home/jovyan/data-infra/docs
Config Path: /home/jovyan/data-infra/docs/_config.yml
Output Path: /home/jovyan/data-infra/docs/_build/html
Running Sphinx v5.3.0
[etoc] Changing master_doc to 'intro'
loading pickled environment... done
myst v1.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'substitution', 'colon_fence', 'dollarmath', 'tasklist', 'linkify'}, disable_syntax=[], all_links_external=False, url_schemes=('mailto', 'http', 'https'), ref_domains=None, fence_as_directive=set(), …
```
> Fixing docs from errors generated from previous pr 

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
Adds a field - holiday_website__from_provider_ - needed for queries.
Not tested.
_If making changes to dbt models, please run the command `poetry run dbt run -s CHANGED_MODEL` and include the output in this section of the PR._
> Adds a single field to external_airtable

- warehouse/models/mart/gtfs/dim_calendar_dates.sql
This PR fixes the error on issue #3065 adding `exception_type` column as part of the generate_surrogate_key in order to make _gtfs_key on dim_calendar_dates pass the unique key test.
Tested locally generating table on stating.
Since the table is set to incremental materialization, if the error still happening after merging and running the process we need to run a `Full Refresh` to regenerate the `_gtfs_key` for old records.
> Fix Not Unique Error on dim_calendar_dates._gtfs_key

- airflow/dags/create_external_tables/ntd_data_products/historical__fra_regulated_mode_major_security_events.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__major_safety_events.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__monthly_modal_time_series_safety_and_service.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__nonmajor_safety_and_security_events.yml
- airflow/dags/sync_ntd_data_api/safety_service_and_security_historical/major_safety_events.yml
- airflow/dags/sync_ntd_data_api/safety_service_and_security_historical/monthly_modal_time_series_safety_and_service.yml
- airflow/plugins/operators/scrape_ntd_api.py
Ingest NTD safety and security table endpoints from DOT API using the pattern developed for the NTD annual reporting ingest in #3415 
First step in unblocking safety and security questions in #3562. Next step is staging and mart tables in the warehouse and metabase 
New endpoints:
* `monthly_modal_time_series_safety_and_service`
* `major_safety_events`
* `nonmajor_safety_and_security_events`
* `fra_regulated_mode_major_security_events`
New tables:
* `historical__monthly_modal_time_series_safety_and_service`
* `external_ntd__safety_and_security.historical__major_safety_events`
* `external_ntd__safety_and_security.historical__nonmajor_safety_and_security_events`
* `external_ntd__safety_and_security.historical__fra_regulated_mode_major_security_events`
Resolves #3580 
locally using airflow …
> NTD: Modify API sync for column name handling, ingest safety and security tables, create external tables

- warehouse/models/mart/ntd_fct_annual/_mart_ntd_fct_annual.yml
- warehouse/models/mart/ntd_fct_annual/fct_ntd_annual_data__2023_agency_information.sql
- warehouse/models/mart/ntd_fct_annual/fct_ntd_annual_data__2023_contractual_relationships.sql
- warehouse/models/staging/ntd_annual_data_tables/_src.yml
- warehouse/models/staging/ntd_annual_data_tables/_stg_ntd_annual_data_tables.yml
- warehouse/models/staging/ntd_annual_data_tables/stg_ntd_annual_data__2023_agency_information.sql
- warehouse/models/staging/ntd_annual_data_tables/stg_ntd_annual_data__2023_contractual_relationships.sql
Following up on #3584, this brings the external tables for agency and contractual relationships created in that PR into the Warehouse as MVP staging and mart tables.
New staging tables:
* stg_ntd_annual_data__2023_agency_information
* stg_ntd_annual_data__2023_contractual_relationships
New mart tables:
* fct_ntd_annual_data__2023_agency_information
* fct_ntd_annual_data__2023_contractual_relationships
Observe for expected behavior, follow up with documentation, tests, typecasting
> ntd: staging and mart warehouse tables for agency and contractual relationship tables

- airflow/dags/create_external_tables/ntd_data_products/2022__annual_database_agency_information.yml
- airflow/dags/create_external_tables/ntd_data_products/2023__annual_database_agency_information.yml
- airflow/dags/create_external_tables/ntd_data_products/2023__annual_database_contractual_relationships.yml
- airflow/dags/sync_ntd_data_xlsx/agency_information/2022_annual_database_agency_information.yml
- airflow/dags/sync_ntd_data_xlsx/scrape_ntd_xlsx_urls.py
- airflow/plugins/operators/scrape_ntd_xlsx.py
This PR ingests the 2022 agency database information table using previous patterns and expands the dynamic URL scraping for use with this endpoint. This PR also cleans up previous commits.
Observe for expected behavior and external table creation
> NTD: ingest 2022 agency and create external table, expand dynamic url scrape, clean up previous code

- warehouse/models/mart/ntd_annual_reporting/dim_2022_agency_information.sql
- warehouse/models/staging/ntd_annual_reporting/_src.yml
- warehouse/models/staging/ntd_annual_reporting/_stg_ntd_annual_reporting.yml
- warehouse/models/staging/ntd_annual_reporting/stg_ntd__2022_agency_information.sql
Following up on #3604, this PR creates a staging and mart table for the ingest of `external_ntd__annual_reporting.2022__annual_database_agency_information`
Test once the external table is created
> NTD: staging and mart tables for 2022 agency data

- warehouse/models/mart/ntd/_mart_ntd.yml
- warehouse/models/staging/ntd_annual_reporting/_src.yml
- warehouse/models/staging/ntd_annual_reporting/_stg_ntd_annual_reporting.yml
Fixing some failing tests for new NTD models [#3475].
- Report Year was updated from string to integer: tests that validates the year are failing because need to add a param to remove quotes
- Service by Mode: I added not null test last week, but the table contains null values for `max_time_period`, so removing the test.
Tested locally, creating tables and running tests.
```
❯ poetry run dbt test -s +models/staging/ntd_annual_reporting/
21:14:43  1 of 22 START test accepted_values_stg_ntd__service_by_agency_report_year__False__2022__2023  [RUN]
21:14:43  2 of 22 START test accepted_values_stg_ntd__service_by_mode_and_time_period_report_year__False__2022__2023  [RUN]
21:14:43  3 of 22 START test accepted_values_stg_ntd__service_by_mode_and_time_period_time_period__Annual_Total__Average_Week …
```
> Fix NTD test errors

- warehouse/models/mart/ntd/_mart_ntd.yml
Fixing failing test from fct_annual_service_modes erroring because of null values.
```
❯ poetry run dbt test -s models/mart/ntd
19:19:53  Running with dbt=1.5.1
19:19:57  1 of 33 START test accepted_values_dim_annual_funding_sources_funding_source__federal__state__local  [RUN]
19:19:57  2 of 33 START test accepted_values_dim_annual_funding_sources_report_year__False__2022__2023  [RUN]
19:19:57  3 of 33 START test accepted_values_dim_annual_service_agencies_report_year__False__2022__2023  [RUN]
19:19:57  4 of 33 START test accepted_values_dim_annual_service_mode_time_periods_report_year__False__2022__2023  [RUN]
19:19:57  5 of 33 START test accepted_values_dim_annual_service_mode_time_periods_time_period__Average_Weekday_AM_Peak__Average_Weekday_Midday__Avera19:19:57  5 of …
```
> Fix NTD test error

- ci/pyproject.toml
- kubernetes/apps/charts/jupyterhub/values.yaml
With this deployment, when using jupyterhub you should be able to select another image from the list. This image (2024.5.24) was created a while back.
Has not been tested!  Will go straight to production.
Make sure jupyterhub is still functional
> Add a new profile to test a jupyterhub image

- kubernetes/apps/charts/jupyterhub/values.yaml
Adjusted the jupyterhub config docker / tag names to match the website
Follows https://z2jh.jupyter.org/en/latest/jupyterhub/customizing/user-environment.html#multiple-profiles
Meant to fix https://github.com/cal-itp/data-infra/pull/3614
Resolves #3615
- [] New feature
Has not been tested
Deploy and monitor
> Adjusted jupyterhub config name to match documentation

- images/jupyter-singleuser/Dockerfile
- images/jupyter-singleuser/README.md
- images/jupyter-singleuser/poetry.lock
- images/jupyter-singleuser/pyproject.toml
- kubernetes/apps/charts/jupyterhub/values.yaml
Major Changes:
Updates google cloud SDK to latest version (so it stops using python 3.9 and uses python 3.11 instead)
Holds down setuptools so it doesn't update to 75
Removes altair-saver
Resolves #3648
Built docker image locally
Went into docker image and tested setuptools, it was okay!  Tested _shared_utils
Deploy to Kubes and test
> Updated jupyterhub image to resolve setuptools issues

- airflow/dags/sync_ntd_data_xlsx/funding_and_expenses/capital_expenditures_time_series.yml
- airflow/dags/sync_ntd_data_xlsx/funding_and_expenses/operating_and_capital_funding_time_series.yml
- airflow/dags/sync_ntd_data_xlsx/funding_and_expenses/service_data_and_operating_expenses_time_series_by_mode.yml
- airflow/dags/sync_ntd_data_xlsx/scrape_ntd_xlsx_urls.py
- airflow/plugins/operators/scrape_ntd_xlsx.py
This PR scrapes the following NTD time series excel spreadsheet endpoints and writes the contents to GCS buckets, following the patterns developed in #3604, others
* capital_expenditures_time_series
* operating_and_capital_funding_time_series
* service_data_and_operating_expenses_time_series_by_mode
Referenced in #3562
Monitor for expected behavior, create external tables and warehouse tables in follow-on PRs
> Add additional ntd time series datasources to pipeline

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/gtfs/fct_vehicle_locations_dwell.sql
- warehouse/models/mart/gtfs/fct_vehicle_locations_grouped.sql
* Part of https://github.com/cal-itp/data-infra/issues/3645
* Redo #3646 with new image 
```
jovyan@jupyter-tiffanychu90 ~/data-infra/warehouse (fct_vehicle_locations_grouped) $ poetry run dbt run -s fct_vehicle_locations_grouped+
19:18:18  Running with dbt=1.5.1
19:18:30  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.calitp_warehouse.mart.ad_hoc
19:18:31  Found 477 models, 1013 tests, 0 snapshots, 0 analyses, 852 macros, 0 operations, 12 seed files, 178 sources, 4 exposures, 0 metrics, 0 groups
19:18:31  
19:18:49  Concurrency: 8 threads (target='dev')
19:18:49 …
```
> Add `mart_gtfs.fct_vehicle_locations_grouped`

- .github/workflows/build-warehouse-image.yml
- warehouse/pyproject.toml
Adds the export command package so poetry 2.0.1 works correctly.
Test out the latest version of the docker build command.
I don't know of a way to test this locally.
Resolves #3662
Hasn't really been tested.  Ran some github actions through this PR but it skips the build push step that fails.
https://github.com/cal-itp/data-infra/actions/runs/12958690921/job/36149632450?pr=3661
Re-run this action:
https://github.com/cal-itp/data-infra/actions/runs/12935530888
And see if the job goes further.
> test-fix(build-warehouse-image): test upgrade of build

- warehouse/models/mart/gtfs/fct_vehicle_locations_grouped.sql
Airflow DAG error showed missing `dt`. Instead of using partitions of `service_date`, we'll grab `dt` from `mart_gtfs.fct_vehicle_locations` and pass it through so source table and downstream derived table are partitioned the same way. 
``` 
Runtime Error
[2025-02-04, 00:26:15 UTC] {pod_manager.py:435} INFO - [base]   Database Error in model fct_vehicle_locations_grouped (models/mart/gtfs/fct_vehicle_locations_grouped.sql)
[2025-02-04, 00:26:17 UTC] {pod_manager.py:435} INFO - [base]     Unrecognized name: dt at [3:17]
```
Follow-up to #3660 
[Slack thread](https://cal-itp.slack.com/archives/C0332307HKM/p1738628781207819) -- are there implications for data duplication, data storage, since vehicle locations is probably some of the biggest tables
```
jovyan@jupyter-tiffanychu90 …
```
> `mart_gtfs.fct_vehicle_locations_grouped` - incremental settings like `fct_vehicle_locations`

- airflow/dags/sync_ntd_data_xlsx/scrape_ntd_xlsx_urls.py
- airflow/docker-compose.yaml
- airflow/plugins/operators/scrape_ntd_api.py
- airflow/plugins/operators/scrape_ntd_xlsx.py
- airflow/plugins/operators/scrape_state_geoportal.py
We recently introduced MVP data syncs of the DOT NTD data portal and the state geodata portal. This PR goes back and introduces the appropriate exception handling to catch unwanted behavior.
Operators impacted:
* airflow/plugins/operators/scrape_ntd_api.py
* airflow/plugins/operators/scrape_ntd_xlsx.py
* airflow/plugins/operators/scrape_state_geoportal.py
* airflow/dags/sync_ntd_data_xlsx/scrape_ntd_xlsx_urls.py
ensure these operators run as expected
> Add exception handling for recent data scraping airflow operators

- warehouse/models/mart/benefits/_mart_benefits.yml
This PR fixes DBT error while running transform_warehouse. Some columns were removed from MART_BENEFITS.FCT_BENEFITS_EVENTS but was mentioned on yml file for documentation.
[Commit that removed columns](https://github.com/cal-itp/data-infra/commit/34aa4a0379672b9936a71b7c8805fd299f14bd16)
Resolves #3659
Error before fix:
Running model after fix and testing without errors:
Make sure the issue is resolved on newer transform_warehouse.dbt_run_and_upload_artifacts logs.
> Fix DBT error related to deleted columns on fct_benefits_events

- warehouse/dbt_project.yml
- warehouse/seeds/_seeds.yml
This PR will add two labels to DBT models helping us to improve billing reports as part of the issue #3541.
Label were based on the current dataset structure.
* domain:
- seeds
- staging
- intermediate
- mart
* dataset:
- audit
- benefits (benefits and amplitude datasets)
- gtfs (gtfs and rt datasets)
- gtfs_quality
- gtfs_schedule_latest
- ntd
- ntd_annual_reporting
- ntd_ridership
- ntd_safety_and_security
- ntd_validation
- payments
- state_geoportal
- transit_database
- transit_database_latest
Tested locally creating tables on staging.
Check if all labels on BigQuery were created after next DAGs' run.
> Add labels to DBT models

- kubernetes/apps/charts/jupyterhub/values.yaml
This reverts commit 96395c69796434179ea71e18de94d546ed6f278f.
Accidentally pushed directly to main with my last commit
> Revert "fix(jupyterhub): adjusted timeouts to be way higher"

- kubernetes/apps/charts/jupyterhub/values.yaml
Follow the [guide](https://discourse.jupyter.org/t/spawn-failed-timeout-even-when-start-timeout-is-set-to-3600-seconds/8098/7) to increase the timeouts.  Might resolve the issue for the future.
Note these settings aren't in the[ jupyterhub customization guide](https://z2jh.jupyter.org/en/stable/jupyterhub/customizing/user-management.html).
Resolves #3686 
Not tested!
Check and make sure everything is …
> Try to change jupyterhub timeout settings

- warehouse/dbt_project.yml
We created warehouse tables for the NTD funding and expenses endpoints in #3665 but neglected to define the mart schema in the dbt_project.yml file, so by default they populated in the staging schema, as noticed by @evansiroky. This PR defines the schema for these tables as `mart_ntd_funding_and_expenses` and they will now appear in Bigquery as such.
> ntd: define mart schema in dbt project for funding and expenses tables

- kubernetes/apps/charts/jupyterhub/values.yaml
Switched out the default image for 2025.1.15, keeps older image
It appears the 2025.1.15 image which uses python 3.11 is well accepted by the analytics team, will make it to default.  We can keep the older image (it's only 2 GB).  Also the power user will also use the default image now.
Not tested.
Just make sure jupyterhub is okay today.
> Switched out the default image for 2025.1.15, keeps older image

- kubernetes/apps/charts/jupyterhub/values.yaml
@edasmalchi asks to be able to create power legacy image access to help with debugging stuff: https://github.com/cal-itp/data-analyses/pull/1356
Nein.
> Added a power legacy user

- kubernetes/apps/charts/jupyterhub/values.yaml
Reduce timeout to increase chances of retries.
Previously we had issues where node spin up was too long.  But right now the errors are because we are attaching to the wrong node where our hdds are not located.   This should make iterations faster for this error.  A hacky band-aid if you will.
not tested
> Reduce timeout to increase chances of retries

- .github/workflows/terraform-plan.yml
- iac/README.md
- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra-staging/iam/us/service_account.tf
Adds a service account to run the pytest suite for gtfs-rt-archiver.
> Add Pytest Service Account to Staging

- images/jupyter-singleuser/Dockerfile
- images/jupyter-singleuser/README.md
- images/jupyter-singleuser/pyproject.toml
- kubernetes/apps/charts/jupyterhub/values.yaml
The jupyter images are having serious issues with the node version in the current jupyter notebook.
This switched to a newer image on the same version of python. It also uses something like node ~22, while the old used node ~20.
Resolves #(https://github.com/cal-itp/data-analyses/issues/1388)
Can't test locally, but the build.log looks good!
Test in prod
> Push a newer image with a more updated node version

- warehouse/models/mart/ntd_annual_reporting/_mart_ntd_annual_reporting.yml
- warehouse/models/staging/ntd_annual_reporting/_src.yml
- warehouse/models/staging/ntd_annual_reporting/_stg_ntd_annual_reporting.yml
This PR adds documentation to 2022 and 2023 NTD Agency Information tables and columns.
Tested running model locally and generating docs.
> Add documentation to NTD 2022 and 2023 Agency Information

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_organizations.yml
[//]:# (…tions.yml)
Adding RTPA and MPO to  external_airtable_california_transit_organizations.yml in order to eventually add these fields to the `dim_organizations` in the GBC warehouse.
Resolves #\[3751\]
Once this step is completed, Staging, Intermediate and Marts models will be updated to include these fields in the `dim_organizations`.
> Adding RTPA and MPO to  `external_airtable_california_transit_organizations.yml`

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_organizations.yml
This reverts commit 3e77334f12e4a29d637bd78f470364e0495dce93, reversing changes made to c1faf49dc826b64acd7a132f8a6ef88d61761833.
Reverses an an error detailed in https://github.com/cal-itp/data-infra/pull/3755
Not tested
Re-run the query and make sure it's okay.
> Revert "Pull request #3755"

- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_organizations.yml
Adding RTPA and MPO to external_airtable_california_transit_organizations.yml in order to eventually add these fields to the dim_organizations in the GBC warehouse.
Resolves #\[[3751](https://github.com/cal-itp/data-infra/issues/3751)\]
Once this step is completed, Staging, Intermediate and Marts models will be updated to include these fields in the dim_organizations.
> Adding RTPA and MPO to external_airtable_california_transit_organizations.yml

- warehouse/models/intermediate/transit_database/dimensions/int_transit_database__organizations_dim.sql
- warehouse/models/mart/transit_database/_mart_transit_database.yml
- warehouse/models/mart/transit_database/dim_organizations.sql
- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
Adding `rtpa` and `mpo` fields to `stg`, `int` and `mart` `dim_organizations` table/view.
Resolves #3751
`jovyan@jupyter-fsalemi ~/data-infra/warehouse (rpta_mpo_addition) $ poetry run dbt run -s +dim_organizations
07:34:10  Running with dbt=1.5.1
07:34:13  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.calitp_warehouse.staging.ntd
07:34:14  Found 563 models, 1023 tests, 0 snapshots, 0 analyses, 852 macros, 0 operations, 12 seed files, 206 sources, 4 exposures, 0 metrics, 0 groups
07:34:14  
07:34:17  Concurrency: 8 threads (target='dev')
07:34:17  
07:34:17  1 of 3 START sql view model farhad_staging.stg_transit_database__organizations . [RUN]
07:34:18  1 of 3 OK created sql view …
> Adding rtpa and mpo to stg, int, mart dim_organizations

- airflow/dags/parse_littlepay_v3/METADATA.yml
- airflow/dags/parse_littlepay_v3/README.md
- airflow/dags/parse_littlepay_v3/nevada_county_connects.yml
- airflow/dags/sync_littlepay_v3/METADATA.yml
- airflow/dags/sync_littlepay_v3/README.md
- airflow/dags/sync_littlepay_v3/nevada_county_connects.yml
- airflow/docker-compose.yaml
- airflow/plugins/operators/__init__.py
- airflow/plugins/operators/littlepay_raw_sync_feed_v3.py
- airflow/plugins/operators/littlepay_to_jsonl_feed_v3.py
Littlepay has transitioned to their data feed v3, and data for our most recent open loop agency to come online (Nevada County Connects) is being provided in their v3 format.
This PR iterates on our Airflow sync and parse tasks for feed v1 to accommodate the changes found in feed v3: 
* deprecate dynamic creation of source bucket name due to changes in composition in v3
* stand up new raw and parsed buckets, secrets
* updates based on breaking changes in table names, add new tables
Resolves #3705 
Turn on dags in GUI, observe for expected behavior
> payments: create new operators and dags for littlepay feed v3 sync and parse

- airflow/dags/parse_littlepay_v3/METADATA.yml
The recent merge of #3746 set start date for airflow dag task too far in the past, revising for more recent start date
manually start dag in GUI and run
> payments: fix revise littlepay v3 parse start date

- docs/analytics_tools/saving_code.md
Adding a new section to the Cal-ITP, Saving Code doc page about resolving pre-commit check failures.
For now, creating a new section called `Options for Resolving Pre-commit issues` inbetween the `Options for Resolving Merge Conflicts... Other Common Issues` section (same heading level). Similar language to the `Installing and Using pre-commit hooks` of the `Submitting Changes` doc page, but more in-depth.
> new section in Saving Code doc to address failing pre-commit checks. 

- packages/calitp-data-infra/poetry.lock
- packages/calitp-data-infra/pyproject.toml
The new version of `google-cloud-secret-manager` (>=2.16.4,<2.23) covers the versions pinned in Cloud Composer images from the current image at least up through the latest extended support version (composer-2.10.2-airflow-2.10.2).
Related to #3765 and #3791 
Locally ran tests and linter in Python 3.8 and 3.11 environments using:
```bash
pytest
mypy .
```
Merge #3793
> Loosen the version of google-cloud-secret-manager

- airflow/requirements.txt
Includes dependencies compatible with `composer-2.6.5-airflow-2.5.3` and `composer-2.8.3-airflow-2.6.3`
Resolves #3765
Supersedes #3791 
**Merge _after_ #3792**
In addition to building the image, explicitly resolved dependencies by running the following in a Python 3.8 environment:
```bash
uv pip install -r requirements-composer-2.6.5-airflow-2.5.3.txt -r requirements.txt --dry-run
```
... and the following in a Python 3.11 environment:
```bash
uv pip install -r requirements-composer-2.8.3-airflow-2.6.3.txt -r requirements.txt --dry-run
```
Both commands were successful with the new version pins.
This new set of requirements will be deployed to Cloud Composer. After that is done we should verify that Google thinks we're good to upgrade:
```bash
gcloud beta composer environments …
```
> Use airflow deps that resolve cleanly with current and next Cloud Composer images

- warehouse/models/mart/gtfs/fct_vehicle_locations_grouped.sql
Fix all the dbt errors related to creating `mart_gtfs.fct_vehicle_positions_grouped`. Erika diagnosed this was due to table settings. We can remove `dt` and use `service_date`, since `dt` was needed in `fct_vehicle_locations`, but once we make this table downstream, we'll use `service_date`. [Slack discussion](https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1742490672202539)
Part of #3645
Related to #3660, #3672, #3771
```
jovyan@jupyter-tiffanychu90 ~/data-infra/warehouse (vp-grouped-table-settings) $ poetry run dbt run -s fct_vehicle_locations_grouped --full-refresh
17:56:49  Running with dbt=1.5.1
17:56:52  [WARNING]: Configuration paths exist in your dbt_project.yml …
```
> use service_date for fct_vp_grouped table settings

- warehouse/models/mart/gtfs/fct_vehicle_locations_grouped.sql
This PR fixes error `Unrecognized name: dt at [3:17]` on fct_vehicle_locations_grouped by adding the correct column name to macro `incremental_where` = `this_dt_column='service_date'`.
As requested by @vevetron  I removed the materialization of the table.
[#3790]
After merging the code, we need to run a full-refresh to remove the materialization.
Verify if transform_warehouse is running successfully after the full refresh.
> Fix dt error on fct_vehicle_locations_grouped

- iac/.gitignore
- iac/cal-itp-data-infra/cdn/us/.terraform.lock.hcl
- iac/cal-itp-data-infra/cdn/us/backend_bucket.tf
- iac/cal-itp-data-infra/cdn/us/provider.tf
- iac/cal-itp-data-infra/cdn/us/variables.tf
- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_object.tf
- iac/cal-itp-data-infra/networks/us/global_address.tf
- iac/cal-itp-data-infra/networks/us/outputs.tf
Adds Terraform configuration for:
* GCS Bucket to store GTFS site artifacts
* Load balancer to route inbound requests to the GCS Bucket (future buckets will use this same load balancer)
* External IP address for the load balancer
Resolves #[3812](https://github.com/cal-itp/data-infra/issues/3812)
Visited http://34.8.18.200/
> Add GTFS bucket and CDN

- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_acl.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_binding.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_policy.tf
- iac/cal-itp-data-infra/gcs/us/storage_default_object_acl.tf
This PR adds lifecyle rule to delete data older than 30 days on dev and test buckets (using Terraform).
I am deleting these three obsolete buckets instead of adding the rule since they are old and not in use anymore: `cold-storage-outputs-gtfs-data-test-charlie-test`, `cold-storage-outputs-gtfs-data-test` and `calitp-jamesl-gcp-components-tfstate`.
Resolves [#3666]
Tested running `Terraform plan` locally
Check if data older than 30 days were deleted from dev and test buckets.
> Add lifecyle rule to delete old data on dev and test buckets

- iac/cal-itp-data-infra-staging/cdn/us/backend_bucket.tf
- iac/cal-itp-data-infra-staging/cdn/us/provider.tf
- iac/cal-itp-data-infra-staging/cdn/us/variables.tf
- iac/cal-itp-data-infra-staging/gcs/us/outputs.tf
- iac/cal-itp-data-infra-staging/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra-staging/gcs/us/storage_bucket_iam_member.tf
- iac/cal-itp-data-infra-staging/iam/us/iam_workload_identity.tf
- iac/cal-itp-data-infra-staging/iam/us/outputs.tf
- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra-staging/iam/us/service_account.tf
- iac/cal-itp-data-infra-staging/networks/us/global_address.tf
- iac/cal-itp-data-infra-staging/networks/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/iam/us/iam_workload_identity.tf
- iac/cal-itp-data-infra/iam/us/outputs.tf
- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/service_account.tf
Creates the following buckets:
- calitp-dbt-docs (in cal-itp-data-infra)
- calitp-staging-dbt-docs (in cal-itp-data-infra-staging)
- calitp-staging-dbt-artifacts (in cal-itp-data-infra-staging)
Also creates a service account for staging.
Part of #3783
`terraform plan` runs cleanly
Observe production build output
> Create staging service account, dbt buckets and CDN

- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
This ignores ongoing GCS bucket label changes in Terraform, to reduce the overall noise when merging.
> Ignore GCS label changes in Terraform

- .github/workflows/composer-apply-files.yml
- .github/workflows/composer-plan-files.yml
- .github/workflows/terraform-apply.yml
- .github/workflows/terraform-plan.yml
- iac/cal-itp-data-infra-staging/iam/us/iam_workload_identity.tf
- iac/cal-itp-data-infra-staging/iam/us/outputs.tf
- iac/cal-itp-data-infra-staging/iam/us/service_account_iam_member.tf
- iac/cal-itp-data-infra-staging/iam/us/variables.tf
- iac/cal-itp-data-infra/iam/us/iam_workload_identity.tf
- iac/cal-itp-data-infra/iam/us/outputs.tf
- iac/cal-itp-data-infra/iam/us/project_iam_custom_role.tf
- iac/cal-itp-data-infra/iam/us/service_account_iam_member.tf
- iac/cal-itp-data-infra/iam/us/variables.tf
Adds a role that should allow us to publish from a github repo directly to a bucket. 
Continues work on #3812
Has Not
Capture output with
```gcloud iam service-accounts keys create key.json \
--iam-account <service-account-email>```
Then test in calitp.gtfs.org repo
> Add a role to publish from github to buckets

- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_acl.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_binding.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_policy.tf
- iac/cal-itp-data-infra/gcs/us/storage_default_object_acl.tf
Some Littlepay buckets created in March are not in Terraform: `calitp-payments-littlepay-parsed-v3`, `calitp-payments-littlepay-raw-v3`, `test-calitp-payments-littlepay-parsed-v3`, and `test-calitp-payments-littlepay-raw-v3`.
This PR adds those four buckets and creates a lifecycle rule to `test-calitp-payments-littlepay-parsed-v3` and `test-calitp-payments-littlepay-raw-v3`.
Resolves #3666
Tested locally with `Terraform plan`
> Add new littlepay buckets to Terraform

- warehouse/models/intermediate/transit_database/dimensions/int_transit_database__organizations_dim.sql
- warehouse/models/mart/transit_database/dim_organizations.sql
- warehouse/models/mart/transit_database_latest/dim_organizations_latest_with_caltrans_district.sql
- warehouse/models/staging/transit_database/stg_transit_database__organizations.sql
This PR seeks to replace the deprecated use of `_deprecated__ntd_agency_to_organization` in `dim_organizations` with the appropriate alternative to determine ntd_id, as well as create a `dim_organizations_latest_with_caltrans_district` which is latest only and enriched with `caltrans_district`, and perform some other cleanup tasks as outlined below:
Refactor mart_transit_database.dim_organizations:
* remove deprecated use of `_deprecated__ntd_agency_to_organization`
* instead, utilize `ntd_id` via `ntd_agency_info_key` from `int_transit_database__ntd_agency_info_dim`
* **Remaining Questions**
* Is this an appropriate substitution and use of ntd_id?
* Should we be incorporating versioned use of ntd_id/caltrans district
create mart_transit_database_latest.dim_organizations_latest_with_caltra …
> modify organization tables for enrichment

- airflow/dags/create_external_tables/ntd_data_products/multi_year__employees_by_agency.yml
- warehouse/models/mart/ntd_annual_reporting/fct_employees_by_agency.sql
- warehouse/models/staging/ntd_annual_reporting/stg_ntd__employees_by_agency.sql
The field for agency name in the employees_by_agency-related NTD tables is misnamed as `agency` through the pipeline, instead of how it is actually found in the source data: `max_agency_1`.
Files changed (column name: `agency` to `max_agency_1`): 
* `dags/create_external_tables/ntd_data_products/multi_year__employees_by_agency`
* `staging/ntd_annual_reporting/stg_ntd__employees_by_agency`
* `mart/ntd_annual_reporting/fct_employees_by_agency`
In local airflow
> NTD: fix agency field in employees_by_agency tables

- airflow/dags/create_external_tables/ntd_data_products/2022__annual_database_contractual_relationships.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__asset_inventory_time_series__active_fleet.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__asset_inventory_time_series__ada_fleet.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__asset_inventory_time_series__avg_fleet_age.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__asset_inventory_time_series__avg_seating_capacity.yml
- airflow/dags/create_external_tables/ntd_data_products/historical__asset_inventory_time_series__avg_standing_capacity.yml
Following #3853, this PR creates new external tables for our new `asset_inventory_time_series` and `2022__annual_database_contractual_relationships` endopoints.
External tables created:
* create_external_tables/ntd_data_products/2022__annual_database_contractual_relationships.yml
* create_external_tables/ntd_data_products/historical__asset_inventory_time_series__active_fleet.yml
* create_external_tables/ntd_data_products/historical__asset_inventory_time_series__ada_fleet.yml
* create_external_tables/ntd_data_products/historical__asset_inventory_time_series__avg_fleet_age.yml
* create_external_tables/ntd_data_products/historical__asset_inventory_time_series__avg_seating_capacity.yml
* create_external_tables/ntd_data_products/historical__asset_inventory_time_series__avg_standing_capacity.yml …
> NTD: create external tables for new endpoints – asset_inventory_time_series and 2022 contractual relationships

- warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
- warehouse/models/mart/transit_database/_mart_transit_database.yml
Fixed model documentation correcting columns that were removed or changed.
* Removed GTFS_RT_SCHEDULE_DATASET_KEY since the column on MART_GTFS.FCT_VEHICLE_LOCATIONS_GROUPED does not exist anymore
* Renamed columns RTPA to RTPA_NAME and MPO to MPO_NAME from MART_TRANSIT_DATABASE.DIM_ORGANIZATIONS
* Fixed invalid commenting that will fix the empty columns errors
Resolves [#3862]
```
❯ poetry run dbt run -s models/intermediate/gtfs/int_gtfs_schedule__all_scheduled_service.sql
20:17:31  Running with dbt=1.5.1
20:17:32  Unable to do partial parsing because a project config has changed
20:17:39  Found 582 models, 1072 tests, 0 snapshots, 0 analyses, 852 macros, 0 operations, 12 seed files, 217 sources, 4 exposures, 0 metrics, 0 groups
20:17:39
20:17:44  Concurrency: 8 threads …
```
> Fix Metabase sync errors

- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
This PR adds permission to Github service account through Terraform to be able to run deploy dbt.
Resolves #3862
Tested locally running `Terraform plan`
> Add permissions to GitHub service account to deploy to dbt

- airflow/Dockerfile
- airflow/Dockerfile.composer
- airflow/dags/parse_littlepay_v3/sacrt.yml
- airflow/dags/sync_littlepay_v3/sacrt.yml
Littlepay has generated a new feed v3 for SacRT's recent launch, and this PR sets up the sync and parse tasks necessary to ingest and parse this data.
In this PR, we are also reverting/revising `Dockerfile` and `Dockerfile.composer`
* `Dockerfile` – revising based on the reversion of #3791 
* revert back to apache/airflow:2.5.3-python3.8
* `Dockerfile.composer`
* Fix previously existing error,  configure as apache/airflow:2.5.3-python3.8
* Revert back to Composer 2.6.5
Next:
* Seed mapping for payments organizations
* RBAC for payments users access
* Dashboarding for payments
Partially resolves #3835 
local airflow
> payments: sync, parse tasks for new sacrt littlepay feed v3; modify Dockerfile, Dockerfile.composer

- warehouse/seeds/payments_entity_mapping.csv
Now that #3854 is merged, we need to set up the organizational/GTFS seed mapping for `sacrt` Littlepay feed v3, to faciliate reconciliation and dashboarding
Resolves #3835 
poetry run dbt seed
Finish the dashboarding work in Metabase
> payments: add seed mapping for new sacrt payments feed v3

- .github/workflows/deploy-dbt.yml
- warehouse/models/mart/ntd_annual_reporting/_mart_ntd_annual_reporting.yml
- warehouse/models/mart/ntd_annual_reporting/fct_2022_contractual_relationships.sql
- warehouse/models/mart/ntd_assets/_mart_assets.yml
- warehouse/models/mart/ntd_assets/fct_asset_inventory_time_series_active_fleet.sql
- warehouse/models/mart/ntd_assets/fct_asset_inventory_time_series_ada_fleet.sql
- warehouse/models/mart/ntd_assets/fct_asset_inventory_time_series_avg_fleet_age.sql
- warehouse/models/mart/ntd_assets/fct_asset_inventory_time_series_avg_seating_capacity.sql
- warehouse/models/mart/ntd_assets/fct_asset_inventory_time_series_avg_standing_capacity.sql
- warehouse/models/staging/ntd_annual_reporting/_src.yml
- warehouse/models/staging/ntd_annual_reporting/_stg_ntd_annual_reporting.yml
- warehouse/models/staging/ntd_annual_reporting/stg_ntd__2022_contractual_relationships.sql
- warehouse/models/staging/ntd_assets/_src.yml
- warehouse/models/staging/ntd_assets/_stg_ntd_assets.yml
- warehouse/models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__active_fleet.sql
- warehouse/models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__ada_fleet.sql
- warehouse/models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__avg_fleet_age.sql
- warehouse/models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__avg_seating_capacity.sql
- warehouse/models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__avg_standing_capacity.sql
Following #3857, this PR creates staging, mart tables and their accompanying yml files for our two new NTD data endpoint areas – asset_inventory_time_series and 2022 contractual relationships.
Asset inventory staging tables created:
* models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__active_fleet
* models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__ada_fleet
* models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__avg_fleet_age
* models/staging/ntd_assets/stg_ntd__asset_inventory_time_series__avg_seating_capacity
* models/staging/ntd_assetsstg_ntd__asset_inventory_time_series__avg_standing_capacity
Asset inventory mart tables created:
* models/mart/ntd_assets/fct_asset_inventory_time_series_active_fleet
* …
> NTD: create new warehouse tables for new endpoints – asset_inventory_time_series and 2022 contractual relationships

- warehouse/seeds/payments_entity_mapping.csv
As flagged by Nevada County, we're currently mapping payments data to the incorrect organization entity name. This PR fixes the organization id found in the seed file. (`Nevada County Transportation Commision` -> `Nevada County`)
`poetry run dbt run -s +mart.payments`
> payments: correctly map nevada county organization name to payments data in seed

- warehouse/macros/create_row_access_policy.sql
After correcting the payments organization name seed mapping for Nevada County in #3868, we also need to replace the organization name in the filter for the Elavon row access policy
File modified:
* macros/create_row_access_policy.sql
`poetry run dbt run -s +mart.payments`
> payments: revise elavon row access policy for nevada county after correcting organization seed mapping

- airflow/README.md
- docs/analytics_tools/jupyterhub.md
- iac/login.json
- kubernetes/README.md
- runbooks/workflow/upgrade-metabase.md
- warehouse/README.md
Admins can use the CLI to log in and perform various administrative functions. Most major changes will be performed via Terraform.
Resolves #3748
`gcloud auth login` locally
> Add Admin login instructions for @dot.ca.gov emails

- packages/calitp-data-infra/calitp_data_infra/auth.py
- packages/calitp-data-infra/pyproject.toml
- packages/calitp-data-infra/tests/test_auth.py
Rather than hard-coding the project ID in the `calitp_data_infra` package code, use an environment variable.
Rel #3856 
Ran included unit tests; added unit tests for getting project ID.
1. Locally update version dependency for images to `2025.5.6-rc1` and test
2. If tests are successful, update version to `2025.5.6`
> Update calitp_data_infra to pull project from environment variable

- .github/workflows/deploy-dbt.yml
- iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf
This PR fixes errors when generating and visualizing the model change report for #3784.
When `Deploy dbt` workflow runs, the job `Pull Request visualization` is failing with the message `Got a state selector method, but no comparison manifest`.
To visualize a model change it needs to compare the artifacts (ex. manifest.json) with the latest artifacts to compare the difference.
The artifacts in latest should be based on the models in the Main branch that is uploaded when `transform_warehouse` DAG runs. So I removed uploading artifacts to latest from `Deploy dbt` workflow.
I am also preparing to add a new step on `Sync Metabase` (that is part of Deploy dbt workflow).
In order to `Sync Metabase` to pass it needs the new or changed dbt models to be created on `cal-itp-data-infra-staging` …
> Fix sync Metabase and Visualize on Deploy dbt workflow

- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
This PR adds `iam.roleAdmin` permission to allow Staging Terraform service account to change custom role's permission.
The `iam.roleAdmin` permission on Staging is needed because I need Terraform to add `bigquery.tables.update` to [calitp-dds-analyst](https://github.com/cal-itp/data-infra/blob/5ee76444f3d624fb41a6255d522b4eaef472dc63/iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf#L19) in order to [dbt-deploy workflow](https://github.com/cal-itp/data-infra/blob/5ee76444f3d624fb41a6255d522b4eaef472dc63/.github/workflows/deploy-dbt.yml#L208) run dbt models on staging.
Running locally `terraform plan`.
> Allow Staging Terraform Service Account to change custom role's permission

- iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf
…alyst role in order to run dbt models on staging
This PR is a continuation of permissions requested in order to run dbt models on staging: `bigquery.tables.updateData` to [calitp-dds-analyst](https://github.com/cal-itp/data-infra/blob/5ee76444f3d624fb41a6255d522b4eaef472dc63/iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf#L19)
Tested locally using `terraform plan`
> Add other permission requested to calitp-dds-analyst role to run dbt models

- iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf
Add a new permission to GitHub service account in order to fix access denied when dbt run payment models on sync Metabase Staging.
Part of a sequence of PRs to add permissions nedded: https://github.com/cal-itp/data-infra/pull/3915, https://github.com/cal-itp/data-infra/pull/3910
Tested running `terraform plan` locally.
> Add permission to GitHub service account to create payment models

- warehouse/models/mart/gtfs/fct_scheduled_trips.sql
- warehouse/seeds/_seeds.yml
- warehouse/seeds/gtfs_optional_shapes.csv
Within `mart_gtfs.fct_scheduled_trips`, use `route_id` and `direction_id` to fill in Metrolink's rows to get `shape_id`. 
Resolves #2194 - we've known about this for awhile, and a manual fix seems to be the only way for this to work in downstream analysis.
* The current bug is that `shape_id` is NaN in the trips table, but it's populated in `dim_shapes`. This merge won't link any of Metrolink's shapes in `fct_daily_scheduled_shapes` because of the trips that are counted filter out for null shapes [here](https://github.com/cal-itp/data-infra/blob/6821ffd9cbb07ca9527400278c41964e4b44a74d/warehouse/models/mart/gtfs/fct_daily_scheduled_shapes.sql#L39)
```
trips_counted AS (
SELECT
*
FROM fct_scheduled_trips
WHERE shape_id IS NOT NULL
GROUP BY 1, 2, 3, 4, 5
)
```
* **TODO**: A query to check …
> Populate Metrolink `shape_id` to `fct_scheduled_trips`

- packages/calitp-data-infra/calitp_data_infra/auth.py
- packages/calitp-data-infra/pyproject.toml
The calitp-data-infra package used an incorrect format for identifying secrets since version `2025.05.06-rc1`. This release candidate version was being used to test Cloud Composer upgrades. This is related to updating the secrets capabilities for staging Airflow. This PR also creates a new release candidate version of calitp-data-infra.
Ref #3856 
Locally ensuring that the format of the secrets ID results in a valid response from the `google.cloud` client library. E.g.:
```py
from google.cloud import secretmanager
client = secretmanager.SecretManagerServiceClient()
project = 'cal-itp-data-infra-staging'
name = 'LITTLEPAY_AWS_IAM_MST_ACCESS_KEY'  # Any secret that exists in the project will do.
version = f'projects/{project}/secrets/{name}/versions/latest'
response = …
```
> fix: Prefix secrets version string with "projects/"

- iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf
- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
Added permissions that are missing for MS Entra ID users on production and staging.
Also as deploy dbt has been requesting many permissions to sync Metabase (https://github.com/cal-itp/data-infra/pull/3910, https://github.com/cal-itp/data-infra/pull/3915, https://github.com/cal-itp/data-infra/pull/3925), I reviewed roles needed and added instead of only individual permissions on the custom `calitp-dds-analyst` role.
Resolves #3920
Tested locally with `terraform plan`
Check is MS Entra Id users can save queries in the bigquery console.
> Review Staging and Production gh service account and Entra ID permissions

- .github/workflows/README.md
As part of the Quarterly Maintenance: 2025:Q1/Q2 - Github Actions #3701, I am adding information about new workflows that are missing from the Readme.
Preview the Readme on the branch.
> Add github workflows to Readme

- warehouse/models/mart/gtfs/fct_scheduled_trips.sql
* Metrolink's `shape_array_key` still doesn't join in.
* Move the order of where the seed table is up and fix `dim_trips` instead. Doing it later means the left join with `dim_shapes_arrays` still misses Metrolink.
* Follow-up to #3928 to resolve #2194.
* Also add `route_color` to this table because we once wanted it. https://github.com/cal-itp/data-analyses/issues/1107
```
jovyan@jupyter-tiffanychu90 ~/data-infra/warehouse (find-metrolink-shapes) $ poetry run dbt run -s fct_scheduled_trips+ --full-refresh
00:01:54  Running with dbt=1.5.1
00:02:20  Found 612 models, 1078 tests, 0 snapshots, 0 analyses, 853 macros, 0 operations, 13 seed files, 223 sources, 4 exposures, 0 metrics, 0 groups
00:02:20  
00:02:44  Concurrency: 8 threads (target='dev')
00:02:44  
00:02:45  1 of 21 START sql …
```
> Properly attach Metrolink's shape_array_key

- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra-staging/iam/us/service_account_iam_member.tf
Adds necessary permissions to the staging Composer service account.
Relates to #3780
terraform plan in PR
> Add permissions to stating composer service account

- iac/cal-itp-data-infra-staging/iam/us/service_account_iam_member.tf
This commit does not attempt to modify the manually-authorized service account IAM binding for the staging Composer service account.
Relates to #3780 
`terraform apply` locally
> Do not modify manual staging composer service membership

- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
Add roles/secretmanager.admin permission to DDS Admins in order to allow SSO Admins to edit secret keys.
Resolves [#3966]
Running `terraform plan` locally.
> Add roles/secretmanager.admin permission to DDS Admins

- airflow/dags/deploy_dbt_docs/deploy_dbt_docs_site.yml
- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_run_and_upload_artifacts_full_refresh_exclude_rt.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_run_and_upload_artifacts_select_rt.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_test_exclude_rt.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_test_select_rt.yml
- warehouse/dbt_project.yml
- warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
- warehouse/models/staging/hqta/_hqta.yml
The following error occurred after #3974 was merged:
```
Failed to render models/staging/hqta/_hqta.yml from project calitp_warehouse: Parsing Error
[2025-06-11, 14:06:56 UTC] {pod_manager.py:435} INFO - [base]     Env var required but not provided: 'CALITP_BUCKET__PUBLISH'
```
This resolves that error by adding the `CALITP_BUCKET__PUBLISH` environment variable to DBT files and DAGs.
`poetry run dbt compile  --full-refresh`
> Resolve transform_warehouse issue caused by a missing bucket variable

- warehouse/macros/define_gtfs_guidelines.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__wheelchair_accessible_trips.sql
- warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__wheelchair_boarding_stops.sql
- warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__guideline_checks_long.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Adding **_Beyond Compliance_** section to the report website. This PR is the phase one of this project. In this phase, the necessary models and macros where built and modified. They will be used in the report website code. This is a new feature.   
```
jovyan@jupyter-fsalemi:~/data-infra/warehouse$ poetry run dbt run -s +stg_gtfs_quality__intended_checks
09:19:13  Running with dbt=1.5.1
09:19:17  Found 612 models, 1224 tests, 0 snapshots, 0 analyses, 854 macros, 0 operations, 13 seed files, 223 sources, 4 exposures, 0 metrics, 0 groups
09:19:17  
09:19:25  Concurrency: 8 threads (target='dev')
09:19:25  
09:19:25  
09:19:25  Finished running  in 0 hours 0 minutes and 7.80 seconds (7.80s).
jovyan@jupyter-fsalemi:~/data-infra/warehouse$ poetry run dbt run -s …
```
> Add and update wheelchair accessibility models and macros

- iac/cal-itp-data-infra-staging/logging/us/.terraform.lock.hcl
- iac/cal-itp-data-infra-staging/logging/us/audit_config.tf
- iac/cal-itp-data-infra-staging/logging/us/provider.tf
On PR #3983 we are running into an issue syncing metabase caused by a lack of audit tables in BigQuery. These are created by GCP's internal logging sink apparatus. This enables a log sink for those audit logs.
Watch `terraform apply` output and verify that audit logs are streamed to the right location.
> Enable staging audit logging

- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
After merging PR #3983, the Terraform service account is unable to apply changes related to BigQuery datasets. According to the documentation, the least-privileged prebaked role for dataset administration is `roles/bigquery.dataOwner`.
Addresses issue in #3983 
Monitor output of `terraform apply`
> Staging terraform is able to update bigquery datasets

- iac/cal-itp-data-infra-staging/logging/us/audit_config.tf
This re-applies the logging IAM permissions initially applied in #3983.
> Update logging permission configuration

- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
When running the dbt DAGs via Cosmos on staging, Airflow throws the following error:
```
cosmos.exceptions.CosmosDbtRunError: dbt invocation completed with errors: fct_payments_chargeback_transactions: Database Error in model fct_payments_chargeback_transactions (models/mart/payments/fct_payments_chargeback_transactions.sql)
Access Denied: Table cal-itp-data-infra-staging:staging_mart_payments.fct_payments_chargeback_transactions: Permission bigquery.rowAccessPolicies.create denied on table cal-itp-data-infra-staging:staging_mart_payments.fct_payments_chargeback_transactions (or it may not exist). at [3:9]
compiled Code at target/run/calitp_warehouse/models/mart/payments/fct_payments_chargeback_transactions.sql
```
Re-run failing Cosmos DAGs
> Make the composer service account a BigQuery data owner on staging

- docs/analytics_tools/jupyterhub.md
Adjust docs to new glogin instructions.  Removes suggestion of gcloud auth login which doesn't seem to be necessary.
Resolves #3876 
No
Make sure the docs get updated.
> Adjust docs to reflect glogin instructions

- .github/workflows/composer-apply-files.yml
- .github/workflows/composer-plan-files.yml
- iac/cal-itp-data-infra/airflow/us/.terraform.lock.hcl
- iac/cal-itp-data-infra/airflow/us/provider.tf
- iac/cal-itp-data-infra/airflow/us/storage_bucket_object.tf
- iac/cal-itp-data-infra/airflow/us/variables.tf
- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_acl.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_binding.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_policy.tf
- iac/cal-itp-data-infra/gcs/us/storage_default_object_acl.tf
This switches production Airflow deployment from from gsutil sync to terraform, matching staging. This starts syncing dbt so that cosmos can load.
Resolves #4010
> Update production composer deployment to use terraform

- iac/cal-itp-data-infra-staging/composer/us/environment.tf
- iac/cal-itp-data-infra-staging/composer/us/kubernetes.tf
- iac/cal-itp-data-infra-staging/gke/us/container_cluster.tf
- iac/cal-itp-data-infra-staging/iam/us/service_account_iam_member.tf
This PR adds Terraform configuration to allow Composer Service Account to authenticate via workload identity federation, like Github Actions, rather than by using a service account keyfile, which is not recommended. https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
Related to #3780
> Add GKE workload identity federation for composer service account

- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
This PR adds service account admin permissions to terraform service accounts needed to apply changes made on PR `Add GKE workload identity federation for composer service account` #4020.
Run `terraform plan`.
> Add service account admin permissions to terraform service accounts

- airflow/dags/cosmos_payment_dag.py
- airflow/dags/deploy_dbt_docs/deploy_dbt_docs_site.yml
- airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml
- airflow/dags/transform_warehouse_full_refresh/dbt_test.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_run_and_upload_artifacts_full_refresh_exclude_rt.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_run_and_upload_artifacts_select_rt.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_test_exclude_rt.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/dbt_test_select_rt.yml
This PR updates Cosmos payment DAG to use `DBT_TARGET` (prod or staging) as the target name to run correcly on Production.
Related to #3780
Tested running `cosmos_payment` DAG on Staging.
Run Cosmos payment DAG after the change to check if it uses the correct target.
> Fix target name on Cosmos payment DAG

- warehouse/scripts/run_and_upload.py
To complete the partial parse improvement as a dbt artifact, I've updated `run_and_upload.py` to include `partial_parse.msgpack`. This will upload it to `{CALITP_BUCKET__DBT_ARTIFACTS}/latest/`.
Related to #3908 and #4010 changes.
> Include partial_parse.msgpack when uploading latest dbt artifacts

- .github/workflows/deploy-dbt.yml
This adds a missing setup step that is causing the dbt github action workflow to fail when synchronizing the dbt directory to GCS: https://github.com/cal-itp/data-infra/actions/runs/16034393514/job/45242743985
Copied from other job steps
Monitor execution of deploy-dag.yml
> Add missing gcloud setup step from dbt Github Action

- iac/cal-itp-data-infra/cdn/us/backend_bucket.tf
- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf
- iac/cal-itp-data-infra/iam/us/iam_workload_identity.tf
- iac/cal-itp-data-infra/iam/us/variables.tf
This adds a bucket and CDN for the reports.dds.dot.ca.gov static site.
Relates to #3890 
Monitor `terraform apply` github action
> Create static site configuration for reports.dds.dot.ca.gov

- .github/workflows/deploy-dbt.yml
The [new dbt docs site](https://dbt-docs.dds.dot.ca.gov) is triggering a file download instead of displaying the index.htm page. This PR removes single quotes around the content-type so the site works correctly.
[#4028]
Removing quotes manually from content-type on files in the dbt-docs bucket made the site works.
Check if all files in the bucket have the correct content-type without quotes.
> Remove single quotes from dbt docs content-type files

- iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf
- iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/service_account_iam_member.tf
- warehouse/macros/create_row_access_policy.sql
@charlie-costanzo is using the SSO account and he is not able to see payments data anymore.
This PR changes the configuration to use DDS custom roles and service accounts to give access to payment’s tables instead of through individual emails.
[#4010]
Running `terraform plan` locally.
Check with @charlie-costanzo if he can see payment's data again.
> Review permissions for Developers and Analysts to access Payment tables

- iac/cal-itp-data-infra/iam/us/service_account_iam_member.tf
Adds missing configuration to enable authentication from https://github.com/cal-itp/reports
Relates to #3890 
> Add missing workload identity federation for reports

- .github/workflows/deploy-dbt.yml
- airflow/dags/create_external_tables/airtable/external_airtable_california_transit_ntd_agency_info.yml
- airflow/docker-compose.yaml
- warehouse/models/mart/payments/indexes/payments_tests_daily_date_spine.sql
This PR adds schema definition for `external_airtable.california_transit__ntd_agency_info` to specify column types.
Previous json files generated contain INTEGER fields with a decimal zero `.0`, so when the AUTO definition tries to create numeric columns as INTEGER it generates the conversion error `Could not convert value 'number_value: 	 "96120.0"' to integer`.
Also converted `original_due_date` and `fy_end_date` to STRING due to conversion error `400 Invalid date: '10/31/18' Field: original_due_date; Value: 10/31/18`
Resolves [#4021]
Running external table DAG locally.
Monitor DAGs to confirm the error were fixed.
> Fix conversion error on `external_airtable.california_transit__ntd_agency_info`

- airflow/dags/sync_elavon/METADATA.yml
- airflow/dags/unzip_and_validate_gtfs_schedule_hourly/METADATA.yml
- iac/cal-itp-data-infra-staging/composer/us/environment.tf
- iac/cal-itp-data-infra/composer/us/environment.tf
When deploying new composer environments, and enabling the `unzip_and_validate_gtfs_schedule_hourly` DAG, currently jobs are enqueued all the way back to 2021. This makes it so that new environments don't enqueue those old jobs. This also configures SMTP settings for staging and production.
Related to #3765 
Validated on staging
Monitor production environment
> Do not catchup old unzip/validate GTFS schedule data jobs

- airflow/dags/copy_prod_archiver_configs_to_test/METADATA.yml
- airflow/dags/create_external_tables/METADATA.yml
- airflow/dags/download_gtfs_schedule_v2/METADATA.yml
- airflow/dags/ntd_report_from_blackcat/METADATA.yml
- airflow/dags/parse_and_validate_rt_v2/METADATA.yml
- airflow/dags/parse_elavon/METADATA.yml
- airflow/dags/parse_littlepay/METADATA.yml
- airflow/dags/parse_littlepay_v3/METADATA.yml
- airflow/dags/publish_open_data/METADATA.yml
- airflow/dags/scrape_feed_aggregators/METADATA.yml
- airflow/dags/scrape_state_geoportal/METADATA.yml
- airflow/dags/sync_littlepay/METADATA.yml
- airflow/dags/sync_littlepay_v3/METADATA.yml
- airflow/dags/sync_ntd_data_api/METADATA.yml
- airflow/dags/sync_ntd_data_xlsx/METADATA.yml
- airflow/dags/transform_warehouse/METADATA.yml
- airflow/dags/transform_warehouse_full_refresh/METADATA.yml
- airflow/dags/transform_warehouse_full_refresh_sunday/METADATA.yml
Update DAG arguments `start_date` to a recent date and `catchup` to `False` reduce runs when creating new composer environments.
Part of testing and updating #3765
Checked Staging start date on DAG details.
> Update DAG arguments to reduce runs when creating new composer environments

- iac/cal-itp-data-infra/composer/us/environment.tf
After running all workloads on the new production cluster, it appears that more and higher-powered worker instances are required to run tasks.
Related to #3765
Converged and ran overnight, production console is now green 
> Bump production composer instance sizing

- iac/cal-itp-data-infra-staging/composer/us/environment.tf
This is the next incremental update to the Composer image, composer-2.8.4-airflow-2.6.3
Related to #3059 
terraform plan
Monitor terraform apply
> Bump staging composer to 2.8.4

- iac/cal-itp-data-infra-staging/composer/us/environment.tf
This advances the staging composer image further after the following error message:
```
Invalid image version: 'composer-2.8.4-airflow-2.6.3' derived based on your input. Currently supported environment update image versions are: [composer-3-airflow-2.10.5, composer-3-airflow-2.9.3, composer-3-airflow-2.10.2, composer-3-airflow-2.7.3, composer-2.13.6-airflow-2.10.5, composer-2.13.6-airflow-2.9.3, composer-2.13.5-airflow-2.10.5, composer-2.13.5-airflow-2.9.3, composer-2.13.4-airflow-2.10.5, composer-2.13.4-airflow-2.9.3, composer-2.13.3-airflow-2.10.5, composer-2.13.3-airflow-2.9.3, composer-2.13.1-airflow-2.10.5, composer-2.13.1-airflow-2.9.3, composer-2.12.1-airflow-2.10.5, composer-2.12.1-airflow-2.10.2, composer-2.12.1-airflow-2.9.3, composer-2.10.2-airflow-2.10.2, …
```
> Bump staging composer image to composer-2.8.6-airflow-2.6.3

- .github/workflows/deploy-kubernetes.yml
- .github/workflows/preview-kubernetes.yml
Habitat, originally by Chef, was acquired some years ago and we were using the community fork Biome but it still used Habitat's public package repository and the new owners recently shut down public use of the package repository
This has recently caused the Kubernetes CI jobs to start failing as they used Biome to install Hologit for generating a working tree of all Helm chart sources
This PR should fix this by installing Hologit through NPM instead of Biome—which only offered the advantage of guaranteeing the `git` version but current GitHub runners come with a new enough git version stock
Opening this PR will be the test, if the kicked-off `preview-kubernetes` action succeeds we're goo to go
> fix(ci): install hologit through NPM instead of Habitat/Biome

- airflow/.test.env
- airflow/dags/create_external_tables/kuba/device_properties.yml
- airflow/dags/sync_kuba/METADATA.yml
- airflow/dags/sync_kuba/README.md
- airflow/dags/sync_kuba/device_monitoring.yml
- airflow/docker-compose.yaml
- airflow/plugins/hooks/kuba_hook.py
- airflow/plugins/operators/__init__.py
- airflow/plugins/operators/kuba_to_gcs_operator.py
- airflow/plugins/src/bigquery_cleaner.py
- airflow/tests/conftest.py
- airflow/tests/hooks/cassettes/test_kuba_hook/TestKubaHook.test_run.yaml
- airflow/tests/hooks/test_kuba_hook.py
- airflow/tests/operators/cassettes/test_kuba_to_gcs_operator/TestKubaToGCSOperator.test_execute.yaml
- airflow/tests/operators/test_kuba_to_gcs_operator.py
- iac/cal-itp-data-infra-staging/composer/us/environment.tf
- iac/cal-itp-data-infra-staging/gcs/us/outputs.tf
- iac/cal-itp-data-infra-staging/gcs/us/variables.tf
- iac/cal-itp-data-infra/composer/us/environment.tf
- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_binding.tf
- iac/cal-itp-data-infra/gcs/us/variables.tf
This adds a bucket to capture raw Kuba output and adds a DAG to snapshot the current Kuba Device Monitoring API.
For future references, it needs: 
* `CALITP_BUCKET__KUBA` environment variable on Composer
* `airflow-connections-http_kuba` secret on secret-manager
* `calitp-kuba` bucket on production / `calitp-staging-kuba` bucket on staging
Relates to #3764 
Run sync_kuba and create_external_tables.kuba.device_properties on staging.
Test on production.
> Create Kuba sync and external table

- airflow/tests/conftest.py
- airflow/tests/hooks/cassettes/test_kuba_hook/TestKubaHook.test_run.yaml
This PR addresses a recent issue with #4083, which added VCR cassettes for the Kuba Proxima API. These VCR cassettes leaked a password string, and should instead filter the KUBA_PASSWORD.
`pytest`
Force-push to main and overwrite the password string
> Change VCR.py cassette request recording logic to scrub sensitive strings

- warehouse/models/mart/gtfs/fct_stop_time_arrivals_week.sql
- warehouse/models/mart/gtfs/fct_stop_time_updates_metrics_week.sql
- warehouse/models/mart/gtfs/fct_stop_time_updates_week.sql
- warehouse/models/mart/gtfs/fct_stop_time_updates_with_arrivals_week.sql
Materialize 1 week's worth `stop_time_updates`, `stop_time_arrivals`, `stop_time_metrics` for `WHERE service_date >= '2025-06-22' AND service_date <= '2025-06-28'` . Use this to inform:
* optimizations / table configurations related to all these tables if we want to use downstream aggregated metrics in a data product somewhere
* exploratory work related to the metrics to make sure everything looks reasonable before we compute across more dates 
* Merge this PR in so we can do more exploratory and warehouse work around it
* This is the main constraint why we aren't able to materialize downstream tables from all these upstream views immediately. `Cannot query over table 'cal-itp-data-infra-staging.external_gtfs_rt_v2.trip_updates' without a filter over column(s) 'base64_url', 'dt', 'hour' …
> materialize 1 week's worth of stop time update metrics

- docs/warehouse/developing_dbt_models.md
This PR updates the link for the JupyterHub onboarding video in the Data Services Documentation, from Google Drive to SharePoint.
Resolves https://github.com/cal-itp/data-infra/issues/4110
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here …
> Update JupyterHub onboarding video link

- docs/analytics_tools/python_libraries.md
This PR adds documentation for use of `GCSGeoPandas` Google Cloud Storage auth helper functions to the "Useful Python Libraries" page.
Resolves [#1547](https://github.com/cal-itp/data-analyses/issues/1547)
Follow-ups
> Document usage of GCSGeoPandas

- airflow/dags/dbt_manual_dag.py
This PR creates `dbt_manual` DAG without schedule to run models as needed. It also removes them from the `dbt_all`.
Initial tables requested to be in the new manual DAG:
* `fct_stop_time_arrivals_week`
* `fct_stop_time_updates_metrics_week`
* `fct_stop_time_updates_week`
* `fct_stop_time_updates_with_arrivals_week`
Resolves [#4113]
Tested on Composer Staging.
Confirm that `fct_stop_time_arrivals_week`, `fct_stop_time_updates_metrics_week`, `fct_stop_time_updates_week`, and `fct_stop_time_updates_with_arrivals_week` were excluded from `dbt_all` and included on `dbt_manual`.
> Create dbt_manual DAG without schedule to run models as needed

- warehouse/macros/gtfs_rt_stg_outcomes.sql
- warehouse/macros/gtfs_rt_stg_validation_notices.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__service_alerts.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__service_alerts_outcomes.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__trip_updates.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__trip_updates_outcomes.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__vehicle_positions.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__vehicle_positions_outcomes.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__service_alerts_validation_notices.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__service_alerts_validation_outcomes.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__trip_updates_validation_notices.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__trip_updates_validation_outcomes.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__vehicle_positions_validation_notices.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__vehicle_positions_validation_outcomes.sql
The `mart_gtfs.fct_trip_updates_summaries` is not able to run anymore due to the size and is cancelled by BigQuery returning the error reported on issue [#4103](https://github.com/cal-itp/data-infra/issues/4103).
In order to reduce the size from the beginning of the process, I am filtering the following staging tables to return only the last 6 months of data from the GTFS RT external tables (`WHERE dt >= DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH)`) and materializing to reduce the processing time and allowing cache to be used.
Added filter directly: 
* staging.stg_gtfs_rt__service_alerts
* staging.stg_gtfs_rt__trip_updates
* staging.stg_gtfs_rt__vehicle_positions
Added filter to macro `gtfs_rt_stg_outcomes` that filters:
* staging.stg_gtfs_rt__service_alerts_outcomes
* …
> Materialize Staging GTFS RT models and filter dt by the last 6 months

- .github/workflows/deploy-dbt.yml
- warehouse/macros/gtfs_rt_stg_outcomes.sql
- warehouse/macros/gtfs_rt_stg_validation_notices.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__service_alerts.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__service_alerts_outcomes.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__trip_updates.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__trip_updates_outcomes.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__vehicle_positions.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__vehicle_positions_outcomes.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__service_alerts_validation_notices.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__service_alerts_validation_outcomes.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__trip_updates_validation_notices.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__trip_updates_validation_outcomes.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__vehicle_positions_validation_notices.sql
- warehouse/models/staging/gtfs_quality/stg_gtfs_rt__vehicle_positions_validation_outcomes.sql
This PR changes the `dt` filter on Staging GTFS RT models to `>= '2025-07-01'` to try to run all the models.
In conversation with @vevetron, we decided to use the fix date '2025-07-01' to reduce more the range (instead of 6 months) to see if BigQuery is able to run successfully all models. The date is also fixed for now because we are planning incrementally add more dates.
I removed the previous materialization on `stg_` models since it didn't help the process.
Related to previous [PR 412](https://github.com/cal-itp/data-infra/pull/4126)
Also based on old full-refresh sundays DAG, I added `--exclude source:external_gtfs_rt+ source:gtfs_rt_external_tables+` to the command`poetry run dbt run ... --full-refresh` to avoid full-refresh on those models because of the size and incremental …
> Reduce more the dt filter on Staging GTFS RT models to run downstream models

- .github/workflows/deploy-dbt.yml
- warehouse/macros/gtfs_rt_stg_outcomes.sql
- warehouse/macros/gtfs_rt_stg_validation_notices.sql
- warehouse/models/mart/gtfs/fct_vehicle_positions_trip_metrics.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__service_alerts.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__trip_updates.sql
- warehouse/models/staging/gtfs/stg_gtfs_rt__vehicle_positions.sql
This PR is part of the work trying to fix issue #4103 to run stg_ GTFS TR models.
After meeting with @lauriemerrell, she explained that upstream tables were supposed to be filtered when incremental tables run accordantly with the filter there, so we probably don't need to have the filters on `dt` as we have been trying to do. So I am removing it to see it working as before.
Since `fct_vehicle_positions_trip_metrics` has not been able to run we are changing it to a View, just to keep the table but it will stop burning BigQuery resources when `dbt_all` DAG runs.
I am also removing `full-refresh` from `poetry run dbt compile` so make sure Macros return the correct date when building queries and hoping that it may help to speed the run process.
Running models locally.
```
❯ poetry run dbt run …
```
> Adjust GTFS RT models and configuration

- images/jupyter-singleuser/poetry.lock
- images/jupyter-singleuser/pyproject.toml
- kubernetes/apps/charts/jupyterhub/values.yaml
This PR 
* converts the `pyproject.toml` to adhere to Poetry v2's specifications
* bumps the default JupyterHub jupyter-singleuser image profile to use `2025.6.10` now that it's been tested by analysts for a couple weeks
* creates a new image profile for these changes to `pyproject.toml` and for where the other in-progress dependency upgrades will land
Resolves https://github.com/cal-itp/data-infra/issues/4136
> Update jupyter-singleuser pyproject.toml and start new image profile for dependency upgrades project

- kubernetes/apps/charts/jupyterhub/values.yaml
I tested `make setup_env` from `cal-itp/data-analyses/_shared_utils` and it worked as expected. I also checked the dependency versions on JupyterHub after deploying to a test image profile and they were updated as expected.
Resolves https://github.com/cal-itp/data-infra/issues/4139
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by …
> [images/jupyter-singleuser] Bump prototype image profile to 2025.8.1

- airflow/.development.env
This PR addresses some issues @mjumbewu and I faced while configuring a local Airflow environment, specifically related to Cosmos execution (the default parallelism is 32, which results in the airflow server getting reaped) and configuring the GCP connection.
Related to #3767 
`composer-dev start` and running DAGs against staging
> Tune settings for local Airflow environment

- warehouse/macros/incremental_max_date.sql
- warehouse/models/intermediate/gtfs/_int_gtfs.yaml
- warehouse/models/intermediate/gtfs/int_gtfs_rt__trip_updates_trip_day_map_grouping.sql
- warehouse/models/mart/gtfs/fct_trip_updates_trip_summaries.sql
Adjusts filters to reprocess last few days of data to catch all incoming trip updates.
Resolves #4103 
```
#This exact record was in both
SELECT * FROM `cal-itp-data-infra.mart_gtfs.fct_trip_updates_trip_summaries`
where service_date = '2025-07-14'
and trip_id = "468"
and base64_url = 'aHR0cHM6Ly9rYXJ0LmNvbm5leGlvbnoubmV0L3J0dC9wdWJsaWMvdXRpbGl0eS9ndGZzcmVhbHRpbWUuYXNweC90cmlwdXBkYXRl'
#These matched within reason
SELECT service_date, count(distinct(base64_url)), count(distinct(trip_id)) FROM `cal-itp-data-infra.mart_gtfs.fct_trip_updates_trip_summaries` 
group by 1
order by service_date DESC
I just did a visual check, i didn't do a full query based comparison of both tables.
```
IN PROD.  JUST FOR PROS WHEN PAIRING WITH @erikamov
```
➜  warehouse git:(productionize_trip_summaries) ✗ …
```
> Re-Productionizing trip update trip summaries

- kubernetes/apps/charts/jupyterhub/values.yaml
This PR promotes the jupyter-singleuser 2025.8.8 image to the Prototype image profile on JupyterHub.
Resolves https://github.com/cal-itp/data-infra/issues/4163
I tested 2025.8.8 in the Dependency Upgrades Testing Image profile first, running `make setup_env` in `data-analyses/_shared_utils` as well as attempting the import documented in this bug https://github.com/cal-itp/data-infra/issues/4169. Both worked as expected.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here to …
> [images/jupyter-singleuser] Promote 2025.8.8 to Prototype image profile

- airflow/dags/create_external_tables/kuba/device_properties.yml
- airflow/plugins/operators/kuba_to_gcs_operator.py
- airflow/tests/operators/cassettes/test_kuba_to_gcs_operator/TestKubaToGCSOperator.test_execute.yaml
- airflow/tests/operators/test_kuba_to_gcs_operator.py
This PR changes how Kuba device properties are partitioned in order to enable row-based access controls for agencies.
Resolves #3764 
`pytest`
Rebuild external table and data
> Analyst sees Kuba device properties partitioned by operator identifier

- warehouse/models/mart/benefits/fct_benefits_events.sql
This column is a JSON array inside a JSON object, so we need to use the `json_extract_flattened_column` macro to parse it correctly.
Follow up to #4166 / #4059
@erikamov tested with the correct function call that this macro expands to: https://cal-itp.slack.com/archives/C050ZNDUL21/p1755101944951569?thread_ts=1754936604.833429&cid=C050ZNDUL21
> Fix: Benefits extra_claims is a JSON array

- airflow/dags/sync_ntd_data_xlsx/scrape_ntd_xlsx_urls.py
This pull request resolves an issue with NTD scraping related to providing user agent strings that look like bots to the DOT WAF, by switching the user agent used for the request from `Cal-ITP/1.0.0` to Chrome 139. This also includes up to date security header definitions.
Resolves #4205 
`curl`
Monitor `sync_ntd_data_xslx` runs
> Request NTD Excel files with Chrome 139 user agent and security headers

- airflow/dags/dbt_all_dag.py
- airflow/dags/dbt_daily_dag.py
- airflow/dags/dbt_manual_dag.py
- warehouse/models/staging/audit/stg_audit__cloudaudit_googleapis_com_data_access.sql
Paired with @erikamov 
This table fct_bigquery_data_access wasn't updating every day.  We think it's because we switched to twice a week dbt_all runs
We looked at the staging table and the code was designed to only run every day.  Instead of updating the code with incremental_where we added this run to daily_dags and updated daily dags to run every day.
Related to #4142
Also we were noticing costs for the querys in https://github.com/cal-itp/data-infra/pull/4172 were high so we moved these test tables to dbt_manual.
Not tested yet.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will …
> Fix audit tables moving forward and move recent test tables to manual

- airflow/dags/parse_and_validate_rt_v2/METADATA.yml
This PR increases `parse_and_validate_rt_v2` timeout to 2 hours to allow tasks to have more time to process all files.
[#4197]
Just a config change, need to test the production DAG to see if it fixes it.
Monitor if `parse_and_validate_rt_v2` tasks are able to run.
> Increase `parse_and_validate_rt_v2` timeout to 2 hours

- warehouse/models/mart/benefits/fct_benefits_events.sql
Follow up to #4059 
We saw in Metabase charts that these two types of "empty" values were being counted separately, when really we want them to be combined. E.g.
```
SELECT
`mart_benefits.fct_benefits_events`.`event_properties_extra_claims`,
COUNT(*) as count
FROM
`mart_benefits.fct_benefits_events`
WHERE
`mart_benefits.fct_benefits_events`.`event_type` = 'returned enrollment'
AND
`mart_benefits.fct_benefits_events`.`event_properties_status` = 'success'
AND
`mart_benefits.fct_benefits_events`.`event_properties_enrollment_flows` = 'medicare'
GROUP BY
`event_properties_extra_claims`
ORDER BY
`event_properties_extra_claims` ASC
```
Result:
| Row | event_properties_extra_claims | count |
| ------ | -------------------------------------------- | ----- |
| 1 | _null_ | 38 |
| 2 | | 25 |
| 3 | …
> Fix: Coalesce blank and null Benefits extra_claims

- airflow/dags/unzip_and_validate_gtfs_schedule_hourly/unzip_gtfs_schedule.py
This PR reduces the parallelism for unzipping GTFS schedules, which is currently running out of resources.
Relates to #4198
`composer-dev`
Monitor execution in production
> Reduce parallelism for GTFS schedule unzipping

- iac/cal-itp-data-infra/composer/us/environment.tf
- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
This PR adjusts two Composer configuration through Terraform:
* Adds permission to `composer-service-account@cal-itp-data-infra.iam.gserviceaccount.com` to copy data to staging buckets. The permission will fix the error (bellow) on the DAG `copy_production_to_staging` created recently [#4195](https://github.com/cal-itp/data-infra/issues/4195).
```
403 GET https://storage.googleapis.com/storage/v1/b/calitp-staging-gtfs-rt-raw-v2/o?projection=noAcl&prefix=service_alerts%2Fdt%3D2025-08-23%2Fhour%3D2025-08-23T00%3A00%3A00%2B00%3A00%2F&delimiter=&prettyPrint=false: composer-service-account@cal-itp-data-infra.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).; 18559) …
```
> Adjust Composer permission and Size

- airflow/dags/copy_production_to_staging/airtable_california_transit.yml
- airflow/dags/copy_production_to_staging/airtable_transit_data_quality_issues.yml
- airflow/dags/copy_production_to_staging/airtable_transit_technology_stacks.yml
- airflow/dags/copy_production_to_staging/gtfs_aggregator_scrape_results.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_parsed_service_alerts.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_parsed_trip_updates.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_parsed_vehicle_positions.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_raw_v2.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_schedule_parsed.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_schedule_parsed_txt_results.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_validation_service_alerts.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_validation_trip_updates.yml
- airflow/dags/copy_production_to_staging/gtfs_rt_validation_vehicle_positions.yml
- airflow/dags/copy_production_to_staging/gtfs_schedule_download_configs.yml
- airflow/dags/copy_production_to_staging/gtfs_schedule_download_outcomes.yml
- airflow/dags/copy_production_to_staging/gtfs_schedule_unzip_outcomes.yml
- airflow/dags/copy_production_to_staging/gtfs_schedule_validation_notices.yml
- airflow/dags/copy_production_to_staging/gtfs_schedule_validation_outcomes.yml
- airflow/dags/copy_production_to_staging/state_highway_network.yml
This PR add tasks to `copy_production_to_staging` DAG to copy buckets and paths that generates external tables.
NTD, Kuba, and Payments buckets were not included.
Resolves [#4195]
Tested on Airflow staging.
Review logs to confirm tasks are running successfully on production.
> Configure copy_production_to_staging DAG tasks

- airflow/dags/dbt_payments_dag.py
We noticed an issue with our Littlepay Settlements Email Reports from Metabase sometimes being delivered without data, captured in #4222. After investigating, we determined that this was occurring because the `dbt_payments_dag` is not being run on the weekends, although agencies reply on payments warehouse tables being run 7 days a week to provide daily reconciliations. This PR adds Saturday and Sunday to the DAG's schedule.
Resolves #4222 
Verify the DAG is being run and data is available after merge
> Payments: adjust dbt_payments_dag to also run on weekends

- images/jupyter-singleuser/Dockerfile
This is required to run accessibility checks on portfolio sites 
references: #3977
- [x ] Bug fix (non-breaking change which fixes an issue)
built container locally
ran `portfolio/portfolio.py check-accessibility` to verify error was resolved.
> Add chrome browser to jupyterhub-singleuser

- airflow/dags/parse_and_validate_rt_v2/METADATA.yml
This PR disables retries for the `parse_and_validate_rt_v2` DAG.
Relates to #4197 
Local execution
> Disable retries for parse_and_validate_rt_v2

- images/jupyter-singleuser/poetry.lock
With this PR, I'm downgrading `jupyterlab` with the intention that image 2025.8.28 be re-built and pushed again incorporating this change. 
Analysts reported weird new notebook rendering behavior with the 2025.8.22 version of the image. After inspection, it became clear the cause of the issue was related to upgrading `jupyterlab` from 3.6.8 to 4.4.6. For now, we want to downgrade it to 3.6.8 and wait until the maintained fix the issues in 4.5.0.
https://github.com/jupyterlab/jupyterlab/issues/15968#issuecomment-3202107050
https://github.com/jupyterlab/jupyterlab/issues/17449#issue-2972861170
Relates to https://github.com/cal-itp/data-analyses/issues/1670
The bug was confirmed to be introduced with 2025.8.22 by attempting and failing to reproduce the issues on 2025.8.8. This is also a …
> [images/jupyter-singleuser] Fix JupyterHub notebook rendering issue

- airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates.yml
Create new dag task for external table creation of new NTD API ridership table
Resolves #4208
local airflow
make sure it runs in production, create warehouse tables
> NTD: external table dag task for ridership API endpoint

- iac/cal-itp-data-infra/composer/us/environment.tf
This PR restores lower settings for Composer to pre-backfill status
Relates to #4197 
Configuration
Monitor production composer environment
> Restore the old Composer provisioning

- iac/cal-itp-data-infra/composer/us/environment.tf
This PR re-enables an option to trigger a DAG at a certain date, which was disabled by default in Airflow 2.7.
Relates to #4284 
Configuration
> Enable Composer trigger configuration popup option when starting a DAG

- docs/analytics_tools/python_libraries.md
- images/jupyter-singleuser/poetry.lock
- images/jupyter-singleuser/pyproject.toml
This PR updates the JupyterHub image to use `calitp-data-analysis` v2025.8.10, which includes a deprecations for `tbls` and supporting code. The PR also updates the "Useful Python Libraries" documentation to reflect this deprecation and the shift away from siuba generally. The documentation now includes useful examples for migrating away from siuba and encourages use of `query_sql()`.
Relates to https://github.com/cal-itp/data-infra/issues/3361
> [images/jupyter-singleuser] Update calitp-data-analysis & add siuba migration docs

- iac/cal-itp-data-infra/gcs/us/outputs.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_acl.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_binding.tf
- iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf
- iac/cal-itp-data-infra/gcs/us/storage_default_object_acl.tf
This PR changes `calitp-ntd-api-products` bucket location to `us-west2` through Terraform.
It is currently using `US` region and since all data was clean up in order to fix some data changes, we can replace the location now without having to copy any data.
This change is important to keep buckets at the same region as BigQuery and part of the Cost Savings plan: [Chore: Review buckets’ location #3712](https://github.com/cal-itp/data-infra/issues/3711)
It also deletes the unused test bucket `test-calitp-ntd-api-products` replaced by `calitp-staging-ntd-api-products`.
Tested running `terraform plan` locally.
Confirm if the correct region `us-west2`  was set to `calitp-ntd-api-products` bucket.
> Change `calitp-ntd-api-products` bucket location to `us-west2`

- airflow/dags/parse_and_validate_rt_filtered.py
- airflow/plugins/operators/gcs_to_gtfs_rt_command_operator.py
- airflow/tests/operators/test_gcs_to_gtfs_rt_command_operator.py
This PR fixes de issue of removing equals sign from base64 url from GCSToGTFSRTCommandOperator that processes parse and validate files.
Also created a temporary DAG `parse_and_validate_rt_filtered` to run all the base64 urls that contains equal signs from 2025-07-08. 
Resolves [#4304]
Tested locally using pytest: `poetry run pytest tests/operators/test_gcs_to_gtfs_rt_command_operator.py`.
Tested on Staging Airflow and it run succesfully.
Turn on `parse_and_validate_rt_filtered` to re-run all parse and validate commands for base64 url that contains equals signs.
> Do not remove equals sign from base64 urls

- airflow/dags/parse_and_validate_rt_filtered.py
Limit parse_and_validate_rt_filtered to run maximum 128 tasks at a time since we need to re-run all past urls from 07/08/2025 and don't want to block other DAGs. #4284
Using the same strategy used before in https://github.com/cal-itp/data-infra/pull/4281/files.
Just configuration.
> Add active tasks limit to `parse_and_validate_rt_filtered`

- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/service_account.tf
As we onboard VCTC to the payments data pipeline, we need to add their new payments agency reader service account to Terraform so as to include their data in the pipeline via our row-based access control policy.
Resolves #4312
#4309
> payments: create and add new service account for VCTC RBAC policy to terraform

- airflow/dags/create_external_tables/ntd_data_products/multi_year__track_and_roadway_by_agency.yml
- warehouse/models/staging/ntd_annual_reporting/stg_ntd__track_and_roadway_by_agency.sql
This PR changes the data type from `NUMERIC` to `BIGNUMERIC` to fix `Invalid NUMERIC value` error accepting longer values on `track_and_roadway_by_agency.sum_total_miles`.
[#4276]
Compiled external table on Airflow Staging:
Running models:
Confirm if `dbt_all` is able to run successfully `fct_track_and_roadway_by_agency`
> Use bignumeric on `track_and_roadway_by_agency. sum_total_miles` to fix INVALID number

- airflow/Makefile
- iac/cal-itp-data-infra/composer/us/environment.tf
This PR bumps production's Google Cloud Composer version to `composer-2.9.7-airflow-2.7.3`
Resolves #3768 
Ran subset of DAGs on staging
Monitor production DAG runs
> Bump production composer to composer-2.9.7-airflow-2.7.3

- iac/cal-itp-data-infra-staging/networks/us/compute_address.tf
- iac/cal-itp-data-infra-staging/networks/us/outputs.tf
- iac/cal-itp-data-infra-staging/sftp/us/enghouse/enghouse-sftp-endpoint.tf
ref: #4048
Mount the sftp data directory such that it is owned by the sftp-user. This will allow `setstat` from sftp clients.
Assign a static ip to the deployment service so that it doesnt change when redeployed.
- [x ] Bug fix (non-breaking change which fixes an issue)
> Mount sftp data directory with ownership, Assign static ip

- iac/cal-itp-data-infra/iam/us/project_iam_member.tf
- iac/cal-itp-data-infra/iam/us/service_account.tf
As we onboard El Dorado to the payments data pipeline, we need to add their new payments agency reader service account to Terraform so as to include their data in the pipeline via our row-based access control policy.
Resolves #4346 
n/a
#4348
> Payments (El Dorado Transit): create and add new service account for RBAC policy to terraform

- airflow/plugins/hooks/ckan_hook.py
- airflow/tests/conftest.py
This PR changes how the CKANHook resolves the host when connecting to the Open Data portal to incorporate the configured `conn_type` (i.e., https), rather than leaving it unspecified.
`pytest`
Monitor execution on staging
> Analyst sees that the CKAN hook gets the correct URL
