airflow/dags/gtfs_static_downloader.py
fix a datetime.datetime.today() call to replace with datetime.datetime.now()
=> fix datetime

airflow/data/agencies.yml
Update the agency list again, let's get to 100% coverage
=> update list of agencies urls

airflow/dags/gtfs_downloader/email_failures.py
@hunterowens merging since this addresses your comment on #25, but def let me know if you'd want to review changes like these first.
=> michael also gets those sweet sweet failure emails

airflow/plugins/calitp.py
=> fix name of dag folder env var on prod

airflow/dags/gtfs_downloader/METADATA.yml
@hunterowens are you also getting emailed on dev failures? If so, I can disable that before merging, so we don't get blasted with failure emails (sorry it took me getting added to the emails for me to ask this question ;).
=> [WIP] add Michael to task failure emails

airflow/data/agencies.yml
This PR updates the agencies YML file for many D4 agencies pulled by @mcplanner. Note, I caught a couple broken ITP_IDs in here, which seems to have been a result of the underlying data changing between loads?
=> update D4 agencies

airflow/data/agencies.yml
Confirmed GTFS feeds and corrected Cal-ITP ID for the Modesto Area Express
=> Corrected MAX's Cal-ITP ID

.github/workflows/lint.yml, .markdownlint.yaml, README.md, airflow/README.md
- De-lint's existing markdown
- Adds `.markdownlint.yaml` config for editors and CI
- Adds workflow steps to existing lint workflow to check markdown files
- Fixes unrelated syntax issue in existing lint workflow
=> style: conform README to markdown linting

.devcontainer/devcontainer.json, .vscode/extensions.json
Turn off whitespace differences in preview...I also cleaned up the inconsistent tabs/spaces that letting vscode create and edit files manifested
=> vscode: recommended extensions for docs

script/docs-server
v1.2.1 has been released with the previous issue fixed: https://github.com/mkdocs/mkdocs/issues/2448
=> fix(docs): unpin mkdocs

airflow/dags/gtfs_downloader/generate_provider_list.py, airflow/data/agencies.yml
This PR addresses #146, by changing agencies.yml to use a `feeds` field. I also addressed #117 by adding an assertion that checks for duplicate itp_id keys (and removed one case of this from the data; duplicate top-level entries for presidio shuttle).
Note that each feed has entries for all rt urls, with null values when they weren't specified. Happy to remove, if feels cleaner to not keep these null entries in.
Here's the code I used to migrate, in case it's useful:
```python
import yaml
from itertools import zip_longest
old_agencies = yaml.safe_load(open("data/agencies.yml"))
headers = ["gtfs_schedule_url", "gtfs_rt_vehicle_positions_url", "gtfs_rt_service_alerts_url", "gtfs_rt_trip_updates_url"]
new_agencies = {}
for k_agency, entry in old_agencies.items():
rt_urls = …
```
=> Refactor agencies yml

airflow/data/agencies.yml
=> Fix schedule link for La Campana Shuttle

airflow/dags/gtfs_schedule_history/validation_report.yml
More validator report field types. Going to merge and check on pipeline..
=> fix(airflow): add more validator field types

airflow/plugins/operators/csv_to_warehouse_operator.py, airflow/requirements.txt
Alright, tested this one very carefully running airflow locally. @cvc5185 do you mind pulling this PR and checking that the sandbox DAG succeeds?
=> fix(airflow): retry fix to CsvToWarehouseOperator

airflow/data/agencies.yml
changes DASH names to LADOT. cc @thekaveman @machow
=> change DASH to LADOT

.pre-commit-config.yaml, docs/services/gtfs-rt-archive.md, services/gtfs-rt-archive/Dockerfile, services/gtfs-rt-archive/gtfs-rt-archive.py
=> GTFS-RT Data Archiving

airflow/data/agencies.yml
As mentioned in issue #49 
* Updated Foothill, Manteca
* Removed E-Tran (they're part of SacRT now)
* South County and Paso Express are part of SLORTA, so I removed those entries as duplicates
=> fixed errors flagged in daily reports

kubernetes/apps/charts/metabase/values.yaml, kubernetes/apps/values/metabase.yaml
=> Metabase hostname dashboards.calitp.org

airflow/dags/gtfs_loader/validation_report_process.py
Blocking #227 , related to loading validation schema #90. The gist is that there is a validation field "fieldValue" that can either be a string or an int. However, bigquery does not like this. Even though we code it as a string in the schema, bigquery complains that it is getting an integer.
The change below fixes this by coercing specified fields to string, when processing validation results. Will merge, then clear processing for July 31, when this issue occured in the results.
(tested by running on dev)
=> fix(airflow): coerce specified validation fields to strings

airflow/dags/sandbox/example_feeds.sql, airflow/dags/sandbox/example_validations.sql, airflow/dags/sandbox/example_validations_changes.sql, docs/datasets/gtfs_schedule.md
Creating demo tables for the sandbox dataset to show basic analyses, dependencies, and metabase.
=> document warehouse

airflow/dags/sandbox/example_validations_changes.sql
Quick fix, while pairing w/ @cvc5185 on docs
=> fix: removed staging hardcoding in sandbox view

airflow/dags/sandbox/example_feeds.sql
Last PR I swear, we just need to reviews these tables in metabase 😅
=> fix: corrected destination table name in sandbox

airflow/dags/payments_loader/customer_funding_source.sql, airflow/dags/payments_loader/device_transactions.sql, airflow/dags/payments_loader/micropayment_device_ids_fare_type.sql, airflow/dags/payments_loader/update_materialized.sql
Demonstration PR, don't merge. See #245
=> WIP: Littlepay ETL fixes

airflow/dags/gtfs_schedule_history2/calitp_schedule_feeds.sql
WIP for creating a gfts schedule feed snapshot table. Still need to add columns and add md5 hashes to track changes
=> GTFS schedule feed snapshot table

airflow/data/agencies.yml
=> Corrected Unitrans' static data

kubernetes/apps/charts/metabase/templates/metabase.yaml
=> fix(kubernetes/metabase): prevent kill loops on long startups

kubernetes/apps/overlays/gtfs-rt-archive-release/kustomization.yaml, services/gtfs-rt-archive/gtfs-rt-archive.py
ISO 8601 timestamps are more easily made sense of by human eyes
=> Timestamp refactor

services/gtfs-ckan-uploader/calitp_data_ca_exporter.py
=> fix(CKAN): remove extra stop_times download

airflow/dags/gtfs_views/gtfs_schedule_fact_daily_service.sql
Adds feed_key to daily service, so we can join with dimensional table
=> fix(content): add feed_key to daily service view

airflow/dags/gtfs_views/gtfs_schedule_fact_daily_trips.sql
pairing w/ @cvc5185, noticed we're missing a trips key
=> fix(content): gtfs schedule daily trips missing trips key

airflow/dags/gtfs_views/dim_date.yml
this will let us filter to see feed publish dates at the beginning of a selected month on metabase
=> feat(content): add is_month_start to dim date

airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feeds.sql
Adds two new columns
* days_until_feed_end_date - how long until this feed ends?
* days_from_feed_start_date - how long ago did this feed start
* is_feed_published_date_valid - are those above values both >= 0?
=> feat(content): gtfs schedule daily feeds days to/from published

airflow/dags/gtfs_views/gtfs_schedule_fact_daily_stops.sql
Adds a fact table for daily stops, so we can count them up for the gtfs schedule dashboard
=> feat(content): add gtfs schedule daily_feed_stops

docs/datasets/transitstacks.md
small update to diagram. will refine once we start working on ingestion / exploration.
=> docs(transitstacks): update erd

airflow/dags/gtfs_views/dim_metric_date.sql, airflow/dags/gtfs_views/gtfs_schedule_fact_route_id_changes.sql
Pairing w/ anthony on gtfs schedule, going to merge
=> feat(airflow): add dim_metric_date, track route and stop changes

airflow/dags/gtfs_views/gtfs_schedule_data_feed_trip_stops_latest.sql
From pairing w/ @charlie-costanzo on adding a tutorial. Need to tweak how the golden view is calculated.
=> fix(content): golden view name and correctly filter latest data

README.md
This PR updates the README to more accurately reflect how to find docs etc.
=> feat: change readme to reflect updates since ... March

airflow/data/agencies.yml
Adds a GCS url with the Amtrak feed for temporary use.
=> feat: add amtrak

airflow/dags/payments_views/mst_transactions_gtfs_enhanced.sql, airflow/dags/payments_views/payments_feeds.sql
This should let us see SBMTD in the [MST transit dashboard](https://metabase.k8s.calitp.jarv.us/dashboard/3?transit_provider=mst).
@mjumbewu do you mind double checking, and merging? Feel free to make any changes! Once it's available in the dashboard, do you mind letting people know in [this slack thread..](https://cal-itp.slack.com/archives/C02CYPQKHH8/p1632343593002300)?
=> fix(payments): remove custom mst filters, add payments_feeds table

airflow/dags/rt_loader/parse_rt_vehicle_positions.py
I noticed that the RT tasks were being killed without logs, which often indicates a resource issue. I've made some adjustments that appear to drop memory usage down from 2Gb+ to 500Mb. (mainly clearing a cache, handling thread pool better)
=> fix(gtfs-rt): handle memory usage for rt parsing

airflow/dags/payments_loader/authorisations.yml, airflow/dags/payments_loader/calitp_included_payments_tables.py, airflow/dags/payments_loader/device_transaction_purchases.yml, airflow/dags/payments_loader/product_data.yml, airflow/dags/payments_loader/productdata.yml, airflow/dags/payments_loader/refunds.yml, airflow/dags/payments_loader/settlements.yml
Adds remaining Littlepay data exports to the ingested tables. Ran this code in Airflow locally to ensure correct names. Data loads into staging correctly.
=> Add device_transaction_purchases (and other Littlepay tables) to ingested data

airflow/README.md
I picked the wrong project upon gcloud initialization. It appears there aren't the properly configured google storage buckets in staging.
=> Note gcloud project selection requirement

docs/_config.yml
To documentation GitHub options and connected repository branch to main rather than master
=> feat:documentation added edit page button 

.github/workflows/publish-docs.yml, docs/_config.yml, docs/_toc.yml, docs/ci/Git-Flow-Services.md, docs/intro.md, docs/kubernetes/README.md, docs/warehouse/01_agencies.md
added -warnings is error and --keep going flags so sphinxs warnings will fail in github action. Second commit will be the fix to resolve the errors
=> feat:documentation- change config file to fail on sphinx warning

airflow/dags/gtfs_views/gtfs_schedule_fact_route_id_changes.sql, airflow/dags/gtfs_views/gtfs_schedule_fact_stop_id_changes.sql
Fixes https://github.com/cal-itp/data-infra/issues/666 by adding appropriate task dependencies so that daily updates are included in these tables.
=> Add additional dependencys for tasks in gtfs_views

.github/ISSUE_TEMPLATE/new-team-member.md, .github/ISSUE_TEMPLATE/user-story.md
@holly-g this is the unconventional way that I got the issue template to appear last time, your new user story issue template should hopefully show up now
=> Bypassed github admin settings to get user story issue template to appear

kubernetes/apps/values/metabase.yaml
This change was deployed this morning in order to perform the maintenance for #610
=> apps/metabase: upgrade v0.38.2 -> v0.41.1

.github/workflows/publish-docs.yml, docs/warehouse/02_agencies.md
Resolves https://github.com/cal-itp/data-infra/issues/677.
This PR depends on #701.
This previously failed on the publish-docs workflow action, but is now fixed. [See updated publish-docs workflow run here](https://github.com/cal-itp/data-infra/runs/4172811587?check_suite_focus=true).
=> Update agency secret workflow docs

airflow/dags/gtfs_downloader/METADATA.yml, airflow/dags/gtfs_downloader/email_failures.py, airflow/dags/gtfs_loader/METADATA.yml, airflow/dags/gtfs_schedule_history/METADATA.yml, airflow/dags/gtfs_schedule_history2/METADATA.yml, airflow/dags/gtfs_views/METADATA.yml, airflow/dags/gtfs_views_staging/METADATA.yml
Also remove @mcplanner's DOT email.
=> Add Evan Siroky to airflow email failures

CODEOWNERS
Remove @hunterowens from most things, remove @themightychris from everything (fixes https://github.com/cal-itp/data-infra/issues/723), add @evansiroky to a bunch of stuff.
=> Update codeowners a bit

airflow/dags/gtfs_views/reports_gtfs_schedule_index.sql
Hardcodes the hiding of two private feeds:
- Amtrak
- Tulare County Regional Transit Agency
=> Hide certain feeds in reports

airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feed_files.sql, airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feeds.sql
This PR adds info about feed parse errors to daily fact tables about feeds and feed files respectively.
=> Add parse error stats to feed and files fact tables

docs/analytics_publishing/how_to_publish.md, docs/analytics_tools/notebooks.md, docs/analytics_tools/python_libraries.md, docs/analytics_tools/storing_data.md, docs/contribute/submitting_changes.md
Addressing these issues: 
python libraries #732
how to publish #793
submitting changes #739
=> (docs): expand python libraries, how to publish, and submitting changes

.github/ISSUE_TEMPLATE/new-team-member.md
Added:
* missing meetings
* missing slack channels
* 'reports to'
Reformatted the layout
=> Updates to the new team member issue template

docs/analytics_examples/warehouse_tutorial.md, docs/analytics_onboarding/overview.md, docs/analytics_tools/overview.md, docs/analytics_tools/saving_code.md, docs/analytics_welcome/how_we_work.md, docs/analytics_welcome/overview.md
analytics_onboarding/overview:
* Added more detail to jupyterbook, added brief reference to BigQuery
analytics_welcome/how_we_work:
* added missing meetings and slack channels
* removed unnecessary channel
* cleaned up project board section
analytics_welcome/overview:
* shortened a lengthy link
analytics_tools/oveview: 
* made layout more intuitive
* removed unnecessary wordiness
analytics_welcome/how_we_work:
* added internal link to 'personal access token section'
analytics_tools/saving_code:
* fixed broken link pointing to 'personal access token' section
analytics_examples/tutorial:
* reordered queries to make more sense
=> Updated docs information for new hires re meetings, slack channels

docs/analytics_tools/saving_code.md, docs/analytics_welcome/how_we_work.md
Holly added great information to the `analytics_tools/saving_code` section, but some conflicts were created when we merged PR #831. I opened a new PR that added Holly's content, and also removed content that would be outdated as a result in 'analytics_welcome/how_we_work`
=> Reconciling Holly's 'saving_code' branch with PR #831

airflow/dags/rt_loader_files/calitp_files_process.py, airflow/dags/rt_loader_files/external_calitp_files.sql
Should fix errors parsing RT files introduced by #852. I have docker running airflow v2 right now, so need to spin things up to test, before switching this out of being a draft.
=> fix(gtfs-rt): fix typecasting for rt files

airflow/dags/gtfs_views/gtfs_schedule_dim_feeds.sql, airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feeds.sql
This is a work in progress until it can be figured out how to match the raw feed extraction date with the rest of the data in the dim feeds table.
=> Load raw RT urls into dim feeds

docs/analytics_tools/saving_code.md
* Resolve the `git merge` section
* Add more helpful hints of common GitHub commands to Saving Code
GH issue: #733
=> (docs): saving code, add more GitHub commands

kubernetes/apps/charts/jupyterhub/values.yaml
Resolves (so we believe):
- #634 
- #684
=> jupyterhub/values: add proxy-body-size to ingress annotations

airflow/data/agencies.yml
Also confirmed that all agencies with two real time options have those options properly grouped.
=> Added all agency-specific feeds for the MTC region

airflow/data/agencies.yml
These won't work unless they're https.
=> Update OCTA URLs

.github/ISSUE_TEMPLATE/update_gtfs.md, .github/PULL_REQUEST_TEMPLATE/update_gtfsdata_pr.md
We may only want/need one of these, but I think they could be useful, especially for articulating a checklist.
=> Add PR and Issue templates for updating GTFS data

airflow/dags/gtfs_views/validation_fact_notice_fields.py
addresses #900 
* fixes a high memory brought on by validation_fact_notice_fields loading everything into memory up front
* TODO: test locally
=> fix(gtfs-schedule): validation notice fields

kubernetes/apps/charts/jupyterhub/values.yaml
Added new image release version to values.yml
=> Update jupyterhub image release version to kubernetes cluster

airflow/dags/gtfs_downloader/email_failures.py, airflow/dags/payments_loader/METADATA.yml, airflow/dags/payments_views/METADATA.yml, airflow/dags/payments_views_staging/METADATA.yml, airflow/dags/rt_loader/METADATA.yml, airflow/dags/rt_loader_files/METADATA.yml, airflow/dags/rt_views/METADATA.yml, airflow/dags/sandbox/METADATA.yml, airflow/dags/transitstacks_loader/METADATA.yml, airflow/dags/transitstacks_views/METADATA.yml
Fixes #854
- Adds @evansiroky to the rest of the DAG failure emails
- Adds @o-ram to daily feed download email
=> Email a few more people from DAG tasks

docs/analytics_tools/python_libraries.md, docs/analytics_welcome/how_we_work.md
This PR will:
/analytics_welcome/how_we_work:
* update the link under the lunch n learn section to point to the new youtube playlist
* reorder headers to make more sense intuitively
/analytics_tools/python_libraries:
* add query_sql as helpful function within the calitp library section
=> Misc Docs Updates - adding lunchnlearn recordings, adding function to python libraries

airflow/data/agencies.yml
Added LACMTA-managed la-puente
=> Add La Puente and El Segundo

.github/pull_request_template.md
Now that #908 is fixed, refer PR authors to checking the GitHub action.
=> Update agencies.yml PR checklist

airflow/plugins/operators/amplitude_to_warehouse.py
This PR simply sets up the Python module that will contain our Airflow operator and the function for creating a DataFrame from Amplitude data. 
This is a base from which we can work on other issues for epic #960.
=> Set up module for Amplitude ingestion

ci/vars/releases/jupyterhub-prod.env, kubernetes/apps/charts/jupyterhub/values.yaml
As part of a pairing session with @lottspot, removed the memory limitation in the jupyterhub values.yml and created a production deployment environment
=> Jupyterhub memory increase

airflow/dags/rt_loader_files/calitp_files_process.py
Resolves #1123 by changing `calitp_files_process` to glob the past  **two** days of data. This way data that had not yet been written as of midnight UTC will be picked up on the second run (idea credit to @mjumbewu). This will resolve the issue where the 2300 hour seems to have worse performance than it actually does, because the files simply haven't finished writing at the time that the globbing completes. 
Downstream tasks are running into the `query limit` issue that @atvaccaro described on Slack, but I don't think it's related -- I can run the query directly in BigQuery and confirmed that the data looks ok.
This PR updates the `rt_loader_files` DAG in order to update the following DAG tasks:
- `calitp_files_process`: lookback for 2 days to ensure that all files ultimately get picked …
=> fix(gtfs-rt): expand globbing window so we get all files in calitp_files

airflow/dags/rt_views/gtfs_rt_validation_code_descriptions.py
This creates a DAG task to read in a sheet that contains the list of RT validation error descriptions and whether or not each error is considered a critical error. This resolves (partially) #1009.
This PR updates the `rt_views` DAG in order to add a task to download a sheet with RT error descriptions.
Adds the following DAG tasks:
- `rt_views.gtfs_rt_validation_code_descriptions`
=> Add RT validation code descriptions

kubernetes/apps/manifests/gtfs-rt-archive/archiver-app-vars.yaml
Reverts cal-itp/data-infra#1213
=> Revert "change log level back to debug"

.github/workflows/publish-docs.yml, .github/workflows/push_to_gcloud.yml, .github/workflows/service-build.yml, .github/workflows/service-release.yml, .github/workflows/update_gcloud_requirements.yml
see https://github.com/cal-itp/data-infra/runs/5646646205?check_suite_focus=true
=> update gcloud action to v0

airflow/dags/gtfs_downloader/METADATA.yml, airflow/dags/gtfs_downloader/email_failures.py, airflow/dags/gtfs_loader/METADATA.yml, airflow/dags/gtfs_schedule_history/METADATA.yml, airflow/dags/gtfs_schedule_history2/METADATA.yml, airflow/dags/gtfs_views/METADATA.yml, airflow/dags/gtfs_views_staging/METADATA.yml, airflow/dags/payments_loader/METADATA.yml, airflow/dags/payments_views/METADATA.yml, airflow/dags/payments_views_staging/METADATA.yml, airflow/dags/rt_loader/METADATA.yml, airflow/dags/rt_loader_files/METADATA.yml, airflow/dags/rt_views/METADATA.yml, airflow/dags/sandbox/METADATA.yml, airflow/dags/transitstacks_loader/METADATA.yml, airflow/dags/transitstacks_views/METADATA.yml
Updates DAG failure alert configurations to notify current staff, by removing Michael and including Blake & Jameelah.
=> Update alert configs to notify current staff

kubernetes/apps/values/metabase-preprod.yaml
=> Upgrade metabase to v0.42.3

.github/workflows/service-release-candidate.yml, kubernetes/apps/charts/metabase/values.yaml, kubernetes/apps/values/metabase-preprod.yaml, kubernetes/apps/values/metabase.yaml, kubernetes/apps/values/postgresql-backup-metabase.yaml
This deploys #1299 and #1303 into production
=> Deploy metabase remediations into production

.github/workflows/build-gtfs-rt-parser.yml
follow-up from https://github.com/cal-itp/data-infra/pull/1272#discussion_r842057004
=> also build the gtfs rt parser image on the workflow file changing

airflow/plugins/operators/__init__.py
=> remove this again

kubernetes/apps/values/metabase-preprod.yaml, kubernetes/apps/values/metabase.yaml
=> Upgrade metabase to 0.42.3

ci/vars/releases/prod-airflow-jobs.env, kubernetes/apps/manifests/airflow-jobs/kustomization.yaml, kubernetes/apps/manifests/airflow-jobs/ns.yaml, kubernetes/apps/values/metabase-preprod.yaml, kubernetes/apps/values/metabase.yaml
This deploys the upgrade merged in #1347
=> Deploy metabase v0.42.3

airflow/dags/sandbox/METADATA.yml
closes https://github.com/cal-itp/data-infra/issues/1357
I've created `sandbox_pool` in airflow https://o1d2fa0877cf3fb10p-tp.appspot.com/pool/edit/3
=> only allow 1 sandbox task at a time

kubernetes/apps/charts/jupyterhub/values.yaml
merge after https://github.com/cal-itp/calitp-py/pull/57
=> bump to hub v11

airflow/dags/transform_warehouse/dbt_run_and_upload_artifacts.yml, airflow/dags/transform_warehouse/dbt_test.yml, warehouse/Dockerfile, warehouse/scripts/run_and_upload.py
Note this still deploys to a preview URL; will deploy to the prod site when we feel comfortable (i.e. when @lauriemerrell has merged her GTFS work I think?)
=> actually run dbt test, and deploy the docs!

ci/vars/releases/prod-promtail.env, kubernetes/apps/values/promtail.yaml
=> Deploy promtail values file into production

kubernetes/apps/values/promtail.yaml
=> Deploy lokiAddress fix into production

kubernetes/apps/values/promtail.yaml
Without this, the promtail push attempts are 404'ing
=> Add path component to URL for promtail instances

kubernetes/apps/values/promtail.yaml
=> Deploy promtail url path into production

kubernetes/apps/values/promtail.yaml
=> Deploy monitoring toleration fix into production

services/gtfs-ckan-uploader/README.md
Update the CKAN script readme to include a notes about the size of stop times and included the data portal site for convenience.
=> Docs(CKAN): update readme to have website and note about resource ids

warehouse/README.md
Adds more detail to the `warehouse/README` for dbt setup.
These are the instructions that @charlie-costanzo and I used to get dbt set up for ourselves.
=> dbt: clarify setup steps in README

.github/pull_request_template.md
**Description**
The purpose of this new template is to formalize and standardize our PR process (following a team meeting that agreed to adopt this workflow). In a PR, we would like to be able to clearly and concisely communicate the what, why, and how, and ensure that code reviewer(s) have the relevant context and information they need to review/test the proposed changes.
=> Update PR template to standardize workflow

kubernetes/apps/charts/jupyterhub/values.yaml
Bumped up jupyterhub `values.yml` to `hub-v12`
Resolves cal-itp/data-analyses/#205
=> k8s: bumped up jupyterhub values.yml to hub-v12

docs/analytics_tools/saving_code.md
Coming out of conversation in the Analyst Round Table meeting, I added information on options for how to resolve merge conflicts in Pull Requests.
=> docs(github): added information on options for how to resolve merge conflicts

warehouse/README.md
I got feedback from @mjumbewu that I should delete the extra context in the sample `profiles.yml` for clarity.
=> dbt: simplify readme per feedback

airflow/data/agencies.yml
Reverts cal-itp/data-infra#1592
Bringing these back; seems to have been a coincidence.
=> Revert "Revert "Add all current MTC 511 agencies""

airflow/data/agencies.yml
Angel Island-Tiburon Ferry Company published data for their ferry company on MTC 511. This PR adds the URLs for this respective feed.
Confirmed with agency, downloaded locally.
=> Update links for Angel Island-Tiburon Ferry Company

warehouse/README.md
This PR updates the warehouse README with more detailed setup instructions that should work from scratch and minimize other method/workarounds.
We went through this fresh last week on @edasmalchi's machine.
=> Update dbt docs

airflow/requirements.txt
=> use good version of typing extensions

warehouse/scripts/run_and_upload.py
We renamed `Warehouse Views` to `Data Marts (formerly Warehouse Views)`.
=> update metabase database names again

kubernetes/apps/charts/jupyterhub/values.yaml
@edasmalchi ran out of space with the current config; a 4x increase is reasonable.
=> bump jupyterhub storage to 32gi

warehouse/profiles.yml
=> bump to 30m

.github/ISSUE_TEMPLATE/new-team-member.md
Fixed added missing meetings, deleted old meetings. Deleted auto-assign.
=> Update new-team-member.md issue template

kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/archiver-channel-vars.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-release/kustomization.yaml, services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py, services/gtfs-rt-archiver-v3/pyproject.toml
Adds additional logging context, renders logs as JSON, and cleans up some exception type formatting in logs.
Already deployed v3.1.1
=> RT archiver logging improvements

ci/vars/releases/prod-sftp-ingest-elavon.env, kubernetes/apps/charts/jupyterhub/values.yaml, kubernetes/apps/manifests/gtfs-rt-archiver-v3/archiver-app-vars.yaml, kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml, kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-ticker.yaml, kubernetes/apps/manifests/gtfs-rt-archiver-v3/kustomization.yaml, kubernetes/apps/manifests/gtfs-rt-archiver-v3/redis.yaml, kubernetes/apps/manifests/sftp-server/intranet-service.yaml, kubernetes/apps/manifests/sftp-server/kustomization.yaml, kubernetes/apps/manifests/sftp-server/sshd_config, kubernetes/apps/manifests/sftp-server/workload.yaml, kubernetes/apps/overlays/base-sftp-ingest-elavon/kustomization.yaml, kubernetes/apps/overlays/base-sftp-ingest-elavon/sftp-user.yaml, kubernetes/apps/overlays/dev-sftp-ingest-elavon/kustomization.yaml, kubernetes/apps/overlays/dev-sftp-ingest-elavon/ns.yaml, kubernetes/apps/overlays/dev-sftp-ingest-elavon/sftp-user-config.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/archiver-channel-vars.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/consumer.patch.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/ns.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/ticker.patch.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/archiver-channel-vars.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/ns.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-release/kustomization.yaml, kubernetes/apps/overlays/prod-sftp-ingest-elavon/internet-service.yaml, kubernetes/apps/overlays/prod-sftp-ingest-elavon/kustomization.yaml, kubernetes/apps/overlays/prod-sftp-ingest-elavon/ns.yaml, kubernetes/apps/overlays/prod-sftp-ingest-elavon/patch-volume-size.json, kubernetes/apps/overlays/prod-sftp-ingest-elavon/sftp-user-config.yaml
Deploys changes merged in #1692 into production
=> Deploy Elavon SFTP ingest server into production

kubernetes/apps/charts/jupyterhub/values.yaml
=> deploy voila fix

airflow/dags/publish_open_data/publish_california_open_data.yml, docs/publishing/sections/8_ckan.md, warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml, warehouse/scripts/dbt_artifacts.py, warehouse/scripts/publish.py, warehouse/scripts/run_and_upload.py
Saves dbt artifacts in timestamped partitions in addition to `latest/`.
Improves `publish.py` in a variety of ways: simplifies the logging and configuration; uses env vars for configuration; allows reading manifest from GCS. Also changes documentation to reflect these changes.
Resolves https://github.com/cal-itp/data-infra/issues/1679
Locally, will test in local Airflow before merging.
```
[2022-08-30 21:47:15,349] {pod_launcher.py:198} INFO - Event: publish-california-open-data.c89d1e266796436fb0aad503b1fd93b1 had an event of type Running
[2022-08-30 21:47:15,514] {pod_launcher.py:149} INFO - reading manifest from gs://test-calitp-dbt-artifacts/latest/manifest.json
[2022-08-30 21:47:15,738] {pod_launcher.py:149} INFO - writing 17 rows to …
```
=> Improvements to dbt artifacts and publish workflow

jobs/gtfs-rt-parser-v2/Dockerfile, jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py, jobs/gtfs-rt-parser-v2/poetry.lock, jobs/gtfs-rt-parser-v2/pyproject.toml
Closes https://github.com/cal-itp/data-infra/issues/1727
Updates RT validation with a named/commented file from GitHub. Saves the version in output metadata.
Also fixes a bug with downloading schedule data via gcsfs; the method call was expecting a directory path not a full path to a file, so the actual file ended up in a nested directory (gcsfs creating `/dir/filename` as a _directory_ to then put the file in). This caused the RT validator to be unable to find the zipped schedule data.
Locally and in docker-compose.
```
[2022-09-01 16:38:27,149] {pod_launcher.py:149} INFO - WARNING: no validation output file found in /tmp/tmp_nis3egj/rt_f8ef61327fcda12658d1a10c4e04c611/feed__2022-08-15T16:59:40Z.results.json
[2022-09-01 16:38:27,153] {pod_launcher.py:149} INFO - writing 119 lines to …
```
=> Set RT validator version as metadata and fix a bug

CODEOWNERS
I'm not as active anymore in the day-to-day stuff here and am getting a lot of notifications that I don't need to act upon. Therefore, I'm proposing to remove myself from everything except agencies.yml stuff.
Hasn't been tested.
=> Remove evansiroky from most CODEOWNERS items

airflow/requirements.txt, kubernetes/apps/overlays/gtfs-rt-archiver-v3-dev/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, services/gtfs-rt-archiver-v3/Dockerfile, services/gtfs-rt-archiver-v3/poetry.lock, services/gtfs-rt-archiver-v3/pyproject.toml
=> Hotfix jinja

airflow/data/agencies.yml
Updates RT URLs as specified in #1777.
Resolves #1777 
Verified that all URLs work; both service alert files are empty except for version information (not uncommon)
=> update Anaheim and Santa Maria RT URLs

airflow/dags/parse_and_validate_rt_v2/METADATA.yml, airflow/dags/unzip_and_validate_gtfs_schedule/METADATA.yml
quick fix, data interval starts yesterday not today
=> start date needs to be one day prior cause data interval

kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/archiver-channel-vars.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/archiver-channel-vars.yaml
=> missed this

airflow/dags/create_external_tables/METADATA.yml, airflow/dags/transform_warehouse/METADATA.yml, airflow/dags/transform_warehouse_full_refresh/METADATA.yml
Closes https://github.com/cal-itp/data-infra/issues/1718
locally
=> run external tables daily and adjust emails

warehouse/scripts/run_and_upload.py
We should actually check if the docs deploy subprocess succeeded as the error message is easy to miss in the Airflow logs. I've already updated the k8s secret with the new Netlify token.
Closes https://github.com/cal-itp/data-infra/issues/1818
Tested locally in docker-compose/k8s.
=> actually check if netlify deploys succeeded

jobs/gtfs-rt-parser/Dockerfile
=> fix this image building

airflow/data/agencies.yml, airflow/data/headers.yml
=> Add RT data for eTrans

.github/workflows/terraform-deploy.yml, .github/workflows/terraform-report.yml, .gitmodules, iac/terraform/.gitignore, iac/terraform/deployments/gcp-components/.terraform.lock.hcl, iac/terraform/deployments/gcp-components/terraform.tf, iac/terraform/deployments/gcp-components/vars.tf, iac/terraform/targets/dev/gcp-components/target.tfbackend, iac/terraform/targets/dev/gcp-components/target.tfvars, iac/terraform/targets/local/README.md, iac/terraform/targets/local/gcp-components/.gitignore, iac/terraform/targets/local/gcp-components/target.tfvars, iac/terraform/targets/prod/gcp-components/target.tfbackend, iac/terraform/targets/prod/gcp-components/target.tfvars
This changeset introduces a skeleton through which Terraform resources can be tracked and managed.
Resolves #1719
=> Terraform integration

airflow/data/agencies.yml
Adds some GTFS-RT URLs for Torrance Transit.
Downloaded locally. Secrets updated.
=> Add GTFS-RT URLs for Torrance Transit

airflow/data/agencies.yml, airflow/data/headers.yml
Adds a Swiftly Feed for the SF Bay Ferry.
Downloaded locally
=> Add swiftly feed for SF Bay Ferry

airflow/dags/gtfs_downloader/download_data.py, airflow/data/agencies.yml, airflow/data/headers.yml, script/agencies_verify.py
Adds some Umo IQ URLs for Bear Transit.
=> Add Bear Transit Umo IQ URLs and header

airflow/data/agencies.yml
Updates all URLs that use HTTP to use HTTPS protocol instead.
Using CI test to make sure each feed can download.
=> Update all HTTP URLs to HTTPS

airflow/data/agencies.yml, airflow/data/headers.yml
Adds Swiftly URL's to agencies.yml and authorization key to headers.yml
Manual check to be done due to API Key.
=> Add Torrance Transit Swiftly URLs and Header

.github/workflows/build-gtfs-rt-archiver-v3-image.yml, .github/workflows/build-jupyter-singleuser-image.yml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml, services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py, services/gtfs-rt-archiver-v3/pyproject.toml
The new image is already deployed.
=> add bear transit api key to v3, build the RT image in ci/cd

kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml
quick follow-up to https://github.com/cal-itp/data-infra/pull/1741, I forgot to update the prod image tag too
=> update prod image, I missed this

warehouse/models/mart/gtfs/_mart_gtfs.yml, warehouse/models/mart/gtfs/fct_vehicle_locations.sql, warehouse/models/mart/gtfs/fct_vehicle_positions_messages.sql, warehouse/poetry.lock, warehouse/pyproject.toml
I am _not_ actually trying to clean the "trips" more than right now. I want/need some input on the scope of this model. 
Example query showing too-fast position changes
```
with joined as (
select locations.dt
, locations.key
, next_locations.key
, locations.location_timestamp
, locations.header_timestamp
, locations.vehicle_timestamp
, locations.position_latitude
, locations.position_longitude
, next_locations.location_timestamp
, next_locations.header_timestamp
, next_locations.vehicle_timestamp
, next_locations.position_latitude
, next_locations.position_longitude
, ST_DISTANCE(locations.position, next_locations.position)                                AS DISTANCE
, TIMESTAMP_DIFF(next_locations.location_timestamp, locations.location_timestamp, SECOND) AS seconds_in_between
, …
```
=> Initial cleaned vehicle positions/locations model

airflow/data/agencies.yml, airflow/data/headers.yml
Updates Tahoe Transportation District RT feeds as well as Manteca's schedule feed.
Resolves # [1939]
Downloaded locally (API needs to be tested)
=> Update Tahoe RT and Manteca schedule feed

airflow/dags/unzip_and_validate_gtfs_schedule/unzip_gtfs_schedule.py, jobs/gtfs-schedule-validator/gtfs_schedule_validator.py
Currently, the Schedule validate job raises an error if any validation throws an exception; we should be using a threshold like everywhere else. I also noticed the unzip job does not check for any exceptions, so I also changed it to check against a threshold.
```
[2022-11-08 16:45:37,375] {pod_launcher.py:149} INFO - got 217 successes and 1 failures
[2022-11-08 16:45:37,376] {pod_launcher.py:149} INFO - saving 218 to gs://test-calitp-gtfs-schedule-validation/validation_job_results/dt=2022-11-07/results.jsonl
[2022-11-08 16:45:43,652] {pod_launcher.py:198} INFO - Event: validate-gtfs-schedule.b6a25fba0a42438e95128792f829a1f9 had an event of type Succeeded
[2022-11-08 16:45:43,652] {pod_launcher.py:311} INFO - Event with job id validate-gtfs-schedule.b6a25fba0a42438e95128792f829a1f9 …
```
=> add failure thresholds for schedule unzip/validate

airflow/dags/create_external_tables/airtable/external_airtable_california_transit_gtfs_service_data.yml, warehouse/models/mart/transit_database/_mart_transit_database.yml, warehouse/models/mart/transit_database/dim_gtfs_service_data.sql, warehouse/models/staging/transit_database/_stg_transit_database.yml, warehouse/models/staging/transit_database/stg_transit_database__gtfs_service_data.sql
Resolves https://github.com/cal-itp/data-infra/issues/1963
This model does have a failing test, but it's expected.
Locally.
=> add schema for gtfs_service_data and remove deleted column

warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml, warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__shapes_for_all_trips.sql, warehouse/models/mart/gtfs_quality/fct_daily_feed_guideline_checks.sql, warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Migrate existing check
I looked through several examples of PASS and FAIL to ensure the feeds looked as expected.
I created and ran a test on this int table.
=> migrate check for shapes-for-all-trips

warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml, warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__technical_contact_listed.sql, warehouse/models/mart/gtfs_quality/fct_daily_feed_guideline_checks.md, warehouse/models/mart/gtfs_quality/fct_daily_feed_guideline_checks.sql, warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Migrate existing technical contact check to v2.
Verified pass and fail results.
=> new technical contact check

docs/publishing/sections/8_ckan.md, warehouse/models/gtfs_schedule_latest_only/_gtfs_schedule_latest_only.yml, warehouse/scripts/dbt_artifacts.py, warehouse/scripts/publish.py
Closes https://github.com/cal-itp/data-infra/issues/1776
Closes https://github.com/cal-itp/data-infra/issues/1780
* Adds retries as the resource level
* Tried to PATCH resource file types but got a 404, likely a permissions thing
* Add field description authorities
* Only pass through the numeric value for EPSG
* Uppercase CSV headers
I have an email thread going with CDOT about the 500s we're experiencing; the retries help but do not fix the problem.
=> make changes per chads email; add retries; log errors

warehouse/scripts/dbt_artifacts.py
See https://cal-itp.slack.com/archives/C0332307HKM/p1669118811933679
```
➜  warehouse git:(fix-manifest-seed-parsing) ✗ poetry run python scripts/dbt_artifacts.py
./target/manifest.json is a valid Manifest!
./target/run_results.json is a valid RunResults!
```
=> add seed and source as missing node types

.github/workflows/build-gtfs-aggregator-checker-image.yml, .github/workflows/build-gtfs-rt-parser-image.yml, .github/workflows/build-gtfs-rt-parser-v2-image.yml, .github/workflows/build-gtfs-schedule-validator-image.yml, .github/workflows/build-warehouse-image.yml, airflow/requirements.txt, images/dask/requirements.txt, images/jupyter-singleuser/poetry.lock, images/jupyter-singleuser/requirements.txt, jobs/gtfs-aggregator-checker/poetry.lock, jobs/gtfs-rt-parser-v2/poetry.lock, jobs/gtfs-rt-parser/poetry.lock
We have various open PRs from dependabot trying to update dependencies. This PR handles those as well as sets up a bit more CI/CD testing.
https://github.com/cal-itp/data-infra/pull/2002
https://github.com/cal-itp/data-infra/pull/1979
https://github.com/cal-itp/data-infra/pull/1978
https://github.com/cal-itp/data-infra/pull/1846
https://github.com/cal-itp/data-infra/pull/1845
https://github.com/cal-itp/data-infra/pull/1842
https://github.com/cal-itp/data-infra/pull/1840
See CI/CD.
=> update dependencies flagged by dependabot

kubernetes/apps/manifests/gtfs-rt-archiver-v3/gtfs-rt-archiver-consumer.yaml
I mean to do this in the probes PR
=> forgot this; we want 5 consumers in prod

airflow/data/agencies.yml
Updates agencies.yml to the latest feed information found on [LACMTA's GitHub](https://github.com/LACMTA/los-angeles-regional-gtfs).
Hasn't.
=> Update to latest feed data on LACMTA GitHub

warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.sql
I had neglected to add int table name to rt checks table - getting used to new data model, clearly!
passed `./dbt.sh build --select +fct_daily_rt_feed_guideline_checks+`
=> add missing rt check

warehouse/models/intermediate/transit_database/int_transit_database__service_datasets_pivoted.sql
This PR removes a CTE that was supposed to be deduping Torrance's two "primary" quartets for the same service. The logic was buggy I think (alphabetic sorting was not behaving how I thought, my bad) and also the underlying data has been fixed in Airtable now.
Resolves one of the errors in: https://sentry.calitp.org/organizations/sentry/issues/15474/?environment=cal-itp-data-infra&project=2&query=is%3Aunresolved+message%3A%22test.calitp_warehouse.unique_dim_provider_gtfs_data_service_key.b143d47c20+-+Got+3+results%2C+configured+to+fail+if+%21%3D+0+DbtTestFail+False%22&statsPeriod=14d
`dbt run` and `dbt test`
=> Remove buggy torrance deduping

airflow/dags/check_data_freshness/METADATA.yml, airflow/dags/check_feed_aggregators/METADATA.yml, airflow/dags/download_gtfs_schedule_v2/METADATA.yml, airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py, airflow/dags/gtfs_downloader/METADATA.yml, airflow/dags/gtfs_downloader/email_failures.py, airflow/dags/gtfs_loader/METADATA.yml, airflow/dags/gtfs_schedule_history/METADATA.yml, airflow/dags/gtfs_schedule_history2/METADATA.yml, airflow/dags/parse_and_validate_rt/METADATA.yml, airflow/dags/parse_and_validate_rt_v2/METADATA.yml, airflow/dags/payments_loader/METADATA.yml, airflow/dags/rt_loader_files/METADATA.yml, airflow/dags/sandbox/METADATA.yml
Updates email notifications list to:
1. Bring v2 schedule downloader into alignment with v1 
2. Remove outdated email addresses
N/A
=> Update email failure list

airflow/data/agencies.yml
Fixes #2071
Downloaded locally
=> Add cerritos on wheels

.github/workflows/push_to_gcloud.yml
Fix based on https://github.com/google-github-actions/setup-gcloud/issues/561
CI passing on https://github.com/cal-itp/data-infra/pull/2090
=> try to fix ci

.github/workflows/build-warehouse-image.yml
quick fix, I shouldn't have changed the image build conditions on pushes to main in https://github.com/cal-itp/data-infra/pull/2076
CI should run
=> always build on warehouse changes on main

kubernetes/apps/charts/jupyterhub/values.yaml
I'd like to be able to parallelize via processes rather than just threads.
=> remove cpu limit on a jupyter user pod

airflow/dags/parse_and_validate_rt_v2/parse_rt_service_alerts.yml, airflow/dags/parse_and_validate_rt_v2/parse_rt_trip_updates.yml, airflow/dags/parse_and_validate_rt_v2/parse_rt_vehicle_positions.yml, airflow/dags/parse_and_validate_rt_v2/validate_rt_service_alerts.yml, airflow/dags/parse_and_validate_rt_v2/validate_rt_trip_updates.yml, airflow/dags/parse_and_validate_rt_v2/validate_rt_vehicle_positions.yml, jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py, jobs/gtfs-rt-parser-v2/poetry.lock, jobs/gtfs-rt-parser-v2/pyproject.toml
Closes https://github.com/cal-itp/data-infra/issues/2106 (once the jobs are cleared back to 2022-12-03).
gcsfs 2022.05 silently fails to download files if given a directory as the destination, and then the RT validator fails with a file-not-found error which we haven't been monitoring well.
This PR also adds Sentry logging to the RT file processing. We should be starting to use Sentry in processing jobs as well, I think; we can set alerts that will help us catch issues sooner. We should start using this in more places IMO.
Locally; I've also confirmed that validator call exceptions end up in [Sentry](https://sentry.calitp.org/organizations/sentry/issues/36041/?environment=development&project=2&query=is%3Aunresolved&statsPeriod=24h).
```
[2023-01-03 01:57:53,949] {pod_launcher.py:149} INFO …
```
=> fix RT files failing to validate in v2

kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/archiver-channel-vars.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/consumer.patch.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml, services/gtfs-rt-archiver-v3/poetry.lock, services/gtfs-rt-archiver-v3/pyproject.toml
Hotfix for https://sentry.calitp.org/organizations/sentry/issues/36069/?environment=cal-itp-data-infra&project=2&query=is%3Aunresolved
Also shrink the test archiver while I'm at it
Deployed to test and prod.
=> Upgrade calitp

airflow/dags/parse_and_validate_rt_v2/validate_rt_service_alerts.yml, airflow/dags/parse_and_validate_rt_v2/validate_rt_trip_updates.yml, airflow/dags/parse_and_validate_rt_v2/validate_rt_vehicle_positions.yml, airflow/dags/transform_warehouse_full_refresh/dbt_run_and_upload_artifacts.yml, airflow/dags/transform_warehouse_full_refresh/dbt_test.yml, warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml, warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__outcome_validator_versions.sql, warehouse/models/mart/ad_hoc/_mart_ad_hoc.yml, warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml, warehouse/models/mart/gtfs_quality/fct_daily_schedule_feed_validation_notices.sql
Fix some small issues found during storm analysis work.
* Missing/incorrect resource requests caused dbt jobs to get crushed by validation jobs
* Validation notices need to be version-aware for key uniqueness
Resolves https://github.com/cal-itp/data-infra/issues/2131
=> Post-storm analysis dbt cleanup

warehouse/macros/gtfs_rt_stg_outcomes.sql, warehouse/models/intermediate/gtfs/_int_gtfs.yaml, warehouse/models/intermediate/gtfs/int_gtfs_schedule__joined_feed_outcomes.sql, warehouse/models/mart/gtfs/fct_schedule_feed_downloads.sql
Quick parsing of `Last-Modified` headers.
Resolves https://github.com/cal-itp/data-infra/issues/1993
=> pull through a parsed last-modified header

warehouse/models/staging/gtfs/_stg_gtfs.yml, warehouse/models/staging/gtfs/gtfs_quality/_stg_gtfs_quality.yml
Closes https://github.com/cal-itp/data-infra/issues/2135
The project compiles, not really able to test removing tests?
=> remove staging gtfs tests

warehouse/models/mart/audit/_mart_audit.yml
Several tests written for the table being brought into the staging project no longer hold true, and needed revision. New filters have been added to two sets of tests, and another test has been (at least temporarily) removed in order to investigate underlying behavior before revision.
Ran local dbt tests within the staging version of the project.
=> Hotfix bigquery cost table tests

airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
=> provide schema to airtable services external table

images/dask/requirements.txt, images/jupyter-singleuser/poetry.lock, images/jupyter-singleuser/pyproject.toml, images/jupyter-singleuser/requirements.txt, kubernetes/apps/charts/dask/values.yaml, kubernetes/apps/charts/jupyterhub/values.yaml
Deploys https://github.com/cal-itp/calitp-py/pull/95
Maybe we should use https://github.com/machow/dbcooper-py at some point?
in a notebook; this is deployed already
=> update calitp in jupyter/dask images, update k8s

warehouse/macros/define_gtfs_guidelines.sql, warehouse/macros/gtfs_rt_stg_outcomes.sql, warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml, warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.md, warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.md, warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.sql, warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Reverts cal-itp/data-infra#2180
=> Revert "new check for rt modification date presence"

warehouse/macros/define_gtfs_guidelines.sql, warehouse/macros/gtfs_rt_stg_outcomes.sql, warehouse/models/intermediate/gtfs/gtfs_quality/_int_gtfs_quality.yml, warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__modification_date_present_rt.sql, warehouse/models/mart/gtfs_quality/fct_daily_guideline_checks.md, warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.md, warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_guideline_checks.sql, warehouse/models/staging/gtfs/gtfs_quality/stg_gtfs_quality__intended_checks.sql
Checks for presence of modification date for each RT file. 
Update macro to properly assign last-modified timestamp (i confirmed that they are being pulled through)
`./dbt.sh build -s int_gtfs_quality__modification_date_present_rt+`
=> mod date check, bug fix, featuring the actual sql file this time

warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__feed_aggregator_rt.sql, warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__feed_aggregator_schedule.sql, warehouse/models/mart/gtfs/dim_shapes_arrays.sql
couple small post-merge fixes
`env BIGQUERY_KEYFILE_LOCATION=/Users/andrewvaccaro/.jarvus/bq_svc_acct.json poetry run dbt test --profiles-dir . --target prod_service_account -m fct_daily_organization_combined_guideline_checks fct_daily_service_combined_guideline_checks fct_daily_guideline_checks` passes with flying colors
=> Post airtable merge fixes

kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/archiver-channel-vars.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml, services/gtfs-rt-archiver-v3/docker-compose.yml, services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/consumer.py, services/gtfs-rt-archiver-v3/gtfs_rt_archiver_v3/tasks.py, services/gtfs-rt-archiver-v3/pyproject.toml
Minor tweaks based on instability today
Already deployed!
=> Additional archiver configuration

warehouse/models/mart/transit_database/_mart_transit_database.yml
Adds missing docs & tests for the organizations/NTD agency info bridge table.
Locally.
=> add missing docs for organization/ntd bridge

kubernetes/apps/values/metabase.yaml
=> upgrade metabase

.holo/sources/jarvus-cluster-template.toml, airflow/docker-compose.yaml, kubernetes/apps/charts/metabase/templates/ingress.yaml, kubernetes/apps/charts/sentry/values.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/archiver-channel-vars.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/archiver-channel-vars.yaml, kubernetes/apps/values/metabase.yaml, kubernetes/kind/.gitignore, kubernetes/kind/cluster.yaml, kubernetes/system/kustomization.yaml
I also updated AIrflow to point at the new Sentry domain.
=> Upgrading k8s

warehouse/models/intermediate/gtfs/gtfs_quality/int_gtfs_quality__data_license.sql
In manual QA I saw a manual check value that didn't match what's in Airtable. Hurrah for manual testing!
=> bugfix: map correct airtable field to check

warehouse/models/mart/ntd/_mart_ntd.yml
I imported new data so this test is no longer accurate.
=> remove NTD dim bad test

images/jupyter-singleuser/Dockerfile, images/jupyter-singleuser/pyproject.toml
@amandaha8 may have hit an issue with an outdated gcloud CLI in jupyter, so updating here.
I built the image.
=> update gcloud version in jupyter singleuser image

airflow/dags/create_external_tables/airtable/external_airtable_california_transit_modes.yml, airflow/dags/create_external_tables/ntd_data_products/annual_database_agency_information.yml
Quick follow-up to https://github.com/cal-itp/data-infra/pull/2138
Ran the offenders locally.
=> disable required filters on new tables

airflow/dags/create_external_tables/gtfs_schedule_v2/gtfs_schedule_validations_outcomes.yml
Resolves https://github.com/cal-itp/data-infra/issues/2291
=> do not require partition filters on schedule validation outcomes

kubernetes/apps/charts/jupyterhub/values.yaml
Actually deploys the image built in https://github.com/cal-itp/data-infra/pull/2279
n/a
=> point hub at new jupyter singleuser image

warehouse/macros/define_gtfs_guidelines.sql, warehouse/models/mart/gtfs_quality/fct_daily_organization_combined_guideline_checks.sql, warehouse/models/mart/gtfs_quality/fct_daily_service_combined_guideline_checks.sql
A few changes that I meant to get into #2304 -- linting had failed and I didn't notice
See #2304
=> Apply guidelines macro updates

warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml, warehouse/poetry.lock, warehouse/scripts/run_and_upload.py
Apparently a string with a space is not the same as two separate string arguments when calling `subprocess` 🤦 
This PR does stop syncing payments docs to Metabase since we're planning on v2 soon and I don't expect them to be changed/maintained right now.
Fully passes locally using the actual `scripts/run_and_upload.py`
=> finally get dbt-metabase fully passing?

warehouse/profiles.yml
Couple quick changes based on new huge full refresh findings
=> dbt tweaks for new RT lookback

airflow/plugins/operators/littlepay_raw_sync.py, airflow/plugins/operators/littlepay_to_jsonl.py
Follow-up from biweekly sync meeting; I forgot to use the actual `ProcessingOutcome` model we try to use everywhere.
Run locally.
=> use actual processing outcome class for littlepay

.github/workflows/build-dbt.yml
Fix CI issue on https://github.com/cal-itp/data-infra/pull/2371; I thought I changed the arguments here but must've missed. Since there's only one command now, typer does not create a `viz` subcommand for the app.
Will cherry-pick to other branch.
=> fix calling visualize in ci

airflow/dags/airtable_loader_v2/generate_gtfs_download_configs.py
Resolves https://github.com/cal-itp/data-infra/issues/2436
Long-term we should probably just push these to a prometheus pushgateway and alert via grafana.
Ran locally.
```
[2023-03-29, 10:44:10 EDT] {logging_mixin.py:137} INFO - loading raw airtable records from gs://test-calitp-airtable/california_transit__gtfs_datasets/dt=2023-03-29/ts=2023-03-29T14:43:47.423324+00:00/gtfs_datasets.jsonl.gz
[2023-03-29, 10:44:14 EDT] {logging_mixin.py:137} INFO - got 523 valid configs out of 552 total records; skipped 29
[2023-03-29, 10:44:14 EDT] {logging_mixin.py:137} INFO - Invalid records:
[2023-03-29, 10:44:14 EDT] {logging_mixin.py:137} INFO - Skipped records:
[2023-03-29, 10:44:14 EDT] {logging_mixin.py:137} INFO - Historic TIME Alerts https://tularetransit.com/gtfs-rt/alerts
...
```
=> fix alerting on download configs; account for skipped records

warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__feed_aggregator.sql, warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__feed_listed.sql, warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__schedule_download_success.sql, warehouse/models/intermediate/gtfs_quality/guidelines_checks/int_gtfs_quality__trip_planners.sql, warehouse/models/intermediate/gtfs_quality/int_gtfs_quality__scheduled_trip_version_summary.sql, warehouse/tests/validate_guidelines_checks_rows_per_check_matches_index.sql
A bunch of small guidelines checks cleanup items as outlined in #2439. 
TODO after merge:
* full refresh on trip version summaries to get changes in concat
Resolves #2439
Ran guidelines checks long + its immediate parents, tested guidelines checks long
=> Guideline reindexing cleanup

warehouse/models/intermediate/gtfs/_int_gtfs.yaml, warehouse/models/mart/gtfs/_mart_gtfs_dims.yml, warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml, warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
* Adds a few more exceptions for Auburn that I missed in #2465 yesterday -- handles the following Sentry issues:    
* https://sentry.calitp.org/organizations/sentry/issues/69999/
* https://sentry.calitp.org/organizations/sentry/issues/69998/
* https://sentry.calitp.org/organizations/sentry/issues/70000/
* Removes the test that was causing this Sentry issue: https://sentry.calitp.org/organizations/sentry/issues/70016 -- can't have a relationships test on an array column
I wrote up issue #2469 to follow up on the other new related test failure.  
Resolves Sentry issues listed above
Ran & tested dim routes locally
=> Fix failing / erroring dbt tests 4/11/23

warehouse/models/mart/payments/fct_payments_rides_v2.sql
Include CCJPA in row access policy on fct_payments_rides_v2
=> add fct_payments_rides_v2 row access policy for CCJPA

airflow/dags/deploy_dbt_docs/sync_dbt_docs_to_metabase.yml, warehouse/scripts/run_and_upload.py
Resolves https://github.com/cal-itp/data-infra/issues/2536
Note: this does not fix the underlying mismatches right now.
=> fix dbt-metabase not executing if model mismatch exists

airflow/dags/unzip_and_validate_gtfs_schedule_hourly/unzip_gtfs_schedule.py, airflow/plugins/operators/gtfs_csv_to_jsonl_hourly.py, airflow/plugins/utils.py
This commit was supposed to be on https://github.com/cal-itp/data-infra/pull/2460.
=> create hourly feed file so we can use the new bucket

airflow/dags/transform_warehouse/dbt_test.yml, airflow/dags/transform_warehouse_full_refresh/dbt_test.yml, warehouse/scripts/run_and_upload.py
Resolves https://github.com/cal-itp/data-infra/issues/2537
Testing locally via docker-compose, it did not work yet.
=> also apply config selector to test

images/jupyter-singleuser/Dockerfile, images/jupyter-singleuser/docker-compose.yaml, images/jupyter-singleuser/jupyter_notebook_config.py, images/jupyter-singleuser/pyproject.toml, kubernetes/apps/charts/jupyterhub/values.yaml
Resolves https://github.com/cal-itp/data-infra/issues/2517
Have tested locally in docker-compose, but need to test in Hub.
=> move ipynb checkpoint files to home dir to avoid dbt conflict

jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py
Resolves https://github.com/cal-itp/data-infra/issues/2534
Resolves https://github.com/cal-itp/data-infra/issues/2535
Tested locally; [example issue](https://sentry.calitp.org/organizations/sentry/issues/70317/?environment=local&project=2&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h).
=> improve RT sentry context

airflow/plugins/operators/gtfs_csv_to_jsonl_hourly.py
May resolve https://github.com/cal-itp/data-infra/issues/2559 but won't be sure until we re-run it.
I'm intentionally *not* changing this in the daily job, so we can see if it also fails.
Ran locally.
Re-run the failed jobs
=> maybe fix memory leak in hourly schedule parse job

airflow/plugins/operators/gtfs_csv_to_jsonl_hourly.py, warehouse/models/mart/gtfs/_mart_gtfs_dims.yml, warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
Resolves https://github.com/cal-itp/data-infra/issues/2560
I messed up and didn't think about double-quotes appearing later in the CSV file. We can just read the entire file since individual files tend to be small.
Will test a full run; I've confirmed it works on the specific known file.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated …
=> Sniff entire CSV rather than just header

airflow/plugins/operators/gtfs_csv_to_jsonl.py
=> also do this in daily job

airflow/dags/unzip_and_validate_gtfs_schedule_hourly/METADATA.yml
Follow-up to https://github.com/cal-itp/data-infra/pull/2460
=> backfill hourly schedule parsing to 2021

runbooks/data/deprecation-warehouse-models.md
Adapted from @SorenSpicknall's process outline here: https://github.com/cal-itp/data-infra/issues/1355#issuecomment-1500608684
Resolves #1355
N/A
=> Model deletion runbook 

runbooks/pipeline/sentry-triage.md
Adds a second search to the Sentry runbook based on convo with @atvaccaro this morning
N/A
=> update Sentry runbook with Discover search for events on existing issues

warehouse/models/docs/_docs_overview.md
Docs fix -- noticed issue taking a screenshot to share on https://github.com/cal-itp/data-analyses/issues/750
N/A
=> fix incorrect copy-paste

airflow/dags/create_external_tables/gtfs_schedule_v2/stop_times.yml
Breaking this out from #2601 so I can test the rest of the changes there.
Have been testing in #2601, confirmed that the data is there
Manually trigger the external table DAG
=> add gtfs flex v2 columns to stop times external table

warehouse/scripts/run_and_upload.py
Follow-up to the never-ending dbt version/artifact saga (https://github.com/cal-itp/data-infra/pull/2598)
I've also added more dbt context ([example event](https://sentry.calitp.org/organizations/sentry/issues/37478/events/b15b7a594b1e4b10a5e3022d2388b8b4/?project=2)); I think we should be more liberal/generous with context in general
I've verified the types and fingerprints look good now.
```
reporting <class '__main__.DbtTestWarn'> for test.calitp_warehouse.not_null_fct_daily_schedule_feeds_gtfs_dataset_key.27c1f8f0d2 with fingerprint ['warn', 'test.calitp_warehouse.not_null_fct_daily_schedule_feeds_gtfs_dataset_key.27c1f8 …
```
=> fix dbt failure fingerprinting for sentry (again)

airflow/dags/publish_open_data/publish_california_open_data.yml, warehouse/Dockerfile, warehouse/Dockerfile.local, warehouse/scripts/publish.py
Resolves https://github.com/cal-itp/data-infra/issues/2596
I've been attempting to reproduce, but I may ask to deploy this `del` and see if it recurs.
Run the publishing in prod.
=> CKAN publishing fix/doc updates

.github/workflows/build-dbt.yml, warehouse/scripts/dbt_artifacts/__init__.py, warehouse/scripts/templates/ci_report.md, warehouse/scripts/visualize.py
Actual PR of https://github.com/cal-itp/data-infra/pull/2605; I'd forgotten to remove the test commits and had to revert.
=> Fix dag viz ci

warehouse/models/mart/gtfs_quality/fct_daily_service_combined_guideline_checks.sql
=> add parens

kubernetes/apps/charts/sentry/values.yaml
This is already applied to the current PVC.
=> bump sentry postgres to 100gi storage

images/jupyter-singleuser/docker-compose.yaml, kubernetes/apps/charts/jupyterhub/values.yaml
Following up on #2696, fixes a relative directory reference that should have been fully qualified.
We will deploy the new image following this change
=> Fix mkdir directory reference in jupyterhub image

docs/analytics_tools/rt_analysis.md
Revise rt_analysis documentation to included embedded maps via web app per changes in https://github.com/cal-itp/data-analyses/pull/781
https://github.com/cal-itp/data-infra/tree/main/apps/maps
=> update for spa map option

kubernetes/apps/charts/postgresql-backup/templates/cronjob.yaml, kubernetes/apps/charts/postgresql-backup/values.yaml, kubernetes/apps/values/postgresql-backup-grafana.yaml, kubernetes/apps/values/postgresql-backup-metabase-prod.yaml, kubernetes/apps/values/postgresql-backup-sentry.yaml
Resolves https://github.com/cal-itp/data-infra/issues/2671
See https://healthchecks.jarv.us! Lmk if you need an invite.
=> add healthchecks pings to pg backup cronjobs

warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
Test had wrong column name, caused dbt errors.
Fixes CAL-ITP-DATA-INFRA-2622 ([link](https://sentry.calitp.org/organizations/sentry/issues/72079/))
Fixes CAL-ITP-DATA-INFRA-2624 ([link](https://sentry.calitp.org/organizations/sentry/issues/72081/))
Fixes CAL-ITP-DATA-INFRA-2621 ([link](https://sentry.calitp.org/organizations/sentry/issues/72078/))
Resolves #2730
`poetry run dbt test -s fct_service_alerts_messages fct_vehicle_positions_messages fct_trip_updates_messages` - now passes, no errors
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a …
=> fix RT test column name reference

kubernetes/apps/values/metabase-test.yaml, kubernetes/apps/values/metabase.yaml, warehouse/scripts/run_and_upload.py
Upgrades metabase and uses a more explicitly-named sync endpoint.
Deployed to https://metabase-test.k8s.calitp.jarv.us
@lauriemerrell suggested trying to trigger a sync and match it against the audit logs, which is a good idea. I'll do that as I keep digging into our billing.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue …
=> Upgrade metabase and change sync endpoint

warehouse/scripts/run_and_upload.py
This has been buggy and I want to just get rid of it for now.
Ran locally.
=> remove dbt-metabase reporting to sentry

ci/vars/releases/prod-postgresql-backup-grafana.env
=> fix grafana backup CI namespace

kubernetes/apps/charts/sentry/values.yaml
=> extend sentry cleanup job deadline

ci/channels/prod.yaml
I missed these in https://github.com/cal-itp/data-infra/pull/2736
Release to prod
=> split couple more helm values into lists

runbooks/pipeline/sentry-triage.md
Change measurement recommendation to Fridays
I am also announcing this on Slack so people are aware
=> change recommended checks to fridays

warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
Unfortunately #2807 did not entirely resolve [CAL-ITP-DATA-INFRA-13EH](https://sentry.calitp.org/organizations/sentry/issues/36334/), so this adjusts test thresholds and updates docs to note exceptions.
Can't effectively test locally because affected dates are March 2023 or earlier, but it's the same resolution pattern applied elsewhere.
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed …
=> final updates for fct daily service alerts uniqueness & docs

kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml, services/gtfs-rt-archiver-v3/README.md
Noticed this while attempting a deploy; the `-v3` suffix was missing.
Will deploy to test
Deploy to prod
=> fix archiver image tag base

ci/channels/prod.yaml
Found while deploying https://github.com/cal-itp/data-infra/pull/2812
n/a
merge https://github.com/cal-itp/data-infra/pull/2827
=> add archiver and sentry to prod release definitions

ci/channels/prod.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-prod/kustomization.yaml, kubernetes/apps/overlays/gtfs-rt-archiver-v3-test/kustomization.yaml, kubernetes/apps/values/metabase.yaml
Deploys metabase upgrade, archiver fix, and archiver/sentry CI to prod.
=> Deploy main to prod

ci/channels/prod.yaml
=> prod has no suffix

kubernetes/apps/charts/jupyterhub/values.yaml
part of https://github.com/cal-itp/data-infra/issues/2797
I've already applied the change
Someone will need to attempt to log in.
=> add ntd-slalom github team to oauth for jupyter

airflow/dags/publish_open_data/publish_california_open_data.yml, images/jupyter-singleuser/pyproject.toml, kubernetes/apps/charts/jupyterhub/values.yaml
Couple small follow-ups to https://github.com/cal-itp/data-infra/pull/2838
Ran publish via airflow locally.
Prod release.
=> Calitp py followups

ci/README.md
=> fix plural word

images/jupyter-singleuser/poetry.lock, images/jupyter-singleuser/pyproject.toml, kubernetes/apps/charts/jupyterhub/values.yaml, packages/calitp-data-analysis/calitp_data_analysis/__init__.py, packages/calitp-data-analysis/pyproject.toml
I missed keeping `get_fs` in calitp-data-analysis
Publishing and installing locally.
Still pending full prod release.
=> add get_fs back to calitp-data-analysis

.github/workflows/build-calitp-data-analysis.yml, .github/workflows/build-calitp-data-infra.yml, .github/workflows/build-calitp-map-utils.yml, .github/workflows/build-dbt.yml, apps/maps/calitp_map_utils/__init__.py, apps/maps/pyproject.toml, apps/maps/tests/test_calitp_map_utils.py
Final follow-up from https://github.com/cal-itp/data-infra/pull/2838
This will deploy to pypi on merges to main, and ignores if the version has already been published. Developers can publish new versions by incrementing the version number defined in poetry; this seemed better than having to rely on specific tags for now.
CI needs to pass
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other …
=> publish python packages to pypi in ci

ci/channels/prod.yaml
Follow-up from https://github.com/cal-itp/data-infra/pull/2855
=> increase sentry ci timeout

airflow/dags/parse_elavon/README.md, airflow/dags/sync_elavon/README.md
Adds various details about the function of the Elavon pipeline to that pipeline's READMEs in Airflow
Markdown linted successfully
=> Update Elavon sync DAG READMEs with more details

.github/ISSUE_TEMPLATE/new-team-member.md, docs/analytics_new_analysts/05-spatial-analysis-basics.md, docs/analytics_tools/local_oracle_db_connections.md
Update the new-team-member template to reflect the permissions we want to grant for JupyterHub access. Otherwise...we're hitting `403 forbidden` errors. Also fix typos/weird formatting in tutorials.
=> Update new team member template

kubernetes/apps/charts/sentry/Chart.yaml
Upgrades sentry to the latest helm chart.
n/a
Release to prod and handle any failed consumer restarts.
=> upgrade sentry helm chart

warehouse/models/mart/benefits/_mart_benefits.yml, warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml, warehouse/models/mart/gtfs_quality/_mart_gtfs_quality.yml, warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
Responsive to #2865, updates YAML to prevent Metabase sync failures. This is not going to be marked as resolving the issue right away, since I want to do some additional testing and cleanup after merge.
YAML compared by hand to table SQL and production tables for impacted models
Monitor [the deploy_dbt_docs Airflow task](https://o1d2fa0877cf3fb10p-tp.appspot.com/dags/deploy_dbt_docs/grid?root=), and make further changes to rectify mismatches if needed.
=> Metabase YAML alignment

warehouse/models/mart/payments/fct_payments_rides_v2.sql
Resolves failing CI
I re-built the table manually; CI should pass.
=> add github actions service user to new v2 payments rides table

docs/warehouse/developing_dbt_models.md
Adds video from troubleshooting call yesterday to dbt development docs and adds a section incremental models.
=> Add dbt troubleshooting video

kubernetes/README.md
=> update k8s auth docs

docs/analytics_tools/github_setup.md
add stub docs on which software to request for Git/VS Code on Caltrans PCs
=> add stub docs on which software to request for Git/VS Code on Caltrans PCs

docs/analytics_tools/github_setup.md
Finish documenting Windows Git setup for Caltrans PCs.
=> Windows git instructions

warehouse/models/staging/transit_database/_stg_transit_database.yml, warehouse/models/staging/transit_database/stg_transit_database__funding_programs.sql
Resolves #2983 
Rerun Airflow job
=> fix typo in stg_transit_database__funding_programs

warehouse/models/mart/gtfs/_mart_gtfs_fcts.yml
Resolves all the alerts we've been getting related to netlify docs / ` dbt_run_and_upload_artifacts`
Resolving this [Slack thread](https://cal-itp.slack.com/archives/C050ZNDUL21/p1697041795888169)
This PR should go before https://github.com/cal-itp/data-infra/pull/3005
=> remove shape_array_key from yml

warehouse/models/docs/_docs_littlepay.md, warehouse/models/intermediate/payments/_int_payments.yml, warehouse/models/intermediate/payments/int_payments__authorisations_to_aggregations.sql, warehouse/models/intermediate/payments/int_payments__latest_authorisations_by_aggregation.sql, warehouse/models/intermediate/payments/int_payments__micropayments_to_aggregations.sql, warehouse/models/intermediate/payments/int_payments__settlements_to_aggregations.sql, warehouse/models/mart/payments/_payments.yml, warehouse/models/mart/payments/fct_payments_aggregations.sql, warehouse/models/staging/payments/littlepay/_littlepay.yml
Creates `fct_payments_aggregations` model to use for payments reconciliation.
Resolves #2958
Resolves #2979
```
laurie ~/git/data-infra/warehouse [fct-aggregations] $ poetry run dbt build -s +fct_payments_aggregations
19:24:04  Running with dbt=1.5.1
19:24:05  Unable to do partial parsing because profile has changed
19:24:18  Found 331 models, 905 tests, 0 snapshots, 0 analyses, 846 macros, 0 operations, 8 seed files, 126 sources, 4 exposures, 0 metrics, 0 groups
19:24:18 …
```
=> Payments: Create `fct_payments_aggregations` model

.github/workflows/lint.yml, airflow/dags/airtable_loader_v2/generate_gtfs_download_configs.py, airflow/dags/dags.py, airflow/dags/download_gtfs_schedule_v2/download_schedule_feeds.py, airflow/dags/download_gtfs_schedule_v2/email_download_failures.py, airflow/dags/unzip_and_validate_gtfs_schedule_hourly/unzip_gtfs_schedule.py, airflow/plugins/operators/gtfs_csv_to_jsonl.py, airflow/plugins/operators/gtfs_csv_to_jsonl_hourly.py, airflow/plugins/operators/littlepay_raw_sync.py, jobs/gtfs-aggregator-scraper/gtfs_aggregator_scraper.py, jobs/gtfs-rt-parser-v2/gtfs_rt_parser.py, jobs/gtfs-schedule-validator/gtfs_schedule_validator_hourly.py, packages/calitp-data-analysis/calitp_data_analysis/geography_utils.py, packages/calitp-data-analysis/calitp_data_analysis/sql.py, packages/calitp-data-analysis/calitp_data_analysis/tables.py, packages/calitp-data-analysis/tests/test_tables.py, packages/calitp-data-infra/calitp_data_infra/storage.py, warehouse/scripts/dbt_artifacts/__init__.py, warehouse/scripts/json_to_docblocks.py, warehouse/scripts/publish.py, warehouse/scripts/visualize.py
For some reason flake8 [just decided](https://github.com/cal-itp/data-infra/actions/runs/6658741394/job/18096678340) to throw a ton of linting errors about strings in code (ex. templated strings and comments). This PR suppresses those errors.
GitHub Action is now passing
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and …
=> Address a bunch of linter failures

warehouse/macros/annotate_payments_entities.sql, warehouse/models/docs/_docs_littlepay.md, warehouse/models/mart/payments/_payments.yml, warehouse/models/mart/payments/fct_elavon__transactions.sql, warehouse/models/mart/payments/fct_payments_adjustment_transactions.sql, warehouse/models/mart/payments/fct_payments_billing_transactions.sql, warehouse/models/mart/payments/fct_payments_chargeback_transactions.sql, warehouse/models/mart/payments/fct_payments_deposit_transactions.sql, warehouse/models/mart/payments/fct_payments_settlements.sql, warehouse/models/staging/payments/littlepay/_littlepay.yml
* Fixes YAML for settlements that is causing Metabase failure in the dbt DAG task.
* Breaks up Elavon transactions by type in the mart for easier access 
* Adds `littlepay_participant_id` as a column in Elavon data so it can be filtered on which customers do/don't have LP data
* Adds organization name to `fct_payments_settlements` for BI purposes
ETA: Per @charlie-costanzo question below -- I am not deleting `fct_elavon__transactions` in this PR because there are a few dashboards that use it, but ultimately I would like to delete it and use these more specific tables instead
```
laurie ~/git/data-infra/warehouse …
```
=> Break up Elavon transactions by type & other small tweaks

warehouse/README.md
Add a note about a workaround to get the data warehouse running on ARM Macs.
https://github.com/pygraphviz/pygraphviz/issues/398#issuecomment-1450367670
=> Add note about pygraphviz error on ARM Macs

images/jupyter-singleuser/poetry.lock, jobs/gtfs-schedule-validator/poetry.lock, packages/calitp-data-analysis/poetry.lock, packages/calitp-data-infra/poetry.lock, script/poetry.lock, services/gtfs-rt-archiver-v3/poetry.lock, warehouse/poetry.lock
Groups a bunch of dependabot-suggested changes into a single PR, a partial resolution for #3062
Dependency changes checked for conflicts or downstream impacts
=> Bump urllib3 v1 to 1.26.18

warehouse/README.md
I've made minor structuring changes and added some notes and warnings in a consistent manner after my experience setting everything up.
Also, turns out the note I added in #3072 can apply to Intel Macs too, so I clarified that in that note.
View the new README on GitHub
=> Improve warehouse README with some more information

images/jupyter-singleuser/Dockerfile, warehouse/Dockerfile, warehouse/Dockerfile.local
Erroneously included a `sudo` in #3090, which this resolves
=> HOTFIX gpg command in Dockerfiles

warehouse/README.md
In my initial PR #3091, I only touched the setup instructions but I forgot to update the other sections about prepping your machine. So here's that update!
Look at the README on GitHub. Also, I've been stepping through these steps on a clean computer and verifying links are still accurate.
=> Improve warehouse README (part 2)

warehouse/models/mart/payments/_payments.yml, warehouse/models/mart/payments/fct_payments_rides_v2.sql, warehouse/models/staging/payments/littlepay/_littlepay.yml, warehouse/models/staging/payments/littlepay/int_littlepay__customer_funding_source_vaults.sql, warehouse/models/staging/payments/littlepay/int_littlepay__customers.sql, warehouse/models/staging/payments/littlepay/stg_littlepay__customer_funding_source.sql
See [this Google Doc](https://docs.google.com/document/d/1YFz0kWXHOhd5_giHo6V0hi6CnQ6wVaDs2hfVHA9qRK8/edit) for context. 
Resolves #3079 
Resolves #3097 
`poetry run dbt build -s +fct_payments_rides_v2,source:external_littlepay+` passes
=> Payments: Make customer processing participant-specific

warehouse/models/mart/transit_database/_mart_transit_database.yml, warehouse/models/mart/transit_database/dim_mobility_mart_providers.sql
This PR is one of many steps towards the Mobility Marketplace (Mobi Mart) [Provider Map Refresh](https://github.com/cal-itp/mobility-marketplace/milestone/23). Currently, the Provider Map/data on Mobi Mart is dated and was created manually years ago. One of the goals of this refresh is to automate the aggregation of this data using the warehouse.
This is my first PR to the warehouse infrastructure, and I would appreciate all feedback on moving forward with this PR. I have a few questions/concerns/thoughts listed below:
1. Should this query exist as a dimension or fact in the warehouse?
2. Should this be a table or a view?
I am thinking of this being a view since all of the data that is presented via this query is pulled from other tables, so no data is living here. Also, this data should …
=> Create new table to be used for Mobility Marketplace's new provider map

runbooks/workflow/payments/add_agency_dashboard_data_source.md
Adds a diagram showing the relationships of the different entities described in the narrative text.
N/A
=> Add diagram showing RBAC/security for Payments dashboards

airflow/dags/create_external_tables/METADATA.yml
=> Move create external tables DAG to 9am UTC

airflow/plugins/operators/blackcat_to_gcs.py, warehouse/models/mart/ntd_validation/fct_ntd_rr20_service_checks.py
When the year changed to 2024 on January 1, a few things broke because there is no NTD validation data for 2024. `this_year` and `last_year` are variables that dynamically change with they years, so we added a few more null checks to continue functions when no NTD data has yet come through for any given year. Also changed the validation report table to have some output even when there is no data to check - was getting an error if returning an empty data frame to BigQuery via dbt. It now looks like this:
Also, the change in year is what broke the Airflow ingest job, because the URL dynamically changes with the current year appended to the end. Added a None check to the GCS operator.
Tested locally. Local Airflow job also passed.
=> add null checks for when the year changes

.github/workflows/deploy-kubernetes.yml, .github/workflows/preview-kubernetes.yml
Some minor cleanup following merge of #3205
=> Minor follow-up fixes to new Kubernetes deployment f low

packages/calitp-data-analysis/calitp_data_analysis/styleguide.py
* [Slack thread. ](https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1704306757062929) Testing to see if we can make changes to the `calitp_data_analysis utils` by deleting the font references.
=> (calitp_data_analysis): styleguide - removed reference to fonts

packages/calitp-data-infra/calitp_data_infra/auth.py, packages/calitp-data-infra/pyproject.toml
Hotfix to #3274
CI Tests Only
Change out refs in other ecosystem components once published
=> HOTFIX: revision to prior package change

airflow/dags/create_external_tables/airtable/external_airtable_transit_data_quality_issues_services.yml
Bad datatype in https://github.com/cal-itp/data-infra/pull/3284
No
=> Fixed field type

.pre-commit-config.yaml, warehouse/models/mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml
Resolves #3104 
* Use yaml anchors in `mart/gtfs_schedule_latest/_gtfs_schedule_latest.yml`
* Fill in columns missing documentation, except for exposure `dim_shapes_arrays_latest`. Columns are not defined where the [exposures](https://docs.getdbt.com/docs/build/exposures) are.
* `poetry run dbt docs generate`
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link it here …
=> Docs - audit `mart_gtfs_schedule_latest`

.github/workflows/build-jupyter-singleuser-image.yml, images/jupyter-singleuser/pyproject.toml
Previous PR did not update project version and was going to overwrite old docker image.
There was also two build workflows running because the GitHub Action was configured to run on pull requests but would have used the same image tag, so I removed running it on pull request
YOLO
=> Jupyter custom image build workflow

docs/publishing/sections/4_notebooks_styling.md, docs/publishing/sections/5_analytics_portfolio_site.md
Erased netlify token check section and added sentence to second section. Fixed some typos.
=> Small tweaks to the Cal ITP Portfolio Docs

kubernetes/apps/values/promtail.yaml
Update promtail helm configuration to newer syntax to fix flow of data into Loki
Resolves #3348
=> fix(k8s): update promtail client configuration

kubernetes/apps/values/grafana-prod.yaml
This should correct the self-referential URLs Grafana generates
=> fix(k8s): configure Grafana root URL

airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__calendar_year_upt.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__calendar_year_vrm.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__master.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__upt.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__upt_estimates.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__voms.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__vrh.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__vrm.yml, airflow/dags/create_external_tables/ntd_data_products/historical__complete_monthly_ridership_with_adjustments_and_estimates__vrm_estimates.yml, airflow/docker-compose.yaml
This PR creates the NTD external tables for XLSX Complete Monthly Ridership with Adjustments and Estimates Data
#3403
Tested with local Airflow and the tables were created on cal-itp-data-infra-staging.external_ntd__ridership
Validate the creation of all tables on cal-itp-data-infra.external_ntd__ridership
=> NTD external tables for Complete Monthly Ridership with Adjustments and Estimates Data

docs/analytics_tools/knowledge_sharing.md
fix link to Composing Programs
=> fix composing programs link

airflow/dags/create_external_tables/airtable/external_airtable_california_transit_services.yml
Update to https://github.com/cal-itp/data-infra/pull/3488 - adds a few holiday columns I missed before.
Resolves https://github.com/cal-itp/data-infra/issues/3487
Not tested
_If making changes to dbt models, please run the command `poetry run dbt run -s CHANGED_MODEL` and include the output in this section of the PR._
=> fix(california_transit_services): missed a few holidays on my first pass

airflow/requirements.txt
This PR adds the library beautifulsoup4 required in recently merged PR #3545 
local airflow
monitor for expected behavior
=> add requirement necessary for recently merged pr 3545

warehouse/models/docs/_docs_ntd.md, warehouse/models/intermediate/ntd/int_ntd.yml, warehouse/models/mart/ntd/_mart_ntd.yml, warehouse/models/staging/ntd/_src.yml, warehouse/models/staging/ntd/_stg_ntd.yml, warehouse/models/staging/ntd_annual_data_tables/_src.yml, warehouse/models/staging/ntd_annual_data_tables/_stg_ntd_annual_data_tables.yml, warehouse/models/staging/ntd_ridership/_src.yml, warehouse/models/staging/ntd_ridership/_stg_ntd_historical_ridership_tables.yml
This PR is part of the work to add documentation and tests to all new NTD models [3475](https://github.com/cal-itp/data-infra/issues/3475).
Reviewing existing documentation and tests for NTD models, I moved the common descriptions to docs .
Next PRs will be adding new documentation and tests for models without any. 
Created table and documentation locally.
Check if the documentation was added to the models and DBT documentation, and if all tests are passing.
=> Review existing NTD documentation

.github/pull_request_template.md
Add one more command to test changes made to dbt models to validate changes.
N/A
=> Add command to test changes made to dbt models

packages/calitp-data-analysis/pyproject.toml, packages/calitp-data-infra/pyproject.toml
Added package-mode lines to calitp data-infra and calitp map-utils packages since it has started to break our github actions.
Minor updates so used post
Has not been tested.
Test github actions / update them, make sure they still work.
=> Added package-mode lines to calitp data-infra and calitp map-utils packages

airflow/dags/create_external_tables/ntd_data_products/historical__operating_and_capital_funding_time_series__read_me_data_dictionary.yml, airflow/dags/create_external_tables/ntd_data_products/historical__service_data_and_operating_expenses_time_series_by_mode__read_me_data_dictionary.yml
In #3655 I made changes locally that fixed two failing external table tasks, but the changes never made it into the PR by accident. This PR fixes that issue.
Ensure tables are created as expected
=> Fix: NTD external tables failing due to typo

airflow/dags/create_external_tables/ntd_data_products/historical__service_data_and_operating_expenses_time_series_by_mode__read_me_data_dictionary.yml
Unfortunately following #3658 there was a case of one more failure that needs to be rectified due to unpushed local changes, a two character fix
clear task and make sure it's running appropriately
=> fix: remaining ntd external table error

.github/workflows/build-warehouse-image.yml, warehouse/Dockerfile
Previously failing job, this should fix it.
Tested in https://github.com/cal-itp/data-infra/pull/3669
Also holds poetry version down to 2.0.1 for warehouse images
Resolves #3662 
Modified build commands, and tested in https://github.com/cal-itp/data-infra/pull/3669
Tested locally with docker build .
Check and make sure push goes through successfully
=> Fixes the warehouse dockerfile update

kubernetes/apps/charts/jupyterhub/values.yaml
=> Add debugging to jupyterhub

.github/ISSUE_TEMPLATE/quarterly-maintenance.md
Adds a template to aid in adding quarterly maintenance tickets.
Discussed: https://cal-itp.slack.com/archives/C01FNDG1ZPA/p1727198167293059
Didn't put in the effort to make this automated yet.  Instead we can just quickly create the tickets from this template.
Tested in [another repo](https://github.com/cal-itp/bus-stop-data-therapy/issues)
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be …
=> Adds a quarterly maintenance ticket

runbooks/workflow/payments/add_agency_dashboard_data_source.md
While working on #3708, it was realized that we should revise the dashboards that we recommend duplicating when creating dashboards for new agencies
=> payments: revise recommended dashboards for duplication in runbook

iac/README.md, iac/cal-itp-data-infra-staging/gcs/us/storage_bucket.tf, iac/cal-itp-data-infra-staging/project/us/project.tf, iac/cal-itp-data-infra/disks/us/compute_disk.tf, iac/cal-itp-data-infra/disks/us/outputs.tf, iac/cal-itp-data-infra/gcs/us/outputs.tf, iac/cal-itp-data-infra/gcs/us/storage_bucket.tf, iac/cal-itp-data-infra/gcs/us/storage_bucket_acl.tf, iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_binding.tf, iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf, iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_policy.tf, iac/cal-itp-data-infra/gcs/us/storage_default_object_acl.tf, iac/cal-itp-data-infra/gke/us/container_cluster.tf, iac/cal-itp-data-infra/gke/us/container_node_pool.tf, iac/cal-itp-data-infra/instanceGroupManagers/us/compute_instance_group_manager.tf, iac/cal-itp-data-infra/instanceGroups/us/compute_instance_group.tf, iac/cal-itp-data-infra/project/us/project.tf, warehouse/dbt_project.yml
Updates terraform to add permission to the existing service account, and removes some deprecated resources.
Part of #\[3291\]
Terraform plan tested locally.
=> Updates terraform and remove deprecated resources

.github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml, iac/cal-itp-data-infra-staging/project/us/project.tf, iac/cal-itp-data-infra/gke/us/container_cluster.tf, iac/cal-itp-data-infra/gke/us/container_node_pool.tf, iac/cal-itp-data-infra/iam/us/iam_workload_identity.tf, iac/cal-itp-data-infra/instanceGroupManagers/us/compute_instance_group_manager.tf, iac/cal-itp-data-infra/instanceGroups/us/compute_instance_group.tf, iac/cal-itp-data-infra/project/us/project.tf
[3a0bb40](https://github.com/cal-itp/data-infra/commit/3a0bb403820d5019a56dc5fa3b90eb9308417868) checked in a divergent state. This resolves that divergence.
Issue introduced in #3775
Terraform plan output in this PR.
Verify convergence after merging to main.
=> Only run Terraform modules with changes

.github/workflows/deploy-airflow.yml
This PR adds process to deploy changes to new Composer.
Resolves #3824
It was tested deploying from this branch.
Confirm changes on new Composer after next deployment.
=> Fix production composer deployment

iac/cal-itp-data-infra-staging/cdn/us/.terraform.lock.hcl
Initializes Terraform for the staging CDN resource
Part of #3783
`terraform plan` and `terraform apply` locally
=> Initialize cdn terraform

.github/workflows/build-warehouse-image.yml, .github/workflows/deploy-airflow-requirements.yml, .github/workflows/deploy-airflow.yml, .github/workflows/deploy-dbt.yml, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml, iac/cal-itp-data-infra-staging/iam/us/project_iam_custom_role.tf, iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf, iac/cal-itp-data-infra/iam/us/project_iam_custom_role.tf, iac/cal-itp-data-infra/iam/us/project_iam_member.tf
This change rebuilds dbt documentation in Github Actions. Previously, the `transform_warehouse` Airflow job would compile, build documentation, and upload metadata to Metabase. However, this presumes that all models change in lockstep, which is no longer true as of #3780.
Resolves #3783 
Run locally and as part of the pull request process.
Review https://dbt-docs.calitp.org
=> Compile dbt documentation in Github actions

.github/workflows/deploy-airflow-requirements.yml, .github/workflows/deploy-airflow.yml, .github/workflows/deploy-dbt.yml
-Add staging credentials to test workflows on pull requests
Use credentials with the right access to Deploy Airflow DAGs and Requirements.
Fix credential error from PR https://github.com/cal-itp/data-infra/pull/3814.
Resolves https://github.com/cal-itp/data-infra/issues/3783
Tested on github actions.
=> Review credentials on Deploy Airflow DAGs and Requirements

docs/analytics_tools/jupyterhub.md
Adds a few more specifics to make the instructions analyst first.
Resolves #3748
=> feat(docs): Adds more info to gcloud login instructions

.github/CODEOWNERS
In this system if you are on the list, you can approve code changes.
We just trust the people on the list to approve the right kinds of changes.
Additionally we modify our repo to so we use the codeowners file again.
=> Change our codeowner system

airflow/README.md, iac/cal-itp-data-infra-staging/composer/us/environment.tf
This documents the Composer secrets setup corresponding to the merge of https://github.com/cal-itp/data-infra/pull/3908
Resolves #4012 
=> Add Composer secrets documentation

.github/CODEOWNERS
Remove @themightychris from Github codeowners
=> codeowners: remove themightychris

ci/kubernetes-workloads.yaml
Attempts to resolve JupyterHub deployment issue by bumping timeout https://github.com/cal-itp/data-infra/issues/4087
=> Increase timeout for jupyterhub deploy

ci/kubernetes-workloads.yaml, kubernetes/apps/charts/jupyterhub/values.yaml
Fixes typo in jupyter-singleuser version string so that it hopefully deploys now and also reverts the timeout increase
Resolves #4087
=> Fix typo in jupyter-singleuser version string

iac/cal-itp-data-infra/cdn/us/backend_bucket.tf, iac/cal-itp-data-infra/gcs/us/outputs.tf, iac/cal-itp-data-infra/gcs/us/storage_bucket.tf, iac/cal-itp-data-infra/gcs/us/storage_bucket_iam_member.tf
Bucket and network config for analysis.dds.dot.ca.gov
Related: #3975
=> Create infra for analysis.dds.dot.ca.gov

iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf, iac/cal-itp-data-infra/iam/us/project_iam_member.tf
Adds a role to this repo's action in order to manage the workflow providers
Resolves: #4123
- [ x] Bug fix (non-breaking change which fixes an issue)
Was manually added and then removed via cloud interface
=> Add needed github workflow permission

images/jupyter-singleuser/poetry.lock, images/jupyter-singleuser/pyproject.toml, kubernetes/apps/charts/jupyterhub/values.yaml
See commit messages
Resolves https://github.com/cal-itp/data-infra/issues/4163
This will be tested by analysts over 1-2 weeks as they use the prototype image during their normal work and if they report no breaking changes.
Post merge follow-up
=> [images/jupyter-singleuser] Resolve remaining dependabot alerts

warehouse/macros/_macros.yml
Resolves #4167
Documents the `incremental_where` macro and its parameters
N/A
_Document any actions that must be taken post-merge to deploy or otherwise implement the changes in this PR (for example, running a full refresh of some incremental model in dbt). If these actions will take more than a few hours after the merge or if they will be completed by someone other than the PR author, please create a dedicated follow-up issue and link …
=> Document `incremental_where` macro

iac/cal-itp-data-infra-staging/iam/us/project_iam_member.tf, iac/cal-itp-data-infra/iam/us/outputs.tf, iac/cal-itp-data-infra/iam/us/project_iam_member.tf
This PR allows the production terraform account to make changes to the staging GCS environment.
Resolves #4195
`terraform apply`
=> Grant production terraform permission to administer staging GCS

airflow/plugins/operators/scrape_ntd_xlsx.py
Following the successful scrape of XLSX URLs after merging #4258, we're experiencing similar timeout/request issues with the downstream tasks that actually download the XLSX files from the URLs that we scrape. This PR extends the improvements to the requests that we made to the upstream operator to the downstream operator
Ensure that this works in production
=> NTD: fix downstream XLSX download timeout

iac/cal-itp-data-infra-staging/sftp/us/enghouse/enghouse-sftp-endpoint.tf
Use a deployment instead of a raw pod to deploy sftp server 
Ref: #4048
=> Use deployment for enghouse sftp on staging

airflow/Makefile, airflow/poetry.lock, airflow/pyproject.toml, iac/cal-itp-data-infra-staging/composer/us/environment.tf
This PR updates staging and develompent Airflow to 2.9.3
Related to #4333
Configuration
Validate staging DAGs
=> Update staging and development to airflow 2.9.3

iac/cal-itp-data-infra/sentinel/us/.terraform.lock.hcl, iac/cal-itp-data-infra/sentinel/us/gcpiamlogs.tf, iac/cal-itp-data-infra/sentinel/us/output.tf, iac/cal-itp-data-infra/sentinel/us/provider.tf, iac/cal-itp-data-infra/sentinel/us/variables.tf
This PR adds terraform scripts for Sentinel log streaming.
Monitor `terraform apply` output
=> Add sentinel log setup

iac/cal-itp-data-infra/sentinel/us/variables.tf
This PR updates a variable name for the Sentinel integration
Documentation
=> Update variable name
